### ISSUE TITLE
POM.xml is not generating properly

### ISSUE THREAD

**Issue by dbutala1985** [TIBCOSoftware/bw6-plugin-maven#1]
Hi,

I have project with customeXpath function and one shared module. I tried to create a POM.xml file but the file got generated with out the dependency, I manually added the dependencies and created pom again not it was complaining about the <packaging>bwear</packaging> for application module, it was not allowing to change from UI so I manually updated POM.xml which fix the error after I ran the package goal which generated ear which was missing all the dependencies.

**Comment by ashutoshbhide** [comment]
Dhruvesh,

Can you please share the sample project as well for reproducing the issue.

**Comment by ashutoshbhide** [comment]
Please run it with selecting the Base Location as Workspace location variable.
