### ISSUE TITLE
Please don't hard code Group ID

### ISSUE THREAD

**Issue by John-Zg** [TIBCOSoftware/bw6-plugin-maven#100]
Group ID "com.tibco.bw" is hard coded when creating pom files. Please let the user configure their own group id in preferences. Then, they don't need to change it all the time.

**Comment by NidhiRajeshDhoka** [comment]
Hi @John-Zg ,
"com.tibco.bw" is default groupID that is provided.User can remove it and configure their own group id in preferences.After installing it into the repository,you will find it in the configured group id path.

**Comment by awagle** [comment]
Related to #157

**Comment by awagle** [comment]
A new preference page is added via pull request #160
