### ISSUE TITLE
I am Trying to add maven plugin for tibco studio but facing issue:- Unable to access jarfile ${launcher.jar} .

### ISSUE THREAD

**Issue by DandaRaviteja** [TIBCOSoftware/bw6-plugin-maven#101]
devbuild.launcher.jar:

studio-install:
     [echo]  Installing Eclipse M2E Plugin to Tibco Home
     [exec] Error: Unable to access jarfile ${launcher.jar}
     [exec] Result: 1
     [exec] Error: Unable to access jarfile ${launcher.jar}
     [exec] Result: 1
     [exec] Error: Unable to access jarfile ${launcher.jar}
     [exec] Result: 1
     [echo]  UnInstalling the existing version of Plugin Code for Apache Maven and TIBCO BusinessWorksÖ
     [exec] Error: Unable to access jarfile ${launcher.jar}
     [exec] Result: 1
     [echo]  Installing Studio Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorksÖ to the Tibco Home
     [exec] Error: Unable to access jarfile ${launcher.jar}
     [exec] Result: 1

**Comment by fcenedes** [comment]
You need to put the root dir of the TIBCO HOME path

the build.xml is looking after ${tibco.home}/bwce/<version>

So you need to enter just the TIBCO HOME 

ie : /opt/tibco

**Comment by awagle** [comment]
@DandaRaviteja can you confirm if the solution given by @fcenedes solved the issue?

**Comment by SujataDarekar** [comment]
@DandaRaviteja,
    As per previous comment mentioned by @fcenedes , You need to provide root directory of the TIBCO HOME path.After providing proper TIBCO HOME path,issue will get resolve. Hence marking the issue as closed.
