### ISSUE TITLE
Maven Plugin version: 1.2.2

### ISSUE THREAD

**Issue by IsabelLeon** [TIBCOSoftware/bw6-plugin-maven#102]
Maven Plugin version: 1.2.2

Maven version: 3.3.9

Product : TIBCO Businessworks Container edition

Product version: 2.3.1

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1. I do a simple java Project with a method and a constructor (like HelloWorld). The method has "name" as input parameter and returns a gretting with the name. Compile with maven and upload local repository (helloWorld-0.0.1-SNAPSHOT.jar)
2. I do a simple BWCE application with a simple process. 
3. I add the java dependency of HelloWorld to pom. 
4. I Update Maven Projejct so i see the library in Maven Dependencies folder. 
5. I add to java invoke (call gretting method) in my simple process. 
6. I run in Business Studio and do a test and it is OK. 
7. Create .EAR with Maven Plug-in. 

**Additional environment details if any:**
I unzip .EAR and i see the java library (helloWorld-0.0.1-SNAPSHOT.jar) was added in /lib. So I suppose everything is OK. The Maven Plugin take the libraries of Maven Depedencies and add them to EAR. 

**Describe the results you received:**
But when i run a docker imagen with EAR i see "ClassNotfoundException". 

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
I edit the MANIFEST.MF file and change the next line: 
Before --> Bundle-ClassPath: .
After --> Bundle-ClassPath: lib/helloWorld-0.0.1-SNAPSHOT.jar,.

After this change i run a docker with the updated EAR and it's run correctly. 

If i copy the java libraries in /lib and create EAR from Maven Plugin I don't need to edit MANIFEST.MF. 

I need to know how to add libraries in classpath without copy libraries in /lib during desing, or editing MANIFEST.MF. 

Or how to change the property Bundle-ClassPath to: 

<'Bundle-ClassPath'>{maven-dependencies},.</'Bundle-ClassPath'>

**Comment by IsabelLeon** [comment]
I have repeated the test with BWCE 2.3 and Maven Plugin Version 1.1.0 and in this case the  Bundle-ClassPath property (of MANIFEST.MF) is correct. So the application start properly in docker. 

I guess it is necesary a fix in Maven Plugin Versión 1.2.2.

**Comment by fcenedes** [comment]
Hi IsaBelLeon,

Could you fetch and try the new 1.3.0 plugin version, and let us know how it goes for you ?

Thanks

**Comment by HiteshNembhwani** [comment]
works well for 2 use-cases we've tried using Maven 1.3.0 version.

**Comment by IsabelLeon** [comment]
Hi, 
I have tested with BWCE 2.3.2 and Maven 1.3.0 and now everything is OK. 

Thanks.

**Comment by awagle** [comment]
Closing Issue based on latest comments.
