### ISSUE TITLE
Retrocompatibility 1.2.1 - 1.2.2

### ISSUE THREAD

**Issue by roccokp** [TIBCOSoftware/bw6-plugin-maven#103]
Hi,
I have the following scenario:
BW6 application that is using maven plugin 1.2.2 and a referenced shared module that is using maven version 1.2.2

** Trying to build the application I have the following error **
[WARNING] The POM for com.tibco.plugins:bw6-maven-plugin:jar:1.2.1 is missing, no dependency information available
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin com.tibco.plugins:bw6-maven-plugin:1.2.1 or one of its dependencies could not be resolved: Failure to find com.tibco.plugins:bw6-maven-plugin:jar:1.2.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ 
[ERROR] Unknown packaging: bwmodule @ line 8, column 14
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project it.company:SharedHTTPResources:1.0 (C:\Users\Administrator\git\ICBPIPhoneTopUpManagement\Shared\SharedHTTPResources\pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin com.tibco.plugins:bw6-maven-plugin:1.2.1 or one of its dependencies could not be resolved: Failure to find com.tibco.plugins:bw6-maven-plugin:jar:1.2.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
[ERROR]     Unknown packaging: bwmodule @ line 8, column 14
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 

** Here my POM **
**BW6 Application**
_Parent POM_
project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
 http://maven.apache.org/xsd/maven-4.0.0.xsd" 
 xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   modelVersion 4.0.0 /modelVersion 
   groupId com.tibco.bw /groupId 
   artifactId ICBPIPhoneTopUpManagement.parent /artifactId 
   version 1.0 /version 
   packaging pom /packaging 
   modules 
     module ..\Shared\SharedHTTPResources /module 
     module ..\ICBPIPhoneTopUpManagement.module /module 
     module ..\ICBPIPhoneTopUpManagement /module 
   /modules 
 /project 

_Module POM_
 ?xml version="1.0" encoding="UTF-8"? 
 ?xml version="1.0" encoding="UTF-8"?
project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  modelVersion4.0.0/modelVersion
  parent
    groupIdcom.tibco.bw/groupId
    artifactIdICBPIPhoneTopUpManagement.parent/artifactId
    version1.0/version
    relativePath..\ICBPIPhoneTopUpManagement.parent/relativePath
  /parent
  artifactIdICBPIPhoneTopUpManagement.module/artifactId
  packagingbwmodule/packaging
  dependencies
    dependency
      groupIdcom.tibco.plugins/groupId
      artifactIdcom.tibco.bw.palette.shared/artifactId
      version6.1.100/version
    /dependency
  /dependencies
  build
    sourceDirectorysrc/sourceDirectory
    outputDirectorytarget/classes/outputDirectory
    plugins
      plugin
        groupIdcom.tibco.plugins/groupId
        artifactIdbw6-maven-plugin/artifactId
        version1.2.2/version
        extensionstrue/extensions
      /plugin
    /plugins
  /build
/project

_Application POM_
?xml version="1.0" encoding="UTF-8"?
project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  modelVersion4.0.0/modelVersion
  parent
    groupIdcom.tibco.bw/groupId
    artifactIdICBPIPhoneTopUpManagement.parent/artifactId
    version1.0/version
    relativePath..\ICBPIPhoneTopUpManagement.parent/relativePath
  /parent
  artifactIdICBPIPhoneTopUpManagement/artifactId
  packagingbwear/packaging
  build
    plugins
      plugin
        groupIdcom.tibco.plugins/groupId
        artifactIdbw6-maven-plugin/artifactId
        version1.2.2/version
        extensionstrue/extensions
        configuration /
      /plugin
    /plugins
  /build
/project

**BW6 SharedModule POM**
?xml version="1.0" encoding="UTF-8"?
project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  modelVersion4.0.0/modelVersion  
  groupIdit.findomestic/groupId
  artifactIdSharedHTTPResources/artifactId
  version1.0/version
  packagingbwmodule/packaging
  build
    sourceDirectorysrc/sourceDirectory
    outputDirectorytarget/classes/outputDirectory
    plugins
      plugin
        groupIdcom.tibco.plugins/groupId
        artifactIdbw6-maven-plugin/artifactId
        version1.2.1/version
        extensionstrue/extensions
      /plugin
    /plugins
  /build
/project

Does the error got resolved including 1.2.1 jar plugin?

thx
-

**Comment by ashutoshbhide** [comment]
@roccokp  
Can you please attach the POM files in the issue. The POM file text that you have put as part of the comment is not readable .

Thanks
-Ashutosh

**Comment by awagle** [comment]
Please re-open the issue with the requested information.

**Comment by anithareddycog** [comment]
can some one give a solution!!!!

**Comment by awagle** [comment]
@anithareddycog this issue is closed due to lack of information provided. If you have reproducible case please create a new issue with steps to reproduce the issue.
