### ISSUE TITLE
Question: Deploy a Shared Module as a jar to Maven repo and use in another application's Call Process activity?

### ISSUE THREAD

**Issue by jcabe** [TIBCOSoftware/bw6-plugin-maven#106]
We have a set of shared processes that are used to log data throughout the workflow of our BW application. We would like to compile those processes to a jar and host them in a Maven repository for other applications to use. Is this supported by TIBCO Business Works and the plugin?

Here are the steps we have followed using **Maven Eclipse Plugin 1.2.2**, **TIBCO BW 6.4.0**, and **Apache Maven 3.5.2**:

1. Deploy a Shared Module to a Maven Repository as a jar with a configured pom file.
2. In a BW application, add the Maven Repository to the project's pom file using the repositories section.
3. In a BW application, add the Maven Dependency for the Shared Module to the project's pom file using the dependencies section.
4. Build the BW Application via Maven with an install goal and observe as the Shared Module is downloaded from the Maven Repository. Note that the shared Module is now listed under Maven  Dependencies and that if you drill down in the project explorer you can see the processes you want to utilize. Also note that if you view the Java Build Path of the project that the dependency shows under the Libraries tab.
5. Add a Call Process activity to a process in the BW Application.
6. Select the activity and click the Properties tab.
7. Next to the Process Name click the magnifying glass/search icon.
8. In the popup window note that the Shared Module does not show. Note that you cannot find it via a partial or whole search.
9. Press cancel on the popup window.
10. Enter the name in the Process Name field as you would have referenced the Sub Module if it were part of the same workspace in a separate project.
11. Note the compile errors on the Problems tab indicating that the Shared Module service cannot be found.

Thanks for your time.

**Comment by HiteshNembhwani** [comment]
Could you please use BW 6.4.2 and Maven 1.3.0 version for your specific use-case and let us know if it helps?

**Comment by jcabe** [comment]
Hello, are you the same Hitesh who responded to the similar question we posted below on the TIBCO Community forum? If not then should we wait on the Maven plugin update as advised in the  response below?

https://community.tibco.com/questions/tibco-bw-64-it-possible-deploy-shared-module-jar-maven-repository-and-have-bw-application

>yes, this is feasible using the latest BW6 version - 6.4.2 released just today! Take a look at our documentation. 
>The existing 1.2.2 Maven version needs an update to support this feature and we'd upload the updated Maven version on Github this week. 
>Thank you,
>-Hitesh

**Comment by HiteshNembhwani** [comment]
yep @jcabe, I'm the same Hitesh who responded to you on the community :) You're good to verify your test case now - both BW 6.4.2 and Maven 1.3.0 versions are available now.

**Comment by jcabe** [comment]
Thanks Hitesh. I got confused between Apache Maven and Maven Plugin versions. We should be able to test this out next week after the holiday. I will update the two question locations once we have the results.

**Comment by awagle** [comment]
Have a look at https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/SharedModule for more information on how to do this in Studio. Please re-open the ticket if you still have questions.
