### ISSUE TITLE
Question: Builds for ADB adapters

### ISSUE THREAD

**Issue by kanigicharla8** [TIBCOSoftware/bw6-plugin-maven#107]
Hi, 

We are able to build the ear packages for the BW components, but are struggling to find a way to build the ear packages for ADB adapter component using the BW6 maven plugin.

Is there a recommendation on how to build ADB adapters using the bw6 maven plugin. Please advise.

Thanks.

Gupta Kanigicharla.

**Comment by awagle** [comment]
The maven plugin only builds BW6 or BWCE applications. It doesn't build adapter archives if that's what you are asking for.

**Comment by bloomfm100** [comment]
HI @awagle,
What specific action in relation is planned for the next release?   I understand the response to the question but not the planned "To Do" action?

**Comment by awagle** [comment]
@bloomfm100 this needs to be done by the Adapters Product. I recommend raising an support request for getting more information on timelines.

**Comment by awagle** [comment]
Please reach out to TIBCO Support for the Adapter to support maven. ADB needs to write its own maven plugin or contribute to this one.
