### ISSUE TITLE
bw6-maven-plugin:1.2.0 or one of its dependencies could not be resolved

### ISSUE THREAD

**Issue by vinisha91** [TIBCOSoftware/bw6-plugin-maven#110]
I am using BWCE 2.2.1.
I am trying to use Jenkins to check-out and build ear
While building the ear, I am getting below error. Please advise on how to integrate the plugin into Jenkins Maven build.
Locally i am able to build the ear in my linux machine, but in same linux when i set up jenkins and run I am getting following error :+1:
[new_job] Running shell script

/opt/apache-maven-3.3.9/bin/mvn -f simdetails_customer.application.parent/pom.xml clean package
[INFO] Scanning for projects...
[WARNING] The POM for com.tibco.plugins:bw6-maven-plugin:jar:1.2.0 is missing, no dependency information available
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin com.tibco.plugins:bw6-maven-plugin:1.2.0 or one of its dependencies could not be resolved: Failure to find com.tibco.plugins:bw6-maven-plugin:jar:1.2.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @
[ERROR] Unknown packaging: bwmodule @ com.tibco.bw:simdetails_customer:[unknown-version], /var/lib/jenkins/workspace/new_job/simdetails_customer/pom.xml, line 12, column 14
[ERROR] Unresolveable build extension: Plugin com.tibco.plugins:bw6-maven-plugin:1.2.0 or one of its dependencies could not be resolved: Failure to find com.tibco.plugins:bw6-maven-plugin:jar:1.2.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @
[ERROR] Unknown packaging: bwear @ com.tibco.bw:simdetails_customer.application:[unknown-version], /var/lib/jenkins/workspace/new_job/simdetails_customer.application/pom.xml, line 12, column 14
@
[ERROR] The build could not read 2 projects -> [Help 1]
[ERROR]
[ERROR] The project com.tibco.bw:simdetails_customer:1.0.0-SNAPSHOT (/var/lib/jenkins/workspace/new_job/simdetails_customer/pom.xml) has 2 errors
[ERROR] Unresolveable build extension: Plugin com.tibco.plugins:bw6-maven-plugin:1.2.0 or one of its dependencies could not be resolved: Failure to find com.tibco.plugins:bw6-maven-plugin:jar:1.2.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
[ERROR] Unknown packaging: bwmodule @ com.tibco.bw:simdetails_customer:[unknown-version], /var/lib/jenkins/workspace/new_job/simdetails_customer/pom.xml, line 12, column 14
[ERROR]
[ERROR] The project com.tibco.bw:simdetails_customer.application:1.0.0-SNAPSHOT (/var/lib/jenkins/workspace/new_job/simdetails_customer.application/pom.xml) has 2 errors
[ERROR] Unresolveable build extension: Plugin com.tibco.plugins:bw6-maven-plugin:1.2.0 or one of its dependencies could not be resolved: Failure to find com.tibco.plugins:bw6-maven-plugin:jar:1.2.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
[ERROR] Unknown packaging: bwear @ com.tibco.bw:simdetails_customer.application:[unknown-version], /var/lib/jenkins/workspace/new_job/simdetails_customer.application/pom.xml, line 12, column 14
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
My pom.xml that is added in the parent pom inlcudes the following ;

  <plugin>
        <groupId>com.tibco.plugins</groupId>
        <artifactId>bw6-maven-plugin</artifactId>
        <version>1.2.0</version>
        <extensions>true</extensions>
      </plugin>

My linux machine env variables are as follows
USERNAME=vagrant
MAVEN_HOME=/usr/share/maven
PATH=/sbin:/bin:/usr/sbin:/usr/bin
M2_HOME=/usr/share/maven

My jenkins configuration - Global tool Configuration

Default settings provider-/home/vagrant/.m2
Default global settings provider-/home/vagrant/.m2
MAVEN_HOME- /opt/apache-maven-3.3.9

Not able to find out what is my mistake here as locally mvn package works fine and gets me the ear.
Pls help

**Comment by fcenedes** [comment]
You are probably running jenkins with another username than "vagrant". therefore the maven repo does'nt match : M2-HOME.

so you have two choices, fix m2 repo to be the same, or install the plugin to be available from the jenkins user or any user used by your jenkins job.

**Comment by vinisha91** [comment]
Hi issue resolved :+1: 

The problem was ,it was trying to point to central repo and not to my local nexus where i had the  reuqired plugins.
All i had to do was under my MAVEN/HOME- conf/settings.xml, I pointed the <localrepository> to my .m2 repository and then added my nexus profile settings , which was available in .m2/settings.xml , to here and boom it worked fine , as it was able to fetch the plugins from my local nexus.
