### ISSUE TITLE
Publish BW Maven plugin to Maven Central

### ISSUE THREAD

**Issue by awagle** [TIBCOSoftware/bw6-plugin-maven#111]
Currently users have to install the maven plugin manually on the build server. By providing it on maven central, the installation part can be only localized for the Studio plugin. The actual build plugin can be pulled in from the central maven repository.

**Comment by ashutoshbhide** [comment]
Maven 2.0.0 Plugin is now hosted on Maven Central

**Comment by mshahat** [comment]
Could not resolve dependencies for project PROJECT NAME Could not find artifact com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100 in central (https://repo.maven.apache.org/maven2)
