### ISSUE TITLE
[Question]handle shared modules as dependencies

### ISSUE THREAD

**Issue by SamirCesium** [TIBCOSoftware/bw6-plugin-maven#113]
Hi Guys,

I use the last version of this plugin (1.3.0) with Tibco Business Works 6.4.2 in order to handle my Shared Module as a standard dependency and not as Module.

But When I transform my Application to Maven Project (by right clicking on the application and choosing  Generate POM for Application as indicated,  the generation updates the pom.xml of my SharedModule to transform it as a Module of the new Parent Project created. Hence, before generation I had:

TestCIModule
TestCIApp
SharedModule with a pom.xml independent of previous projects
After generation, I got

TestCIApp.parent
TestCIApp
TestCIModule
SharedModule with a pom.xml updated referencing the TestCIApp.parent as its parent !

To fix this:
I revert manually the pom.xml of my Shared Module to its previous state.
I modify the pom.xml of TestCIApp to inclue a dependency for my SharedModule.

Is it possible to add a such feature to the plugin, so during the generation of the pom.xml we are asked if the Shared Modules should be handled as dependencies or modules ?

Best Regrads,
Samir

**Comment by GAcharya1** [comment]
I'm encountering exact same behavior with maven plug-in v1.3.1 and want shared modules pom to not have reference to the application module. Instead, only application module pom should have reference to shared module. Any plans to fix this ?

**Comment by sonalshingavi** [comment]
Hi @SamirCesium 
**Handling the Shared Module as a standard dependency and not as Module**
Follow the following steps (try with the latest plugin TIB_BW_Maven_Plugin_2.0.1)

1) Create a shared module, generate POM for a shared module and run the shared module as maven 
     install.
2) After installing the shared module, the installed shared module will go into the .m2 repository 
    (path : ~\.m2\repository\com\tibco\bw).
3) Delete the shared module from the workspace.
4) Modify the pom.xml of your application module to include a dependency of your shared module.
    or you can follow https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/SharedModule

By following these steps, the shared module pom will no longer have any reference to the application module and only application module pom will have the reference to the shared module.

**Comment by sonalshingavi** [comment]
Closing the issue, Please re-open if this is still have a question with 2.0.1.
