### ISSUE TITLE
Refactor code for easy addition of new platforms 

### ISSUE THREAD

**Issue by zsurka** [TIBCOSoftware/bw6-plugin-maven#114]
The code for Maven Eclipse Plugin assumes a fixed set of platforms (PCF, docker and so on). This should be re-factored so that there is a set of classes for each platform. This would include their respective wizard pages as well. This will make the design flexible enough to easily contribute more platforms without risk of regressions.

**Comment by awagle** [comment]
@NidhiRajeshDhoka and @sonalshingavi  can you confirm this is now resolved with the upcoming release?
