### ISSUE TITLE
Gradle plugin

### ISSUE THREAD

**Issue by gaspo53** [TIBCOSoftware/bw6-plugin-maven#118]
Is there any chance to get this plugin for Gradle also?

Thanks

**Comment by mshahat** [comment]
Hi Gaspar, If you can expand a little on your need for using Gradle. is it just a customer situation who are using Gradle ? or you're looking for solving some pain with maven ? that would be useful feedback for some work taking place now.  Cheers,

**Comment by gaspo53** [comment]
Hi, Mohamed! Thank you for your answer.
I'm an engineer working on a TIBCO client, and we are migrating all projects from Ant/Maven to Gradle. That's why we'd like this plugin to be available in Gradle also.

**Comment by awagle** [comment]
This is being looked at actively. Closing this issue for now. This will be a different Github repository for the Gradle Plugin.

**Comment by AntAreS24** [comment]
@awagle @mshahat  any update on that plugin? I can't see the repo for this feature.

**Comment by awagle** [comment]
We are still working on it. The repo will be private until we have completed everything and have obtained all approvals.
