### ISSUE TITLE
BW6 Maven Plugin Issue

### ISSUE THREAD

**Issue by NNishikar** [TIBCOSoftware/bw6-plugin-maven#119]
Hi All,

We are facing an issue while building the code using Maven Plugin. The EAR which is generated does not contain the resources folder which has all process images, Hence when we deploy using the EAR generated by maven, we don't see process diagram on TEA.
We are using BW 6.4.2 and tried using 1.2.2 and 1.3.0 version of Maven Plugin.
In other threads someone mentioned it's expected behavior, Kindly confirm.

Thanks!!

**Comment by HiteshNembhwani** [comment]
@NNishikar please follow the steps as mentioned in the last comment on https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/78

**Comment by NNishikar** [comment]
@HiteshNembhwani 
Hi,
I tried the option mentioned in issue #78 , Generated the process diagram on studio, now i can see the resources folder under application but on build and deployment through Maven BW plugin 1.2.2, the Process diagram on TEA is still not coming up.
Please suggest.
Thanks

**Comment by HiteshNembhwani** [comment]
@NNishikar you need the Maven 1.3.0 version as mentioned on https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/78. Please give it a try using Maven 1.3.0 and BW 6.4.2 version and confirm, thanks.

**Comment by NNishikar** [comment]
@HiteshNembhwani It works, Thanks for your help

**Comment by HiteshNembhwani** [comment]
great! thanks for the confirmation @NNishikar. Will close this issue now.
