### ISSUE TITLE
Lack of support for environment variables

### ISSUE THREAD

**Issue by mhale** [TIBCOSoftware/bw6-plugin-maven#12]
Hi,

In a PCF manifest.yml file, environment variables are set like this:

```
env:
  BW_LOGLEVEL: ERROR
  BW_PROFILE: PCF
```

There is no currently support for setting these values in the plugin, or reading them from the properties files. Instead they need to be hardcoded in the pom.xml like this:

```
<env>
  <BW_LOGLEVEL>ERROR</BW_LOGLEVEL> 
  <BW_PROFILE>PCF</BW_PROFILE> 
</env>
```

This means it is impossible to use different values in different environments, defeating the purpose of using environment variables in the first place.

Could the ability to set environment variables in properties files and dialogs be added to this plugin please.

Thanks.

**Comment by roagarwal** [comment]
That's correct, this plugin right now doesn't support environment variables, for now as you rightly mentioned you can hard-code them using <env> tag in your pom.xml of application project. We will going to add this feature in our next release.  Thanks.

**Comment by ukuppa-tibco** [comment]
We do support environment variables now when the deployment mode is Docker/PCF.
