### ISSUE TITLE
Maven plugin Version updates are not reflecting in dependent modules

### ISSUE THREAD

**Issue by adityagali** [TIBCOSoftware/bw6-plugin-maven#120]
Hi,

   Upgraded maven plugin version from 1.2.2 to 1.3.0 and regenerated POM. Version is updated to 1.3.0 of maven plugin dependency in “*.application” POM.xml file. But,not updating in POM.xml files of dependent modules that were included in the “*.application”.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->
Maven Plugin version:1.3.0.002

Maven version:3.3.9

Product : TIBCO Businessworks Container edition

Product version: 2.3.2

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1. Install latest plugin version.
2. Generate POM
3. Dependency version is unchanged on POM files of dependent modules

**Additional environment details if any:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by ashutoshbhide** [comment]
Hi @adityagali 
This is now fixed with 1.3.1 release. If the problem still persists do let us know. I am closing this issue as of now.
