### ISSUE TITLE
Maven Build failing with Package does not exist

### ISSUE THREAD

**Issue by banapart** [TIBCOSoftware/bw6-plugin-maven#121]
Maven Plugin version: 1.2.0

Maven version: 3.5.0

Product : TIBCO ActiveMatrix Businessworks 6

Product version: 6.3.5

Component: Maven Build Plugin.

Hi,

I am trying to build a BW6 project with maven build and the maven build is failing because it can not find the dependent Jar files. 

The following is the error message. 

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.049 s
[INFO] Finished at: 2018-01-19T14:45:44+05:30
[INFO] Final Memory: 19M/272M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project int.common.dlq.server.md: Compilation failure: Compilation failure:
[ERROR] /C:/TUI/Repo/int.picr.common.dlq/src/main/bw6/int.common.dlq.server.md/src/tui/common/dlq/server/undelivered/EMSUndeliveredRouter.java:[21,24] package com.tibco.tibjms does not exist
[ERROR] /C:/TUI/Repo/int.picr.common.dlq/src/main/bw6/int.common.dlq.server.md/src/tui/common/dlq/server/undelivered/BWEMSUndeliveredRouter.java:[25,55] package com.tibco.security does not exist
[ERROR] /C:/TUI/Repo/int.picr.common.dlq/src/main/bw6/int.common.dlq.server.md/src/tui/common/dlq/server/undelivered/EMSUndeliveredRouter.java:[267,17] cannot find symbol
[ERROR]   symbol:   class TibjmsQueueConnectionFactory
[ERROR]   location: class tui.common.dlq.server.undelivered.EMSUndeliveredRouter
[ERROR] /C:/TUI/Repo/int.picr.common.dlq/src/main/bw6/int.common.dlq.server.md/src/tui/common/dlq/server/undelivered/EMSUndeliveredRouter.java:[267,60] cannot find symbol
[ERROR]   symbol:   class TibjmsQueueConnectionFactory
[ERROR]   location: class tui.common.dlq.server.undelivered.EMSUndeliveredRouter
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :int.common.dlq.server.md

I am unable to add these jars to the dependencies as they are not found by searching in dependency manager. 

Please help me resolve this issue.

Thanks,
Narasimha Babu Anaparthi.

**Comment by awagle** [comment]
Please re-open with information requested by @ashutoshbhide

**Comment by nagoriyn** [comment]
I am getting the same error
 Compilation failure:
[ERROR] /C:/Code/BW6/MyWorkspace/zb-file-watch-utility/zb-file-watch-utility/src/Services/Process/FTPMonitoringAlertOperation/pwdDecryptor.java:[2,26] package com.tibco.security does not exist
[ERROR] /C:/Code/BW6/MyWorkspace/zb-file-watch-utility/zb-file-watch-utility/src/Services/Process/FTPMonitoringAlertOperation/pwdDecryptor.java:[28,25] cannot find symbol
[ERROR]   symbol:   variable ObfuscationEngine
[ERROR]   location: class Services.Process.FTPMonitoringAlertOperation.pwdDecryptor

I am using the java invoke activity and I used the imported package to get com.tibco.security.
there is no error in runtime but when i am building EAR using maven getting this eror.
