### ISSUE TITLE
Service startup issue post deployment using BW6 maven plugin

### ISSUE THREAD

**Issue by NNishikar** [TIBCOSoftware/bw6-plugin-maven#122]
Hi, 
The services are not starting up post deployment using latest Maven BW 6 plugin 1.3.0, BW version 6.4.2.
It used to work fine with bw6 plugin 1.2.2, but we upgraded to 1.3.0 because earlier the process diagram were not coming up on TEA. Kindly suggest.

PFB the appnode logs:

WARNING: exception with message ***Error starting application [HIP.OA.ConcurEmployee:2.0]*** has not been localized: TIBCO-BW-ADMIN-500444: Failed to start Application in AppNode [AN1FRHIPMDVESB01]. Check the AppNode log files for messages starting with TIBCO-THOR-FRWK, TIBCO-BW-FRWK, or TIBCO-BW-SR-FRWK for details. Application State [StartFailed], reason : TIBCO-THOR-FRWK-500201: Failed to start bundle [HIP.OA.ConcurEmpExpense.module_2.0.1.201801291131 [631]], <CausedBy> Could not resolve module: HIP.OA.ConcurEmpExpense.module [631] Unresolved requirement: Require-Capability: com.tibco.bw.module; filter:="(&(name=HIP.ESB.ProjectTemplate)(version=2.0.0))"

**Comment by ashutoshbhide** [comment]
Hi @NNishikar 

Can you please try with the Maven 1.3.1 release.
If it still doesnt work then can you upload your project which we can test at our end.

-Ashutosh

**Comment by awagle** [comment]
Please re-open if this is doesn't work with latest version as requested by @ashutoshbhide

**Comment by NNishikar** [comment]
@ashutoshbhide It doesn't work even with the latest version :(

**Comment by ashutoshbhide** [comment]
@NNishikar  Let me check and get back to you.

**Comment by RakeshNayakR** [comment]
@ashutoshbhide Any update on the above issue?

**Comment by mpaithan** [comment]
@ashutoshbhide  any updates on this issue. ? I am facing the similar problem.
