### ISSUE TITLE
repo name

### ISSUE THREAD

**Issue by mshahat** [TIBCOSoftware/bw6-plugin-maven#123]
Hi, 

With the maven plugin supporting both bw6 and bwce, this is a suggestion to refactor the repo name to reflect that ? 

Thanks,
/M

**Comment by ashutoshbhide** [comment]
@rahulkamdar 

Do you want to comment on this one?

-Ashutosh

**Comment by rahulkamdar** [comment]
Yes, we will review this.

**Comment by awagle** [comment]
Based on discussion we aren't changing the repo name as of now.
