### ISSUE TITLE
binaries to github repo releases

### ISSUE THREAD

**Issue by mshahat** [TIBCOSoftware/bw6-plugin-maven#124]
Hi, 

Can we have the releases ( installer binaries ) going to github repo releases https://help.github.com/articles/creating-releases/ as binaries for separate download ? that would keep the git repo to source code. 

Thanks,

**Comment by ashutoshbhide** [comment]
Hi @mshahat 

We are in process of changing the download experience. Will keep you updated.

-Ashutosh

**Comment by awagle** [comment]
Duplicate of #111 . We will be publishing binaries to Maven Central.
