### ISSUE TITLE
Maven plugin for BW6.3 sets the application version of the Shared Module instead of the Application

### ISSUE THREAD

**Issue by pedro-jorge-pereira** [TIBCOSoftware/bw6-plugin-maven#13]
Hi,

Problem:

When generate an EAR using Maven package goal, the version of the application inside the EAR is set to the version of the Shared Module instead of the version of Application.

Expectation:

On our real project several applications have the same Shared Modules as dependency. We can’t change the version of Shared Modules since they have their own lifecycle.

Evidence:

 Tea Application Version 3.0.0.datetime
![Image of tea_application_version.png](http://i1084.photobucket.com/albums/j401/Pedro_Jorge_Pereira/tea_application_version_zpsgn1hmcqs.png)

 Application Version 5.0.0.datetime
![Image of Application_Overview.png](http://i1084.photobucket.com/albums/j401/Pedro_Jorge_Pereira/Application_Overview_zpsnqac3iej.png)

Application Module Version 5.0.0.datetime
![Image of ApplicationModule_Overview.png](http://i1084.photobucket.com/albums/j401/Pedro_Jorge_Pereira/ApplicationModule_Overview_zps0n9xs5oh.png)

Shared Module Version 3.0.0.datetime
![Image of SharedModule_Overview.png](http://i1084.photobucket.com/albums/j401/Pedro_Jorge_Pereira/SharedModule_Overview_zpsljpesq7v.png)

How to reproduce:
0.	Pre-requisites:

	 a.	Maven installed
	 b.	BW Maven Plug-in installed (https://github.com/TIBCOSoftware/bw6-plugin-maven)
	 c.	BW 6.3.0 HF2

1.	Create a new workspace called workspace_sr_maven

2.	Import sr_maven.zip(https://drive.google.com/open?id=0B9RIgsiVuX1EZExrT2xwVzdZZ0E) with projects into that new workspace.

3.	Right-Click on ServiceProject.application and select “Generate POM from Application”. The version of this module is 5.0.0.qualifier.
	![Image of Generate POM from Application](http://i1084.photobucket.com/albums/j401/Pedro_Jorge_Pereira/Generate_POM_Application_zpsbpmwpcbh.png)

4.	Open Run/Debug Configurations. Create a new Maven Build.

5.	Under the "Base directory" choose add variable for Workspace location. The variable name is ${workspace_loc}.

6.	In the Goal enter the Goal to be executed: package

7.	Click Debug. This will create the EAR file in the target folder under the Application project - 'Refresh' your project using the right-click menu if this folder is not visible.

8.	Upload the ServiceProject.application_5.0.0.ear into TEA and check that the application version is wrong (3.0.0.datetime instead of 5.0.0.datetime).

Regards,
Pedro

**Comment by pedro-jorge-pereira** [comment]
Hi,

Please check the following code of the addModules() method that fixes the wrong Bundle-Version of the EAR Manifest file.

**### BWEARPackagerMojo.java**
```java
/**
     * Adds the Modules included in the Application to the EAR file. 
     * It will also maintain a Module vs Version map which will be used later by the Application 
     * to populate the TIBCO.xml
     *  
     * @throws Exception
     */
    private void addModules() throws Exception
    {
    	try
    	{
        	getLog().debug("Adding Modules to the Application EAR");

        	// The fist artifact is an Application Module.
        	boolean isApplicationModuleArtifact = true;
        	BWModulesParser parser = new BWModulesParser(session, project);
        	String bwEdition = manifest.getMainAttributes().getValue("TIBCO-BW-Edition");
        	parser.bwEdtion=bwEdition;
        	List<Artifact> artifacts = parser.getModulesSet();
        	
            for( Artifact artifact : artifacts )
            {
                
                //Find the Module JAR file
                File moduleJar = artifact.getFile();
                
                
                //Add the JAR file to the EAR file
                jarchiver.addFile( moduleJar ,  moduleJar.getName() );
                
                String version = BWProjectUtils.getModuleVersion(moduleJar);
                
                getLog().debug( "Adding Module JAR with name " + moduleJar.getName() + "  with version " + version );
                
                //Save the module version in the Version Map.
                moduleVersionMap.put(  artifact.getArtifactId() , version );
                
                if (isApplicationModuleArtifact)
                {
                	this.version = version;
                	isApplicationModuleArtifact=false;
                }
            }        
    		
    	}
    	catch(Exception e )
    	{
    		getLog().error("Failed to add modules to the Application");
    		throw e;
    	}
    }
}
```

Instead of set the Bundle-Version from the last artifact ( that can be a BW ShareModule), set the Bundle-Version from the first artifact (an Application Module).

Regards,
Pedro

**Comment by fanninj3** [comment]
Hi,
Will this fix be integrated into the next release of the plugin?

**Comment by RajibBiswasTibco** [comment]
Pull Request # 15 taken, which fixed this issue.
