### ISSUE TITLE
How to upgrade the plugin?

### ISSUE THREAD

**Issue by asatsi** [TIBCOSoftware/bw6-plugin-maven#131]
Can I upgrade the plugin from 1.1.0 to 1.3.0? If yes how? Also how can I remove/uninstall the plugin?

**Comment by Strickmabil** [comment]
I have the same question. And btw, is there any documentation on the plugin goals besides that poor help section on the Wiki page?

**Comment by asatsi** [comment]
@Strickmabil as you can see nobody responds! I figured out that you can still go ahead and install the latest plugin. That way you will have both the versions installed on your machine. The individual pom.xml files for your project/modules should have the required version mentioned so that your maven run will pick up the mentioned version of the plugin.
e.g. 
<plugin>
        <groupId>com.tibco.plugins</groupId>
        <artifactId>bw6-maven-plugin</artifactId>
        <version>1.3.1</version>
        <extensions>true</extensions>
      </plugin>

**Comment by Strickmabil** [comment]
Thanks for your help. Done it... seems to work.
