### ISSUE TITLE
Error creating pom.xml file in OS Windows, the character "\" is wrong

### ISSUE THREAD

**Issue by ljferrero** [TIBCOSoftware/bw6-plugin-maven#134]
Maven Plugin version: 1.3.0

Maven version: 3.3.3

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version: BW 6.4.2 or BWCE 2.3.2 

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1.Create project HelloWorld with Business Studio in Windows 7
2.Apply the plugin to project HelloWorld in Business Studio (Generate POM for Application)
3.Execute command in linux -> mvn org.codehaus.mojo:versions-maven-plugin:2.3:set -DnewVersion=1.0.5

**Additional environment details if any:**
OS Windows 7

**Describe the results you received:**
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
	<groupId>com.tibco.bw</groupId>
	<artifactId>HelloWorldDocker.parent</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>
<modules>
    <module>..\HelloWorldDocker.module</module>
    <module>..\HelloWorldDocker</module>
</modules>
</project>

**Describe the results you expected:**
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
	<groupId>com.tibco.bw</groupId>
	<artifactId>HelloWorldDocker.parent</artifactId>
	<version>1.0.5</version>
	<packaging>pom</packaging>
<modules>
    <module>../HelloWorldDocker.module</module>
    <module>../HelloWorldDocker</module>
</modules>
</project>

**Additional information you deem important (e.g. issue happens only occasionally):**
The maven plugin for BW doesn't build pom.xml file correctly using windows.
All the pom.xml files that are generated have the same error.
Each of the pom.xml files of the module project and of the aplication project in the tag <relativePath>..\Proyect.parent</relativePath> have an error: the character "\" is NOT ok, the right character should be "/".
For the file pom.xml of parent project  the etiquete <module>..\Project.module</module> have an error, the character "\" in not OK, the character correct should be "/".
Note : If the project is created in Business Studio for Linux all is working ok, because the character used  is "/"

**Comment by SonaliDasgupta** [comment]
@ljferrero Could you please try this with release 2.0.1 of BW6 Maven Plugin ? The issue is not reproducible at my end. The POM files generated do not show any error, since the file separator character is appropriately chosen according to the OS ( '\' for Windows and '/' for Linux ). If this issue is still reproduced at your end, could you please attach the project ?

**Comment by osdomin** [comment]
The separator shouldn't be according to the OS but always '/' because otherwise the build is SO dependent. '/' separator works in Windows and Linux.

**Comment by SonaliDasgupta** [comment]
Resolved from Release 2.0.2 onwards.
