### ISSUE TITLE
BW 6.4.1 Maven build bundle version not updated as application version

### ISSUE THREAD

**Issue by fcologno** [TIBCOSoftware/bw6-plugin-maven#135]
We're facing an issue during the maven build for an application in TIBCO BusinessWorks 6.4.1.

**Prerequisites:**

1 TIBCO BusinessStudio (BW 6.4.1)
2 Maven Plugin for BusinessStudio (1.2.1)
3 Application Project - CardManagement_1.0.0.zip (attached below)
[CardManagement_1.0.0.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/1788651/CardManagement_1.0.0.zip)

We're trying to change the application version with the following **steps**:

1 Change Application version in Overview from 1.0.0.qualifer to 1.1.0.qualifer (same in the application and module)
2 Change Lifecycle version from 1.0.0.qualifer to 1.1.0.qualifer (same in the application and module)
3 Re-generate POM for application.
4 Run Maven build from BusinessStudio

When we run the maven build, the bundle version in MANIFEST.MF for the application archive is not upgraded and it remains to 1.0.0

**Comment by sonalshingavi** [comment]
Hi @fcologno , Can you try upgrading maven Plugin to 1.3.1 and try again?

**Comment by awagle** [comment]
Please re-open if this is still an issue with 1.3.1
