### ISSUE TITLE
Create SharedModule as Jar with custom name

### ISSUE THREAD

**Issue by thiyagu19841** [TIBCOSoftware/bw6-plugin-maven#138]
We are in the process of generating dependency jars for all our Shared Modules; but the jars are getting created like this <jar name>_<version> by default..   However, we are expecting jar should be created in the format <jar name>-<version>..  I tried to update POM.xml to generate jar with custom name by including fileName in POM.xml; still jar is getting created with underscore (_) instead of hypen (-)..   Please help me on this..

Thanks & regards,
Thiyagu..

**Comment by ankitapandey1** [comment]
Hi Thiyagu,

Is there a specific business requirement to change the format of generated jar file.
If yes we can make code changes to get the format from properties file.

Please confirm.

**Comment by thiyagu19841** [comment]
I found work around from our jenkins script itself; so we are good to close this
