### ISSUE TITLE
Generate EAR artifact from bwapp that uses custom plug-in

### ISSUE THREAD

**Issue by Scallone** [TIBCOSoftware/bw6-plugin-maven#139]
Maven Plugin version: 1.3.1
Maven version: 3.3.9
Product : TIBCO ActiveMatrix Businessworks CE
Product version: 2.3.2
Component: Maven build plugin

Our project consists of: 

* BW application 
* BW application module
* BW shared module called  
* BW plug-in called "custom.jdbc.driver" . Note: this custom plug-in was developed by tibco engineering team, and the goal was to make a jdbc wrapper / adapter with teradata server instance

The EAR generated manually is OK, the docker image containing this is OK, the business functionality involving these assests has been for months in production without major issues.

However, when we try to automate the build and deploy by using maven plug-in, we are experiencing serious issues: we are unable to even compile and build the code into the EAR.

When we do a run / debug config within the studio, for maven, with goals like "initialize clean package", we encounter the following error (full trace also attached) 

But when we explore the plug-in, we can see under "Plug-in dependencies" the package which maven seems unable to find / locate (see also attached screen cap). 
![image](https://user-images.githubusercontent.com/30195595/38942753-f043006a-432f-11e8-9653-d79370ad6ef5.png)

By exploring the custom plugin pom file, we find no dependencies whatsoever. So we believe that these package dependencies are not being passed to the pom.xml for the custom plugin, so when compiling it does not know that it needs also to copy these jars to its workspace. 

¿Could you give us a hand with this? Have you encountered this behaviour earlier when using maven plugin to generate artifacts that use custom plugins?

Detail for the error (full trace attached) [studio-maven-build-trace-error.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/1924757/studio-maven-build-trace-error.txt)
 
[ERROR] COMPILATION ERROR : 
[INFO] ------------------------------------------------------------- 
[ERROR] /C:/TIBCOBWCE_repo/custom.jdbc.driver/src/custom/jdbc/driver/CustomDataSourceFactory.java:[19,29] package org.osgi.service.jdbc does not exist 
[ERROR] /C:/TIBCOBWCE_repo/custom.jdbc.driver/src/custom/jdbc/driver/CustomDataSourceFactory.java:[28,49] cannot find symbol 
symbol: class DataSourceFactory 
[ERROR] /C:/TIBCOBWCE_repo/custom.jdbc.driver/src/custom/jdbc/driver/CustomDataSourceFactory.java:[36,9] method does not override or implement a method from a supertype 
[ERROR] /C:/TIBCOBWCE_repo/custom.jdbc.driver/src/custom/jdbc/driver/CustomDataSourceFactory.java:[49,9] method does not override or implement a method from a supertype 
[ERROR] /C:/TIBCOBWCE_repo/custom.jdbc.driver/src/custom/jdbc/driver/CustomDataSourceFactory.java:[60,9] method does not override or implement a method from a supertype 
[ERROR] /C:/TIBCOBWCE_repo/custom.jdbc.driver/src/custom/jdbc/driver/CustomDataSourceFactory.java:[71,9] method does not override or implement a method from a supertype 
[ERROR] /C:/TIBCOBWCE_repo/custom.jdbc.driver/src/custom/jdbc/driver/CustomDataSourceFactory.java:[84,50] cannot find symbol 
symbol: variable DataSourceFactory 
location: class custom.jdbc.driver.CustomDataSourceFactory 
[ERROR] /C:/TIBCOBWCE_repo/custom.jdbc.driver/src/custom/jdbc/driver/CustomDataSourceFactory.java:[85,53] cannot find symbol 
symbol: variable DataSourceFactory 
location: class custom.jdbc.driver.CustomDataSourceFactory 
[ERROR] /C:/TIBCOBWCE_repo/custom.jdbc.driver/src/custom/jdbc/driver/CustomDataSourceFactory.java:[86,51] cannot find symbol 
symbol: variable DataSourceFactory 
location: class custom.jdbc.driver.CustomDataSourceFactory 
[ERROR] /C:/TIBCOBWCE_repo/custom.jdbc.driver/src/custom/jdbc/driver/CustomDataSourceFactory.java:[87,53] cannot find symbol 
symbol: variable DataSourceFactory 
location: class custom.jdbc.driver.CustomDataSourceFactory 
[ERROR] /C:/TIBCOBWCE_repo/custom.jdbc.driver/src/custom/jdbc/driver/CustomDataSourceFactory.java:[90,51] cannot find symbol 
symbol: variable DataSourceFactory 
location: class custom.jdbc.driver.CustomDataSourceFactory 
[ERROR] /C:/TIBCOBWCE_repo/custom.jdbc.driver/src/custom/jdbc/driver/CustomDataSourceFactory.java:[91,55] cannot find symbol 
symbol: variable DataSourceFactory 
location: class custom.jdbc.driver.CustomDataSourceFactory 
[ERROR] /C:/TIBCOBWCE_repo/custom.jdbc.driver/src/custom/jdbc/driver/CustomDataSourceFactory.java:[121,50] cannot find symbol 
symbol: variable DataSourceFactory 
location: class custom.jdbc.driver.CustomDataSourceFactory 
[ERROR] /C:/TIBCOBWCE_repo/custom.jdbc.driver/src/custom/jdbc/driver/CustomDataSourceFactory.java:[122,53] cannot find symbol 
symbol: variable DataSourceFactory 
location: class custom.jdbc.driver.CustomDataSourceFactory 
[ERROR] /C:/TIBCOBWCE_repo/custom.jdbc.driver/src/custom/jdbc/driver/CustomDataSourceFactory.java:[123,51] cannot find symbol 
symbol: variable DataSourceFactory 
location: class custom.jdbc.driver.CustomDataSourceFactory 
[ERROR] /C:/TIBCOBWCE_repo/custom.jdbc.driver/src/custom/jdbc/driver/CustomDataSourceFactory.java:[124,53] cannot find symbol 
symbol: variable DataSourceFactory 
location: class custom.jdbc.driver.CustomDataSourceFactory 
[ERROR] /C:/TIBCOBWCE_repo/custom.jdbc.driver/src/custom/jdbc/driver/CustomDataSourceFactory.java:[127,51] cannot find symbol 
symbol: variable DataSourceFactory 
location: class custom.jdbc.driver.CustomDataSourceFactory 
[ERROR] /C:/TIBCOBWCE_repo/custom.jdbc.driver/src/custom/jdbc/driver/CustomDataSourceFactory.java:[128,55] cannot find symbol 
symbol: variable DataSourceFactory 
location: class custom.jdbc.driver.CustomDataSourceFactory

**Comment by HiteshNembhwani** [comment]
Hello @Scallone 

The Custom Datasource is not packaged with the EAR file. 

Also our Maven POM generation wizard doesn't yet support POM file generation for this. 

So for this you need to separately create the POM file like shown below. 

Replace the text between {{ }}

<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
    <groupId> {{Group Id}} </groupId>
    <artifactId> {{ Bundle Name}} </artifactId>
    <version>1.0.0-SNAPSHOT</version>
  <packaging>bwmodule</packaging>
  
  <build>
    <sourceDirectory>src</sourceDirectory>
    <outputDirectory>target/classes</outputDirectory>
    <plugins>
      <plugin>
        <groupId>com.tibco.plugins</groupId>
        <artifactId>bw6-maven-plugin</artifactId>
        <version>1.3.1</version>
        <extensions>true</extensions>
      </plugin>
    </plugins>
  </build>
</project>

There are two options to compile the CustomDataSourceFactory factory class and needs the following JAR to compile. 
tibco.home/bw/6.5/system/shared/org.osgi.service.jdbc_5.0.0.001/lib/org.osgi.service.jdbc.jar

1. Create a folder with name like mavenlib to the bundle. Add the JAR inside this folder. 
Make sure that the JAR is not added to Bundle-ClassPath attribute in the MANIFEST.MF.
Also the folder and JAR is not added to the build.properties.

This will ensure the JAR is only used by Maven for compilation but not packaged or referenced during the Runtime. In this case the POM file will remain unchanged.

2. Publish the JAR to local Maven Repository.
mvn install:install-file -Dfile=org.osgi.service.jdbc.jar -DgroupId=com.tibco.plugins -DartifactId=org.osgi.service.jdbc -Dversion=5.0.0 -Dpackaging=jar
Then add the following entry to the POM file
<dependencies>
    <dependency>
      <groupId>com.tibco.plugins</groupId>
      <artifactId>org.osgi.service.jdbc</artifactId>
      <version>5.0.0</version>
    </dependency>
  </dependencies>

 This will again do the compilation

**Comment by Scallone** [comment]
Thank you @HiteshNembhwani, 

By manually adding the dependency and publishing the jar file to our local maven repo it worked. By replicating this local maven repo to our jenkins maven agent so that all the dependencies are available, it did also work in our ci pipeline.

I will close this issue,

Regards,
