### ISSUE TITLE
com.tibco.plugins:bw6-maven-plugin:1.0.0 or one of its dependencies could not be resolved

### ISSUE THREAD

**Issue by neethuabu** [TIBCOSoftware/bw6-plugin-maven#14]
After creating the maven build and running it for creating package i get the following errors

[INFO] Scanning for projects...
[INFO] Downloading: https://repo.maven.apache.org/maven2/com/tibco/plugins/bw6-maven-plugin/1.0.0/bw6-maven-plugin-1.0.0.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin com.tibco.plugins:bw6-maven-plugin:1.0.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.tibco.plugins:bw6-maven-plugin:jar:1.0.0 @ 

I notice the path : https://repo.maven.apache.org/maven2/com/tibco is invalid. 

Any idea how to solve this?

**Comment by uportalis** [comment]
When I run from TIBCO BW Studio as described  in the documentation it just work.

When I run from command line, I get:
`[ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:1.1.0:bwmodule (default-bwmodule) on project tibco.bw.sample.core.soa.CallProcessAndInvoke: Execution default-bwmodule of goal com.tibco.plugins:bw6-maven-plugin:1.1.0:bwmodule failed: An API incompatibility was encountered while executing com.tibco.plugins:bw6-maven-plugin:1.1.0:bwmodule: java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getRepositorySession()Lo
rg/eclipse/aether/RepositorySystemSession;`

It looks like this plugin is not compatible with my version of Maven (3.0.5). It should be documented.

When I run `mvn install` from another computer, I get the same error as reported (`Failed to read artifact descriptor for com.tibco.plugins:bw6-maven-plugin:jar:1.1.0`).

**Comment by uportalis** [comment]
The plugin installer puts plugin JARs and POMs into your local default Maven repository (C:\User\myself\.m2\repository/com/tibco/plugins.
So, if you run from another computer or user, the plugin modules won't be found.

I found a workaround:
To solve this, you have to update your Maven settings.xml file to point to a repository that contain the JARs.
You could also upload the JARs to an in-house Maven repository server (e.g. JFrog Artifactory) and update your Maven settings.xml file to point to that repository.

**Comment by tcosley** [comment]
I think it would be really nice (and better conform to maven convention for open source plugins) if you were to establish public maven release and snapshot repositories for this project (and/or get releases cached on maven central)  so that we can reference from our poms or settings.xml and pull the plugin the usual way..

I guess there would still be an install step for the Studio aspect of it - but speaking in terms of Eclipse convention it would be nice (and better conform to Eclipse convention) to provide the Studio plugin from a TIBCO/Studio Eclipse update site..

**Comment by neethuabu** [comment]
This was a proxy issue, I setup proxy in m2 settings.xml and it was resolved
