### ISSUE TITLE
BW6 Maven Project with External Dependency 

### ISSUE THREAD

**Issue by Chetan-Vatharkar** [TIBCOSoftware/bw6-plugin-maven#140]
I have to use an external CustomFunction's jar as a dependency into my BW6 Maven Project. How can I do that?

**Comment by HiteshNembhwani** [comment]
@Chetan-Vatharkar have a look at this https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/SharedModule

**Comment by Chetan-Vatharkar** [comment]
@HiteshNembhwani ...  I have created one java plugin project-> with "Custom XPath Function Group" as template, this project takes 2 numbers as input and returns the sum. I converted this project to maven and uploaded it to artifactory.
I have to use this as a dependency into my BW6 Maven Project.

**Comment by awagle** [comment]
@Chetan-Vatharkar to use Custom XPath functions at design time, you have to install them in Studio. The maven plugin only packages them for runtime usage when building an EAR file.

Please re-open if your query is not solved.

**Comment by VarinderSandhu** [comment]
@HiteshNembhwani  @awagle I have created 2 shared modules and 1 xpath plugin project and exported plugin as jar file " https://docs.tibco.com/pub/bwce/2.5.4/doc/html/GUID-13795D07-F63C-4B27-8A6B-9E620A74BB16.html " .then i executed mvn install  "mvn install:install-file -Dfile=C:/CodeBase/2020/BWCEGit/gb8_bwce/lib/plugins/common.xpath.shared_1.0.0.jar -DgroupId=com.tibco.bw -DartifactId=common.xpath.shared -Dversion=1.0.0 -Dpackaging=jar" .

I can see this created in .m2 repository , but is not getting packages in ear file when i run "mvn package" on parent application folder , it only includes both shared module ignoring xpath plugin jar , but it adds when i build from studio . Any idea how to add custom xpath plugin in jar using maven for bwce 2.5.3.
