### ISSUE TITLE
Problems with XMLtoJava and JavaToXML activities

### ISSUE THREAD

**Issue by IsabelLeon** [TIBCOSoftware/bw6-plugin-maven#142]
Hi, 
I have attached three projects. 

Test1 --> It's a BW Application (Convert to Maven Project). I have used Plug-in maven for Tibco 1.3.0
Test2 --> It's a BW Application (Convert to Java Project).
SortMultiNode --> It's a Java Project. It has the class Java that i'm going to use in XMLtoJava and JavaToXML activities.

Test1 and Tes2 are the equal. The only difference one of then is converting to Maven Project and the other is converting to Java Project. 

In Test2 everything is OK. The "com.staffware.util.Item.xsd" file is created in "schemas" when i configured the "XMLToJava" activity. I can to do all maps in SubProcess.

In Test1 I have some problems. The "com.staffware.util.Item1.xsd" is created in "schemas" when i configure "XMLToJava" activity. But I can't to Load the "com.staffware.util.item" class. I think the problem it's because there aren't namespace in the xsd. 

Regards Isabel. 

[projects.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/1970107/projects.zip)

**Comment by NidhiRajeshDhoka** [comment]
@IsabelLeon I made a similar new project,as your project was of older version.I could load the "com.staffware.util.item" class in the XMLToJava activity..But yes,I found out that the schema do not have namespace if the class is in the maven repository.I'll look into it.

**Comment by NidhiRajeshDhoka** [comment]
@IsabelLeon  ,please contact TIBCO support for this issue,because the fix for this defect will be done in BW product specific code.

**Comment by NidhiRajeshDhoka** [comment]
This issue is arised because of jaxb framework(used for schema generation in BW java palette) which does not pick up the namespace URI for Maven project specific classes.So to fix this we need to configure jaxb overriden methods accordingly in BW palette code.Right now we do not have a immediate fix for this.We can have a JIRA  for this, which can be related by a JIRA already raised AMBW-27026.We can keep the GH issue closed as we do not want to make changes in Maven plugin code to fix this.

**Comment by alexandrev** [comment]
@IsabelLeon, have you or someone from your team opened the SR? In case you don't, just let me know it and I'll do it and we'll handle from there.

**Comment by IsabelLeon** [comment]
I just opened the SR 01661850

**Comment by alexandrev** [comment]
Thanks Isabel, I'll work with you and support to solve this issue asap.
