### ISSUE TITLE
bwdocker.host=tcp://0.0.0.0:2376

### ISSUE THREAD

**Issue by mshahat** [TIBCOSoftware/bw6-plugin-maven#145]
Hi team, 

plugin v1.3.1 

the default install generate docker-dev.properties and docker-prod.properites. Both are having 
`bwdocker.host=tcp://0.0.0.0:2376`

which version of docker was this tested against or expected to support?

we had to change to the following to get it to work
`bwdocker.host=unix:///var/run/docker.sock`

tested also with the following which is the non TLS option, but also didn't work. 
`bwdocker.host=tcp://0.0.0.0:2375`

docker version 18.x

thanks,

**Comment by awagle** [comment]
Related to #157

**Comment by awagle** [comment]
A new preference page is added via pull request #160
