### ISSUE TITLE
[QUESTION] When building the source, how do I resolve missing dependencies in the plugin.xml file of bw6.studio.maven.plugin?

### ISSUE THREAD

**Issue by jcabe** [TIBCOSoftware/bw6-plugin-maven#152]
I have downloaded the source code but when I attempt to compile there are errors on the Dependencies tab of the plugin.xml file in the bw6.studio.maven.plugin project.

How can I resolve these missing dependencies? I tried adding the required jars to the build path of the project but this does not resolve the issue.

**Comment by retgits** [comment]
Hi Jason, good question!

I'm guessing you've installed it in TIBCO Business Studio? In that case, you'll need to set up TIBCO Business Studio as Dev environment. 
 
Following are steps :
1. Configure the Studio as Dev eclipse. 
Go to Preferences -> Target Platform 
Remove existing target definition and Click Add.
Select "Default : Default target for running platform". Click Next --> Finish. 
 
2. Import the cloned source code. It should now be possible to compile the source code.

**Comment by jcabe** [comment]
Thanks! Going to Window > Preferences  then Plug-in Development > Target Platform and following your instructions resolved the issue!
