### ISSUE TITLE
An API incompatibility wa s encountered while executing io.fabric8:docker-maven-plugin:0.14.2:build: java. lang.UnsatisfiedLinkError: unknown For BWCE Application Using Maven Plugin

### ISSUE THREAD

**Issue by amsingh21** [TIBCOSoftware/bw6-plugin-maven#153]
I Have built a simple application in BWCE and trying to deploy same on docker using Maven plugin.
POM file is generated without any issues.
When I am running below command to create Docker image using Maven , it failing and giving following error.
mvn initialize docker:build

[POM.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2115005/POM.txt)
I have attached POM file as well.
Maven Version - 3.5.3

[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.14.2:build (defa
ult-cli) on project EmployeeApplication.application: Execution default-cli of go
al io.fabric8:docker-maven-plugin:0.14.2:build failed: An API incompatibility wa
s encountered while executing io.fabric8:docker-maven-plugin:0.14.2:build: java.
lang.UnsatisfiedLinkError: unknown
[ERROR] -----------------------------------------------------
[ERROR] realm = plugin>io.fabric8:docker-maven-plugin:0.14.2--1106001851
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/amita/.m2/repository/io/fabric8/docker-maven-pl
ugin/0.14.2/docker-maven-plugin-0.14.2.jar
[ERROR] urls[1] = file:/C:/Users/amita/.m2/repository/org/apache/httpcomponents/
httpclient/4.3.6/httpclient-4.3.6.jar
[ERROR] urls[2] = file:/C:/Users/amita/.m2/repository/org/apache/httpcomponents/
httpcore/4.3.3/httpcore-4.3.3.jar
[ERROR] urls[3] = file:/C:/Users/amita/.m2/repository/commons-logging/commons-lo
gging/1.1.3/commons-logging-1.1.3.jar
[ERROR] urls[4] = file:/C:/Users/amita/.m2/repository/commons-codec/commons-code
c/1.6/commons-codec-1.6.jar
[ERROR] urls[5] = file:/C:/Users/amita/.m2/repository/com/github/jnr/jnr-unixsoc
ket/0.8/jnr-unixsocket-0.8.jar
[ERROR] urls[6] = file:/C:/Users/amita/.m2/repository/com/github/jnr/jnr-ffi/2.0
.3/jnr-ffi-2.0.3.jar
[ERROR] urls[7] = file:/C:/Users/amita/.m2/repository/com/github/jnr/jffi/1.2.9/
jffi-1.2.9.jar
[ERROR] urls[8] = file:/C:/Users/amita/.m2/repository/com/github/jnr/jffi/1.2.9/
jffi-1.2.9-native.jar
[ERROR] urls[9] = file:/C:/Users/amita/.m2/repository/org/ow2/asm/asm/5.0.3/asm-
5.0.3.jar
[ERROR] urls[10] = file:/C:/Users/amita/.m2/repository/org/ow2/asm/asm-commons/5
.0.3/asm-commons-5.0.3.jar
[ERROR] urls[11] = file:/C:/Users/amita/.m2/repository/org/ow2/asm/asm-analysis/
5.0.3/asm-analysis-5.0.3.jar
[ERROR] urls[12] = file:/C:/Users/amita/.m2/repository/org/ow2/asm/asm-tree/5.0.
3/asm-tree-5.0.3.jar
[ERROR] urls[13] = file:/C:/Users/amita/.m2/repository/org/ow2/asm/asm-util/5.0.
3/asm-util-5.0.3.jar
[ERROR] urls[14] = file:/C:/Users/amita/.m2/repository/com/github/jnr/jnr-x86asm
/1.0.2/jnr-x86asm-1.0.2.jar
[ERROR] urls[15] = file:/C:/Users/amita/.m2/repository/com/github/jnr/jnr-consta
nts/0.8.7/jnr-constants-0.8.7.jar
[ERROR] urls[16] = file:/C:/Users/amita/.m2/repository/com/github/jnr/jnr-enxio/
0.9/jnr-enxio-0.9.jar
[ERROR] urls[17] = file:/C:/Users/amita/.m2/repository/com/github/jnr/jnr-posix/
3.0.12/jnr-posix-3.0.12.jar
[ERROR] urls[18] = file:/C:/Users/amita/.m2/repository/org/apache/commons/common
s-lang3/3.3.2/commons-lang3-3.3.2.jar
[ERROR] urls[19] = file:/C:/Users/amita/.m2/repository/org/json/json/20140107/js
on-20140107.jar
[ERROR] urls[20] = file:/C:/Users/amita/.m2/repository/org/bouncycastle/bcpkix-j
dk15on/1.51/bcpkix-jdk15on-1.51.jar
[ERROR] urls[21] = file:/C:/Users/amita/.m2/repository/org/bouncycastle/bcprov-j
dk15on/1.51/bcprov-jdk15on-1.51.jar
[ERROR] urls[22] = file:/C:/Users/amita/.m2/repository/org/apache/maven/plugins/
maven-assembly-plugin/2.6/maven-assembly-plugin-2.6.jar
[ERROR] urls[23] = file:/C:/Users/amita/.m2/repository/org/slf4j/slf4j-jdk14/1.5
.6/slf4j-jdk14-1.5.6.jar
[ERROR] urls[24] = file:/C:/Users/amita/.m2/repository/org/slf4j/jcl-over-slf4j/
1.5.6/jcl-over-slf4j-1.5.6.jar
[ERROR] urls[25] = file:/C:/Users/amita/.m2/repository/org/apache/maven/reportin
g/maven-reporting-api/2.2.1/maven-reporting-api-2.2.1.jar
[ERROR] urls[26] = file:/C:/Users/amita/.m2/repository/org/apache/maven/doxia/do
xia-sink-api/1.1/doxia-sink-api-1.1.jar
[ERROR] urls[27] = file:/C:/Users/amita/.m2/repository/org/apache/maven/doxia/do
xia-logging-api/1.1/doxia-logging-api-1.1.jar
[ERROR] urls[28] = file:/C:/Users/amita/.m2/repository/junit/junit/3.8.1/junit-3
.8.1.jar
[ERROR] urls[29] = file:/C:/Users/amita/.m2/repository/commons-cli/commons-cli/1
.2/commons-cli-1.2.jar
[ERROR] urls[30] = file:/C:/Users/amita/.m2/repository/org/codehaus/plexus/plexu
s-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.jar
[ERROR] urls[31] = file:/C:/Users/amita/.m2/repository/backport-util-concurrent/
backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
[ERROR] urls[32] = file:/C:/Users/amita/.m2/repository/org/sonatype/plexus/plexu
s-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[33] = file:/C:/Users/amita/.m2/repository/org/sonatype/plexus/plexu
s-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[34] = file:/C:/Users/amita/.m2/repository/org/apache/maven/shared/m
aven-common-artifact-filters/1.4/maven-common-artifact-filters-1.4.jar
[ERROR] urls[35] = file:/C:/Users/amita/.m2/repository/org/codehaus/plexus/plexu
s-archiver/3.0.1/plexus-archiver-3.0.1.jar
[ERROR] urls[36] = file:/C:/Users/amita/.m2/repository/org/iq80/snappy/snappy/0.
3/snappy-0.3.jar
[ERROR] urls[37] = file:/C:/Users/amita/.m2/repository/org/apache/maven/shared/f
ile-management/1.1/file-management-1.1.jar
[ERROR] urls[38] = file:/C:/Users/amita/.m2/repository/org/apache/maven/shared/m
aven-shared-io/1.1/maven-shared-io-1.1.jar
[ERROR] urls[39] = file:/C:/Users/amita/.m2/repository/commons-io/commons-io/2.2
/commons-io-2.2.jar
[ERROR] urls[40] = file:/C:/Users/amita/.m2/repository/org/apache/maven/shared/m
aven-filtering/1.3/maven-filtering-1.3.jar
[ERROR] urls[41] = file:/C:/Users/amita/.m2/repository/org/apache/maven/shared/m
aven-shared-utils/0.6/maven-shared-utils-0.6.jar
[ERROR] urls[42] = file:/C:/Users/amita/.m2/repository/com/google/code/findbugs/
jsr305/2.0.1/jsr305-2.0.1.jar
[ERROR] urls[43] = file:/C:/Users/amita/.m2/repository/org/sonatype/plexus/plexu
s-build-api/0.0.4/plexus-build-api-0.0.4.jar
[ERROR] urls[44] = file:/C:/Users/amita/.m2/repository/org/codehaus/plexus/plexu
s-io/2.6/plexus-io-2.6.jar
[ERROR] urls[45] = file:/C:/Users/amita/.m2/repository/org/apache/maven/maven-ar
chiver/2.5/maven-archiver-2.5.jar
[ERROR] urls[46] = file:/C:/Users/amita/.m2/repository/org/codehaus/plexus/plexu
s-utils/3.0.21/plexus-utils-3.0.21.jar
[ERROR] urls[47] = file:/C:/Users/amita/.m2/repository/org/apache/maven/shared/m
aven-repository-builder/1.0/maven-repository-builder-1.0.jar
[ERROR] urls[48] = file:/C:/Users/amita/.m2/repository/joda-time/joda-time/2.8.2
/joda-time-2.8.2.jar
[ERROR] urls[49] = file:/C:/Users/amita/.m2/repository/org/yaml/snakeyaml/1.16/s
nakeyaml-1.16.jar
[ERROR] urls[50] = file:/C:/Users/amita/.m2/repository/com/google/guava/guava/18
.0/guava-18.0.jar
[ERROR] urls[51] = file:/C:/Users/amita/.m2/repository/org/codehaus/plexus/plexu
s-interpolation/1.22/plexus-interpolation-1.22.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import from realm ClassRealm[project>com.tibco.bw:Employe
eApplication:1.0.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContaine
rException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR] mvn -rf :EmployeeApplication.application

C:\Users\amita\bwceworkspace\EmployeeApplication.application.parent>

If you have a question, please label the issue as question.

If you are reporting a new issue, make sure that we do not have any duplicates
already open. You can ensure this by searching the issue list for this
repository. If there is a duplicate, please close your issue and add a comment
to the existing issue instead.

If you suspect your issue is a bug, please edit your issue description to
include the BUG REPORT INFORMATION shown below. If you fail to provide this
information within 7 days, we cannot debug your issue and will close it. We
will, however, reopen it if you later provide the information.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->
Maven Plugin version:

Maven version:

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version: BWCE 2.3.4

Component: Tibco Apacahe Maven Plugin 1.3.1

**Steps to reproduce the issue:**
1. Build any sample application in BWCE 
2. Generate POM file and check for deploying and running application on Docker
3.Provide Docker details and docker host connecting to Unix default socket.
Now run image build command from command line to build image for this application on docker

**Additional environment details if any:**

**Describe the results you received:**

**Describe the results you expected:**
Image should be built successfully on Docker machine and we should be able to see image on Docker machine.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by amsingh21** [comment]
Anyone facing this issue.

**Comment by SonaliDasgupta** [comment]
Hi @amsingh21 , in the POM file which you have attached, the version of docker-maven-plugin referenced is version 0.26.0 . While in the error logs we see that the version 0.14.2 of docker-maven-plugin is being used in the build goal. This is leading to an API incompatibility.  Could you please change the version of the docker-maven-plugin to the latest version (0.26.1) in all your POM files, and retry running the build goal ? This should resolve the issue. 

Also, with release 2.0.0 of BW6 Maven Plugin, we have upgraded the Docker Maven Plugin to version 0.26.1 , so this version will get automatically picked if the POM files are generated using BW6 Maven POM UI.

**Comment by SonaliDasgupta** [comment]
Closing this issue. Please reopen incase of any query.
