### ISSUE TITLE
PlugIn project Mavanisation

### ISSUE THREAD

**Issue by krishnachaitanya511** [TIBCOSoftware/bw6-plugin-maven#155]
---------------------------------------------------
PlugIn project Mavanisation
---------------------------------------------------
Maven Plugin version: 1.3.1

Maven version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-18T01:33:14+07:00)

Product: Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version: BWCE 2.3.4

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1. Create Custom Function/Plugin Project and Mavenize the same.
2. Create one more shared module and mavenise the same. Refer the Step 1's information the Shared Module POM.
3. Point the same Shared module to any Application module. The custom functions jar is not visible once I create the EAR using the maven. 

Describe the results you received: The Custom function jar is not visible in the final Jar.

Describe the results you expected: Resolve the dependencies.

**Comment by DileepNeti** [comment]
Hi,

Any updates on this isssue ?

Thanks.

**Comment by sonalshingavi** [comment]
Hi @krishnachaitanya511, @DileepNeti 
Follow these steps 

Steps :
1.  Create a Custom XPath Function/Plugin Project.
2. Create one shared module and using custom XPath function in a shared module.
3. Point the same Shared module to the application module. 
4. Add the Custom XPath Function in **Application - Package Unit - Includes**.
5. Generate the POM file and Run Maven "package" goal to generate the EAR file.
6.  Verify that Custom XPath Function and shared module entry in the EAR file.
7. Run Maven "install" goal to deploy the application.

**Comment by sonalshingavi** [comment]
Closing this issue,Please reopen in case of any query.
