### ISSUE TITLE
Unreadable manifest in application dependency causes build to fail

### ISSUE THREAD

**Issue by artificialintellect** [TIBCOSoftware/bw6-plugin-maven#163]
Maven Plugin version: 1.3.1

Maven version: 3.2.5

Product : TIBCO ActiveMatrix Businessworks 6

Product version: 6.4.2

Component: Maven build plugin

**Steps to reproduce the issue:**
1. Create a corporate parent pom that contains the com.tibco.bw.palette.shared artifact as a dependency
2. Use the corporate parent pom in both an application and application module
3. Run mvn package to build the application EAR

**Additional environment details if any:**

**Describe the results you received:**
The build fails with an error of "[ERROR] Failed to add modules to the Application"

**Describe the results you expected:**
The build should succeed

**Additional information you deem important (e.g. issue happens only occasionally):**
I realize this is a bit outside of the suggested path since the dependency isn't required for the application's pom.  However having a unified corporate pom is known to be useful in Java, and has otherwise proven to be useful in Tibco BW 6.  We only recently upgraded to the plugin version 1.3.1, so in previous versions of the plugin this was not an issue.

I debugged the plugin and found that the issue is that in BWEARPackagerMojo.addModules() there is loop over resolved dependencies (retrieved via method getDependenciesResolutionResult()), and in that loop there is a call to ManifestParser.parseManifestFromJAR(File).  That call ends up returning null as the Manifest cannot be read from the jar for some reason.  This specifically happens with the com.tibco.bw.palette.shared dependency but could happen with any dependency.  

I think a reasonable and simple fix for this would be to just add a null check for the manifest since it being unreadable isn't a good reason to fail the whole build.

**Comment by awagle** [comment]
Fixed by pull request #166
