### ISSUE TITLE
No propertie for disk_quota

### ISSUE THREAD

**Issue by rillo-carrillo** [TIBCOSoftware/bw6-plugin-maven#167]
Maven Plugin version: 1.3.1

Maven version: 3.5.4

Product : TIBCO Businessworks Container edition

Product version:2.3.4

Component: Maven Eclipse Plugin

**Describe the Issue:**

I have a simple BWCE application and I want to push on PCF Dev, in the console I can see app crashed, I have faced the issue when trying to push the same image manually but able to fix by simply adding a new property on manifest.yml "disk_quota". When using the maven plugin I also try to add this property to set the disk quota for the application but looks like there is no support for this property like "memory" or "buildpack", I'm right? 

Is there any other way I can achieve this change on maven plugin.

**Comment by SonaliDasgupta** [comment]
Resolved with Pull Request #175
