### ISSUE TITLE
Provide silent installation option

### ISSUE THREAD

**Issue by racheliurui** [TIBCOSoftware/bw6-plugin-maven#168]
Maven Plugin version: 1.3.1

Is there a way to install the plugin silently?
I try to passing my tibco home variable to the command but failed. Not familiar with build.xml, but want to know if it's possible to passing through the input so that we can do silent installation.

Something like below, (linux platform)

```shell
./install.sh /opt/tibco/bw
```

Thanks very much !

**Comment by racheliurui** [comment]
just to share, modified the build.xml and removed the input by giving correct path , silent installation passed. Thanks. This one can be closed. But still, if official can support passing parameter that will be great :)

**Comment by awagle** [comment]
This is now supported in 2.0.2
