### ISSUE TITLE
Maven plugin 2.0.0 takes an excessive amount of time to install

### ISSUE THREAD

**Issue by crmadrig** [TIBCOSoftware/bw6-plugin-maven#177]
Maven Plugin version:
Plugin 2.0.0
Maven version:
Maven version 3.3.3
Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition
BusinessWorks Container Edition
Product version:
2.4.0
Component: Either of Maven Eclipse Plugin or Maven build plugin
Plugin for BusinessStudio

**Steps to reproduce the issue:**
1. Install Plugin

**Additional environment details if any:**
Mac os X, version 10.12.6 
Java version 1.8.0_45

**Describe the results you received:**
Installation of maven plugin takes 35 minutes.

**Describe the results you expected:**
Short install time (5-7 minutes)

**Additional information you deem important (e.g. issue happens only occasionally):**
This install was ran on the TIBCO network.
Attaching logs: 
[maven-plugin-install.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2316003/maven-plugin-install.txt)

**Comment by ashutoshbhide** [comment]
Hi @crmadrig 

Looks like there is a high latency with your artifactory server at http://52.206.62.219/artifactory/

Its taking lot of time to install the Maven Plugin to the local repository. 

Can you try any other non-Tibco Plugin and see if it takes the same amount of time.

Or can you see if you can run it without the Artifactory server?


From the log below I can see it takes close to 7 minutes per maven local install.

     [exec] [WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-javadoc-plugin:2.9.1: Plugin org.apache.maven.plugins:maven-javadoc-plugin:2.9.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-javadoc-plugin:jar:2.9.1
     [exec] [WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-plugin-plugin:3.4: Plugin org.apache.maven.plugins:maven-plugin-plugin:3.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-plugin-plugin:jar:3.4
     [exec] [INFO]
     [exec] [INFO] --- maven-install-plugin:2.4:install-file (default-cli) @ bw6-maven-plugin ---
     [exec] [INFO] Installing /Applications/bwce240/bwce/2.4/maven/plugins/bw6-maven-plugin/bw6-maven-plugin-2.0.0.jar to /Users/crmadrig/.m2/repository/com/tibco/plugins/bw6-maven-plugin/2.0.0/bw6-maven-plugin-2.0.0.jar
     [exec] [INFO] Installing /Applications/bwce240/bwce/2.4/maven/plugins/bw6-maven-plugin/pom.xml to /Users/crmadrig/.m2/repository/com/tibco/plugins/bw6-maven-plugin/2.0.0/bw6-maven-plugin-2.0.0.pom
     [exec] [INFO] ------------------------------------------------------------------------
     [exec] [INFO] BUILD SUCCESS
     [exec] [INFO] ------------------------------------------------------------------------
     [exec] [INFO] Total time: 07:41 min
     [exec] [INFO] Finished at: 2018-08-21T09:33:49-07:00
     [exec] [INFO] Final Memory: 7M/245M
     [exec] [INFO] ------------------------------------------------------------------------
     [exec] [INFO] Scanning for projects...

**Comment by crmadrig** [comment]
Not using the Artifactory server sped up the process (about 1 minute) will close. Thanks.
