### ISSUE TITLE
Request for full mvn management of bw-module dependencies

### ISSUE THREAD

**Issue by tcosley** [TIBCOSoftware/bw6-plugin-maven#18]
Enhancement request so that bw-module dependencies (for both application and shared modules) are resolved via maven in both command-line ear build and Studio debugging use-cases.

Please see [pull request 16](https://github.com/TIBCOSoftware/bw6-plugin-maven/pull/16) for example.

The intent is to enable true shared module development and release as stand-alone projects where inter-bw-module dependencies are resolved via maven (rather than by relative path and/or studio workspace resolution).

**Comment by ashutoshbhide** [comment]
This is now done with version 1.3.0
Now the Shared Module can be specified as POM dependency. The Studio as well as the Maven build will resolve the dependency and execute accordingly.
Look at https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/SharedModule
