### ISSUE TITLE
I want to just deploy the created EAR. Which goal can I use? In 1.3.1 it was bw6maven:bwinstall. But, this goal is not working with v2.0.1.

### ISSUE THREAD

**Issue by Chetan-Vatharkar** [TIBCOSoftware/bw6-plugin-maven#185]
<!--

If you have a question, please label the issue as question.

If you are reporting a new issue, make sure that we do not have any duplicates
already open. You can ensure this by searching the issue list for this
repository. If there is a duplicate, please close your issue and add a comment
to the existing issue instead.

If you suspect your issue is a bug, please edit your issue description to
include the BUG REPORT INFORMATION shown below. If you fail to provide this
information within 7 days, we cannot debug your issue and will close it. We
will, however, reopen it if you later provide the information.

---------------------------------------------------
BUG REPORT INFORMATION

**Comment by NidhiRajeshDhoka** [comment]
Hi @Chetan-Vatharkar ,

You can use "com.tibco.plugins:bw6-maven-plugin:2.0.1:bwinstall" command for specifically deploying the EAR.If you still face the issue,please provide more details with project,error logs and screenshots attached to this issue.

**Comment by Chetan-Vatharkar** [comment]
Thanks! I am able to deploy EAR.
