### ISSUE TITLE
Enhacement Request - Add Java dependencies to pom.xml when "Generating POM for Application"

### ISSUE THREAD

**Issue by alexandrev** [TIBCOSoftware/bw6-plugin-maven#187]
BusinessWorks 6.x / CE application if they have intenral java dependency from some different JAR files (even if they are from BusinessWorks 6 itself) because you need to do something inside a Java activity or something similar, and you create your pom.xml application, this java dependencies are not in the final pom.xml file, not the one from the parent neither the module.

So, when you try to build it, it crashes because of that. It could be great to include this feature in an upcoming release so the pom.xml have all the javadependencies (or at least the ones from TIBCO BW6 classes) instead of needed to add it by hand.

**Comment by NidhiRajeshDhoka** [comment]
@alexandrev Can you attach the project for our better understanding.Also, can you attach the error log files along with it.

**Comment by NidhiRajeshDhoka** [comment]
We have a workaround for this for now,you can install the jars present in the plugin dependencies into your maven local respository using command,

mvn install:install-file -Dfile=com.tibco.bw.palette.shared_6.1.100.003.jar -DgroupId=com.tibco.plugins -DartifactId=com.tibco.bw.palette.shared -Dversion=6.1.100 -Dpackaging=jar

just like we install com.tibco.bw.palette.shared jar into our maven local repository(we specify this in install.bat file of maven plugin) and we find it in our pom.xml for every maven project.

Later on(after Maven 2.1.0 release), we'll get back to you with this enhancement.
