### ISSUE TITLE
Ear deployment with specific config file without build

### ISSUE THREAD

**Issue by khmoez07** [TIBCOSoftware/bw6-plugin-maven#188]
Hi team, 

I need to deploy the ear without  build ear  from the source with specific configuration. 

Best regards 
KHALED Moez

Maven Plugin version:

Maven version:

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version:

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1.
2.
3.

**Additional environment details if any:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by SujataDarekar** [comment]
@khmoez07  We have enhancement #38 (Deploy only goal for BW6 applications) . So we are working on the goal which will deploy specified EAR on target platform using configuration file.

**Comment by emcap** [comment]
I'm using version 2.1.1 of the plugin.
How do I make use of this new feature, how do I set install only goal with specific configuration?

**Comment by khmoez07** [comment]
Hey Sujata Darekar, 
![Plugin maven](https://user-images.githubusercontent.com/34886073/56031522-112cdc00-5d20-11e9-8d2d-acd5362e8bb2.jpg)

the variables ear location and ear name (earLoc, earName) are not taken into account in the pom.xml. Thank you in advance for your answer.

Best regards
KHALED Moez

**Comment by SujataDarekar** [comment]
@khmoez07 those variables are used to deploy the EAR which is not part of the POM file.

**Comment by SujataDarekar** [comment]
> I'm using version 2.1.1 of the plugin.
> How do I make use of this new feature, how do I set install only goal with specific configuration?

Please refer wiki page "https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/EAR-Deployment"

**Comment by khmoez07** [comment]
@SujataDarekar 
 thanks i will test it and i will let you know. 

Best regards 
KHALED Moez

**Comment by khmoez07** [comment]
@SujataDarekar , 

It work thanks you very much .

Best regards 
KHALED Moez
