### ISSUE TITLE
Including Validation of TIBCO projects as part of Maven build process

### ISSUE THREAD

**Issue by atulanand18** [TIBCOSoftware/bw6-plugin-maven#191]
Currently while running the maven build for TIBCO projects, it doesn’t report any project validation errors and goes ahead and creates the application ear.
 
It will be better if we can include this enhancement as part of TIBCO BW6 maven plugin. Thanks.

**Comment by awagle** [comment]
The Maven plugin currently has a soft dependency only for running unit tests on a BW installation. Project validation is only performed using Business Studio or bwdesign both depending on eclipse. This is not something that can be added to the Maven plugin.

We recommend using bwdesign before running the maven target in your script if validation needs to be performed before building the EAR file.
