### ISSUE TITLE
build with different deploymentconfig files (question)

### ISSUE THREAD

**Issue by bryansijs** [TIBCOSoftware/bw6-plugin-maven#193]
Maven Plugin version: 2.0.1
Maven version: 3.5.2
Product :TIBCO ActiveMatrix Businessworks 6 
Product version:
Component: Maven build plugin

I am trying to figure out how to deploy with this plugin to different environments. I am using the following command: 

`mvn install -f ./sampledeploy.parent/pom.xml -DdeploymentConfig.file=./sampledeploy.parent/deployment.properties`

output of this command is:
`[INFO] --- bw6-maven-plugin:1.3.1:bwinstall (default-bwinstall) @ sampledeploy ---
[INFO] BWEAR Installer Mojo started ...
[INFO] No Deployment Config File set. Reading the deployment Properties from POM File.
`

How to set different deployment config files? 

I created multiple property files for different environments to use for deployments. Created a clean bw6 project and used the eclipse plugin to create the config.

**Comment by sonalshingavi** [comment]
Closing the issue, Please reopen in case you have any query.
