### ISSUE TITLE
BW6 Maven plugin Generate POM dialog text is not visible

### ISSUE THREAD

**Issue by rahulkamdar** [TIBCOSoftware/bw6-plugin-maven#2]
Description text below the title in the dialog for Generate POM is not visible - see the screenshot attached.
![screen shot 2015-12-24 at 7 24 47 am](https://cloud.githubusercontent.com/assets/5161378/12116644/54382c48-b3e1-11e5-8aa3-484a1d420eed.png)

**Comment by RajibBiswasTibco** [comment]
In addition to the above issue, I have noticed 2 more issues with the same Wizard:
1. In the top header, the TRADE MARK SYMBOL is not displayed properly in Windows (just after the word "TIBCO BusinessWorks".
2. In the sentence "Enter the GroupId and ArtifactId for for Maven POM File generation.", the word 'for' is repeated twice.
As per my discussion with Zoher, he will take this up and fix all these issues related to wizard.
