### ISSUE TITLE
Build Failure Maven cf:push

### ISSUE THREAD

**Issue by neethuabu** [TIBCOSoftware/bw6-plugin-maven#20]
Hi 

I am trying to do a maven cf:push 
Upon running the configuration i get this error

BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.556 s
[INFO] Finished at: 2016-06-22T11:01:43-04:00
[INFO] Final Memory: 19M/287M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.cloudfoundry:cf-maven-plugin:1.1.3:push (default-cli) on project test.application:
[ERROR] 
[ERROR] -------------------------------------------------------------------------------
[ERROR] 
[ERROR] Required argument 'target' is missing.
[ERROR] ========================================================================
[ERROR] 
[ERROR] Did you configure the parameter? You can provide the parameter either as:
[ERROR] 
[ERROR] - System Property using: -Dcf.target=<provide value> or
[ERROR] - Add the parameter to the pom.xml under the plugin's configuration element:
[ERROR] 
[ERROR] <configuration>
[ERROR] <target>provide value</target>
[ERROR] </configuration>
[ERROR] 

I have provided the pcf target in the pcfdev.properties

Also in the effective xml i can see it as:

 <configuration>
          <server>${bwpcf.server}</server>
          <target>${bwpcf.target}</target>
          <trustSelfSignedCerts>${bwpcf.trustSelfSignedCerts}</trustSelfSignedCerts>
          <org>${bwpcf.org}</org>
          <space>${bwpcf.space}</space>
          <appname>${bwpcf.appName}</appname>
          <url>${bwpcf.url}</url>
          <instances>${bwpcf.instances}</instances>
          <skip>false</skip>
          <memory>${bwpcf.memory}</memory>
          <buildpack>${bwpcf.buildpack}</buildpack>
          <env>
            <APP_CONFIG_PROFILE>${bwpcf.env.0}</APP_CONFIG_PROFILE>
            <BW_LOGLEVEL>${bwpcf.env.1}</BW_LOGLEVEL>
          </env>
        </configuration>

How do i fix this problem?

Thanks,
Neethu

**Comment by awagle** [comment]
@roagarwal is this still an issue?

**Comment by roagarwal** [comment]
No we can close this.
