### ISSUE TITLE
PCF - URL for app contains wrong domain

### ISSUE THREAD

**Issue by hugomcruz** [TIBCOSoftware/bw6-plugin-maven#200]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
When generating a new POM file the pcfdev.properties and pcfprod.properties contain an attribute
bwpcf.url=demo.sys.bw.domain.com

This seems to be derived from the PCF API endpoint: https://api.sys.bw.domain.com

However, in my configuration the applications do not have the same domain. My domain for applications is:
- <app-name>.apps.bw.domain.com

For every POM file I generate I need to go to the properties and change it manually. 

Maven Plugin version: 2.0.1
Maven version:Apache Maven 3.5.4 
Product :TIBCO Businessworks Container edition
Product version: 2.4.0
Component: Either of Maven Eclipse Plugin

**Steps to reproduce the issue:**
1. Need an environment where API and APPS have different domains
2. Generate a pom file for PCF
3. Try maven goal push and see the error.
4. Open the pcfdev.properties and change the domain of property bwpcf.url
5. Build again to push an dsee it works

**Additional environment details if any:**
I ran this on Mac.

**Describe the results you received:**
Described in the steps

**Describe the results you expected:**
I expected not to have to edit the file manually.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by SonaliDasgupta** [comment]
Please refer to pull request #195 for this issue. Added a UI field for the PCF domain to be configured by users while generating/regenerating the POM, without the need to edit the properties files.

**Comment by SonaliDasgupta** [comment]
Resolved from Release 2.0.2 onwards.
