### ISSUE TITLE
not get the current  profil in my backupLocation

### ISSUE THREAD

**Issue by khmoez07** [TIBCOSoftware/bw6-plugin-maven#201]
Hi Team, 

when i want to get a backup of my ear and profile I have the default profile when I have it deployed but not the current profile because we can get some modification in tea admin. 

Best rgards 
KHALED Moez

**Comment by NidhiRajeshDhoka** [comment]
Hi @khmoez07 ,

I have made an enhancement where you can add external profile during deployement.It will available in Maven 2.1.0 release.You can refer #182 for details.I hope your issue gets resolved with this enhancement.

Regards,
Nidhi

**Comment by khmoez07** [comment]
Hi @NidhiRajeshDhoka , 

i can see the profile in the same directory of "ear" but it's not the current profile in tea admin it's the default profile in the ear.

scenario:

1-Deploy ear in tea admin
2-stop ear
3-modify some parameters online
4-restart ear

after taht  i redeploy a new version in tea admin

Verification of default.substvar in backup location, this last not includ the current parameters values indicated in tea admin but contains the  default profile of ear. 

Version Plugin: 2.1.1

I will be there for additional information. 

Thanks  :)
Best regards 
KHALED Moez
