### ISSUE TITLE
Jenkins Build Failed.

### ISSUE THREAD

**Issue by rillo-carrillo** [TIBCOSoftware/bw6-plugin-maven#202]
Maven Plugin version: 2.0.1

Maven version: 3.3.9

Product : TIBCO Businessworks Container edition

Product version: 2.3.4

Component: Maven build plugin

**Steps to reproduce the issue:**
1. Run Jenkins container
2. Create a Maven Job
3. Run Job

**Additional environment details if any:**
https://github.com/rillo-carrillo/Maven.git

maven goals: clean package

**Describe the results you received:**
[ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.0.1:bwmodule (default-bwmodule) on project MavenTest.module: Execution default-bwmodule of goal com.tibco.plugins:bw6-maven-plugin:2.0.1:bwmodule failed. NullPointerException -> [Help 1]

**Describe the results you expected:**
Build Successful

**Additional information you deem important (e.g. issue happens only occasionally):**
On debug console I can see the below dependencies:

[DEBUG] Adding artifact for dependency => com.tibco.plugins:com.tibco.bw.palette.shared:pom.lastUpdated:6.1.100 (provided). The file for Dependency is => /root/.m2/repository/com/tibco/plugins/com.tibco.bw.palette.shared/6.1.100/com.tibco.bw.palette.shared-6.1.100.pom.lastUpdated
*The above log doesnt show the jar in the above location.*
[DEBUG] Adding artifact for dependency => com.tibco.plugins:bw6-maven-plugin:jar:2.0.1 (compile). The file for Dependency is => /root/.m2/repository/com/tibco/plugins/bw6-maven-plugin/2.0.1/bw6-maven-plugin-2.0.1.jar
*the above log does show the jar.*

**Comment by rillo-carrillo** [comment]
Complete logs
[jenkins-logs.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2470009/jenkins-logs.txt)

**Comment by awagle** [comment]
Closing based on latest comment.
