### ISSUE TITLE
initialize fabric8:apply goal cannot find a kubernetes instance

### ISSUE THREAD

**Issue by loreCande81** [TIBCOSoftware/bw6-plugin-maven#205]
I attached the project as what you proposed in the resolution bug #196 didnt work. I am using an older version than 2.0.1 of the plugin. The goal initialize fabric8:json works, but not the initialize fabric8:apply. The error I am getting is the following: No Kubernetes instance found.
[workspace.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2518944/workspace.zip)

**Comment by SonaliDasgupta** [comment]
@loreCande81 Could you please tag your docker image as gcr.io/eaidocker341/heartbeat in the docker properties files (assuming eaidocker341 is your project on GCR) ? The docker image needs to be tagged as gcr.io/project-name/image-name, and pushed to GCR using 'initialize docker:push' maven goal, before applying the Fabric8 goals. 

If the issue persists, could you please attach the target files created after applying fabric8:json goal ? Tried running the project at my end , but the base image 'eaidocker341/eaidev' is not accessible to me.

**Comment by loreCande81** [comment]
Hi, is Google cloud registry mandatory? I pushed it in docker hub and the goal worked fine. ThanksInviato dal mio dispositivo mobile Huawei-------- Messaggio originale --------Oggetto: Re: [TIBCOSoftware/bw6-plugin-maven] initialize fabric8:apply goal cannot find a kubernetes instance (#205)Da: Sonali Dasgupta A: TIBCOSoftware/bw6-plugin-maven CC: loreCande81 ,Mention @loreCande81 Could you please tag your docker image as gcr.io/eaidocker341/heartbeat in the docker properties files (assuming eaidocker341 is your project on GCR) ? The docker image needs to be tagged as gcr.io/project-name/image-name, and pushed to GCR using 'initialize docker:push' maven goal, before applying the Fabric8 goals.
If the issue persists, could you please attach the target files created after applying fabric8:json goal ? Tried running the project at my end , but the base image 'eaidocker341/eaidev' is not accessible to me.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TIBCOSoftware/bw6-plugin-maven","title":"TIBCOSoftware/bw6-plugin-maven","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/TIBCOSoftware/bw6-plugin-maven"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SonaliDasgupta in #205: @loreCande81 Could you please tag your docker image as gcr.io/eaidocker341/heartbeat in the docker properties files (assuming eaidocker341 is your project on GCR) ? The docker image needs to be tagged as gcr.io/project-name/image-name, and pushed to GCR using 'initialize docker:push' maven goal, before applying the Fabric8 goals. \r\n\r\nIf the issue persists, could you please attach the target files created after applying fabric8:json goal ? Tried running the project at my end , but the base image 'eaidocker341/eaidev' is not accessible to me."}],"action":{"name":"View Issue","url":"https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/205#issuecomment-435389527"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/205#issuecomment-435389527",
"url": "https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/205#issuecomment-435389527",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [TIBCOSoftware/bw6-plugin-maven] initialize fabric8:apply goal cannot find a kubernetes instance (#205)",
"sections": [
{
"text": "",
"activityTitle": "**Sonali Dasgupta**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@SonaliDasgupta",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"TIBCOSoftware/bw6-plugin-maven\",\n\"issueId\": 205,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"TIBCOSoftware/bw6-plugin-maven\",\n\"issueId\": 205\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/205#issuecomment-435389527"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 401612236\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by SonaliDasgupta** [comment]
Hi @loreCande81  , pushing your docker container to a Kubernetes cluster is needed for the Fabric8 apply goal to recognize it as a Kubernetes instance. This access to a Kubernetes cluster is through GCR, which is a Container Registry. Dockerhub is used only for docker images, but it is GCR which will provide you the Kubernetes environment. Hence it is necessary to set up a Kubernetes cluster on GCR , and tag your image accordingly.

**Comment by SonaliDasgupta** [comment]
Closing this issue, since using Kubernetes on GCR will resolve the problem. Please reopen in case of any query.
