### ISSUE TITLE
Exception starting EAR generated by Maven build.

### ISSUE THREAD

**Issue by jnaik21987** [TIBCOSoftware/bw6-plugin-maven#207]
Hi Team,

I am facing an issue in starting the EAR generated using Maven Plugin. The project has a DB shared Module and a CustomXPath Function Shared Module which do not get initialized. Hence the project is facing exception starting up.

Below is the version of TIBCO Setup.
BW 6.5
Maven Plugin - 2.0.1

Attached is the logs for the same.
[BWLogFile.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2524733/BWLogFile.txt)

**Comment by awagle** [comment]
Can you unzip the EAR and confirm that com.wu.tibco.custom.xpathfn is present in the EAR file? Can you also confirm that EAR generated using Studio or bwdesign is successfully starting? We need confirmation that this is a Maven Plugin Issue.

**Comment by jnaik21987** [comment]
Hi Aditya,

I did verify that com.wu.tibco.custom.xpathfn is available in the EAR file.
Moreover the EAR generated via Business Studio is running successfully on
TEA.

**Comment by jnaik21987** [comment]
Hi Aditya and Sonal,

Any update on this issue?

**Comment by sonalshingavi** [comment]
Hi @jnaik21987  
I did verify that generate the EAR using Maven Plugin and installing it using Maven, It works fine on our side.
The project has a CustomXPath Function Shared Module.
Below is the version of TIBCO Setup.
BW 6.5.0
Maven Plugin - 2.0.2

Steps :
1. Create a Custom XPath Function/Plugin Project.
2. Create one shared module and using custom XPath function in a shared module.
3. Point the same Shared module to the application module. 
4. Add the Custom XPath Function in **Application - Package Unit - Includes**.
5. Generate the POM file. and Run Maven "**package**" goal to generate the EAR file.
6. Verify that Custom XPath Function and shared module entry in the EAR file.
7. Run Maven "**install**" goal to deploy the application.

I am sharing the demo project and the EAR file which I have tested for the current scenario 

[Project_and_EAR.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2580350/Project_and_EAR.zip)

**Comment by sonalshingavi** [comment]
Closing this issue, Please reopen in case of any query.

**Comment by jnaik21987** [comment]
Hi Sonal,

We did follow the similar steps , the only difference between our projects
is that the Plugin Shared Module that we are using have 3 extra jars
ie(com.tibco.security.tibcrypt_2.18.303.001.jar,
com.tibco.xml.cxf.common_1.3.400.001.jar, commons-lang-2.4.jar) as a part
of PluginDependency. Which we are adding in the Maven Dependency as
"system" provided and copying the same in the lib folder.

There is no issues in packaging , but the EAR created does not initialize
the Plugin Shared Module . Hence the application fails while starting on
TEA.

It would be great if you can generate the scenario where external jars are
used in the Application Module which is installed as a Plugin Custom
function.

**Comment by jnaik21987** [comment]
Hi Sonal,

Any update on this ?

**Comment by sonalshingavi** [comment]
Hi @jnaik21987 
Could you please share your project to reproduce the issue?

**Comment by jnaik21987** [comment]
Hi Sonal,

Due to compliance issues I am restricted to share the code outside
organization network.

Can we have a zoom call to discuss this ?

**Comment by awagle** [comment]
Unfortunately without a reproducible case we are not in a position to move forward. Can you create a sample project which demonstrates the issue or modify the one already attached by Sonal to help us simulate the issue?

**Comment by jnaik21987** [comment]
Hi Aditya and Sonal,

Is it possible for you to get the code from a case created earlier on TIBCO
Support site.

The Case Id is  :  01641299
The File Name is  : TibcoSupport.7z

Thanks.

**Comment by jnaik21987** [comment]
Hi Aditya and Sonal,

Are you able to retrieve the code from the Case Id?

Thanks.

**Comment by sonalshingavi** [comment]
Hi @jnaik21987 
I am trying to reproduce this issue using reference case Id, Will back to you ones we have any update.

Thank you

**Comment by jnaik21987** [comment]
Hi Sonal,

Along with this issue can you please also check why in this project we are
unable to see the drop down as "AppSpace" while generating Pom for
application.
It just shows "None".

**Comment by sonalshingavi** [comment]
Hi @jnaik21987 
This issue is already reported here  #217,
We are working on a solution.

**Comment by SujataDarekar** [comment]
@jnaik21987 
Could you please follow the steps given below to add dependency of JARs(com.tibco.security.tibcrypt_2.18.303.001.jar, commons-lang-2.4.jar) into customXpath function where the JARs are present in tibco home directory:
1. Open command prompt from the JAR file path where your JARS are present
2. Intall the JAR into .m2 repository using command
"mvn install:install-file -Dfile=file-name -DgroupId=group-ID -DartifactId=artifact-id -Dversion=version -Dpackaging=jar"
For example I have installed commons-lang-2.4.jar as follow:
mvn install:install-file -Dfile=commons-lang-2.4.jar -DgroupId=com.tibco.plugins -DartifactId=commons-lang -Dversion=2.4 -Dpackaging=jar
3. Add those JARS dependency through POM file of CustomXPath function  with **"provided"** scope
4. Run the package command and then deploy the ear.

Note: We don't need add dependency of JAR com.tibco.xml.cxf.common as it is already present into .m2 repository

Please let me know if you have any query.

Thanks!
