### ISSUE TITLE
 error dependency Maven

### ISSUE THREAD

**Issue by ljferrero** [TIBCOSoftware/bw6-plugin-maven#214]
Maven Plugin version: 2.0.2

Maven version:3.3.3

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version:BWCE 2.4.0

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
Hello,
We want to do :
https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/SharedModule.

These are the steps. 

1. Create project HelloWorld
2. Create project other of type Shared module (Example: Log_Hello)
3. Apply maven plugin to the two projects
4. Upload project of type Shared module to nexus.
5. Add dependency of project shared module to pom.xml of HelloWorld
6. To do clean to project HelloWorld

**Describe the results you received:**
We have a error : 
"Application configuration error. A set of module properties included in the BW application [HelloWorldDocker] are not in sync with the module properties configured for the module [Log_Hello]. Re-include module in the application.	TIBCO.xml	/HelloWorldDocker/META-INF	Unknown	EMF Validation Problems" 

**Describe the results you expected:**
 The aplication helloworld have working ok

**Comment by ljferrero** [comment]
[errorDependency.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2596302/errorDependency.zip)

**Comment by ljferrero** [comment]
I add video file with the result of problem.

The file is errorDependency.mp4

**Comment by ankitapandey1** [comment]
@ljferrero This issue is not related to Maven this is related to BW studio, we will report this to respective team.There is a workaround you can do till the fix will come.

workaround:
Remove Shared Module dependency from Application module includes and add it again. this will fix the issue.

**Comment by ankitapandey1** [comment]
Hi @ljferrero ,

Closing this issue, you can follow up for the studio fix internally.
I have created a JIRA issue for the same.
