### ISSUE TITLE
Timeout on deployment when appspace doesn't exist

### ISSUE THREAD

**Issue by vtaront** [TIBCOSoftware/bw6-plugin-maven#215]
Hello,

When deploying an application to a non existing appspace, the plugin creates it and starts it.
Often it takes time to start and the HTTP request fails in timeout, so that the deployment of the application is not done.

Can you add parameters to be able to set the timeout values?

I think the fix should be made in:
com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.java

And add something like:
this.jerseyClient(ClientProperties.CONNECT_TIMEOUT, CONNECT_TIMEOUT);
this.jerseyClient(ClientProperties.READ_TIMEOUT,    READ_TIMEOUT);

For example:
https://stackoverflow.com/questions/19543209/how-to-set-the-connection-and-read-timeout-with-jersey-2-x

Regards.

**Comment by NidhiRajeshDhoka** [comment]
@vtaront are you working on this?or shall we do it from our side?

**Comment by vtaront** [comment]
Hello, I haven't worked on it yet.

**Comment by NidhiRajeshDhoka** [comment]
@vtaront do you want to do it by yourself or do you want us to fix it?

**Comment by vtaront** [comment]
Hello,

What you can do is to update com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.java:

1) Add an attribute:
`private final int timeout;`

2) Add, at the end of init() method:
`if (this.timeout > 0) {`
`   log.debug("Setting timeout to: " + this.timeout + " seconds");`
`   this.jerseyClient.property(ClientProperties.CONNECT_TIMEOUT, this.timeout * 1000); // Connect timeout interval, in milliseconds`
`   this.jerseyClient.property(ClientProperties.READ_TIMEOUT, this.timeout * 1000); // Read timeout interval, in milliseconds`
`}`

3) Add a property in the Mojo com.tibco.bw.maven.plugin.application.BWEARInstallerMojo:
`@Parameter(property = "timeout", defaultValue = "0")`
`private Integer timeout;`

4) Then when calling the Maven goal, add the parameter:
`-Dtimeout=60`

**Comment by SujataDarekar** [comment]
@vtaront Could you please send the pull request for the above-mentioned code?

**Comment by SujataDarekar** [comment]
@vtaront Please let us know if you have any concern
