### ISSUE TITLE
Deployment Option for App Space edition projects appear as 'NONE' while generating pom.xml using maven plugin

### ISSUE THREAD

**Issue by ahansa** [TIBCOSoftware/bw6-plugin-maven#217]
Maven Plugin version: 2.0.2

Maven version: Apache Maven 3.6.0

Product : Either of TIBCO ActiveMatrix Businessworks 6

Product version: 650 V99.1

Component: Maven Eclipse Plugin

**Steps to reproduce the issue:**
1. Import any app space sample , say tibco.bw.sample.binding.rest.Basic.application
2. Right click on the .application and Select Generate POM for application 
3. Select deployment option and observe 

**Additional environment details if any:**

**Describe the results you received:**
Only "None" appears as a deployment option

**Describe the results you expected:**
AppSpace should appear as an option

**Additional information you deem important (e.g. issue happens only occasionally):**
![image](https://user-images.githubusercontent.com/45380466/49060262-c3ad4800-f232-11e8-9b77-4e20d2d6b347.png)
cc @ashutoshbhide  @SujataDarekar

**Comment by sonalshingavi** [comment]
Closing this issue, fixed by pull request #242.
