### ISSUE TITLE
Title for" generating pom for application" wizard is missing for maven plugin

### ISSUE THREAD

**Issue by ahansa** [TIBCOSoftware/bw6-plugin-maven#218]
Maven Plugin version: 2.0.2

Maven version: Apache Maven 3.6.0

Product : TIBCO ActiveMatrix Businessworks 6 

Product version: 650 V99.1

Component: Maven Eclipse Plugin

**Steps to reproduce the issue:**
1. Import any app space sample , say tibco.bw.sample.binding.rest.Basic.application
2. Right click on the .application and Select Generate POM for application 
3. Observe the title bar of the wizard window

**Additional environment details if any:**

**Describe the results you received:**
Title is missing

**Describe the results you expected:**
Title should appear for the wizard window

**Additional information you deem important (e.g. issue happens only occasionally):**
![image](https://user-images.githubusercontent.com/45380466/49060361-4504da80-f233-11e8-954e-d17623610df5.png)

cc @ashutoshbhide @SujataDarekar

**Comment by sonalshingavi** [comment]
Closing this issue, fixed by pull request #240.
