### ISSUE TITLE
Missing JAR files from EAR

### ISSUE THREAD

**Issue by anithareddycog** [TIBCOSoftware/bw6-plugin-maven#219]
Team,
Been searching the Issues for solution but none found.
Versions:
maven 3.5.4
plugin 1.2.2
BW 6.3.4

PROB:
 i dont see shared module included in ear file generated and packaged thru maven.whereas "generate archive" has the jar files.i am unable to figure it out. help is appreciated.

**Comment by SujataDarekar** [comment]
@anithareddycog Could you please share the logs of package goal?

**Comment by anithareddycog** [comment]
PF below log. Also, i am missing 'bwear' and 'bwmodule' package types. appreciate if you could explain the package types to be used.
******************************************************************************************************
[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] MessageSequence.application.parent
[INFO] Traf_LoggingClient
[INFO] MessageSequence
[INFO] MessageSequence.application
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building MessageSequence.application.parent 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Traf_LoggingClient 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building MessageSequence 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-ear-plugin:2.8:generate-application-xml (default-generate-application-xml) @ MessageSequence ---
[INFO] Generating application.xml
[INFO] 
[INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @ MessageSequence ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\Anitha.Reddy\Desktop\9-11-2018\MessageSequence\src\main\resources
[INFO] 
[INFO] --- maven-ear-plugin:2.8:ear (default-ear) @ MessageSequence ---
[INFO] Could not find manifest file: C:\Users\Anitha.Reddy\Desktop\9-11-2018\MessageSequence\target\MessageSequence-1.0.0-SNAPSHOT\META-INF\MANIFEST.MF - Generating one
[INFO] Building jar: C:\Users\Anitha.Reddy\Desktop\9-11-2018\MessageSequence\target\MessageSequence-1.0.0-SNAPSHOT.ear
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building MessageSequence.application 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-ear-plugin:2.8:generate-application-xml (default-generate-application-xml) @ MessageSequence.application ---
[INFO] Generating application.xml
[INFO] 
[INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @ MessageSequence.application ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\Anitha.Reddy\Desktop\MessageSeq - Copy\MessageSequence.application\src\main\resources
[INFO] 
[INFO] --- maven-ear-plugin:2.8:ear (default-ear) @ MessageSequence.application ---
[INFO] Could not find manifest file: C:\Users\Anitha.Reddy\Desktop\MessageSeq - Copy\MessageSequence.application\target\MessageSequence.application-1.0.0-SNAPSHOT\META-INF\MANIFEST.MF - Generating one
[INFO] Building jar: C:\Users\Anitha.Reddy\Desktop\MessageSeq - Copy\MessageSequence.application\target\MessageSequence.application-1.0.0-SNAPSHOT.ear
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] MessageSequence.application.parent ................. SUCCESS [  0.001 s]
[INFO] Traf_LoggingClient ................................. SUCCESS [  0.000 s]
[INFO] MessageSequence .................................... SUCCESS [  0.530 s]
[INFO] MessageSequence.application ........................ SUCCESS [  0.017 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.206 s
[INFO] Finished at: 2018-11-27T15:26:41+05:30
[INFO] Final Memory: 15M/368M
[INFO] ------------------------------------------------------------------------
***********************************************************************************************************

**Comment by SujataDarekar** [comment]
@anithareddycog  We just need to execute package goal on parent project using maven build which will ultimately call the bwear and bwmodule goals. Also please make sure that after adding the shared module dependency you are generating the POM for application project and then run the package goal from parent project.

**Comment by anithareddycog** [comment]
since i am new, i will explain what iam doing, please read it and help me out.
steps:
1. imported module and its shared module........and  created .application
2. generated pom on .application
3. hit with multiple errors esp,'bwear','bwmodule' is unknown packaging
4. i manually changed the packages to ear( guess it is wrong to change)
5.under debug config ran package goal on .application.parent.... the LOG above is wat i got.

![image](https://user-images.githubusercontent.com/44568767/49076553-4ea43780-f25f-11e8-9736-b0fcd9f7115a.png)

so......................with what you suggested, plz explain where exactly shd i run the maven build.

**Comment by anithareddycog** [comment]
i really appreciate your answer.

**Comment by SujataDarekar** [comment]
@anithareddycog Please don't change the packaging types from the POM files. Also If you got error of unknown package types which means maven plugin is not installed properly. In studio browse Help->Installation Details->Installed Software and then type Maven. It should show Maven Plugin with version 1.2.2. If it is not then plugin is not installed.
  Attaching the zoom recording for more details.
[SharedModule.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2622895/SharedModule.zip)

**Comment by anithareddycog** [comment]
sujatha,

i followed the sharedmodule.zip. I see maven is installed, tried to do maven build but failed again. PF log.

[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] MessageSequence.application.parent
[INFO] Traf_LoggingClient
[INFO] MessageSequence
[INFO] MessageSequence.application
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building MessageSequence.application.parent 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Traf_LoggingClient 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ Traf_LoggingClient ---
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-artifact/3.0/maven-artifact-3.0.jar
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-inject-plexus/1.4.2/sisu-inject-plexus-1.4.2.jar
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-core/3.0/maven-core-3.0.jar
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-settings/3.0/maven-settings-3.0.jar
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-settings-builder/3.0/maven-settings-builder-3.0.jar
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-repository-metadata/3.0/maven-repository-metadata-3.0.jar
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-aether-provider/3.0/maven-aether-provider-3.0.jar
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/sonatype/aether/aether-impl/1.7/aether-impl-1.7.jar
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/sonatype/aether/aether-spi/1.7/aether-spi-1.7.jar
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/sonatype/aether/aether-api/1.7/aether-api-1.7.jar
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-classworlds/2.2.3/plexus-classworlds-2.2.3.jar
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.1.0/plexus-utils-3.1.0.jar
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-filtering/3.1.1/maven-filtering-3.1.1.jar
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/3.0.0/maven-shared-utils-3.0.0.jar
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[INFO] Downloading: https://repo.maven.apache.org/maven2/commons-io/commons-io/2.5/commons-io-2.5.jar
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-interpolation/1.24/plexus-interpolation-1.24.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] MessageSequence.application.parent ................. SUCCESS [  0.001 s]
[INFO] Traf_LoggingClient ................................. FAILURE [ 22.205 s]
[INFO] MessageSequence .................................... SKIPPED
[INFO] MessageSequence.application ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23.896 s
[INFO] Finished at: 2018-11-28T11:49:26+05:30
[INFO] Final Memory: 17M/306M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.1.0:resources (default-resources) on project Traf_LoggingClient: Execution default-resources of goal org.apache.maven.plugins:maven-resources-plugin:3.1.0:resources failed: Plugin org.apache.maven.plugins:maven-resources-plugin:3.1.0 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.apache.maven:maven-artifact:jar:3.0, org.sonatype.sisu:sisu-inject-plexus:jar:1.4.2, org.sonatype.sisu:sisu-inject-bean:jar:1.4.2, org.sonatype.sisu:sisu-guice:jar:noaop:2.1.7, org.apache.maven:maven-core:jar:3.0, org.apache.maven:maven-settings:jar:3.0, org.apache.maven:maven-settings-builder:jar:3.0, org.apache.maven:maven-repository-metadata:jar:3.0, org.apache.maven:maven-aether-provider:jar:3.0, org.sonatype.aether:aether-impl:jar:1.7, org.sonatype.aether:aether-spi:jar:1.7, org.sonatype.aether:aether-api:jar:1.7, org.sonatype.aether:aether-util:jar:1.7, org.codehaus.plexus:plexus-classworlds:jar:2.2.3, org.sonatype.plexus:plexus-cipher:jar:1.4, org.codehaus.plexus:plexus-utils:jar:3.1.0, org.apache.maven.shared:maven-filtering:jar:3.1.1, org.apache.maven.shared:maven-shared-utils:jar:3.0.0, org.sonatype.plexus:plexus-build-api:jar:0.0.7, commons-io:commons-io:jar:2.5, org.codehaus.plexus:plexus-interpolation:jar:1.24: Could not transfer artifact org.apache.maven:maven-artifact:jar:3.0 from/to central (https://repo.maven.apache.org/maven2): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :Traf_LoggingClient
______________________________________________________________________________________________
i dont understand if other jar files can be downloaded, why do i get the security error" sun.security.validator.ValidatorException: PKIX path building failed: "...........infact i have added the certificate to system.

**Comment by SujataDarekar** [comment]
@anithareddycog Could you please test with Maven Plugin version 1.3.1

**Comment by SujataDarekar** [comment]
@anithareddycog  Also could you please let us know which JRE version you are using? As per logs it seems like your server unable to connect to Maven repository at (https://repo.maven.apache.org/maven2
		 If you are using proxy and can access the link with browser the same settings need to be applied to Maven. For maven you need to add proxy details in settings.xml if you are using a proxy

**Comment by anithareddycog** [comment]
With same versions,i manged to resolve the issue, now i see jar files.
but resources folder is missing.
Any hints please.

**Comment by SujataDarekar** [comment]
@anithareddycog This can be checked by analyzing the logs. Please provide the same.

**Comment by SujataDarekar** [comment]
@anithareddycog Any update on this?

**Comment by SujataDarekar** [comment]
Closing the issue since there is no response from the last 2 months. Also, the issue with Missing JARS has been resolved.
