### ISSUE TITLE
While doing maven build, getting following error: [ERROR]   (use -source 7 or higher to enable multi-catch statement)

### ISSUE THREAD

**Issue by Chetan-Vatharkar** [TIBCOSoftware/bw6-plugin-maven#223]

**Comment by SujataDarekar** [comment]
@Chetan-Vatharkar  Which java version you are using? Please upgrade your java version

**Comment by Chetan-Vatharkar** [comment]
@SujataDarekar ..I am using openjdk version "1.8.0_191".

**Comment by SujataDarekar** [comment]
@Chetan-Vatharkar The error which you mentioned is usually face when we are using Java version below java7.  Could you please provide the complete logs and more details  like which build you are executing,maven plugin version?

**Comment by Chetan-Vatharkar** [comment]
BW6 maven plugin-- 2.0.1
goal--> mvn clean package
LOGS:----------
ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project Akamai: Compilation failure: Compilation failure:
[ERROR] /D:/pri_data/riverbed/base_bw6/Akamai/main/Akamai/src/Processes/IntegrationInterfaces/Akamai/ORACLEAKAMAIIntegration/Services/ScheduleGetCustomerServiceStatus/ScheduleGetCustomerServiceStatusSendRequestToAkamai.java:[138,41] multi-catch statement is not supported in -source 1.6
[ERROR]   (use -source 7 or higher to enable multi-catch statement)
[ERROR] /D:/pri_data/riverbed/base_bw6/Akamai/main/Akamai/src/Processes/IntegrationInterfaces/Akamai/ORACLEAKAMAIIntegration/DELETE/DeleteCustomerService/DeleteCustomerServiceSendRequestToAkamai.java:[126,41] multi-catch statement is not supported in -source 1.6
[ERROR]   (use -source 7 or higher to enable multi-catch statement)
[ERROR] /D:/pri_data/riverbed/base_bw6/Akamai/main/Akamai/src/Processes/IntegrationInterfaces/Akamai/ORACLEAKAMAIIntegration/PUT/UpdateCapacity/UpdateCapacitySendRequestToAkamai.java:[127,41] multi-catch statement is not supported in -source 1.6
[ERROR]   (use -source 7 or higher to enable multi-catch statement)
[ERROR] /D:/pri_data/riverbed/base_bw6/Akamai/main/Akamai/src/Processes/IntegrationInterfaces/Akamai/ORACLEAKAMAIIntegration/GET/GetCustomerServiceStatus/GetCustomerServiceStatusSendRequestToAkamai.java:[138,41] multi-catch statement is not supported in -source 1.6
[ERROR]   (use -source 7 or higher to enable multi-catch statement)
[ERROR] /D:/pri_data/riverbed/base_bw6/Akamai/main/Akamai/src/Processes/IntegrationInterfaces/Akamai/ORACLEAKAMAIIntegration/POST/CreateCustomerService/CreateCustomerServiceSendRequestToAkamai.java:[127,41] multi-catch statement is not supported in -source 1.6
[ERROR]   (use -source 7 or higher to enable multi-catch statement)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :Akamai

**Comment by Chetan-Vatharkar** [comment]
BW6 maven plugin-- 2.0.1
goal--> mvn clean package
LOGS:----------
ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project Akamai: Compilation failure: Compilation failure:
[ERROR] pathServices/ScheduleGetCustomerServiceStatus/ScheduleGetCustomerServiceStatusSendRequestToAkamai.java:[138,41] multi-catch statement is not supported in -source 1.6
[ERROR] (use -source 7 or higher to enable multi-catch statement)
[ERROR] pathDELETE/DeleteCustomerService/DeleteCustomerServiceSendRequestToAkamai.java:[126,41] multi-catch statement is not supported in -source 1.6
[ERROR] (use -source 7 or higher to enable multi-catch statement)
[ERROR] pathPUT/UpdateCapacity/UpdateCapacitySendRequestToAkamai.java:[127,41] multi-catch statement is not supported in -source 1.6
[ERROR] (use -source 7 or higher to enable multi-catch statement)
[ERROR] pathGET/GetCustomerServiceStatus/GetCustomerServiceStatusSendRequestToAkamai.java:[138,41] multi-catch statement is not supported in -source 1.6
[ERROR] (use -source 7 or higher to enable multi-catch statement)
[ERROR] pathPOST/CreateCustomerService/CreateCustomerServiceSendRequestToAkamai.java:[127,41] multi-catch statement is not supported in -source 1.6
[ERROR] (use -source 7 or higher to enable multi-catch statement)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR] mvn -rf :Akamai

**Comment by SujataDarekar** [comment]
@Chetan-Vatharkar  For which  scenario you are facing this issue? Are you using custom path function having dependency on external JARs or do you have any external JAR dependency in your project?

**Comment by SujataDarekar** [comment]
@Chetan-Vatharkar Any update on previous comment?

**Comment by SujataDarekar** [comment]
Closing the issue as there is no response from last one month. Please reopen in case you face the issue again
