### ISSUE TITLE
plugin v 2.1.0 does not have artefacts on maven central. 

### ISSUE THREAD

**Issue by mshahat** [TIBCOSoftware/bw6-plugin-maven#226]
Hi, 

Seems the plugin artefacts are not on maven central which is failing builds on build agents. 
https://mvnrepository.com/artifact/com.tibco.plugins/bw6-maven-plugin 

Thanks,

**Comment by ashutoshbhide** [comment]
Hi @mshahat 

I can see it on 
https://repo.maven.apache.org/maven2/com/tibco/plugins/bw6-maven-plugin/

Not sure why it doesnt get reflected on 

https://mvnrepository.com/artifact/com.tibco.plugins/bw6-maven-plugin

Ashutosh

**Comment by mshahat** [comment]
thanks @ashutoshbhide ... this helps
