### ISSUE TITLE
POM Generated shows error as 'Project Build Error: Non Readable Pom' in App Module.

### ISSUE THREAD

**Issue by BhosaleSaurabh** [TIBCOSoftware/bw6-plugin-maven#232]
Maven Plugin version: 2.1.0

Maven version: 

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version: BW6.5.1

Component: Maven build plugin

**Steps to reproduce the issue:**
1. Import Existing older project in 651 workspace. For older project the manifest file doesn't contain TIBCO-BW-Edition watermark.
2. Generate POM for the application in the wokspace.
3. Check the pom.xml file in the App Module. pom file has the error.

Note: If we refactor the project and update the target platform for same project no error is seen. Also if we generate new application in the same workspace and generate the pom for application, pom.xml doesn't show any error. 
[Maven210_GeneratePOM.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2726217/Maven210_GeneratePOM.zip)
**Additional environment details if any:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue is reproducible in new workspace. And once we refactor in one older project and then try importing other older project without watermark in same workspace and generate pom for same, proper file is generated.

**Comment by sonalshingavi** [comment]
Closing this issue, fixed by pull request #242.
