### ISSUE TITLE
Question: Is there a way to generate the Pom from the command line only and avoid using Designer?

### ISSUE THREAD

**Issue by Work1SaurGitHub** [TIBCOSoftware/bw6-plugin-maven#233]
Maven Plugin version: 1.3.1

Maven version:3.3.9

Product : Either of TIBCO ActiveMatrix Businessworks 

Product version:6.4.2

Component: Either of Maven Eclipse Plugin or Maven build plugin

We would like to do continuous integration. We are concerned about these use cases:
1) a developer adds a shared dependency to an application 
2) creates a new application

Now one way to resolve this would be to have the developers generate the pom using the plug in. But we would like not to burden the developers with this, because typically they test in designer and don't need to use Maven. So if a developer added a new dependency to a shared module and forgot to update the pom then the build would break. We realize we could enforce pom generation as a dev standard, but would prefer to automate this step and free our developers to concentrate on other things.

Ideally we would use Jenkins to pick up each check in and then generate all the poms needed for deployment and then  deploy. To do that we would need to build the poms from the command line.

**Comment by SujataDarekar** [comment]
@Work1SaurGitHub  We don't generate the POM file from command line. We are using the GUI to generate the POM and this can be done via studio only.

**Comment by Work1SaurGitHub** [comment]
SujataDarekar - Is there any prospect of that changing in a future version? Typically our developers do not use Maven in their daily work and we would not like to add the extra burden of forcing them to generate a POM (and possible having to regenerate one if shared dependencies change). If there was a way that the poms could be generated from the command line - than we could  have automated deployments and our developers would not have to worry about Maven.

**Comment by rubirada** [comment]
@Work1SaurGitHub Currently our plugin has the provision of generating POM through UI only. It is not feasible to provide an option for generating POM through the Command line. So you may not expect this in future releases also.

**Comment by SujataDarekar** [comment]
closing the issue based on the above comment

**Comment by rutujadeo-TIBCO** [comment]
An enhancement has been filed for this  [AMBW-49157](https://jira.tibco.com/browse/AMBW-49157)
