### ISSUE TITLE
External Shared Module not imported in Studio after searching the available ESM using Group ID in Dependency section of the POM.xml file 4 of 5 Return to search

### ISSUE THREAD

**Issue by ankitapandey1** [TIBCOSoftware/bw6-plugin-maven#234]
Maven Plugin version: 2.0.1

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version:6.4.2

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
When we search the available External Shared Module in the Maven Repository by providing the Group ID in the text field and select the External Shared Module from the Search Result, the Shared Module is not added in the Workspace.

**Comment by SujataDarekar** [comment]
Issue fixed with pull request https://github.com/TIBCOSoftware/bw6-plugin-maven/pull/238
