### ISSUE TITLE
Providing Invalid Tibco Home location during installation, the cmd window is closed directly.

### ISSUE THREAD

**Issue by BhosaleSaurabh** [TIBCOSoftware/bw6-plugin-maven#235]
Maven Plugin version: 2.1.0

Maven version:

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version:BW6.5.1

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1. Run Install.bat file in the installer package.
2.Provide invalid Tibco Home path.
3.Check the window. It is closed directly. User is unable to check the reason for the same.

**Additional environment details if any:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
May we we can show the Error/Warning as invalid Tibco Home path and don't close the command window.
[Maven_InvalidTibcoHome_WindowClosed.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2740648/Maven_InvalidTibcoHome_WindowClosed.zip)

**Comment by SujataDarekar** [comment]
@BhosaleSaurabh If you run the  install.bat on command prompt with invalid Tibco home, It is showing the proper error message. PFA screenshot for more details.
![maveninstall](https://user-images.githubusercontent.com/31987978/51098764-97ee1d80-17f2-11e9-9811-159e2d90dd60.jpg)
