### ISSUE TITLE
Maven goal timing out.

### ISSUE THREAD

**Issue by Chetan-Vatharkar** [TIBCOSoftware/bw6-plugin-maven#236]
How can we increase the timeout value of a maven goal?

**Comment by NidhiRajeshDhoka** [comment]
@Chetan-Vatharkar Currently,we don't support goal timeout configuration.What is the exact requirement and use-case for this?

**Comment by NidhiRajeshDhoka** [comment]
@Chetan-Vatharkar  Any updates on this?

**Comment by SujataDarekar** [comment]
Closing the issue since there is no response from long time
