### ISSUE TITLE
confusion about tibco-home

### ISSUE THREAD

**Issue by mshahat** [TIBCOSoftware/bw6-plugin-maven#24]
An install on Mac OS X 10.11.6 (15G31)

/opt/tibco ( bw v6.3.2 )
/opt/tibco/bwce (bwce v2.0.0 ) 

Installing bw-plugin-mavin v1.1 - provided /opt/tibco as tibco_home 

installed it under bwce and not bw ! 

Thanks,

**Comment by roagarwal** [comment]
Can you please change bwce v2.0.0 path name from bwce to something else -
/opt/tibco/bwce2.0  (may-be)
I think this should solve your problem, we are using bwce as a key-word for installation.

**Comment by mshahat** [comment]
Alright. 

In the meanwhile i've uninstall bwce and that seems to have solved the situation . 

Do you need me to reproduce it ? or you know 'bwce' as name has caused the issue

**Comment by roagarwal** [comment]
Great. 
No I am sure that 'bwce' keyword has caused the issue.
