### ISSUE TITLE
Issue - BW 6.5 maven plugin installation failed

### ISSUE THREAD

**Issue by exceed007** [TIBCOSoftware/bw6-plugin-maven#245]
### BW version 6.5 , apache-maven version - 3.6.0 , BW maven plugin version - 2.1.0

 **Build is failing due to unknown errors. Thanks in advance.** 

> studio-install:
>      [echo]  Installing Eclipse M2E Plugin to Tibco Home
>      [exec] org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
>      [exec] log4j:WARN No appenders could be found for logger (org.apache.http.impl.conn.SingleClientConnManager).
>      [exec] log4j:WARN Please initialize the log4j system properly.
>      [exec] Installing org.eclipse.equinox.p2.discovery.feature.feature.group 1.0.200.v20140512-1802.
>      [exec] Operation completed in 31079 ms.
>      [exec] org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
>      [exec] Installing bw6.maven.dependencies.feature.feature.group 1.0.0.001.
>      [exec] Operation completed in 4875 ms.
>      [exec] org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
>      [exec] Installing org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836.
>      [exec] Installing org.eclipse.m2e.sdk.feature.feature.group 1.6.2.20151013-0836.
>      [exec] Installing org.eclipse.m2e.logback.feature.feature.group 1.6.2.20151013-0836.
>      [exec] Operation completed in 2881 ms.
>      [echo]  UnInstalling the existing version of Plugin Code for Apache Maven and TIBCO BusinessWorksÖ
>      [exec] org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
>      [exec] Uninstalling bw6.studio.maven.feature.feature.group 2.1.0.001.
>      [exec] Operation completed in 7625 ms.
>      [echo]  Installing Studio Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorksÖ to the Tibco Home
>      [exec] org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
>      [exec] Installing bw6.studio.maven.feature.feature.group 2.1.0.001.
>      [exec] Operation completed in 9115 ms.
> 
> maven-install:
>      [echo]  Installing Maven Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorksÖ to Local Maven Repository
> 
> BUILD FAILED
> C:\Users\akhairna\Desktop\cicd\TIB_BW_Maven_Plugin_2.1.0\build.xml:134: Directory C:\Program Files\tibco\bw6\bw\6.5\maven\plugins creation was not successful for an unknown reason
> 
> Total time: 1 minute 48 seconds

**Comment by SujataDarekar** [comment]
@exceed007 Could you please check directory "C:\Program Files\tibco\bw6\bw\6.5\maven\plugins"  is already created?

**Comment by exceed007** [comment]
> \maven\plugins  is not created.

**Comment by exceed007** [comment]
@SujataDarekar Any updates on this ?

**Comment by SujataDarekar** [comment]
@exceed007 as per the logs I can see that error is coming while creating directory "C:\Program Files\tibco\bw6\bw\6.5\maven\plugins". The reason could be the permission problem. Please check for the same.

**Comment by exceed007** [comment]
i created new tibco home and now it is working. thanks.

**Comment by vaishnavishan** [comment]
I faced same error ...after creating new tibco home ...how to generate pom application in studio designer

**Comment by ukuppa-tibco** [comment]
> I faced same error ...after creating new tibco home ...how to generate pom application in studio designer

Can you check for permissions on the TIBCO home folder.
