### ISSUE TITLE
Question: Install Share Module in Maven Repository as Binary

### ISSUE THREAD

**Issue by alexandrev** [TIBCOSoftware/bw6-plugin-maven#247]
Is it possible to install shared module in maven repository as binary? I've read wiki about Shared Moudle support but the steps there are to push a "normal" shared module to the repository but not as binary, so all the process are in text and could be viewed. 

Can this be done with configuration in pom file? 

Regards,

**Comment by alexandrev** [comment]
it's question but I couldn't apply labels to the issue. Sorry.

**Comment by alexandrev** [comment]
@SujataDarekar but does this pom have something special from the one that is shared module (without binary?) It should be the same since this must be done before "Exporting as Binary".. so, it means there are no way to store it in the .m2 as binary, only as a normal shared module. Could you confirm?

Thanks,

**Comment by SujataDarekar** [comment]
@alexandrev Yes, we can store the only normal shared module in .m2. Closing the issue.
