### ISSUE TITLE
Enhacement JUnit Support

### ISSUE THREAD

**Issue by alexandrev** [TIBCOSoftware/bw6-plugin-maven#255]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->
Maven Plugin version: 2.1.1

Maven version: 3.5.2

Product : TIBCO ActiveMatrix Businessworks 

Product version: 6.5.0

Component: Maven Build / Test Plugin

**Steps to reproduce the issue:**
1. When you do an mvn test or similar command output should be not only the great HTML page we have now but JUnit file so this could be imported and used in other tools based on that common standard like SonarQube.

**Comment by ashutoshbhide** [comment]
@alexandrev 

After running the maven test goal the the response from the BWEngine is stored in file bwtestreport.xml at location
<Workspace>/<Application Project>/target/bwtest/bwtestreport.xml
The Site report HTML page is generated from this xml file.

You can take a look at this file to see if you have the required data for exporting to SonarCube.

If you look at the class /bw6-maven-plugin/src/main/java/com/tibco/bw/maven/plugin/test/rest/BWTestRunner.java

here you can find how the report xml is saved. Look at method
private void saveReport( CompleteReportDTO resultDTO) 

If you want to have your own format you can customize it here and use it.

-Ashutosh

**Comment by alexandrev** [comment]
Hi Ashutosh,

What I'd like to do to be able to have the info imported in sonarqube, is
to be abel to export the data in the Surefire format. Please take a look at
the format, but this is quite common in java+ maven world.

https://maven.apache.org/surefire/maven-surefire-plugin/

https://docs.sonarqube.org/display/PLUG/Java+Unit+Tests+and+Coverage+Results+Import

Taking a look at the schema:
https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report-3.0.xsd
I'm not sure we have all data needed in the report XML file that we're
generating at the moment, thats why I'm asking for this enhacement.

Thanks!

**Comment by ashutoshbhide** [comment]
@alexandrev 

We have similar though not exact structure. 
Surefire report mainly deals with Java classes while we deal with Processes so we had to modify the objects accordingly.

To generate with the Surefire test report schema, you will have to first see what is one-2-one mapping of Java Class vs the BW Process and then decide what values to populate there.

So basically you will have to construct your own Java beans corresponding to the xml structure you want to achieve and then marshal that beans to the xml file and then pass that file to Sonarcube plugin.

It will not be that straight forward but it will be doable. But it will require efforts and time.

-Ashutosh

**Comment by rutujadeo-TIBCO** [comment]
This enhancement will be part of [AMBW-49782](https://jira.tibco.com/browse/AMBW-49782)
