### ISSUE TITLE
Runnable getInputRunnable java code UNIT TESTING

### ISSUE THREAD

**Issue by jwerginz** [TIBCOSoftware/bw6-plugin-maven#258]
I turned on debugging here:
while((line = br.readLine()) != null) {
			        	
			        	**System.out.println( " getInputRunnable line "+line);**
			        	if( line.contains( "Started BW Application") )
						{
							latch.countDown();
						}
			        	
			            sb.append( line );
			        }
[test.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2985581/test.txt)
Getting all kinds of weird errors it looks like from within Business Studio when running unit testing.

Any help would be much appreciated

**Comment by jwerginz** [comment]
Does anyone how those resource files were generated?

**Comment by SujataDarekar** [comment]
@jwerginz  As per the logs, I can see the bundle unresolved errors. There was a unit testing issue with 6.5.0 HF4 which was fixed with maven Plugin 2.2.0. You can try to debug with the latest installer and source code.
Please reopen in case you any errors.
