### ISSUE TITLE
NullPointerException in BWTestMojo.java if skipTests property not set

### ISSUE THREAD

**Issue by kkane-tibco** [TIBCOSoftware/bw6-plugin-maven#261]
The BWTestMojo class has an invalid test for a property, which produces an NPE if the property is not set. The problem is the method isSkipTests assumes the property exists in the pom.xml file for the application.

Here's the code, with the suggested fix in a comment:

>if( project.getProperties().get("skipTests").equals("true") )
// should be if( "true".equals(...)

Maven Plugin version: 2.1.1
Maven version: 3.3.9 (or thereabouts)
Product : BW6
Product version: 6.5.1
Component: Maven build plugin

**Steps to reproduce the issue:**
1. Remove the <properties> section from the pom.xml file of the application
2. Run mvn package on the parent build pom
3. Observe the error

**Comment by SujataDarekar** [comment]
@kkane-tibco when the property is not set,  It will not throw the NPE because It will consider it's  default value but when we remove the property "skipTests" from the POM file it will throw NPE which we will fix.

**Comment by SujataDarekar** [comment]
Changes have been done with Maven Plugin 2.2.0
