### ISSUE TITLE
Add swagger HTTP port as property for Maven [enhancement]

### ISSUE THREAD

**Issue by kwoodie** [TIBCOSoftware/bw6-plugin-maven#262]
We have been using the maven plugin to deploy to our BW6 standard environment (not containers).  We have many application nodes running on the same hosts and the default port of the Swagger-ui is causing us to have contention on ports.   Currently we will deploy via the Maven plugin and it will create an appnode with the 7777 port selected (BW default) for the swagger port.  I would like to have this port as a parameter in the properties that Maven takes when creating the AppNode/AppSpace.   As of right now after the deployment finishes I have to remember to go and fix the port and restart the AppNode.  It would be much cleaner if I could just pre-configure that within the properties to Maven.

**Comment by bakchatmantics** [comment]
any news on this ?

**Comment by anouarattn** [comment]
any news on this ?
