### ISSUE TITLE
Missing ActivityId caused by recent versions of the plugin 

### ISSUE THREAD

**Issue by mshahat** [TIBCOSoftware/bw6-plugin-maven#263]
Hi, 
this issue is experienced on multiple BWCE versions 2.4.3 and 2.4.2 on both macOS and Windows 10. it was possible to isolate the problem on multiple environments and is not experienced on environments without the plugin. 

the issue is as shown in the screenshot. 

Thanks, 

![Screenshot 2019-01-30 at 14 27 01](https://user-images.githubusercontent.com/8035442/55631804-c99ed100-57b0-11e9-8793-18de4b7681ff.png)

**Comment by skumar-tibco** [comment]
@mshahat  Thanks for the feedback.  The issue has been reproduced and we are working to address the same.

**Comment by albertosev** [comment]
Hi,

I have the same problem with the version 2.1.1 Is there any solution?

Thanks!

**Comment by awagle** [comment]
This is related to Studio and not maven plugin as such. This has been fixed in the latest versions with quick fixes available.
