### ISSUE TITLE
pom.xml is getting generated with Errors

### ISSUE THREAD

**Issue by amitmohanty88** [TIBCOSoftware/bw6-plugin-maven#264]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->
Maven Plugin version:TIB_BW_Maven_Plugin_2.1.1

Maven version:apache-maven-3.5.3

Product : Either of TIBCO ActiveMatrix Businessworks 6 

Product version:6.4.2

Component: Either of Maven Eclipse Plugin 

Steps to reproduce the issue:
1.Import Code.zip in BW 6.4.2 studio Version .Right Click HIP.GLBL.ACCESS.SalesOrder.application Generate POM for Application
2.pom.xml will be created with errors .
3.Then Maven clean still errors .
4.Attached all the Necessary Screenshots and codes.

Additional environment details if any:
windows 64 bit

Describe the results you received:
Attached in SR.docx screenshot and other artifacts attached

Describe the results you expected:

pom.xml should be generate with no errors

Additional information you deem important (e.g. issue happens only occasionally):
[Code.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3054138/Code.zip)
[POMProject.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3054140/POMProject.zip)
[settings.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3054143/settings.zip)
[SR.docx](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3054145/SR.docx)

**Comment by amitmohanty88** [comment]
@sonalshingavi  Thanks for looking the issue .I have uninstalled and Reinstalled TIBCO BW Maven Plugin 2.1.1 and now i am no longer getting the missing dependancy error .Now i am getting below error 

[ERROR] Unknown lifecycle phase "Order". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhaseNotFoundException

KIndly let me know what is going wrong

**Comment by sonalshingavi** [comment]
Hi @amitmohanty88 

Which goal are you executing when you get the error  **Unknown lifecycle phase "Order". **?

**Comment by amitmohanty88** [comment]
@sonalshingavi ,

Thanks for the Quick Response .This goal issue is fixed now because there was a space in the path given to the deployment configuration file which contains appnode and appspace details .

But again i am getting the old error for which i raised this issue 

Below is the Error the ear is getting deployed to TEA but going to start failed due to below error for the project attached in this SR:

[ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.1.1:bwinstall (default-bwinstall) on project HIP.GLBL.ACCESS.SalesOrder.application: Failed to deploy BW Application : TIBCO-BW-RESTAPI-500400: Deployed application from the archive [HIP.GLBL.ACCESS.SalesOrder.application_1.0.0.ear], however not all application instances started.  <CausedBy> WARNING: exception with message ***Error starting application [HIP.GLBL.ACCESS.SalesOrder.application:1.0]*** has not been localized: TIBCO-BW-ADMIN-500444: Failed to start Application in AppNode [AN_3DPACKSHOT]. Check the AppNode log files for messages starting with TIBCO-THOR-FRWK, TIBCO-BW-FRWK, or TIBCO-BW-SR-FRWK for details. Application State [StartFailed], reason : TIBCO-THOR-FRWK-500201: Failed to start bundle [HIP.GLBL.ACCESS.SalesOrder_1.0.0.201904170547 [1381]], <CausedBy> Could not resolve module: HIP.GLBL.ACCESS.SalesOrder [1381]
[ERROR]   Unresolved requirement: Require-Bundle: HIP.ESB.ProjectTemplate; bundle-version="1.3.0"
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :HIP.GLBL.ACCESS.SalesOrder.application



All our Project auto deployment is blocked due to this issue .

If required can i  share my webex so that this issue can be fixed ?

**Comment by sonalshingavi** [comment]
Hi @amitmohanty88 
You can share the webex.
Are you able to deploy this project successfully without using maven?

**Comment by amitmohanty88** [comment]
@sonalshingavi ,

Yes i am able to deploy to TIBCO TEA but its getting deployed with Start failed with above error

https://infosys.webex.com/join/amit.mohanty

Can you please join above webex at 3 PM IST  .

I will open my webex at 3 PM IST.

**Comment by sonalshingavi** [comment]
Hi @amitmohanty88 
Do you mean that application getting start failed even you deployed the EAR without using maven plugin?

Sorry, I can not join webex.
I will try it out at my end and let you know.
Thank You

**Comment by amitmohanty88** [comment]
@sonalshingavi ,

Yes Application is getting started and Running fine in TEA  if i am deploying without maven plugin .

But if i am deploying with maven plugin using pom.xml its getting deployed to TEA but status is coming as Start failed with below error in TEA:

2019-04-17 05:41:25.967 INFO  [qtp206554640-41] com.tibco.thor.frwk.Application - TIBCO-THOR-FRWK-300008: Stopped BW Application [HIP.GLBL.ACCESS.SalesOrder.application:1.0]
2019-04-17 05:48:07.889 INFO  [qtp206554640-40] com.tibco.thor.frwk.Application - TIBCO-THOR-FRWK-300009: Preparing to undeploy BW Application [HIP.GLBL.ACCESS.SalesOrder.application:1.0]
2019-04-17 05:48:07.889 INFO  [qtp206554640-40] com.tibco.thor.frwk.Application - TIBCO-THOR-FRWK-300010: Undeploying BW Application [HIP.GLBL.ACCESS.SalesOrder.application:1.0]
2019-04-17 05:48:08.046 INFO  [Thread-23] com.tibco.thor.frwk.Application - TIBCO-THOR-FRWK-300011: Undeployed BW Application [HIP.GLBL.ACCESS.SalesOrder.application:1.0]
2019-04-17 05:49:59.207 INFO  [Refresh Thread: Equinox Container: a01ff28d-5660-0019-1bc3-e8cbe2d2ba0e] com.tibco.thor.frwk.Application - TIBCO-THOR-FRWK-300018: Deploying BW Application [HIP.GLBL.ACCESS.SalesOrder.application:1.0].
2019-04-17 05:49:59.207 INFO  [Refresh Thread: Equinox Container: a01ff28d-5660-0019-1bc3-e8cbe2d2ba0e] com.tibco.thor.frwk.Application - Application bundle [HIP.GLBL.ACCESS.SalesOrder.application_1.0.0.201904170547 [1378]] is resolved, but not started
2019-04-17 05:49:59.650 INFO  [Thread-34] com.tibco.thor.frwk.Application - TIBCO-THOR-FRWK-300008: Stopped BW Application [HIP.GLBL.ACCESS.SalesOrder.application:1.0]
2019-04-17 05:49:59.722 INFO  [qtp206554640-38] com.tibco.thor.frwk.Application - TIBCO-THOR-FRWK-300005: Starting BW Application [HIP.GLBL.ACCESS.SalesOrder.application:1.0]
2019-04-17 05:49:59.755 INFO  [qtp206554640-38] com.tibco.thor.frwk.Application - TIBCO-THOR-FRWK-300021: All Application dependencies are resolved for Application [HIP.GLBL.ACCESS.SalesOrder.application:1.0]
2019-04-17 05:49:59.773 ERROR [qtp206554640-38] c.t.b.thor.runtime.model.Application - The following error has occurred for "name: HIP.GLBL.ACCESS.SalesOrder.application version: 1.0 bundle name: HIP.GLBL.ACCESS.SalesOrder.application " which needs to be resolved.
2019-04-17 05:49:59.773 ERROR [qtp206554640-38] c.t.b.thor.runtime.model.Application - TIBCO-THOR-FRWK-500201: Failed to start bundle [HIP.GLBL.ACCESS.SalesOrder_1.0.0.201904170547 [1381]], <CausedBy> Could not resolve module: HIP.GLBL.ACCESS.SalesOrder [1381]
  Unresolved requirement: Require-Bundle: HIP.ESB.ProjectTemplate; bundle-version="1.3.0"

2019-04-17 05:50:00.106 INFO  [qtp206554640-38] com.tibco.thor.frwk.Application - TIBCO-THOR-FRWK-300008: Stopped BW Application [HIP.GLBL.ACCESS.SalesOrder.application:1.0]



And below Error is we are getting during deployment using Maven plugin fro jenkins 

[ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.1.1:bwinstall (default-bwinstall) on project HIP.GLBL.ACCESS.SalesOrder.application: Failed to deploy BW Application : TIBCO-BW-RESTAPI-500400: Deployed application from the archive [HIP.GLBL.ACCESS.SalesOrder.application_1.0.0.ear], however not all application instances started. WARNING: exception with message Error starting application [HIP.GLBL.ACCESS.SalesOrder.application:1.0] has not been localized: TIBCO-BW-ADMIN-500444: Failed to start Application in AppNode [AN_3DPACKSHOT]. Check the AppNode log files for messages starting with TIBCO-THOR-FRWK, TIBCO-BW-FRWK, or TIBCO-BW-SR-FRWK for details. Application State [StartFailed], reason : TIBCO-THOR-FRWK-500201: Failed to start bundle [HIP.GLBL.ACCESS.SalesOrder_1.0.0.201904170547 [1381]], Could not resolve module: HIP.GLBL.ACCESS.SalesOrder [1381]
[ERROR] Unresolved requirement: Require-Bundle: HIP.ESB.ProjectTemplate; bundle-version="1.3.0"
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR] mvn -rf :HIP.GLBL.ACCESS.SalesOrder.application

Attached is the Start Failed Screenshot from TEA when deploying via Maven plugin 
[MavenPluginIssue.docx](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3088813/MavenPluginIssue.docx)

**Comment by sonalshingavi** [comment]
Thank You @amitmohanty88 
I will try it out at my end and let you know.

**Comment by amitmohanty88** [comment]
@sonalshingavi 
Thanks for checking out the issue just checking if you have  found the issue on this .

**Comment by awagle** [comment]
Please check HIP.ESB.ProjectTemplate project. The version in pom.xml is 1.0.0 and Manifest is 1.3.0. Can you sync them to one version and rebuild the EAR and attach it again? Try changing the version to 1.3.0 in the POM file and rebuild using Maven. The Application Module is trying to find version 1.3.0 but the built version is 1.0.0

**Comment by amitmohanty88** [comment]
@awagle  
Aditya after changing all project versions to 1 version we were able to deploy successfully but the ear is going under Application Archives Section .But we have project specific folders inside Application Archives where we want to place the archive during auto deployment .

Below is the Deployment Config Properties which is working

deployToAdmin=true
profile=QA.substvar
domain=QAESB
appSpace=ACCESS_CUSTOMER
redeploy=true
httpPort=8079
hostname=FRHIPGQAESB01.emea.loreal.intra
appNode=AN_ACCESS_CUSTOMER
agentPort=8079
agentHost=FRHIPGQAESB01

But if I am trying to update with Application Archive Folder Auto deployment is happening but ear is not going to Project Specific Folder below does not work.Tried with (Application Archives,Archives,archives,archive)

deployToAdmin=true
profile=QA.substvar
domain=QAESB
appSpace=ACCESS_CUSTOMER
redeploy=true
httpPort=8079
hostname=FRHIPGQAESB01.emea.loreal.intra
appNode=AN_ACCESS_CUSTOMER
agentPort=8079
agentHost=FRHIPGQAESB01
Application Archives=ACCESS

Can you please tell what property we need to add for Application Folder Archive location

**Comment by amitmohanty88** [comment]
@awagle @sonalshingavi @SujataDarekar 
After changing all project versions to 1 version we were able to deploy successfully but the ear is going under Application Archives Section .But we have project specific folders inside Application Archives where we want to place the archive during auto deployment .

Below is the Deployment Config Properties which is working

deployToAdmin=true
profile=QA.substvar
domain=QAESB
appSpace=ACCESS_CUSTOMER
redeploy=true
httpPort=8079
hostname=FRHIPGQAESB01.emea.loreal.intra
appNode=AN_ACCESS_CUSTOMER
agentPort=8079
agentHost=FRHIPGQAESB01

But if I am trying to update with Application Archive Folder Auto deployment is happening but ear is not going to Project Specific Folder below does not work.Tried with (Application Archives,Archives,archives,archive)

deployToAdmin=true
profile=QA.substvar
domain=QAESB
appSpace=ACCESS_CUSTOMER
redeploy=true
httpPort=8079
hostname=FRHIPGQAESB01.emea.loreal.intra
appNode=AN_ACCESS_CUSTOMER
agentPort=8079
agentHost=FRHIPGQAESB01
Application Archives=ACCESS

Could you please tell what property we need to add for Application Folder Archive location

**Comment by sonalshingavi** [comment]
Hi @amitmohanty88 
We don't provide any config property for Application Archives folder when you are deploying the application from the studio.
Whenever you are deploying the application, the EAR file will be created under **project_application/target/** folder and it will deploy the application successfully.

If you want to deploy EAR from project specific folder we provide "bwdeployer" goal. You can refer 
https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/EAR-Deployment  

Let me know if you have any queries.

**Comment by goutham-muragavel** [comment]
> Hi @amitmohanty88
> We don't provide any config property for Application Archives folder when you are deploying the application from the studio.
> Whenever you are deploying the application, the EAR file will be created under **project_application/target/** folder and it will deploy the application successfully.
> 
> If you want to deploy EAR from project specific folder we provide "bwdeployer" goal. You can refer
> https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/EAR-Deployment
> 
> Let me know if you have any queries.

Hi Sonal, we are deploying the application using jenkins and using the deployment.properties file which has the details of appspace, domain. we would like to know how to mention the application archives directory in this deployment.properties file as by default everything is getting stored in <<BW_HOME>>/domains/<<DomainName>>/archives/. In TIBCO Tea there is provision to create a sub folder from the mentioned path and upload the ear.
We are looking for the same functionality. Please let us know on this.

**Comment by goutham-muragavel** [comment]
Hi @sonalshingavi , we are deploying the application using jenkins and using the deployment.properties file which has the details of appspace, domain. we would like to know how to mention the application archives directory in this deployment.properties file as by default everything is getting stored in <<BW_HOME>>/domains/<>/archives/. In TIBCO Tea there is provision to create a sub folder from the mentioned path and upload the ear.
We are looking for the same functionality. Please let us know on this.

**Comment by goutham-muragavel** [comment]
> Hi @sonalshingavi , we are deploying the application using jenkins and using the deployment.properties file which has the details of appspace, domain. we would like to know how to mention the application archives directory in this deployment.properties file as by default everything is getting stored in <<BW_HOME>>/domains/<>/archives/. In TIBCO Tea there is provision to create a sub folder from the mentioned path and upload the ear.
> We are looking for the same functionality. Please let us know on this.

@awagle , can you please look into this.

**Comment by sonalshingavi** [comment]
Hi @goutham-muragavel 
Can you please elaborate the scenario. as it seems a bit unclear.

**Comment by sonalshingavi** [comment]
Hi @goutham-muragavel 
As you mentation, You have application archive location which you want to add in deployment.properties file.
Do you have an EAR file already created? or are you using the same EAR file generated in the target folder?
Can you please elaborate the scenario, as it seems lit unclear to me.

**Comment by goutham-muragavel** [comment]
Hi @sonalshingavi , we are using the same EAR file generated in target folder and using the deployment.properties file to deploy to the specified appspace. Now, we would like to know how to mention the application archive location to a different folder.
Please let me know if we need to setup a webex to discuss on this.

**Comment by sonalshingavi** [comment]
Hi @goutham-muragavel 
Thanks for elaborating the scenario, I get your requirement.
I am working on it. I will let you know ones I have more information.

**Comment by goutham-muragavel** [comment]
> Hi @goutham-muragavel
> Thanks for elaborating the scenario, I get your requirement.
> I am working on it. I will let you know ones I have more information.

@awagle @sonalshingavi , Please let me know if you were able to check on this.

**Comment by awagle** [comment]
Folks this is an enhancement and @sonalshingavi will provide updates once we have completed evaluation. Appreciate your patience. Meanwhile if you do have suggestions feel free to send a pull request and we would be happy to merge it.

**Comment by awagle** [comment]
@goutham-muragavel I will create a new issue and reference this issue there. I see the original issue reported was different to the one we are talking about now.
Closing this issue. Opened #276
