### ISSUE TITLE
Missing artifact com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100 --- Maven 1.3.1

### ISSUE THREAD

**Issue by saravanaprasaths** [TIBCOSoftware/bw6-plugin-maven#265]
Hi All,

I am using BWCE 2.3.4 and using Maven plugin 1.3.1. Still getting the below error:

Error: Missing artifact com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100	pom.xml	/HelloWorld.module	line 14	Maven Dependency Problem

I can find the jar file in the below directory:
TIBCO_HOME\bwce\2.3\maven\plugins\bw6-maven-plugin\com.tibco.bw.palette.shared_6.1.100.003.jar

Please help how to resolve?

**Comment by SujataDarekar** [comment]
@saravanaprasaths Please try with the latest Tibco Maven plugin version 2.1.1 and let us know if you face the same issue again

**Comment by vinitamonga** [comment]
> @saravanaprasaths Please try with the latest Tibco Maven plugin version 2.1.1 and let us know if you face the same issue again

I am facing this same issue with Maven plugin 2.1.1. Below are the errors after generating pom.xml file.

Missing artifact com.tibco.plugins:com.tibco.xml.cxf.common:jar:1.3.200
Missing artifact com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100

I can see both jars are present in \TIBHome_CE\bwce\2.4\maven\plugins\bw6-maven-plugin

**Comment by SujataDarekar** [comment]
@saravanaprasaths  Which Apache Maven version are you using?

**Comment by SumenBiswas** [comment]
@SujataDarekar 
Installed TIB_BW_Maven_Plugin_2.1.1 but still I'm getting Missing artifact com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100.

![image](https://user-images.githubusercontent.com/51710102/59279511-09ab8580-8c32-11e9-93cb-d4532ffbc083.png)

![image](https://user-images.githubusercontent.com/51710102/59279597-3495d980-8c32-11e9-897d-63c08f2615f8.png)

**Comment by SujataDarekar** [comment]
@saravanaprasaths Can you please confirm which apache maven version you are using by running "mvn -v" on command prompt

**Comment by saravanaprasaths** [comment]
@SujataDarekar , I am using the latest Maven, but my issue was not related to version. For me the issue got resolved after renaming the jar's, those files where having ".lastUpdated".

**Comment by SujataDarekar** [comment]
@saravanaprasaths there are 2 reasons for getting Missing artifact error. One if you have the artifact with .lastupdated  and the second one is if you don't have Apache Maven installed in that case also there is a chance to get Missing artifact exception. Now in your last comment, I can see the JARs with proper extension hence asked for maven version. If your issue got resolved then, please close the same
