### ISSUE TITLE
EAR generated using maven for BW6.5 application is incomplete

### ISSUE THREAD

**Issue by deepatailor** [TIBCOSoftware/bw6-plugin-maven#268]
I ma using maven plugin to facilitate CI/CD for our BW 6.5 applications. I have gone through various steps to set it up, however while running the maven build the EAR generated seems to be incomplete and not containing any of the BW application resources or dependency shared modules.

I am suspecting its due to its trying to look for source code according to java project structure instead of BW project structure.

Need help determining what to be done to instruct maven to consider BW application EAR packaging instead of Java. I have provided log from the maven build below for reference and can provide any additional information needed to help resolve this issue.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Maven Plugin version:2.1.1
Maven version:3.6.1
Product : TIBCO ActiveMatrix Businessworks 6.5
Product version:6.5
Component: Maven Eclipse Plugin
**Steps to reproduce the issue:**
1. Install BW maven plugin
2. Genarate pom for application
3.Create new maven configuration with goals as validate compile package
4. Run the maven configuration

**Additional environment details if any:**
NA
**Describe the results you received:**
Build is successful and EAR is generated, but size of the EAR is 27KB whereas if we manually generate EAR of the applicaiton the size is close to 780 KB

**Describe the results you expected:**
EAR generated using Maven is same as EAR generated manually

**Additional information you deem important (e.g. issue happens only occasionally):**
Below is the execution log for the build from eclipse
[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building crm.systemuser.application 1.10.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ crm.systemuser.application ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\deepat\workspace-MavenTest\crm.systemuser.application\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ crm.systemuser.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ crm.systemuser.application ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\deepat\workspace-MavenTest\crm.systemuser.application\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ crm.systemuser.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ crm.systemuser.application ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\deepat\workspace-MavenTest\crm.systemuser.application\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ crm.systemuser.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- bw6-maven-plugin:2.1.1:bwtest (default-bwtest) @ crm.systemuser.application ---
[INFO] -------------------------------------------------------
[INFO] Provided TibcoHome directory is invalid. Skipping Test Phase.
[INFO] -------------------------------------------------------
[INFO] 
[INFO] --- bw6-maven-plugin:2.1.1:bwear (default-bwear) @ crm.systemuser.application ---
[INFO] BWEARPackager Mojo started ...
[INFO] Updated the Manifest version 
[INFO] The OSGi verion is 1.10.0.201905011109 for Maven version of 1.10.0.201905011109
[INFO] Adding Modules to the EAR file
[INFO] Adding EAR Information to the EAR File
[INFO] Manifest updated with Version 1.10.0.201905011109
[INFO] The EAR file name for Application is C:\Users\deepat\workspace-MavenTest\crm.systemuser.application\target\crm.systemuser.application_1.10.0.ear
[INFO] Building jar: C:\Users\deepat\workspace-MavenTest\crm.systemuser.application\target\crm.systemuser.application_1.10.0.ear
[INFO] BWEARPackager Mojo finished execution
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.680 s
[INFO] Finished at: 2019-05-01T11:09:22-04:00
[INFO] Final Memory: 18M/284M
[INFO] ------------------------------------------------------------------------

**Comment by ashutoshbhide** [comment]
@deepatailor Are you running the Maven command from application project or parent project?
When you generate the POM files it generates the parent project as well.
Do try running it from that project and then let us know if it works or not?

**Comment by deepatailor** [comment]
@ashutoshbhide 
Today after seeing your comment, I tried running it from the .parent project as well and got the same result and same EAR got generated

**Comment by ashutoshbhide** [comment]
@deepatailor 
Can you add the logs after running the maven build from the parent project here.

**Comment by deepatailor** [comment]
Sure its as below:

[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building crm.systemuser.application 1.10.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ crm.systemuser.application ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\deepat\workspace-MavenTest\crm.systemuser.application\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ crm.systemuser.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ crm.systemuser.application ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\deepat\workspace-MavenTest\crm.systemuser.application\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ crm.systemuser.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ crm.systemuser.application ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\deepat\workspace-MavenTest\crm.systemuser.application\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ crm.systemuser.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- bw6-maven-plugin:2.1.1:bwtest (default-bwtest) @ crm.systemuser.application ---
[INFO] -------------------------------------------------------
[INFO] Provided TibcoHome directory is invalid. Skipping Test Phase.
[INFO] -------------------------------------------------------
[INFO] 
[INFO] --- bw6-maven-plugin:2.1.1:bwear (default-bwear) @ crm.systemuser.application ---
[INFO] BWEARPackager Mojo started ...
[INFO] Updated the Manifest version 
[INFO] The OSGi verion is 1.10.0.201905021240 for Maven version of 1.10.0.201905021240
[INFO] Adding Modules to the EAR file
[INFO] Adding EAR Information to the EAR File
[INFO] Manifest updated with Version 1.10.0.201905021240
[INFO] The EAR file name for Application is C:\Users\deepat\workspace-MavenTest\crm.systemuser.application\target\crm.systemuser.application_1.10.0.ear
[INFO] Building jar: C:\Users\deepat\workspace-MavenTest\crm.systemuser.application\target\crm.systemuser.application_1.10.0.ear
[INFO] BWEARPackager Mojo finished execution
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.097 s
[INFO] Finished at: 2019-05-02T12:40:30-04:00
[INFO] Final Memory: 21M/273M
[INFO] ------------------------------------------------------------------------

**Comment by deepatailor** [comment]
I am going away from my laptop for few mins,  I will check the thread when I get back and respond if there is any new comments.

**Comment by ashutoshbhide** [comment]
@deepatailor 

I still dont think its being run from parent project.
If you run from Parent project it will print the logs similar to following.

Probably try it from command line as well. 


[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] demo.application.parent                                            [pom]
[INFO] demo                                                          [bwmodule]
[INFO] demo.application                                                 [bwear]

**Comment by deepatailor** [comment]
@ashutoshbhide 
Now I am running it from the parent folder and getting below error for the deploy goal:

[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] crm.systemuser.application.parent
[INFO] ws.cmn.cle.framework
[INFO] ws.cmn.framework.resources
[INFO] ws.cmn.smartmapper.client
[INFO] crm.systemuser
[INFO] crm.systemuser.application
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building crm.systemuser.application.parent 1.10.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ crm.systemuser.application.parent ---
[INFO] Installing C:\Users\deepat\workspace-MavenTest\crm.systemuser.application.parent\pom.xml to C:\Users\deepat\.m2\repository\com\tibco\bw\crm.systemuser.application.parent\1.10.0-SNAPSHOT\crm.systemuser.application.parent-1.10.0-SNAPSHOT.pom
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ crm.systemuser.application.parent ---
[INFO] Installing C:\Users\deepat\workspace-MavenTest\crm.systemuser.application.parent\pom.xml to C:\Users\deepat\.m2\repository\com\tibco\bw\crm.systemuser.application.parent\1.10.0-SNAPSHOT\crm.systemuser.application.parent-1.10.0-SNAPSHOT.pom
[INFO] 
[INFO] --- maven-deploy-plugin:2.7:deploy (default-deploy) @ crm.systemuser.application.parent ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] crm.systemuser.application.parent .................. FAILURE [  0.579 s]
[INFO] ws.cmn.cle.framework ............................... SKIPPED
[INFO] ws.cmn.framework.resources ......................... SKIPPED
[INFO] ws.cmn.smartmapper.client .......................... SKIPPED
[INFO] crm.systemuser ..................................... SKIPPED
[INFO] crm.systemuser.application ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.475 s
[INFO] Finished at: 2019-05-02T13:34:18-04:00
[INFO] Final Memory: 18M/217M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project crm.systemuser.application.parent: Deployment failed: repository element was not specified in the POM inside distributionManagement element or in -DaltDeploymentRepository=id::layout::url parameter -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by ashutoshbhide** [comment]
@deepatailor 
Try the command mvn install 

To run mvn deploy you will have to setup a maven central repository ( Nexus or Artifactory) and then do the required configuration.

**Comment by deepatailor** [comment]
@ashutoshbhide 
Thank you so much. I will install/setup Artifactory and try, will update the ticket if I run into any issues after that or if it works as expected.

**Comment by deepatailor** [comment]
@ashutoshbhide 
I was able to deploy the application to the tea domain, thanks much for your help with this.

**Comment by SujataDarekar** [comment]
@deepatailor Closing the issue based on previous comment
