### ISSUE TITLE
Missing artifact com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100 and Missing artifact com.tibco.plugins:com.tibco.xml.cxf.common:jar:1.3.200

### ISSUE THREAD

**Issue by vinitamonga** [TIBCOSoftware/bw6-plugin-maven#270]
TIBCO BW CE version 2.4.
Maven Plugin version 2.1.1

Both below jar are present in location /bwce/2.4/maven/plugins/bw6-maven-plugin

![mavenJars](https://user-images.githubusercontent.com/15131957/57969094-6fd51d80-7990-11e9-802f-95de7c055e0a.PNG)

Still after generate pom.xml , getting error as 
**Missing artifact com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100 
Missing artifact com.tibco.plugins:com.tibco.xml.cxf.common:jar:1.3.200**

Need help in understanding where I am going wrong.

**Comment by SujataDarekar** [comment]
@vinitamonga Could you please whether those JAR's are present on .m2 home or not?

**Comment by SujataDarekar** [comment]
@vinitamonga Also please let us know which Apache Maven version you are using

**Comment by SonaliDasgupta** [comment]
@vinitamonga  Any updates ?
