### ISSUE TITLE
Error Installing in BW 6.5.1+ Eclipse installable unit is not found

### ISSUE THREAD

**Issue by vyada7** [TIBCOSoftware/bw6-plugin-maven#273]
C:\software\TIB_BW_Maven_Plugin_2.1.1>install

C:\software\TIB_BW_Maven_Plugin_2.1.1>java -Dtibcohomepath= -cp antpackage.jar o
rg.apache.tools.ant.launch.Launcher
Buildfile: C:\software\TIB_BW_Maven_Plugin_2.1.1\build.xml

getTibcoHome:
     [echo]
     [echo]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%
     [echo]                 Installing Plugin Code for Apache Maven and TIBCO Bu
sinessWorksÖ
     [echo]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%
     [echo]
    [input]
    [input]                %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%
    [input]
    [input]                  Input the path for Tibco Home here. Default will be
 c:\tibco
    [input]
    [input]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%
    [input]
    [input]
C:\tibco65
     [echo] BW Version 6.5

setupMacros:

vbuild.launcher.jar:

devbuild.launcher.jar:

studio-install:
     [echo]  Installing Eclipse M2E Plugin to Tibco Home
     [exec] Installation failed.
     [exec] The installable unit org.eclipse.equinox.p2.discovery.feature.featur
e.group has not been found.
     [exec] Application failed, log file location: C:\tibco65\studio\4.0\eclipse
\configuration\1558591512721.log
     [exec]
     [exec] Result: 13
     [echo] Project directory C:\software\TIB_BW_Maven_Plugin_2.1.1
     [exec] Installing bw6.maven.dependencies.feature.feature.group 1.0.0.001.
     [exec] Operation completed in 3089 ms.
     [exec] Installing org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836
.
     [exec] Installing org.eclipse.m2e.sdk.feature.feature.group 1.6.2.20151013-
0836.
     [exec] Installing org.eclipse.m2e.logback.feature.feature.group 1.6.2.20151
013-0836.
     [exec] Cannot complete the install because one or more required items could
 not be found.Installation failed.
     [exec]  Software being installed: m2e - Maven Integration for Eclipse (incl
udes Incubating components) 1.6.2.20151013-0836 (org.eclipse.m2e.feature.feature
.group 1.6.2.20151013-0836)
     [exec]  Missing requirement: m2e Marketplace 1.6.2.20151013-0836 (org.eclip
se.m2e.discovery 1.6.2.20151013-0836) requires 'bundle org.eclipse.equinox.p2.ui
.discovery 0.0.0' but it could not be found
     [exec]  Cannot satisfy dependency:
     [exec]   From: m2e - Maven Integration for Eclipse (includes Incubating com
ponents) 1.6.2.20151013-0836 (org.eclipse.m2e.feature.feature.group 1.6.2.201510
13-0836)
     [exec]   To: org.eclipse.m2e.discovery [1.6.2.20151013-0836]
     [exec] Application failed, log file location: C:\tibco65\studio\4.0\eclipse
\configuration\1558591523251.log
     [exec]
     [exec]
     [exec] Result: 13
     [echo]  UnInstalling the existing version of Plugin Code for Apache Maven a
nd TIBCO BusinessWorksÖ
     [exec] The installable unit bw6.studio.maven.feature.feature.group has not
been found.Installation failed.
     [exec]
     [exec] Application failed, log file location: C:\tibco65\studio\4.0\eclipse
\configuration\1558591528617.log
     [exec]
     [exec] Result: 13
     [echo]  Installing Studio Plugin for Plugin Code for Apache Maven and TIBCO
 BusinessWorksÖ to the Tibco Home
     [exec] Installing bw6.studio.maven.feature.feature.group 2.1.1.001.
     [exec] Installation failed.
     [exec] Cannot complete the install because one or more required items could
 not be found.
     [exec]  Software being installed: TIBCO BusinessWorksÖ Studio Feature for M
aven 2.1.1.001 (bw6.studio.maven.feature.feature.group 2.1.1.001)
     [exec]  Missing requirement: TIBCO BusinessWorksÖ Studio Plugin for Maven 2
.1.1.001 (bw6.studio.maven.plugin 2.1.1.001) requires 'bundle org.eclipse.m2e.co
re [1.3.1,2.0.0)' but it could not be found
     [exec]  Cannot satisfy dependency:
     [exec]   From: TIBCO BusinessWorksÖ Studio Feature for Maven 2.1.1.001 (bw6
.studio.maven.feature.feature.group 2.1.1.001)
     [exec]   To: bw6.studio.maven.plugin [2.1.1.001]
     [exec] Application failed, log file location: C:\tibco65\studio\4.0\eclipse
\configuration\1558591532564.log
     [exec]
     [exec] Result: 13

maven-install:
     [echo]  Installing Maven Plugin for Plugin Code for Apache Maven and TIBCO
BusinessWorksÖ to Local Maven Repository
    [unzip] Expanding: C:\software\TIB_BW_Maven_Plugin_2.1.1\config\bw6-maven-pl
ugin.zip into C:\tibco65\bw\6.5\maven\plugins\bw6-maven-plugin

winInstall:
     [exec]
     [exec] C:\tibco65\bw\6.5\maven\plugins\bw6-maven-plugin>echo Installing Mav
en Plugin to Maven Repository
     [exec] Installing Maven Plugin to Maven Repository
     [exec]
     [exec] C:\tibco65\bw\6.5\maven\plugins\bw6-maven-plugin>start cmd.exe /C mv
n install:install-file -Dfile=com.tibco.bw.palette.shared_6.1.100.003.jar -Dgrou
pId=com.tibco.plugins -DartifactId=com.tibco.bw.palette.shared -Dversion=6.1.100
 -Dpackaging=jar
     [exec]
     [exec] C:\tibco65\bw\6.5\maven\plugins\bw6-maven-plugin>start cmd.exe /C mv
n install:install-file -Dfile=com.tibco.xml.cxf.common_1.3.200.001.jar -DgroupId
=com.tibco.plugins -DartifactId=com.tibco.xml.cxf.common -Dversion=1.3.200 -Dpac
kaging=jar
     [exec]
     [exec] C:\tibco65\bw\6.5\maven\plugins\bw6-maven-plugin>start cmd.exe /C mv
n install:install-file -Dfile=bw6-maven-plugin-2.1.1.jar -DpomFile=pom.xml
     [exec]
     [exec] C:\tibco65\bw\6.5\maven\plugins\bw6-maven-plugin>start cmd.exe /C mv
n install:install-file -Dfile=fabric8/fabric8-maven-plugin-2.2.102.jar -DpomFile
=fabric8/pom.xml

linuxInstall:

maven-plugin-install:

setup:

BUILD SUCCESSFUL
Total time: 1 minute 1 second

C:\software\TIB_BW_Maven_Plugin_2.1.1>install

C:\software\TIB_BW_Maven_Plugin_2.1.1>java -Dtibcohomepath= -cp antpackage.jar o
rg.apache.tools.ant.launch.Launcher
Buildfile: C:\software\TIB_BW_Maven_Plugin_2.1.1\build.xml

getTibcoHome:
     [echo]
     [echo]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%
     [echo]                 Installing Plugin Code for Apache Maven and TIBCO Bu
sinessWorksÖ
     [echo]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%
     [echo]
    [input]
    [input]                %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%
    [input]
    [input]                  Input the path for Tibco Home here. Default will be
 c:\tibco
    [input]
    [input]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%
    [input]
    [input]
C:\tibco65
     [echo] BW Version 6.5

setupMacros:

vbuild.launcher.jar:

devbuild.launcher.jar:

studio-install:
     [echo]  Installing Eclipse M2E Plugin to Tibco Home
     [exec] The installable unit org.eclipse.equinox.p2.discovery.feature.featur
e.group has not been found.
     [exec] Application failed, log file location: C:\tibco65\studio\4.0\eclipse
\configuration\1558592484055.log
     [exec] Installation failed.
     [exec]
     [exec] Result: 13
     [echo] Project directory C:\software\TIB_BW_Maven_Plugin_2.1.1
     [exec] Installing bw6.maven.dependencies.feature.feature.group 1.0.0.001.
     [exec] Operation completed in 3339 ms.
     [exec] Installing org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836
.
     [exec] Installing org.eclipse.m2e.sdk.feature.feature.group 1.6.2.20151013-
0836.
     [exec] Installing org.eclipse.m2e.logback.feature.feature.group 1.6.2.20151
013-0836.
     [exec] Cannot complete the install because one or more required items could
 not be found.
     [exec]  Software being installed: m2e - Maven Integration for Eclipse (incl
udes Incubating components) 1.6.2.20151013-0836 (org.eclipse.m2e.feature.feature
.group 1.6.2.20151013-0836)
     [exec]  Missing requirement: m2e Marketplace 1.6.2.20151013-0836 (org.eclip
se.m2e.discovery 1.6.2.20151013-0836) requires 'package org.eclipse.equinox.inte
rnal.p2.discovery.compatibility 0.0.0' but it could not be found
     [exec]  Cannot satisfy dependency:
     [exec]   From: m2e - Maven Integration for Eclipse (includes Incubating com
ponents) 1.6.2.20151013-0836 (org.eclipse.m2e.feature.feature.group 1.6.2.201510
13-0836)
     [exec]   To: org.eclipse.m2e.discovery [1.6.2.20151013-0836]
     [exec] Application failed, log file location: C:\tibco65\studio\4.0\eclipse
\configuration\1558592500981.log
     [exec] Installation failed.
     [exec]
     [exec] Result: 13
     [echo]  UnInstalling the existing version of Plugin Code for Apache Maven a
nd TIBCO BusinessWorksÖ
     [exec] The installable unit bw6.studio.maven.feature.feature.group has not
been found.
     [exec] Application failed, log file location: C:\tibco65\studio\4.0\eclipse
\configuration\1558592507205.log
     [exec] Installation failed.
     [exec]
     [exec] Result: 13
     [echo]  Installing Studio Plugin for Plugin Code for Apache Maven and TIBCO
 BusinessWorksÖ to the Tibco Home
     [exec] Installing bw6.studio.maven.feature.feature.group 2.1.1.001.
     [exec] Installation failed.
     [exec] Cannot complete the install because one or more required items could
 not be found.
     [exec]  Software being installed: TIBCO BusinessWorksÖ Studio Feature for M
aven 2.1.1.001 (bw6.studio.maven.feature.feature.group 2.1.1.001)
     [exec]  Missing requirement: TIBCO BusinessWorksÖ Studio Plugin for Maven 2
.1.1.001 (bw6.studio.maven.plugin 2.1.1.001) requires 'bundle org.eclipse.m2e.co
re [1.3.1,2.0.0)' but it could not be found
     [exec]  Cannot satisfy dependency:
     [exec]   From: TIBCO BusinessWorksÖ Studio Feature for Maven 2.1.1.001 (bw6
.studio.maven.feature.feature.group 2.1.1.001)
     [exec]   To: bw6.studio.maven.plugin [2.1.1.001]
     [exec] Application failed, log file location: C:\tibco65\studio\4.0\eclipse
\configuration\1558592511235.log
     [exec]
     [exec] Result: 13

maven-install:
     [echo]  Installing Maven Plugin for Plugin Code for Apache Maven and TIBCO
BusinessWorksÖ to Local Maven Repository
    [unzip] Expanding: C:\software\TIB_BW_Maven_Plugin_2.1.1\config\bw6-maven-pl
ugin.zip into C:\tibco65\bw\6.5\maven\plugins\bw6-maven-plugin

winInstall:
     [exec]
     [exec] C:\tibco65\bw\6.5\maven\plugins\bw6-maven-plugin>echo Installing Mav
en Plugin to Maven Repository
     [exec] Installing Maven Plugin to Maven Repository
     [exec]
     [exec] C:\tibco65\bw\6.5\maven\plugins\bw6-maven-plugin>start cmd.exe /C mv
n install:install-file -Dfile=com.tibco.bw.palette.shared_6.1.100.003.jar -Dgrou
pId=com.tibco.plugins -DartifactId=com.tibco.bw.palette.shared -Dversion=6.1.100
 -Dpackaging=jar
     [exec]
     [exec] C:\tibco65\bw\6.5\maven\plugins\bw6-maven-plugin>start cmd.exe /C mv
n install:install-file -Dfile=com.tibco.xml.cxf.common_1.3.200.001.jar -DgroupId
=com.tibco.plugins -DartifactId=com.tibco.xml.cxf.common -Dversion=1.3.200 -Dpac
kaging=jar
     [exec]
     [exec] C:\tibco65\bw\6.5\maven\plugins\bw6-maven-plugin>start cmd.exe /C mv
n install:install-file -Dfile=bw6-maven-plugin-2.1.1.jar -DpomFile=pom.xml
     [exec]
     [exec] C:\tibco65\bw\6.5\maven\plugins\bw6-maven-plugin>start cmd.exe /C mv
n install:install-file -Dfile=fabric8/fabric8-maven-plugin-2.2.102.jar -DpomFile
=fabric8/pom.xml

linuxInstall:

maven-plugin-install:

setup:

BUILD SUCCESSFUL
Total time: 48 seconds

C:\software\TIB_BW_Maven_Plugin_2.1.1>

**Comment by ankitapandey1** [comment]
@vyada7  Please check the proxy settings , It seems the error occurs because of proxy that denies to access the internet, which is preventing the installer from retrieving packages from the Eclipse site.

**Comment by vyada7** [comment]
Hi Ankit,

While running install bat , I am setting proxy setting for HTTP and HTTPS like this on cmd. These credentials are working fine for me in explorer and eclipse.


set HTTP_PROXY=http://GROUP\XXXX:XXXX@proxy.xxx.com:8080

Did I need to do something else also.

Regards
Vikas

**Comment by ankitapandey1** [comment]
you can also add Proxy details via the Studio Windows -> Preferences -> General --> Network Connections.

**Comment by vyada7** [comment]
Already did same

**Comment by SujataDarekar** [comment]
@vyada7 If you are using proxy and can access the link(org.eclipse.m2e) with the browser the same settings need to be applied to Maven. For maven, you need to add proxy details in settings.xml if you are using a proxy

**Comment by SujataDarekar** [comment]
Closing the issue based on the above comments.
