### ISSUE TITLE
Business Studio stops responding when open a sub process in shared module

### ISSUE THREAD

**Issue by akashgugale15** [TIBCOSoftware/bw6-plugin-maven#274]
Maven Plugin version: 2.1.1

Maven version: 3.6.0

Product : TIBCO ActiveMatrix Businessworks 6

Product version: 6.5.0 HF07

Component: Maven Eclipse Plugin

**Steps to reproduce the issue:**
1. Add a shared module as dependency in pom.xml
2. Open a sub-process in shared module
3. Studio hangs (stops responding)

**Comment by akashgugale15** [comment]
Is there any update on above issue? Its been a month and the ticket is still not assigned.

**Comment by SujataDarekar** [comment]
@akashgugale15 The issue is not reproducible at our end. Could you please share the reproducible use case?

**Comment by awagle** [comment]
Please provide reproducible case and re-open.
