### ISSUE TITLE
Ability for users to provide application archives folder to upload the EAR in domain. See #264

### ISSUE THREAD

**Issue by awagle** [TIBCOSoftware/bw6-plugin-maven#276]
See #264 for detailed conversations.

**Comment by goutham-muragavel** [comment]
@sonalshingavi , Gentle Reminder: Please let me know if we have any update on this.

**Comment by sonalshingavi** [comment]
@goutham-muragavel 
I am working on it. I will let you know ones 
I have more information.

**Comment by sonalshingavi** [comment]
Hi @goutham-muragavel 

As your requirement to provide Application archive folder in the config file.
Now, You can add "externalEarLoc" with external EAR location path in the config file.
It will create an EAR file at the provided location and deploy on tea.

I am sharing the zoom recording to show you this new feature to provide the external ear location in the config file.

It will come in the next release. Please go throw recording and let me know in case you have any query.
[zoom_0.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3313640/zoom_0.zip)

**Comment by amitmohanty88** [comment]
@awagle 
Thanks for sharing the steps we have gone through the zoom recording .Currently we are using TIB_BW_Maven_Plugin_2.1.1 version in TIBBCO BW 6 Studio .This new feature is added in which version of Maven Plugin and is the new Plugin is available now ?If the New feature containing plugin is available can you please  share the download link .If the New Feature containing Maven plugin is not available now when it will be available ?

**Comment by sonalshingavi** [comment]
Hi @amitmohanty88 
Probably, This feature will add in TIB_BW_Maven_Plugin_2.3.0. We haven't finalized the date yet, to release TIB_BW_Maven_Plugin_2.3.0. I will update to you soon when will be a plugin available.

**Comment by sonalshingavi** [comment]
Closing this issue, fixed by pull request #327
