### ISSUE TITLE
Ability to generate Unit testing report in SonarQube supported Generic format

### ISSUE THREAD

**Issue by kgera-tibco** [TIBCOSoftware/bw6-plugin-maven#279]
Hi, this is regarding an enhancement request from a customer who uses SonarQube to store Unit testing coverage reports from BW.
For Unit Testing, BW generate report in HTML format which is not supported by SonarQube at the moment.
Requirement: Provide ability in BW to generate Unit Testing report in one of the formats supported by SonarQube or Generic Format allowed by SonarQube(which is XML).
Please find required XML structure and sample here: https://docs.sonarqube.org/latest/analysis/generic-test/

**Comment by awagle** [comment]
Karan I think this issue can be closed based on internal discussions.

**Comment by kgera-tibco** [comment]
Yes, thanks Aditya.
