### ISSUE TITLE
Sample BW6 project that uses maven

### ISSUE THREAD

**Issue by JaganChinthakayala** [TIBCOSoftware/bw6-plugin-maven#29]
Can someone upload a sample BW6 project that uses maven to generate EAR file. When  I run the maven build with “package” goal, it creates an EAR but the EAR file does not have the project jar and resources folder, it just has the META-INF folder.

**Comment by fanninj3** [comment]
Hi,

Ensure you are doing the package command using the .parent project, it should work fine then.

**Comment by rathd** [comment]
If i do the mvn package, from the .parent folder, then it just gives error for all the dependency packages defined in the .application module. If i do the mvn package from the .application folder, it effectively does the same issue that Jagan has mentioned.

**Comment by JaganChinthakayala** [comment]
[Test.parent.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/462201/Test.parent.zip)


Attached is my test project which uses maven. It has Test application along with Test.module and Test.parent projects. Can you please take a look at it and let me know where I am going wrong. It is a very simple project with only the greetings service.

Appreciate your help on this.

**Comment by HiteshNembhwani** [comment]
I'll take a look at this and let you know soon.

Could you confirm the BW6, Maven plugin versions?

On Thu, Sep 8, 2016 at 9:59 AM, JaganChinthakayala <notifications@github.com

**Comment by JaganChinthakayala** [comment]
Thanks!! Hitesh

Versions are BW6.3.3 and TIB_BW_Maven_Plugin_1.1.0.zip

**Comment by HiteshNembhwani** [comment]
So, I tried this with BW 6.3.3 and Maven 1.1.0 plugin. I'm able to see the
project jar file but not the resources folder which contains the diagrams
files.

The reason you don't see the resources folder is because it has a certain
dependency on GMF to generate the diagram files and hence in a headless
mode, diagram files are not generated.

[image: Inline image 1]

Same goes with the Test application which was provided earlier by
JaganChinthakayala. See below:

[image: Inline image 2]

**Comment by JaganChinthakayala** [comment]
Can you please the upload the project that used to generate the ear. Also please provide a screenshot of the maven run configuration. I want to make that I am not missing any settings like Goals, profiles, user setting etc...

**Comment by HiteshNembhwani** [comment]
Here you go: (rename the attachment to .zip extension)

[image: Inline image 1]

**Comment by JaganChinthakayala** [comment]
I cannot find the attachment. Can you pls attach again.

**Comment by HiteshNembhwani** [comment]
[Archive.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/462454/Archive.zip)

Hoping this one makes it through :)

**Comment by JaganChinthakayala** [comment]
Yeah.. I got the zip file. But I cannot import these project to my workspace for some reason.
So I check the POM files and they are no different and also since my test project is able to generate the ear, with the project jar, at your side. I think this could be an environment issues. 

The machine on which I am running the BW6 does not have access to internet. Also no proxy allowed.
When I installed Maven, I had to dowdload equinox-SDK-LunaSR2 and specify that in the build file.

But now, I suspect that since it is not able to connect to internet, it is generated ear properly. I am just toying with different possibilities. Can you please provide your insights.

**Comment by HiteshNembhwani** [comment]
[MavenProjects.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/462821/MavenProjects.zip)

Could you please try importing the projects from this attachment? I exported them from BusinessStudio, this should work when you import.

**Comment by awagle** [comment]
Closing this issue based on @HiteshNembhwani 's comment. Please re-open if you still see the issue.
