### ISSUE TITLE
Transitive dependencies are not getting included in the BW Module Jar files.

### ISSUE THREAD

**Issue by ashutoshbhide** [TIBCOSoftware/bw6-plugin-maven#3]
While running the package command on bwmodule the transitive dependencies are not getting resolved and added to the JAR.

**Comment by ashutoshbhide** [comment]
Added the code to fetch transitive dependency and add it to the bwmodule JAR.

**Comment by artificialintellect** [comment]
Will this change scheduled to be released in the near future?

**Comment by artificialintellect** [comment]
I see - its already been released.  I didn't realize the file in the installer was folder had the most recent release since the version number hadn't changed.
