### ISSUE TITLE
Business Works 6.3 - maven plugin for Windows

### ISSUE THREAD

**Issue by vairav05** [TIBCOSoftware/bw6-plugin-maven#31]
I have installed the Maven plugin 1.1.0 from https://github.com/TIBCOSoftware/bw6-plugin-maven/. When I'm trying to generate POM file in Business Works 6.3.3 I'm getting errors in that POM file and I cannot enter the deployment details. These are the errors

->Project build error: Unresolveable build extension: Plugin com.tibco.plugins:bw6-maven-plugin:1.1.0 or one of its dependencies could not be resolved: Failed to collect dependencies at com.tibco.plugins:bw6-maven-plugin:jar:1.1.0 -> org.apache.maven:maven-plugin-api:jar:3.3.3

->Project build error: Unknown packaging: bwear

->Error resolving version for plugin 'org.apache.maven.plugins:maven-site-plugin' from the repositories [local (D:\Users\vaira.v\.m2\repository), central (https://repo.maven.apache.org/maven2)]: Plugin not found in any plugin repository

**Comment by HiteshNembhwani** [comment]
Vairav,

Is this the first time you're running Maven plugin on this machine? Just
trying to see if it could be an environmental (proxy) issue.

Please follow the below links and see if it helps:

http://stackoverflow.com/questions/18590506/maven-build-failing-on-dependencies

http://stackoverflow.com/questions/11280142/maven-unresolvable-build-extension

-Hitesh

**Comment by vairav05** [comment]
I tried that but still I'm getting the same error. This is my POM file

<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.tibco.bw</groupId>
    <artifactId>sample.application.parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <relativePath>..\sample.application.parent</relativePath>
  </parent>
  <artifactId>sample.application</artifactId>
  <packaging>ear</packaging>
  <build>
    <plugins>
      <plugin>
        <groupId>com.tibco.plugins</groupId>
        <artifactId>bw6-maven-plugin</artifactId>
        <version>1.1.0</version>
        <extensions>true</extensions>
        <configuration />
      </plugin>
    </plugins>
  </build>
</project>

**Comment by uksaumya** [comment]
I'm also facing the same issue.Checked the settings.xml file and jar files are available in the local repository path.

**Comment by vairav05** [comment]
I have resolved this issue. For this you have go to the POM file location of the Maven plugin in command line and then you have to run"install -X" . This command will download all the dependencies for maven plugin. Example - My maven plugin location is D:\TIBCO_BW6.3.3\bw\6.3\maven\plugins\bw6-maven-plugin . go to this location in command line and execute install -X command.

**Comment by awagle** [comment]
Closing based on @vairav05's comment.
