### ISSUE TITLE
Need to do versioning of TIBCO BW ear

### ISSUE THREAD

**Issue by vyada7** [TIBCOSoftware/bw6-plugin-maven#318]
Hi,

We are using tibco Bw 6.5.1 and want to do versioning of ear on higher environment for tracking purpose.

We are using maven to build and deploy. What would be the steps to do ear versioning on each build?

Maven Plugin version:

Maven version:

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version:

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1.
2.
3.

**Additional environment details if any:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by SujataDarekar** [comment]
@vyada7 We have default format to generate EAR version which is the combination of artifact_id and major and minor bundle version. We don't provide any steps do ear versioning

**Comment by vyada7** [comment]
Hi Sujata,

I need to change in ear version. So , where I should do the change in artifact id and major and minor version.

Regards
Vikas

**Comment by SujataDarekar** [comment]
@vyada7 As I said currently the default versioning is done through code if you have a requirement to do customized versioning for  BW ear then we will consider this as an enhancement where the user will provide the EAR name while running the "package" goal.

**Comment by SujataDarekar** [comment]
@
Please create the new enhancement if there is any new requirement related to EAR versioning. Closing the issue as per the above comment.
