### ISSUE TITLE
Building the project

### ISSUE THREAD

**Issue by teivah** [TIBCOSoftware/bw6-plugin-maven#32]
Hello guys,

I am very interested in working on the project (at least for the moment trying to get an overview of how things are working together).
In particular I am looking for a solution to manage dependencies (one application referencing a module or * shared module, based on a package repository).

First of all I would like to know please how to build the project. I mean starting from the /Source and being able to produce a TIB_BW_Maven_Plugin_x.zip file.
Is there any kind of procedure to achieve this? Do I need to package things manually?

Thanks for your help and the great job btw.

**Comment by Tantino** [comment]
Hello,
I would like to work on this project.
@teivah comment " _please how to build the project. I mean starting from the /Source and being able to produce a TIB_BW_Maven_Plugin_x.zip file._" Please , Could you respond?

Thanks and regards.

**Comment by awagle** [comment]
@teivah @Tantino we will document how to add build the project this week. Thank you for your interest.

**Comment by teivah** [comment]
Can't wait.. :)

Thanks

**Comment by RajibBiswasTibco** [comment]
The build process for creating bw6-plugin-maven installer is documented at: https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/Build
