### ISSUE TITLE
Support for BW Cloud and creating of manifest

### ISSUE THREAD

**Issue by mmussett** [TIBCOSoftware/bw6-plugin-maven#328]
Maven Plugin version: 2.2.0
Maven version: 3.6.0

Please can we include support for deployment to cloud so that both EAR and manifest are generated.

**Comment by SujataDarekar** [comment]
@mmussett  This feature will be available in Maven 2.8.1. Please refer https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/TCI-Deployment-via-Maven-Plugin for more details
