### ISSUE TITLE
Packager is including Maven dependencies with test scope

### ISSUE THREAD

**Issue by kkane-tibco** [TIBCOSoftware/bw6-plugin-maven#329]
For Java shared modules it is common to include some test cases (under src/test/java) for unit tests to be executed by JUnit. 

When running Maven builds, this requires the appropriate JUnit library to be added as a dependency in the pom file - typically with scope "test", so that it is not packaged into a deployable archive.

With the BW Maven plug-in we've noticed that this dependency is still getting packaged into the jar file for the shared module. Looking at the source code, I can see that dependencies with "provided" and "system" scopes are ignored but not ones with a "test" scope.

The BW Maven plug-in should also ignore dependencies with "test" scope during the module packaging phase.

**Comment by SujataDarekar** [comment]
The issue is fixed and will be available with Maven Plugin 2.3.1
