### ISSUE TITLE
Unable to bind BWCE monitoring service with BWCE application via Maven (Fabric8) on K8S

### ISSUE THREAD

**Issue by HiteshNembhwani** [TIBCOSoftware/bw6-plugin-maven#330]
I'm using BWCE 2.4.4 version with Maven 2.2.0 plugin version. Goal is to deploy the application on K8S (GKE) over Docker containers using Maven and Jenkins. In the deployment.yml file, I've specified the environment variable in various different formats but after running the goal fabric8:resource fabric8:apply, the environment variables are getting reset and hence the BWCE Monitoring environment variable is not getting reflected. All of this works well if it I do the deployments manually.  @SonaliDasgupta this is the same issue as we were discussing last week.

**Comment by SonaliDasgupta** [comment]
@HiteshNembhwani  Could you please confirm once whether the following format in the YAML file works , to successfully register with the BWCE Monitor ? 
env:
        - name: BW_APP_MONITORING_CONFIG
          value: '{"url": "http://146.148.58.182"}'

Please edit the YAML file with the following content before running the maven goal "fabric8:apply"

**Comment by awagle** [comment]
@HiteshNembhwani please re-open if this is till an issue.
