### ISSUE TITLE
Ability to package without unused resources

### ISSUE THREAD

**Issue by HiteshNembhwani** [TIBCOSoftware/bw6-plugin-maven#331]
Could we please provide an ability to package an EAR (archive) without unused resources via Maven similar to the feature available via BusinessStudio in BWCE 2.4.4 version - https://docs.tibco.com/pub/bwce/2.4.4/doc/html/GUID-339673A0-C101-44B9-8B77-41DD3316AB64.html

**Comment by awagle** [comment]
Cannot be done since the unused resources functionality relies on Studio and cannot be ported to Maven.
