### ISSUE TITLE
Enhancement - Support Kubernetes Deployment controller

### ISSUE THREAD

**Issue by rishikeshpalve** [TIBCOSoftware/bw6-plugin-maven#332]
Currently the maven plug-in allows creation of Kubernetes ReplicationController. Kubernetes also supports Deployments Controller and 'Deployments' is a recommended way for creating and managing pods in Kubernetes environments. The plug-in should support creating 'Deployments'.

**Comment by sarundes-tibco** [comment]
<img width="566" alt="image" src="https://github.com/user-attachments/assets/b987dfa3-9f22-48d2-9e88-717c091e4798">

**Comment by sarundes-tibco** [comment]
Currently we support this feature.. Attached screen shot for the reference. 
Hence closing this ticket.
