### ISSUE TITLE
Bw 6 maven plugin Query

### ISSUE THREAD

**Issue by goutham-muragavel** [TIBCOSoftware/bw6-plugin-maven#333]
Hi @sonalshingavi  ,
Please let us know the property that can be used in config file for deploying the application without starting it.

Thanks and Regards,
Goutham

**Comment by SujataDarekar** [comment]
@goutham-muragavel  please refer wiki https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/EAR-Deployment

**Comment by goutham-muragavel** [comment]
@SujataDarekar , it does not provide me the information on which property to use in the config file for not starting the application after deployment.

**Comment by sonalshingavi** [comment]
Hi @goutham-muragavel 
Currently, We do not support any property in the config file for deploying the application without starting it.

**Comment by goutham-muragavel** [comment]
Thanks @sonalshingavi  for the reply.
