### ISSUE TITLE
maven package (or a new goal) to autogenerate process diagrams

### ISSUE THREAD

**Issue by j-ajendra** [TIBCOSoftware/bw6-plugin-maven#334]
**Enhancement**

Environment - CI/CD server

Ears built using maven does not include process diagrams unless explicitly generated from studio before code check-in.

Is it possible to have a maven goal do the task of generating diagrams? 

Any other recommended approach to do this?

**Comment by awagle** [comment]
We have discussed this in other issues as well. The building of process diagrams needs eclipse. Bwdesign utility can be used instead of Studio if required but this functionality cannot be ported to Maven.
