### ISSUE TITLE
Failed to instantiate type com.tibco.bw.extensions.logback.BWCustomConverter

### ISSUE THREAD

**Issue by cmocanu1** [TIBCOSoftware/bw6-plugin-maven#337]
I have a working project with tests and is running ok with version 2.2.0 but after upgrade to 2.3.0 is not working anymore and is complaining about some logger classes.

`java.lang.ClassNotFoundException: com.tibco.bw.extensions.logback.BWAppFileAppenderFilter cannot be found by com.tibco.tpcl.logback_1.1.100.001`

If I switch back on version 2.3.0 (only by changing the version in pom.xml of the project) then is working again (the test are run).

In attachment can find the output for running with 2.2.0 and 2.3.0.

[mvn-2.2.0.log](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3436377/mvn-2.2.0.log)
[mvn-2.3.0.log](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3436378/mvn-2.3.0.log)

**Comment by SujataDarekar** [comment]
@cmocanu1 Can you please share the reproducible use case?

**Comment by cmocanu1** [comment]
If I share the project ... I don't know how useful will be because requires an AS/400 (IBM i plugin) in order to run.

I had an working project, build, package and testes in maven 2.2.0 plugin and I just upgraded the maven plugin to 2.3.0 and updated the version in pom.xml and obtained the error.

**Comment by SujataDarekar** [comment]
@cmocanu1  Based on the logs I have fixed the issue and the fix will be available with Maven Installer 2.3.1

**Comment by cmocanu1** [comment]
Thank you! I'll be glad to test it and confirm it!

**Comment by SujataDarekar** [comment]
@cmocanu1 I have committed the fix. Please follow the below steps to test the issue
1. Pull out source code "bw6-plugin-maven/tree/master/Source/bw6-maven-plugin" in the studio and just run the package goal on it. It will create the bw6-maven-plugin-2.3.0.jar in target folder.
2. Download the TIB_BW_Maven_Plugin_2.3.0 installer and unzip it. 
3. Unzip\TIB_BW_Maven_Plugin_2.3.0\config\bw6-maven-plugin.zip.
4.Replace file 'bw6-maven-plugin-2.3.0.jar' from \Source\bw6-maven-plugin\target(generated in step1) to \TIB_BW_Maven_Plugin_2.3.0\config\bw6-maven-plugin and generate the zip file
5. Replace old bw6-maven-plugin.zip to the new bw6-maven-plugin.zip file created in step4.
6. run the install.bat / install.sh command from the root folder.

Please let me know if you face any problem in the above steps.

**Comment by cmocanu1** [comment]
I follow the steps you described and seams that this fix is ok. Problem is solved. You can find the logs attached.
[mvn-2.3.1.log](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3447204/mvn-2.3.1.log)
