### ISSUE TITLE
Unit Tests with BWCE 2.4.5 and Maven 2.3.0 version

### ISSUE THREAD

**Issue by HiteshNembhwani** [TIBCOSoftware/bw6-plugin-maven#340]
Tried to run a simple unit test against this version with Maven Plugin 2.3.0, the output was reporting that it found the 1 unit test but there was no success or failure result (see below). 
[20190729-SimpleApp.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3445465/20190729-SimpleApp.zip)

I have also attached my project. Please advise.

This works well with BWCE 2.4.4 version. 

[INFO] 
Tests for simpleapp.module.SubProcess
Tests run : 1    Success : 0 	Failure : 0	Errors : 0

Results 
Success : 0    Failure : 0    Errors : 0
[INFO] ------------------------------------------------------------------------

**Comment by HiteshNembhwani** [comment]
@SujataDarekar - fyi, I'll share the mock file also soon.

**Comment by HiteshNembhwani** [comment]
[Uploading InvokeRESTAPIMockOutput.xml.zip…]()

@SujataDarekar mock file also attached but the issue is even without the mocking. (meaning remove the mocking from the activity and just have unit test scenario) thanks.

**Comment by SujataDarekar** [comment]
@HiteshNembhwani  Can you create the process property with the default value of gold input and map that property to the gold input and run the project?

**Comment by jchongtibco** [comment]
It does report success/failure if I use the gold input from a process property. However, when it is comparing the input json string with the gold input (from process property) with the same json string, it is reporting as failure.

Tests for simpleapp.module.SubProcess
Tests run : 1    Success : 0 	Failure : 1	Errors : 0
Results 
Success : 0    Failure : 1    Errors : 0

**Comment by SujataDarekar** [comment]
@jchongtibco As discussed on slack I have tested the attached project by providing the gold input value through process property and it worked fine. Please check the project shared on slack.

**Comment by SujataDarekar** [comment]
This can be achieved through Enhancement AMBW-36632 related to assert complete activity output and will be provided with BW6.6.0 and feature maven release.
 Also providing the output through process property can be considered as an alternative to provide XML/JSON value to the gold input string which is working fine
