### ISSUE TITLE
Unit Test Successful Even Though Mapper Mock File Has Bad Value

### ISSUE THREAD

**Issue by jchongtibco** [TIBCOSoftware/bw6-plugin-maven#341]
[20190730-BWCE244UnitTest.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3448440/20190730-BWCE244UnitTest.zip)
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Maven Plugin version:
2.3.0
Maven version:
3.3.3
Product : TIBCO Businessworks Container edition

Product version: 2.4.4

Component: Maven build plugin

**Steps to reproduce the issue:**
1. Import the attached project. 
2. Run the project.

**Additional environment details if any:**

**Describe the results you received:**
The unit test reports as success even though the first mapper mock output file provides a BAD value.

**Describe the results you expected:**
The unit test should be failed.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by SujataDarekar** [comment]
@jchongtibco Can you please update the issue title as  Unit test is successful even though mapper mock output file has a BAD value or something like that. Also please share the mock output which has BAD value

**Comment by SujataDarekar** [comment]
@jchongtibco  Please share the mock output which has BAD value
