### ISSUE TITLE
The Maven imported shared module shows an error when trying to open a subprocess within it

### ISSUE THREAD

**Issue by tanu1127** [TIBCOSoftware/bw6-plugin-maven#344]
Maven Plugin version: v 2.1.1
Maven version: 3.5.4

Product : Either of TIBCO ActiveMatrix Businessworks 6

Product version: 6.5.0 HF06

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1. Import the shared module through reference method (preferences -> target platform -> edit -> add ->  BW Shared Module and click 'next' -> Enter the location of the directory that contains one or more binary shared modules and click 'finish' )
2. Open the module (in which you want to use the shared binary module) and go to Module Descriptors and open dependencies and add the shared module as a dependency. Save the project.
3. Call the subprocess in the shared  module from the application module. Try to open the subprocess and you'll see an error "failed to create part’s controls".

![image](https://user-images.githubusercontent.com/42173671/62218792-6f53fc80-b3ad-11e9-9733-f123b61b6b86.png)

The shared module jar:

[Context-1.0.9.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3452235/Context-1.0.9.zip)

**Additional information you deem important (e.g. issue happens only occasionally):**

Faced another issue which related to this: 
https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/274

**Comment by tanu1127** [comment]
Can someone please pick this issue up?

**Comment by awagle** [comment]
Can you try this with the latest Studio and BW Maven plugin versions and re-open if the issue is reproducible.
