### ISSUE TITLE
Question: Java dependency not in classpath EAR

### ISSUE THREAD

**Issue by pbelien** [TIBCOSoftware/bw6-plugin-maven#345]
Maven Plugin version: 2.2.0

Maven version: 3.5,4

Product : Either of TIBCO ActiveMatrix Businessworks 6.5.0 HF7

Product version: 6.5.0 HF7

Component: Maven build plugin

**Steps to reproduce the issue:**
1. Open Maven BW6 project
2. Add dependency in module pom
<dependency>
    <groupId>org.jasypt</groupId>
    <artifactId>jasypt</artifactId>
    <version>1.9.2</version>
</dependency>
3. Generate EAR or Run mvn package

**Describe the results you received:**
Dependency gets resolved just fine in eclipse and runs locally, but when generating the ear the jar does not get added into the package, therefore failing tp start after I deploy it on TEA.
It shows Maven Dependencies in the Java Build Path with the expected jar, but after build it doesn't only seems to package the shared modules, not the java dependency. Instead I have to manually add the lib etc like the Tibco Documentation suggests

**Describe the results you expected:**
Expected the jasypt jar to be present in the ear after simply adding it as a dependency. I expected this to be encountered before by someone but I couldn't find any issue here.
**Question I have is really only if this is indeed unexpected behaviour or not. If it is unexpected I'll go invest some time looking in to it more, otherwise I know I wont have to right now**

**Comment by SujataDarekar** [comment]
@pbelien When you add any dependency in module POM with "compile" scope,  it should get added in the EAR. I tried to add dependency "jasypt " mentioned by you and I am able to generate  EAR successfully with that dependency.

**Comment by pbelien** [comment]
Thnx, played around with it some more and I indeed see the dependency now being packaged.
