### ISSUE TITLE
How to generate substvar file without "deploy ear to bw administrator"

### ISSUE THREAD

**Issue by anithareddycog** [TIBCOSoftware/bw6-plugin-maven#346]
Maven Plugin version:

Maven version:

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version:

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1.
2.
3.

**Additional environment details if any:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by awagle** [comment]
Please provide some description. The question is not self explanatory.
