### ISSUE TITLE
Not able to import BW Shared Module jar into Workspace using add dependency

### ISSUE THREAD

**Issue by R-Lamberson** [TIBCOSoftware/bw6-plugin-maven#349]
Maven Plugin version: 2.3.0
Maven version: 3.6.0

Product : TIBCO Businessworks Container edition 2.4.3

Product version:

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1. Create shared component in BW and publish to maven repository.  Install it into the local .m2 repo
2. In the application pom.xml, add dependency to the appropriate group id, artifact and version
3. -- nothing is added to the BWCE workspace 

Studio / Plugin provide no information as to why it did not get added to the workspace.  

How do you troubleshoot this issue or what are possible causes for the import into the workspace to fail?

Is there a manual mechanism for importing a shared module reference into the workspace as work around??

**Comment by SujataDarekar** [comment]
@R-Lamberson when we add dependency through module POM it gets pulled into studio workspace. We don't need to do any manual mechanism. Can you please make sure that you have added a dependency in module POM rather than application POM?

**Comment by R-Lamberson** [comment]
Sujata, yes sorry mistake in my note above, I added it to the module POM.  Through some trial and error I found that I seem to need to have the version attribute on the POM in the shared module include -SNAPSHOT.  After changing this the component was able to be added to the workspace as described.  Any details as to the requirement on the version tags?

**Comment by krishsaha2020** [comment]
I am facing the same issue can you please suggest how to resolve it. I have added the dependency to module pom. The shared module jar file gets downloaded from NEXUS and also is available under Maven Dependencies. But the shared module does not gets downloaded into the studio.

**Comment by R-Lamberson** [comment]
@krishsaha2020 I found that I had to be very explicit in the BW Shared Module to set the Packaged version to the following pattern {major}.{minor}.{instance}-SNAPSHOT (eg 1.0.0-SNAPSHOT).  Also in some instances I had to use the Studio option for Maven - Force Update to get the local maven repo

**Comment by krishsaha2020** [comment]
The import of the Shared Module Project  (reference) works once we import the actual shared module project into studio and build it once again. Then the project referring it is able to import it. So there is some problem in the Tibco Business Studio which is not allowing the retrieval of the shared module project into Studio after its downloaded to m2 from the Nexus Jar.

**Comment by krishsaha2020** [comment]
@SujataDarekar , Any idea if there is any option to directly get the Shared Module Project directly into Studio from NEXUS ?

**Comment by vkrejcirik** [comment]
@SujataDarekar, we are facing same issue. Our shared modules get downloaded from Nexus to the local Mvn repository, but they don't appear in Business Studio. We tried Maven -> Update Project, but it didn't help. Any ideas? 

Also it is happening to some of our developers. For the others it is working relatively fine. We are on BWCE 2.5.0 and Plugin version 2.7.0

Thank you

**Comment by sarundes-tibco** [comment]
We are supporting this feature ..hence marking this ticket as closed
