### ISSUE TITLE
BW6 6.5.1 + Maven plugin 2.2 : The Java class  is not found in the classpath

### ISSUE THREAD

**Issue by Pittonio** [TIBCOSoftware/bw6-plugin-maven#352]
Hello,

in BW6 I have a BW project converted in Java, and I have a class in it that I use in a JavaInvoke palette.

When I build the package with maven, everything is og, but if I try to run a UnitTest the running fails because the classpath doesn't contain the class used in the JavaInvoke Palette.

The error in the console is:

_The Java class [my.test.org.MyTestClass] is not found in the classpath._

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->
Maven Plugin version: 2.2

Maven version: 3.6.1

Product : TIBCO ActiveMatrix Businessworks 6

Product version: 6.5.1

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1. Run maven for UnitTesting (mvn clean initialize site package)
2. 
3.

**Additional environment details if any:**

**Describe the results you received:**
Error in the console: The Java class [my.test.org.MyTestClass] is not found in the classpath.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by SujataDarekar** [comment]
@Pittonio Could you please attach the reproducible case?

**Comment by Pittonio** [comment]
@SujataDarekar please find attached my project.
[MyTest.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3500206/MyTest.zip)

**Comment by SujataDarekar** [comment]
@Pittonio The issue has been fixed and will be available in next maven release 2.4.0 and with BW 6..6.0.
 The changes are from BW and maven side as well. Closing the issue
