### ISSUE TITLE
Maven Plugin 2.3.0 fails to install on BWCE 2.4.5

### ISSUE THREAD

**Issue by crmadrig** [TIBCOSoftware/bw6-plugin-maven#353]
Maven Plugin version: 2.3.0

Maven version: 3.3.3

Product : TIBCO Businessworks Container edition

Product version: 2.4.5

Component: Maven build plugin

**Steps to reproduce the issue:**
1. Install a fresh copy of BWCE 2.4.5
2. Try to install BW Maven plugin 2.3.0 in the TIBCO Home that BWCE 2.4.5 was installed. It will hang for a bit, fail and continue on to the next steps

**Additional environment details if any:**
Java version: 1.8.0
OS 10.14.3

**Describe the results you received:**
Maven plugin not installed

**Describe the results you expected:**
Maven plugin installed.

**Additional information you deem important (e.g. issue happens only occasionally):**
Attaching logs. 
[1565380584466.log](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3488094/1565380584466.log)

Note: looking at the logs it seems like a timeout issue, i'm on the TIBCO corporate network.

EDIT: I was successfully able to get this installed when on a different network. So it seems to be an issue when you're on the TIBCO network...

**Comment by SujataDarekar** [comment]
@crmadrig This issue is not with BW Maven Plugin but as you mentioned it's a network issue which can not be fixed at plugin level
