### ISSUE TITLE
Custom Libs project - .ear built in Jenkins/Maven does not work

### ISSUE THREAD

**Issue by eangelelli** [TIBCOSoftware/bw6-plugin-maven#354]
Maven Plugin 2.1.1
Business Works 6.5.0 HF7

We have a project that is using custom libs for jms and db connectivity.
The .ear built in studio works - the .ear created from the same project (uploaded on Git) using Jenkins/Maven pipeline is not.
From the appnode log we can see the app remaining in 'impaired state' and no start.

Below the application 'includes' and the application 'pom'. Libs are not present in the pom, do we have to add? If yes please provide pointers.

![image](https://user-images.githubusercontent.com/20589018/62810419-c5622780-bab2-11e9-9e54-2c20613227b7.png)

![image](https://user-images.githubusercontent.com/20589018/62810430-cdba6280-bab2-11e9-91d9-b2ce73ffac27.png)

Thanks

  Emiliano

**Comment by HiteshNembhwani** [comment]
@eangelelli could you please upload the projects along with the POM files? thanks!

**Comment by eangelelli** [comment]
Thanks Hitesh,
code uploaded in:
https://drive.google.com/drive/folders/1lSuQquCp61loKP1wY3nlzaPM9kge9OWW?usp=sharing

**Comment by SujataDarekar** [comment]
@HiteshNembhwani @eangelelli Currently we don't provide support to include Custom plugin while packaging the application. This will be considered as an enhancement. 
For now, the following workaround may be useful to include the custom plugin with lib JAR.
1. Add the POM in Custom plugin with Manifest import bundles as a dependency with "provided" scope.
2. Install the custom plugin using the "install" goal.
3. Add the dependency of Custom plugin in the application POM and run the "package" goal. 

This will include the custom plugin with lib folder dependency in EAR likewise studio EAR.

Please check the attached project for more details:
https://drive.google.com/file/d/1vhFVAIKEvOOQyZmfzCO8xQK1qtATsHVa/view?usp=sharing

**Comment by SujataDarekar** [comment]
@eangelelli As communicated working with the provided workaround hence closing the issue. Enhancement is created to provide support to include the Custom plugin while packaging the application #357.
