### ISSUE TITLE
Version Number to Allow Alpha-numeric Characters

### ISSUE THREAD

**Issue by trentsch** [TIBCOSoftware/bw6-plugin-maven#358]
In POM.xml can we use alpha numeric  values in place of APP_VERSION ?

Currently only numeric values are supported.

<version>${APP_VERSION}.${BUILD_NUMBER}</version>

Purpose : we can make use of the branch name as APP_VERSION which will give better understanding  of which code deployed.

Ex : "release.r2019-05-29.002"

**Comment by awagle** [comment]
This cannot be supported due to semantic version support required from OSGI https://semver.org/
