### ISSUE TITLE
Application status is not reflected in TEA

### ISSUE THREAD

**Issue by moalyousef1** [TIBCOSoftware/bw6-plugin-maven#363]
After successful Jenkins and MAVEN deployment, BW6.5.0 application status is not reflecting to TEA.  Please see attachment for more details
 @[BW6.5.0-status.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3596093/BW6.5.0-status.txt)

**Comment by asatsi** [comment]
Hello @moalyousef1 can you help how you managed to get Jenkins Maven plugin get working? Sorry this is not related to your issue but I am having trouble setting it up.

**Comment by HiteshNembhwani** [comment]
@asatsi check this link and see if it helps - https://community.tibco.com/wiki/automate-tibco-businessworkstm-container-edition-deployments-k8s-maven-and-jenkins-cicd and if it doesn't, please elaborate the issue you're facing.

**Comment by SujataDarekar** [comment]
@moalyousef1 Can you please elaborate the issue like when you deploy the application through maven on tea, Doesn't show the "Started" status?

**Comment by awagle** [comment]
Please re-open with requested details.
