### ISSUE TITLE
Maven fails in jenkins - Failure to find com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100

### ISSUE THREAD

**Issue by asatsi** [TIBCOSoftware/bw6-plugin-maven#367]
BW version: 6.4.2
Maven Plugin version: 1.3.1, 2.3.1, 2.3.2 
OS: Windows
Jenkins: 2.176.3
Apache Maven: 3.6.2

Facing error while executing maven job in Jenkins:
```
[ERROR] Failed to execute goal on project Opr_Inv_Condo_Pub: Could not resolve dependencies for project com.tibco.bw:Opr_Inv_Condo_Pub:bwmodule:1.0.0-SNAPSHOT: Failure to find com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project Opr_Inv_Condo_Pub: Could not resolve dependencies for project com.tibco.bw:Opr_Inv_Condo_Pub:bwmodule:1.0.0-SNAPSHOT: Failure to find com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
```

If I do the same job on command line it works well.
CMDLINE:
 `mvn -f Opr_Inv_Condo_Pub.application.parent/pom.xml clean initialize package`

**Comment by HiteshNembhwani** [comment]
@asatsi please see if you've followed the steps from this post: https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/76

**Comment by asatsi** [comment]
@HiteshNembhwani thanks for the reply. In my case the EAR file could be created successfully on command line. However it fails when I run the same thing in Jenkins with the above error. I can do a screen sharing if you would like to see.

**Comment by asatsi** [comment]
I see the jar and pom files as 
![image](https://user-images.githubusercontent.com/10648621/65182719-8a470280-da27-11e9-9042-172354ac2a83.png)

**Comment by asatsi** [comment]
Looks like I was able to figure out the issue.

**Comment by SujataDarekar** [comment]
@asatsi Based on the above comment closing the issue

**Comment by asatsi** [comment]
For posterity purpose the issue was resolved by copying a working maven repository onto Jenkins configured maven repository.
