### ISSUE TITLE
Maven Plugin Installation Exceptions

### ISSUE THREAD

**Issue by replybin** [TIBCOSoftware/bw6-plugin-maven#37]
Hi, 

I am trying to install the Maven Plugin by executing the install.bat file available in TIB_BW_Maven_Plugin_1.1.0.zip file and **it is** **failing to download the plugin correctly**.

**Can you help me resolve this issue ?**

M2_HOME & PATH Variables are set correctly.

Attached the log file under (C:\Program Files\tibco\studio\4.0\eclipse\configuration\1475097710659.log)
## Here is the output after executing the install.bat ::::::

C:\tmp\BW6Build\bw6-plugin-maven-master\Installer\TIB_BW_Maven_Plugin_1.1.0>java -cp antpackage.jar org.apache.tools.ant.launch.Launcher
Buildfile: C:\tmp\BW6Build\bw6-plugin-maven-master\Installer\TIB_BW_Maven_Plugin_1.1.0\build.xml

getTibcoHome:
     [echo]
     [echo]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     [echo]                 Installing Plugin Code for Apache Maven and TIBCO BusinessWorksÖ
     [echo]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     [echo]
    [input]
    [input]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [input]
    [input]                 Input the path for Tibco Home here. Default will be C:/Program Files/tibco
    [input]
    [input]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [input]

```
 [echo] BW6
```

setupMacros:

vbuild.launcher.jar:

devbuild.launcher.jar:

studio-install:
     [echo]  Installing Eclipse M2E Plugin to Tibco Home
     [exec] log4j:WARN No appenders could be found for logger (org.apache.http.impl.conn.SingleClientConnManager).
     [exec] log4j:WARN Please initialize the log4j system properly.
     [exec] The installable unit org.eclipse.equinox.p2.discovery.feature.feature.group has not been found.Installation failed.
     [exec]
     [exec] **Application failed, log file location: C:\Program Files\tibco\studio\4.0\eclipse\configuration\1475097710659.log**
     [exec]
     [exec] **Result: 13**
     [exec] Installing bw6.maven.dependencies.feature.feature.group 1.0.0.001.
     [exec] Operation completed in 2172 ms.
     [exec] Installing org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836.
     [exec] Installing org.eclipse.m2e.sdk.feature.feature.group 1.6.2.20151013-0836.
     [exec] Installing org.eclipse.m2e.logback.feature.feature.group 1.6.2.20151013-0836.
     [exec] Cannot complete the install because one or more required items could not be found.
     [exec] Installation failed.
     [exec]  Software being installed: m2e - Maven Integration for Eclipse (includes Incubating components) 1.6.2.20151013-0836 (org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836)
     [exec]  Missing requirement: m2e Marketplace 1.6.2.20151013-0836 (org.eclipse.m2e.discovery 1.6.2.20151013-0836) requires 'bundle org.eclipse.equinox.p2.ui.discovery 0.0.0' but it could not be found
     [exec]  Cannot satisfy dependency:
     [exec]   From: m2e - Maven Integration for Eclipse (includes Incubating components) 1.6.2.20151013-0836 (org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836)
     [exec]   To: org.eclipse.m2e.discovery [1.6.2.20151013-0836]
     [exec] Application failed, log file location: **C:\Program Files\tibco\studio\4.0\eclipse\configuration\1475098014470.log**
     [exec]
     [exec] Result: 13
     [echo]  UnInstalling the existing version of Plugin Code for Apache Maven and TIBCO BusinessWorksÖ
     [exec] The installable unit bw6.studio.maven.feature.feature.group has not been found.
     [exec] Installation failed.
     [exec] Application failed, log file location: **C:\Program Files\tibco\studio\4.0\eclipse\configuration\1475098018906.log**
     [exec]
     [exec] Result: 13
     [echo]  Installing Studio Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorksÖ to the Tibco Home
     [exec] Installing bw6.studio.maven.feature.feature.group 1.1.0.201605061954.
     [exec] Cannot complete the install because one or more required items could not be found.Installation failed.
     [exec]  Software being installed: TIBCO BusinessWorksÖ Studio Feature for Maven 1.1.0.201605061954 (bw6.studio.maven.feature.feature.group 1.1.0.201605061954)
     [exec]  Missing requirement: TIBCO BusinessWorksÖ Studio Plugin for Maven 1.1.0.201605061954 (bw6.studio.maven.plugin 1.1.0.201605061954) requires 'bundle org.eclipse.m2e.core [1.3.1,2.0.0)' but it could not be found
     [exec]  Cannot satisfy dependency:
     [exec]   From: TIBCO BusinessWorksÖ Studio Feature for Maven 1.1.0.201605061954 (bw6.studio.maven.feature.feature.group 1.1.0.201605061954)
     [exec]   To: bw6.studio.maven.plugin [1.1.0.201605061954]
     [exec] Application failed, log file location: C:\Program Files\tibco\studio\4.0\eclipse\configuration\1475098021842.log
     [exec]
     [exec]
     [exec] Result: 13

maven-install:
     [echo]  Installing Maven Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorksÖ to Local Maven Repository
    [unzip] Expanding: C:\tmp\BW6Build\bw6-plugin-maven-master\Installer\TIB_BW_Maven_Plugin_1.1.0\config\bw6-maven-plugin.zip into C:\Program Files\tibco\bw\6.3\maven\plugins\bw6-maven-plugin

winInstall:
     [exec]
     [exec] C:\Program Files\tibco\bw\6.3\maven\plugins\bw6-maven-plugin>echo Installing Maven Plugin to Maven Repository
     [exec] Installing Maven Plugin to Maven Repository
     [exec]
     [exec] C:\Program Files\tibco\bw\6.3\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=com.tibco.bw.palette.shared_6.1.100.003.jar -DgroupId=com.tibco.plugins -DartifactId=com.tibco.bw.palette.shared -Dversion=6.1.100 -Dpackaging=jar
     [exec]
     [exec] C:\Program Files\tibco\bw\6.3\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=com.tibco.xml.cxf.common_1.3.200.001.jar -DgroupId=com.tibco.plugins -DartifactId=com.tibco.xml.cxf.common -Dversion=1.3.200 -Dpackaging=jar
     [exec]
     [exec] C:\Program Files\tibco\bw\6.3\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=bw6-maven-plugin-1.1.0.jar -DpomFile=pom.xml
     [exec]
     [exec] C:\Program Files\tibco\bw\6.3\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=fabric8/fabric8-maven-plugin-2.2.102.jar -DpomFile=fabric8/pom.xml

linuxInstall:

maven-plugin-install:

setup:

BUILD SUCCESSFUL
Total time: 5 minutes 38 second

[1475097710659.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/499325/1475097710659.zip)

**Comment by awagle** [comment]
Are you trying to upgrade from an earlier version of maven plugin?

**Comment by replybin** [comment]
Thanks for the response. 

We are installing it for first time and we also tried to include proxy parameters by updating build.xml with setProxy parameters. but no luck.

**Comment by rahulkamdar** [comment]
Did you provide the full location for your "TIBCO-HOME" (which is the
folder at which you have installed TIBCO ActiveMatrix BusinessWorks 6)? The
log messages earlier possibly indicate the response was "BW6" for the
TIBCO-HOME.

**Comment by tmichaudtibx** [comment]
It appears this error occurs because there is a corporate proxy that requires authentication to access the internet, and it is preventing the installer from retrieving packages from the Eclipse site (per the build.xml script).  

Proxy details were added via the Studio GUI - "General --> Network Connections" but the following error was generated after re-running the install:

"org.eclipse.equinox.security.storage.StorageException: Unable to locate secure storage module"

**Comment by tmichaudtibx** [comment]
More details:

!MESSAGE Unable to locate secure storage module (org.eclipse.equinox.security.windowspasswordprovider64bit).
!STACK 0
org.eclipse.equinox.security.storage.StorageException: Unable to locate secure storage module (org.eclipse.equinox.security.windowspasswordprovider64bit).
	at org.eclipse.equinox.internal.security.storage.PasswordProviderSelector.findStorageModule(PasswordProviderSelector.java:190)

**Comment by rahulkamdar** [comment]
Closing as per the comment from @tmichaudtibx. Re-open if that's not the issue.
