### ISSUE TITLE
Support to Generate POM for application with TIBCO Cloud as deployment option

### ISSUE THREAD

**Issue by kgera-tibco** [TIBCOSoftware/bw6-plugin-maven#374]
Currently, applications with TIBCO Cloud as deployment option cannot be deployed via Maven. Please can we include support for respective deployment option so POM can be generated in same way as docker/AppSpace.

**Comment by SujataDarekar** [comment]
@kgera-tibco This feature will be available in Maven 2.8.1. Please refer https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/TCI-Deployment-via-Maven-Plugin for more details
