### ISSUE TITLE
BW 6.5.1 Maven installation successful, but the application is not showing Generate POM file option

### ISSUE THREAD

**Issue by prashanthme88** [TIBCOSoftware/bw6-plugin-maven#375]
studio-install:
     [echo]  Installing Eclipse M2E Plugin to Tibco Home
     [exec] log4j:WARN No appenders could be found for logger (org.apache.http.impl.conn.SingleClientConnManager).
     [exec] log4j:WARN Please initialize the log4j system properly.
     [exec] Installation failed.
     [exec] Unable to load repositories.
     [exec] Application failed, log file location: D:\tibco_upgrade2\studio\4.0\eclipse\configuration\1570704860482.log
     [exec]
     [exec] Result: 13
     [exec] Installing bw6.maven.dependencies.feature.feature.group 1.0.0.001.
     [exec] Operation completed in 13320 ms.
     [exec] Installing org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836.
     [exec] Installing org.eclipse.m2e.sdk.feature.feature.group 1.6.2.20151013-0836.
     [exec] Installing org.eclipse.m2e.logback.feature.feature.group 1.6.2.20151013-0836.
     [exec] Cannot complete the install because one or more required items could not be found.
     [exec]  Software being installed: m2e - Maven Integration for Eclipse (includes Incubating components) 1.6.2.20151013-0836 (org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836)
     [exec] Installation failed.
     [exec]  Missing requirement: m2e Marketplace 1.6.2.20151013-0836 (org.eclipse.m2e.discovery 1.6.2.20151013-0836) requires 'bundle org.eclipse.equinox.p2.ui.discovery 0.0.0' but it could not be found
     [exec]  Cannot satisfy dependency:
     [exec]   From: m2e - Maven Integration for Eclipse (includes Incubating components) 1.6.2.20151013-0836 (org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836)
     [exec]   To: org.eclipse.m2e.discovery [1.6.2.20151013-0836]
     [exec] Application failed, log file location: D:\tibco_upgrade2\studio\4.0\eclipse\configuration\1570704880736.log
     [exec]
     [exec] Result: 13
     [echo]  UnInstalling the existing version of Plugin Code for Apache Maven and TIBCO BusinessWorksÖ
     [exec] Installation failed.The installable unit bw6.studio.maven.feature.feature.group has not been found.
     [exec]
     [exec] Application failed, log file location: D:\tibco_upgrade2\studio\4.0\eclipse\configuration\1570704887437.log
     [exec]
     [exec] Result: 13
     [echo]  Installing Studio Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorksÖ to the Tibco Home
     [exec] Installing bw6.studio.maven.feature.feature.group 2.3.1.001.
     [exec] Installation failed.Cannot complete the install because one or more required items could not be found.
     [exec]
     [exec]  Software being installed: TIBCO BusinessWorksÖ Studio Feature for Maven 2.3.1.001 (bw6.studio.maven.feature.feature.group 2.3.1.001)
     [exec]  Missing requirement: TIBCO BusinessWorksÖ Studio Plugin for Maven 2.3.1.001 (bw6.studio.maven.plugin 2.3.1.001) requires 'bundle org.eclipse.m2e.core [1.3.1,2.0.0)' but it could not be found
     [exec]  Cannot satisfy dependency:
     [exec]   From: TIBCO BusinessWorksÖ Studio Feature for Maven 2.3.1.001 (bw6.studio.maven.feature.feature.group 2.3.1.001)
     [exec]   To: bw6.studio.maven.plugin [2.3.1.001]
     [exec] Application failed, log file location: D:\tibco_upgrade2\studio\4.0\eclipse\configuration\1570704889471.log
     [exec]
     [exec] Result: 13

maven-install:
     [echo]  Installing Maven Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorksÖ to Local Maven Repository
    [mkdir] Created dir: D:\tibco_upgrade2\bw\6.5\maven\plugins
    [unzip] Expanding: C:\Users\pmachalakaranji\Downloads\TIB_BW_Maven_Plugin_2.3.1\config\bw6-maven-plugin.zip into D:\tibco_upgrade2\bw\6.5\maven\plugins\bw6-maven-plugin

winInstall:
     [exec]
     [exec] D:\tibco_upgrade2\bw\6.5\maven\plugins\bw6-maven-plugin>echo Installing Maven Plugin to Maven Repository
     [exec] Installing Maven Plugin to Maven Repository
     [exec]
     [exec] D:\tibco_upgrade2\bw\6.5\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=com.tibco.bw.palette.shared_6.1.100.003.jar -DgroupId=com.tibco.plugins -DartifactId=com.tibco.bw.palette.shared -Dversion=6.1.100 -Dpackaging=jar
     [exec]
     [exec] D:\tibco_upgrade2\bw\6.5\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=com.tibco.xml.cxf.common_1.3.200.001.jar -DgroupId=com.tibco.plugins -DartifactId=com.tibco.xml.cxf.common -Dversion=1.3.200 -Dpackaging=jar
     [exec]
     [exec] D:\tibco_upgrade2\bw\6.5\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=bw6-maven-plugin-2.3.1.jar -DpomFile=pom.xml
     [exec]
     [exec] D:\tibco_upgrade2\bw\6.5\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=fabric8/fabric8-maven-plugin-2.2.102.jar -DpomFile=fabric8/pom.xml

linuxInstall:

maven-plugin-install:

setup:

BUILD SUCCESSFUL
Total time: 46 seconds

**Comment by SujataDarekar** [comment]
@prashanthme88 In Studio Can you check the Maven Version is showing or not in the following way:
 Help->Installation Details-> Installed Software->  TIBCO BusinessWorks™ Studio Feature for Maven

**Comment by prashanthme88** [comment]
This is installed in the installed software: BW6 Maven Dependencies Feature. This is required to install prerquisite JARs to the BW Studio before installing the m2e plugin.

**Comment by prashanthme88** [comment]
Issue resolved, the issue was with installation, the install.bat was trying to connect to internet to download the file for installation, later added the proxy in the Studio under Window --> Preferences -->General --> Network Connection.

**Comment by kirankondapally** [comment]
> Issue resolved, the issue was with installation, the install.bat was trying to connect to internet to download the file for installation, later added the proxy in the Studio under Window --> Preferences -->General --> Network Connection.

HI Prashant , could you help me how to added that proxy in the network connection.iam also facing same issue here

**Comment by prashanthme88** [comment]
In the preference update the proxy from ur company. Check with ur network admin for proxy settings


Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
