### ISSUE TITLE
Unit test was not able to run on BW 6.5.1 HF2 [FileNotFoundException: bwtestreport.xml]

### ISSUE THREAD

**Issue by Hohenheim-of-Light** [TIBCOSoftware/bw6-plugin-maven#377]
Maven Plugin version: 2.3.1

Maven version: 3.6.2

Product : TIBCO ActiveMatrix Businessworks 6

Product version: 6.5.1 HF 2

Component: Maven Eclipse Plugin or Maven build plugin

Steps to reproduce the issue:

Install BW 6.5.1 HF2
Install Maven Plugin
Create a simple project with unit test (attached) and run with Maven goal of test. (clean initialize site  package )

Additional environment details if any:
Windows 10

The results:
The run is in error. Attached console log.
the Target folder is created + folder (site , css ) + some jif and pnj file+bwtest.html

[INFO] Generating "bwtest" report --- bw6-maven-plugin:2.3.1:bwreport
javax.xml.bind.UnmarshalException

with linked exception:
[java.io.FileNotFoundException: D:\workspace\testRestADN.module\target\bwtest\bwtestreport.xml (Le chemin d’accès spécifié est introuvable)]

The results i'm expecting:
Run completes and reports success or failure.

[errorTestBuild.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3778828/errorTestBuild.txt)

![targetFolder](https://user-images.githubusercontent.com/56733622/67681980-ad51c400-f98e-11e9-960c-2d2df292b4cc.PNG)

Additional information:

I produced the issue in 2 different environment :(The second using maven 3.3.9)

Best Regards

**Comment by SujataDarekar** [comment]
@msanchet Can you check if this case is reproducible at our end with BW 6.5.1 HF02?

**Comment by msanchet** [comment]
@Hohenheim-of-Light 
I have tried with my environment.
Unit Testing project is working fine at my end (BW 6.5.1 HF2  and Maven plugin 2.3.1)
Could you please attach the project with you are trying it out?

**Comment by SujataDarekar** [comment]
@Hohenheim-of-Light We don't see the issue with Maven plugin or unit testing testing framework. The issue is not reproducible at our end as well.

**Comment by ihabbishara** [comment]
The issue still there.
I saw in Gitmemory.com you have copy/pasted the question there!
Why is it failing to find/generate the bwreport.xml file?

**Comment by ihabbishara** [comment]
@msanchet do you have a solution already?, i know its a year ago
