### ISSUE TITLE
Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.3.0:bwmodule

### ISSUE THREAD

**Issue by AKandoi** [TIBCOSoftware/bw6-plugin-maven#378]
Trying to run mvn clean package and facing this issue. 
Background is using TIBCO BWCE 2.4.3 version. BWCE plugin bw6-maven-plugin:2.3.0 is installed.
Maveniged the project in TIBCO stiudio using 'Generate POM' option. Added all dependencies and
after that I hit this issue. 

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 49.376 s
[INFO] Finished at: 2019-11-07T15:52:33-05:00
[INFO] Final Memory: 22M/109M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.3.0:bwmodule (default-bwmodule) on project com.tibco.custom.jms.provider: Execution default-bwmodule of goal com.tibco.plugins:bw6-maven-plugin:2.3.0:bwmodule failed. NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :com.tibco.custom.jms.provider

Any guidance/support is highly appreciated.

[BUILD FAILURE.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3821707/BUILD.FAILURE.txt)

**Comment by AKandoi** [comment]
what is suggested Maven Plugin Version for TIBCO BWCE 2.4.3 ?

**Comment by SujataDarekar** [comment]
@AKandoi 
Are you running "package" goal on custom plugin i.e com.tibco.custom.jms.provider? As per logs, I can see that you are running "package" goal on custom plugin. Could you please let me know the reason of running the "package" goal on custom plugin?
Also, Currently we don't provide support to include Custom plugin while packaging the application.we have enhancement created for the same.
For now, the following workaround may be useful to include the custom plugin with lib JAR.
1.Add the POM in Custom plugin with Manifest import bundles as a dependency with "provided" scope.
2. Install the custom plugin using the "install" goal.
3. Add the dependency of Custom plugin in the application POM and run the "package" goal.

**Comment by AKandoi** [comment]
Thank you for prompt response. I will work on the same and revert. Yes, we are using custom plugin.

**Comment by AKandoi** [comment]
1.Add the POM in Custom plugin with Manifest import bundles as a dependency with "provided" scope.
Modified the POM.XML attached pom with name (com.tibco.jms.custom.provider.pom)

2. Install the custom plugin using the "install" goal.

ran mvn clean install for above pom and hit below issue. Detailed logs in issue.txt

[INFO] Adding Maven Dependencies to the Plugin JAR file
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  42.882 s
[INFO] Finished at: 2019-11-08T15:53:08-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.3.0:bwmodule (default-bwmodule) on project com.tibco.custom.jms.provider: Execution default-bwmodule of goal com.tibco.plugins:bw6-maven-plugin:2.3.0:bwmodule failed.: NullPointerException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException



3. Add the dependency of Custom plugin in the application POM and run the "package" goal.


Sharing parent pom BulkOrder.application.parent.pom also.

Could you please assist on the same.

Thanks,
Amit K

[issue.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3826228/issue.txt)

**Comment by SujataDarekar** [comment]
@AKandoi  I have checked you com.tibco.jms.custom.provider.pom file and I have following observations/pointers:
1. In POM I can see the "com.tibco.custom.jms.provider" dependency is added. There is no need to add "com.tibco.custom.jms.provider" dependency in custom JMS provider plugin.I am not sure why you have added it
 2. Also for other two dependencies you need to install those JAR in your repository and then you need to add it in POM file. You can use below command to install your dependencies
mvn install:install-file -Dfile=<path-to-file> -DgroupId=<group-id> -DartifactId=<artifact-id> -Dversion=<version> -Dpackaging=<packaging>

example:
mvn install:install-file -Dfile=C:\TIBCO_INSTALLER\BW6\BW6.6.0V39\bw\6.6\system\shared\com.tibco.bw.sharedresource.jms.runtime_6.5.200.025.jar -DgroupId=com.tibco.bw.sr.jms.runtime -DartifactId=com.tibco.bw.sharedresource.jms.runtime -Dversion=6.5.200.025 -Dpackaging=jar

**Comment by AKandoi** [comment]
Thank you SujataDarekar! I will work on the same and revert.

**Comment by AKandoi** [comment]
Appreciate your response and support!
I have installed all 3 jars as suggested and added two of them as dependencies. Removed "com.tibco.custom.jms.provider" as dependency. Some progress in BUILD. However hit "Failed to create BW EAR Archive : NullPointerException". Attaching the full log file(Logs11Nov.txt) for reference

***************
[ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:1.3.1:bwear (default-bwear) on project BulkOrder.application: Failed to create BW EAR Archive : NullPointerException -> [Help 1]
****************

I tried with bw6-maven-plugin versions 1.3.1 and 1.2.2 for that particular POM.xml but same issue. 

below are bw6-maven-plugin versions used for respective POM.xml

[INFO] BulkOrder.application.parent ....................... SUCCESS [  0.108 s] 
[INFO] com.tibco.custom.jms.provider ...................... SUCCESS [  2.396 s] --------> bw6-maven-plugin 1.2.2
[INFO] FSCCustomFunction .................................. SUCCESS [  0.302 s] --------> bw6-maven-plugin 1.2.2
[INFO] PerformDBCRUDOperations ............................ SUCCESS [  0.808 s] --------> bw6-maven-plugin 2.3.0
[INFO] BulkOrder .......................................... SUCCESS [  0.172 s] --------> bw6-maven-plugin 1.2.2
[INFO] BulkOrder.application .............................. FAILURE [  0.625 s] --------> bw6-maven-plugin 1.3.1

Next question would be, what needs to be done to package .bwd with Maven builds.

Could you pls have a look ang guide further.

~Amit
[Logs11Nov.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3833306/Logs11Nov.txt)

**Comment by SujataDarekar** [comment]
@AKandoi Please share you POM file from BulkOrder.application . Also please check your all dependencies JAR are present on corresponding repository(m2 or remote).

**Comment by AKandoi** [comment]
attached the pom.xml. Pls have a look.
Yes we have whatever dependency defined in the respective pom of the package. If any dependency missing shouldn't it throw 'missing artifact'.

**Comment by AKandoi** [comment]
thanks we are able to generate EAR after adding some runtime dependencies to lib of that package and using BW-Maven-Plugin 2.1.1.

I have gone through the other threads where how to add resource folder with .bwd files? But still not able to follow.
Would you be able to guide me how to add those resource folder and .bwd files in EAR generated by Maven.

**Comment by SujataDarekar** [comment]
@AKandoi Please refer https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/Steps-to-add-Process-Diagram-in-EAR to add bwd files in EAR.

**Comment by SujataDarekar** [comment]
@AKandoi Closing the issue based on the above comments. We have enhancement #357 to include custom plugin in EAR
