### ISSUE TITLE
Maven Libraries (jar) import path schema-location wrong when doing coercion

### ISSUE THREAD

**Issue by marchelh** [TIBCOSoftware/bw6-plugin-maven#384]
Hi there,

When adding a coercion on a any element in a process, the schema-location is wrongly formated: <xsl:import-schema namespace="http://www.example.org/NewXMLSchema" schema-location="/Schemas/NewXMLSchema.xsd%3Ffile://home/tibco/.m2/repository/com/tibco/bw/TestModule/1.0.0-SNAPSHOT/TestModule-1.0.0-SNAPSHOT.jar"/>
where it should be:
<xsl:import-schema namespace="http://www.example.org/NewXMLSchema" schema-location="file://home/tibco/.m2/repository/com/tibco/bw/TestModule/1.0.0-SNAPSHOT/TestModule-1.0.0-SNAPSHOT.jar%3F/Schemas/NewXMLSchema.xsd"/>
The jar path and schema file should be in the correct order.

Version of the plugin is 2.3.1 
Version of BW is 6.5.1 HF002
[project(1).zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3845195/project.1.zip)

To reproduce this issue:
You have to create a project with a shared module, make it a maven project add a xml schema file and install this with mvn clean install in your repository.

After that you create a project with a TIBCO Application add a schema with a any element and add this to a sub process input.
Add the sharedmodule to your pom file as include, this will load the jar file into your project.
Then map the input if that subprocess with a coercion on the element with the schema from the sharedmodule. Now the corecion schema import is generated wronly. If you exit the mapping/activity you cant even see the mapping anymor, because it can not load the schema files.

I have attached the projects where this issue is demonstrated.

Kind regards,
Marcel.

**Comment by SujataDarekar** [comment]
@marchelh  It looks like the issue with schema location. At BW side we need to handle the schema having location from the JAR file for the coercion. Jira AMBW-37803 has been created for the same

**Comment by marchelh** [comment]
@Sujata, thanks for the update. I already suspected that, and I will receive updates on the BW Jira item from TIBCO support.
