### ISSUE TITLE
Question: Using BW Maven Plugin 2.4.0 After 1.3.1

### ISSUE THREAD

**Issue by jchongtibco** [TIBCOSoftware/bw6-plugin-maven#385]
We have a BWCE project with POM files generated using the bw6 maven plugin 1.3.1.
If the user were to use this same project (with the generated POM from 1.3.1) in a system with Maven Plugin 2.4.0 only, does he have to change anything in the old generated POM files?

Maven Plugin version: 2.4.0
Maven version: 3.6.1
Product : TIBCO Businessworks Container Edition
Product version: 2.4.5
Component: Maven build plugin

**Comment by SujataDarekar** [comment]
@jchongtibco Regenerate the POM with Maven Plugin 2.4.0
