### ISSUE TITLE
TIBCO BW Maven plugin 2.3.0 externalEarLoc property not working as expected

### ISSUE THREAD

**Issue by amitmohanty88** [TIBCOSoftware/bw6-plugin-maven#386]
Hi Team,

The BW Maven plugin 2.3.0 is not working as expected .we gave deployment configuration file like below for our unix machine

deployToAdmin=true
profile=QA.substvar
domain=QAESB
appSpace=AS_Retail_Store_Stock_BA_01
redeploy=true
httpPort=8079
hostname=FRHIPGQAESB01.emea.loreal.intra
appNode=AN_Retail_Store_Stock_BA_01
agentPort=8079
agentHost=FRHIPGQAESB01
externalEarLoc=/data/master/tibco/bw/6.4/domains/QAESB/archives/RETAIL

Still ear is getting created in root folder its not going to externalEarLoc Folder locatio

Location which we are putting in externalEarLoc in the same machine

 

Please help us what should be correct value to be put on externalEarLoc so that ear will go to RETAIL Folder.

All attachements are added in attached Word Document
[externalEarLoc_issue.docx](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3869518/externalEarLoc_issue.docx)

Thanks & Regards,
Amit Mohanty

**Comment by SujataDarekar** [comment]
@amitmohanty88 looks like you have provided relative path to "externalEarLoc". Please provide the absolute path and then try.

**Comment by amitmohanty88** [comment]
@SujataDarekar ,

Thanks for your Time .But we tried by giving externalEarLoc=RETAIL 

It didnot work .Ear stlll went to Root folder

We tried previously with below properties it didnot work

deployToAdmin=true
profile=QA.substvar
domain=QAESB
appSpace=AS_Retail_Store_Stock_BA_01
redeploy=true
httpPort=8079
hostname=FRHIPGQAESB01.emea.loreal.intra
appNode=AN_Retail_Store_Stock_BA_01
agentPort=8079
agentHost=FRHIPGQAESB01
externalEarLoc=RETAIL

kindly  let me know what value should i pass in externalEarLoc .

**Comment by SujataDarekar** [comment]
Absolute file path means the complete file path like C:\data\master\tibco\bw\6.4\domains\QAESB\archives\RETAIL for windows or home/data/master/tibco/bw/6.4/domains/QAESB/archives/RETAIL for linux. Also Can you please let me know that the path you have mentioned for externalEarLoc is present on the same machine from where you are running the "deploy" goal?

**Comment by amitmohanty88** [comment]
@SujataDarekar 

Neither 

externalEarLoc=RETAIL

Nor 
externalEarLoc=/data/master/tibco/bw/6.4/domains/QAESB/archives/RETAIL

worked .

none of these 2 path  worked.Both cases ear is going to root folder .

Path is already present in the machine attached screenshot also 

we are deploying with goal deploy 

Location.docx contains screenshot of the location on the machine
[Location.docx](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3873798/Location.docx)

**Comment by sonalshingavi** [comment]
Hi @amitmohanty88 

Can you please go through the attached zoom file and tried once.
Please let me know in case if you still have the same issue.
[zoom_0.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3874210/zoom_0.zip)

**Comment by amitmohanty88** [comment]
Hi @sonalshingavi ,

I have gone through the zoom_0.zip .



Kindly Refer issue.Docx for issue Screenshots


I just now redeployed to verify this issue 

You can see highlighted ear in (Issue.docx)went to root folder

externalEarLoc=/data/master/tibco/bw/6.4/domains/QAESB/archives/RETAIL given in properties file as per below

deployToAdmin=true
profile=QA.substvar
domain=QAESB
appSpace=AS_Retail_Store_Stock_BA_01
redeploy=true
httpPort=8079
hostname=FRHIPGQAESB01.emea.loreal.intra
appNode=AN_Retail_Store_Stock_BA_01
agentPort=8079
agentHost=FRHIPGQAESB01
externalEarLoc=/data/master/tibco/bw/6.4/domains/QAESB/archives/RETAIL

But when we see on the  unix machine the ear time stamp says latest ear is not loaded .Old ear is still there in unix machine same given location time 31/10/2019  7:51:50.


latest ear timestamp you can see from TEA and its on root folder its 2019/11/21 19:41:20.

You can see on TEA RETAIL folder is not loaded with latest ear 

[Issue.docx](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3876278/Issue.docx)

Please let me know if you need any webex from my side i can share or please let me know if can we have a zoom meeting

I am available weekdays post 2.30 PM IST.


Thanks and Regards,
Amit Mohanty

**Comment by sonalshingavi** [comment]
Hi @amitmohanty88 
Can you please share the logs.
Thanks.

**Comment by amitmohanty88** [comment]
Hi @sonalshingavi ,

Attached is the 
[bwappnode1723386629411459009.log](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3892351/bwappnode1723386629411459009.log)
[Jenkins_Logs.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3892352/Jenkins_Logs.txt)

BW logs and jenkins Logs

**Comment by sarundes-tibco** [comment]
@amitmohanty88 I have gone through the logs. looks like its yours local machine issue.
