### ISSUE TITLE
Missing artifact com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100

### ISSUE THREAD

**Issue by transferobject** [TIBCOSoftware/bw6-plugin-maven#387]
All, i have already searched this issue and all of the thread didn't mentioned the resolution. My problem is on Windows 10 using TIBCO Business Studio for BusinessWorks (TM) 6.5.1

Maven Plugin version: 2.3.1

Maven version: apache-maven-3.5.3

Product : Either of TIBCO ActiveMatrix Businessworks 6 

Product version: 6.5.1 HF 2

Component: Maven Eclipse Plugin

Please note that, i have already followed these steps

Installation:
a. Goto https://github.com/TIBCOSoftware/bw6-plugin-maven/releases
b. Download TIB_BW_Maven_Plugin_x.y.z.zip
c. Unzip the file in a folder on local drive.
d. Open the Terminal and run install.bat ( for Windows based OS ) )
e. The Installer will ask for TibcoHome location. Provide the TibcoHome to the Script. e.g. C:\tibcobw6\bw\6.5

This will install the Maven Plugin to the Tibco Home.

Steps for TIBCO ActiveMatrix BusinessWorks

Running the Maven Build from Studio.
a. Open the Studio.
b. Right-Click on the Application project.
c. The Context Menu will show the option "Generate POM for Application".
d. Clicking it will launch the POM Generation UI.
e. Enter the Parent POM details here and Click Finish.
f. The Project will be converted to Maven (Eclipse Project) nature. Note the workspace will index after generating POM files for the first time and may take some time. You can continue with the steps below by allowing this indexing to run in the background.
g. Open Run/Debug Configurations. Create a new Maven Build.
h. Under the "Base directory" choose add variable for Workspace location. The variable name is ${workspace_loc}.
i. In the Goal enter the Goal to be executed. The goal can be any standard Maven goal like package, install, deploy etc.
j. Select the goal as "package" for creating the EAR file. This will create the EAR file in the target folder under the Application project - 'Refresh' your project using the right-click menu if this folder is not visible.
k. Select the goal as "install" for creating the EAR file and installing it to local Maven Repository.

**Comment by SujataDarekar** [comment]
@transferobject You have provided wrong tibco home path "C:\tibcobw6\bw\6.5". Please provide the path till root folder only "C:\tibcobw6"

**Comment by transferobject** [comment]
Thank you for response.

I did the following steps>

1) removed repository folder from C:\Users\1111111\.m2
2) removed maven folder from C:\tibcobw6\bw\6.5
3)Installed plugin (attached output). It installed at this location C:\tibcobw6\bw\6.5\maven. is that correct? (attached screenshots)
4) I checked this C:\Users\1111111\.m2 and it empty. should it be empty?
4) then i followed all the steps in "Running the Maven Build from Studio". Again, tibco business studio shows the same error"Missing artifact om.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100"





![7](https://user-images.githubusercontent.com/26683529/69637744-4542dc00-1027-11ea-9084-d56e84547371.JPG)

![8](https://user-images.githubusercontent.com/26683529/69637753-4a079000-1027-11ea-82f2-3c737ea47e41.JPG)


![9](https://user-images.githubusercontent.com/26683529/69637763-4e33ad80-1027-11ea-97a0-3aea6e3c5518.JPG)


![10](https://user-images.githubusercontent.com/26683529/69637772-525fcb00-1027-11ea-9a06-6dbec7171f0e.JPG)


[InstallPlugin.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3892044/InstallPlugin.txt)

**Comment by SujataDarekar** [comment]
@transferobject  .m2 repository should not be empty. When you install BW maven plugin, it installs the shared plugin at m2 home. Please make sure you are checking the correct m2 home

**Comment by transferobject** [comment]
i am checking the correct m2 home

i have apache-maven at this location

C:\Users\111111\apache-maven-3.5.3\conf

setting.xml file has the following which is pointing to this location

<localRepository>C:\Users\111111\apache-maven-3.5.3\repo</localRepository>

I noticed that BW maven plugin install here

C:\Users\111111\apache-maven-3.5.3\repo\com\tibco\plugins

11/29/2019  10:05 AM    <DIR>          .
11/29/2019  10:05 AM    <DIR>          ..
11/29/2019  10:04 AM    <DIR>          bw6-maven-plugin
11/29/2019  10:05 AM    <DIR>          com.tibco.bw.palette.shared

can you let me know where your apache-maven-3.5.3 setting.xml file  point to this variable

<localRepository>/path/to/local/repo</localRepository>

**Comment by SujataDarekar** [comment]
@transferobject As mentioned, The maven plugin get installed at location "C:\Users\111111\apache-maven-3.5.3\repo" because in the settings.xml you have mentioned the local repository path as apache-maven path which is incorrect.  So please change the value of  <localRepository> in settings.xml and install the bw maven plugin. The correct value should be <localRepository>${user.home}/.m2/repository</localRepository>
