### ISSUE TITLE
Question - Compatibility with BW 6.5 hotfix 8

### ISSUE THREAD

**Issue by deepatailor** [TIBCOSoftware/bw6-plugin-maven#389]
We are using BW 6.5 hotfix 8, which version of the MAven plugin should I be using for the same?

I installed Maven plugin V2.4.0, but it does not seem to work as the EAR is not getting generated properly for the BW application using the same.

Please let me know ASAP.

**Comment by SujataDarekar** [comment]
@deepatailor  Please use the Maven Plugin 2.3.1

**Comment by deepatailor** [comment]
I have already installed lugon version 2.3.1 but getting same issue with it as well.

**Comment by SujataDarekar** [comment]
@deepatailor Can you explain issue?

**Comment by deepatailor** [comment]
Hi Sujata,

I uninstalled maven plugin 2.4.0 and installed 2.3.1, after that when I am trying to build the Ear, the size of the EAR is still much less compared to the size when I build it manually.

When I try to deploy the ear built using the plugin, I get errors ( mainly bcos the built EAR does not seem to be correct)

Is it possible for us to do a zoom session to look into this issue ? I am in EST timezone in USA.

**Comment by SujataDarekar** [comment]
@deepatailor Can you please share the EAR generated using maven plugin and EAR generated using studio. Let me check the difference . After that may be we can have a call

**Comment by deepatailor** [comment]
Hi Sujata,

I have attached both files in the zip here.

Ear with v1.21.0 is created manually and v1.27.0 is created using maven plugin.

[crm.merge.application.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3948461/crm.merge.application.zip)

**Comment by SujataDarekar** [comment]
@deepatailor Thanks for sharing the JAR files.  I have checked both JAR files and I see only one difference is that the EAR generated using Studio has resources folder which has diagrams. If you want to include that resources folder while generating EAR through maven please follow the wiki page https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/Steps-to-add-Process-Diagram-in-EAR
