### ISSUE TITLE
Openshift support

### ISSUE THREAD

**Issue by fcenedes** [TIBCOSoftware/bw6-plugin-maven#39]
Hi gents,

could we migrate fabric8 to version3, and add support for openshift as well, along with kubernetes.

regards,
Flo

**Comment by roagarwal** [comment]
We will migrate fabric8 plugin library to version3 in our next release. Let me know your urgency and we can plan accordingly.

**Comment by fcenedes** [comment]
Hi Ronak,

it depends on your timeline for the next release, if less than 2 months, this will be OK.

Regards,
Flo

**Comment by fcenedes** [comment]
Any update on this ?

**Comment by vijaynalawade** [comment]
Due to limited resources, We dont have any upgrade plans for Q1.

**Comment by rahulkamdar** [comment]
On our statement of direction @fcenedes. Will keep this thread updated.

**Comment by SonaliDasgupta** [comment]
Support for Openshift has been added in version 2.0.0 of BW6 Maven Plugin, with Fabric8 Maven Plugin upgraded to version 3.5.41.

**Comment by fcenedes** [comment]
Finally ! :two_hearts:
