### ISSUE TITLE
Warning on activity IDs in businessworks 6.5.1 with git and maven plugin

### ISSUE THREAD

**Issue by giovannibrescia** [TIBCOSoftware/bw6-plugin-maven#390]
Dear Support,

We have a problem with all our BW6 application importing shared modules.
When we import them into the workspace we have warnings in all the activities of the shared modules concerning recovery or recreation of activity Ids.
The applications were previously mavenized.
The suggested "quick fix" resolves the issue but when I have to re-import the project again I still have the same warnings. Also it tracks updates in all the activities, so when I have to commit changes to Git I have to commit the whole project.

Did you ever come across a similar issue?

Here the version of all the components:

Businessworks 6.5.1 HF2
Apache Maven 3.6.2
TIBCO BusinessWorks™ Studio Feature for Maven 2.3.1.001
Eclipse Git plugin 4.4.1 (recommended in documentation)

In attachment a BW project example
[Project.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3933194/Project.zip)

Thank you
Regards
Giovanni

**Comment by MartHustwick** [comment]
I'm experiencing this exact same issue, even when you fix them and check the code into your repo Maven seems to re-generate the issue.

It's also a pain as the Debugger doesn't function correctly, I imagine it requires the activity IDs to function. This can be fixed, as you've mentioned, with the 'quick fix' but it seems to be a 50/50 chance wherever it is going to actually work.

**Comment by awagle** [comment]
This is not a maven plugin issue and some fixes were done in BW for this issue. Please raise an SR if you are still facing the issue and the quick fix isn't working.
