### ISSUE TITLE
Error while running BWunit Test feature in BW6.4.2

### ISSUE THREAD

**Issue by GitGameGit** [TIBCOSoftware/bw6-plugin-maven#395]
**Unable to resolve below error while running into BW6.4 studio:**

[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] BWUnitTestPOC.application.parent
[INFO] BWUnitTestPOC
[INFO] BWUnitTestPOC.application
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building BWUnitTestPOC.application.parent 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ BWUnitTestPOC.application.parent ---
[INFO] Installing D:\TIBCOBW64Project\BWUnitTestPOC.application.parent\pom.xml to C:\Users\428627\.m2\repository\com\tibco\bw\BWUnitTestPOC.application.parent\1.0.0-SNAPSHOT\BWUnitTestPOC.application.parent-1.0.0-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building BWUnitTestPOC 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ BWUnitTestPOC ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\TIBCOBW64Project\BWUnitTestPOC\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ BWUnitTestPOC ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ BWUnitTestPOC ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\TIBCOBW64Project\BWUnitTestPOC\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ BWUnitTestPOC ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M4:test (default-test) @ BWUnitTestPOC ---
[INFO] No tests to run.
[INFO] 
[INFO] --- bw6-maven-plugin:2.4.0:bwmodule (default-bwmodule) @ BWUnitTestPOC ---
[INFO] Module Packager Mojo started for Module BWUnitTestPOC ...
[INFO] Updated the Manifest version 
[INFO] The OSGi verion is 1.0.0.201912181727 for Maven version of 1.0.0.201912181727
[INFO] Removing the externals entries if any. 
[INFO] Created Plugin JAR with name D:\TIBCOBW64Project\BWUnitTestPOC\target\BWUnitTestPOC_1.0.0.201912181727.jar
[INFO] Adding Maven Dependencies to the Plugin JAR file
[INFO] Creating the Plugin JAR file
[INFO] Building jar: D:\TIBCOBW64Project\BWUnitTestPOC\target\BWUnitTestPOC_1.0.0.201912181727.jar
[INFO] BW Module Packager Mojo finished execution.
[INFO] 
[INFO] --- maven-install-plugin:3.0.0-M1:install (default-install) @ BWUnitTestPOC ---
[INFO] Installing D:\TIBCOBW64Project\BWUnitTestPOC\target\BWUnitTestPOC_1.0.0.201912181727.jar to C:\Users\428627\.m2\repository\com\tibco\bw\BWUnitTestPOC\1.0.0-SNAPSHOT\BWUnitTestPOC-1.0.0-SNAPSHOT.jar
[INFO] Installing D:\TIBCOBW64Project\BWUnitTestPOC\pom.xml to C:\Users\428627\.m2\repository\com\tibco\bw\BWUnitTestPOC\1.0.0-SNAPSHOT\BWUnitTestPOC-1.0.0-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building BWUnitTestPOC.application 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ BWUnitTestPOC.application ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\TIBCOBW64Project\BWUnitTestPOC.application\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ BWUnitTestPOC.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ BWUnitTestPOC.application ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\TIBCOBW64Project\BWUnitTestPOC.application\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ BWUnitTestPOC.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- bw6-maven-plugin:2.4.0:bwtest (default-bwtest) @ BWUnitTestPOC.application ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  Running BW Tests 
[INFO] -------------------------------------------------------
[INFO] ## Starting BW Engine in Test Mode ##
[INFO] ----BW Engine Logs Start---------------------------------------------------------------------------------------------------------------------------------------------------
[INFO] 
...17:28:04.284 INFO  [main] com.tibco.thor.frwk - TIBCO ActiveMatrix BusinessWorks version 6.4.2, build V32, 2017-11-05
.................17:28:30.343 INFO  [main] com.tibco.thor.frwk.Deployer - Started by BusinessStudio.
........17:28:41.698 INFO  [main] com.tibco.bw.frwk.engine.BWEngine - TIBCO-BW-FRWK-300002: BW Engine [Main] started successfully.
.......17:28:51.889 INFO  [Framework Event Dispatcher: Equinox Container: f0de91a4-8d21-001a-1999-e6de2c8a5ec8] com.tibco.thor.frwk.Deployer - TIBCO-THOR-FRWK-300001: Started OSGi Framework of AppNode [BWEclipseAppNode] in AppSpace [BWEclipseAppSpace] of Domain [BWEclipseDomain]
17:28:52.384 INFO  [Framework Event Dispatcher: Equinox Container: f0de91a4-8d21-001a-1999-e6de2c8a5ec8] com.tibco.thor.frwk.Application - TIBCO-THOR-FRWK-300018: Deploying BW Application [BWUnitTestPOC.application:1.0].
17:28:52.707 INFO  [Framework Event Dispatcher: Equinox Container: f0de91a4-8d21-001a-1999-e6de2c8a5ec8] com.tibco.thor.frwk.Application - TIBCO-THOR-FRWK-300021: All Application dependencies are resolved for Application [BWUnitTestPOC.application:1.0]
.......17:29:03.383 INFO  [Thread-18] com.tibco.thor.frwk.Application - TIBCO-THOR-FRWK-300006: Started BW Application [BWUnitTestPOC.application:1.0]
[INFO] ## BW Engine Successfully Started ##
17:29:03.383 INFO  [Framework Event Dispatcher: Equinox Container: f0de91a4-8d21-001a-1999-e6de2c8a5ec8] com.tibco.thor.frwk.Application - Started by BusinessStudio, ignoring .enabled settings.
[INFO] 
[INFO] ----BW Engine Logs End---------------------------------------------------------------------------------------------------------------------------------------------------
[INFO] ## Running Test for BWUnitTestPOC1.bwt ##
17:29:03.958 INFO  [bwEngThread:In-Memory Process Worker-3] c.t.b.p.g.Log.BWUnitTestPOC.StartLog - Received Request
17:29:03.968 INFO  [bwEngThread:In-Memory Process Worker-3] c.t.b.p.g.L.BWUnitTestPOC.ReportLog - Transformed Request
17:29:03.973 INFO  [bwEngThread:In-Memory Process Worker-3] c.t.b.p.g.Log.BWUnitTestPOC.EndLog - Completed Request
[INFO] Starting Tests in Module : BWUnitTestPOC
[INFO] Uploading tests for Processes in Module :  BWUnitTestPOC
 bwunittestpoc.Transaformation
javax.ws.rs.NotFoundException: HTTP 404 ProxyServlet: /bwut/tests/runtest
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1008)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:816)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] BWUnitTestPOC.application.parent ................... SUCCESS [  0.256 s]
[INFO] BWUnitTestPOC ...................................... SUCCESS [  1.121 s]
[INFO] BWUnitTestPOC.application .......................... FAILURE [01:05 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:09 min
[INFO] Finished at: 2019-12-18T17:29:05+05:30
	at org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92)
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:700)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:696)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349)
	at com.tibco.bw.maven.plugin.test.rest.BWTestRunner.runTestsPerModule(BWTestRunner.java:122)
	at com.tibco.bw.maven.plugin.test.rest.BWTestRunner.runTests(BWTestRunner.java:86)
	at com.tibco.bw.maven.plugin.test.setuplocal.BWTestExecutor.runTests(BWTestExecutor.java:118)
	at com.tibco.bw.maven.plugin.test.setuplocal.BWTestExecutor.execute(BWTestExecutor.java:38)
	at com.tibco.bw.maven.plugin.test.BWTestMojo.execute(BWTestMojo.java:66)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] Final Memory: 24M/266M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.4.0:bwtest (default-bwtest) on project BWUnitTestPOC.application: HTTP 404 ProxyServlet: /bwut/tests/runtest -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :BWUnitTestPOC.application

**Comment by SujataDarekar** [comment]
@GitGameGit Unit Test Feature is available from BW-Maven Plugin 2.0.0  and BW 6.5.0. Please check https://github.com/TIBCOSoftware/bw6-plugin-maven/releases/tag/v2.0.0.
