### ISSUE TITLE
The POM for com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100 is missing, no dependency information available

### ISSUE THREAD

**Issue by rsunkavalli** [TIBCOSoftware/bw6-plugin-maven#396]
Hi,
I am facing "The POM for com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100 is missing, no dependency information available" issue while trying to build the application through BuildMaster. I am using BW 6.4.2 and Maven plugin 1.3.1.
Below is the execution log from BuildMaster:

[INFO] ------------------< com.tibco.bw:Addition.app.module >------------------
[INFO] Building Addition.app.module 1.0.0-SNAPSHOT                        [3/4]
[INFO] ------------------------------[ bwmodule ]------------------------------
[WARNING] The POM for com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Addition.app.parent 1.0.0-SNAPSHOT:
[INFO] 
[INFO] Addition.app.parent ................................ SUCCESS [  0.060 s]
[INFO] Addition.shared .................................... SUCCESS [  0.646 s]
[INFO] Addition.app.module ................................ FAILURE [  0.017 s]
[INFO] Addition.app ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.037 s
[INFO] Finished at: 2019-12-18T13:52:44-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project Addition.app.module: Could not resolve dependencies for project com.tibco.bw:Addition.app.module:bwmodule:1.0.0-SNAPSHOT: Failure to find com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

I checked in .m2\repository\com\tibco\plugins and the com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100 jar file is under com.tibco.bw.palette.shared\6.1.100 folder instead of having it under \bw6-maven-plugin\ folder.
![image](https://user-images.githubusercontent.com/59032803/71124277-20ff9880-21aa-11ea-8611-3465f1a4b0b2.png)
![image](https://user-images.githubusercontent.com/59032803/71124674-feba4a80-21aa-11ea-80bf-c35724f562d1.png)

The build is successful when I execute through the command line but having an issue when I execute using BuildMaster.

Can someone please help to resolve this issue?

Thanks in advance.

**Comment by SujataDarekar** [comment]
@rsunkavalli com.tibco.bw.palette.shared-6.1.100.jar get installed under com.tibco.bw.palette.shared in local .m2 repo which is correct location. As per the logs we can see the maven look for the dependency in central repository rather than local repository where the shared dependency is present. Can you check which .m2 repo is referring when you execute the goal via build master. Build master should refer the local repo first.You can check it in settings.xml file. Also please check the com.tibco.bw.palette.shared-6.1.100.jar present with .lastupdated or not.

**Comment by rsunkavalli** [comment]
@SujataDarekar settings.xml has local repository set to "Default: ${user.home}/.m2/repository"
I updated it to "BW_HOME\maven\plugins\bw6-maven-plugin" and executed the goal again. It created a bunch of subdirectories and the jar files with .lastupdated under \plugins\com.tibco.bw.palette.shared\6.1.100 folder and build failed with jars missing exception. I renamed the jar and pom files and executed the goal again through Buildmaster and the build is successful this time.
Not sure if updating the localRepository to "BW_HOME\maven\plugins\bw6-maven-plugin" is a good practice. Please advise.

**Comment by SujataDarekar** [comment]
@rsunkavalli  settings.xml should refer the .m2 local repo which is correct in your case. There is no need to changes it to "BW_HOME\maven\plugins\bw6-maven-plugin" . 
1. Are you running the build master from the same machine where your .m2 repository present? 
    --->If yes then does the m2 repo present the shared jar with .updated? 
             -->If yes then remove the shared JAR and re-installed the maven plugin

**Comment by rsunkavalli** [comment]
@SujataDarekar BuildMaster and Maven are not running on the same server. Buildmaster TCP's to the other server which has Maven and executes the build script. The "user_home\.m2" repo has the "com.tibco.bw.palette.shared-6.1.100.jar" file with the correct name.
![image](https://user-images.githubusercontent.com/59032803/71371553-288ebb00-2577-11ea-96a7-e5f8348df584.png)

**Comment by SujataDarekar** [comment]
@rsunkavalli  The machine from where you run the BuildMaster should have BW maven plugin installed to the .m2 repository of the same machine.

**Comment by rsunkavalli** [comment]
The jar file name has ".lastUpdated" in the admin user_home\.m2 on the server. We renamed it and the build is working without any issues.

**Comment by diptimoha** [comment]
Hi , 
I am facing a similar issue when trying to do a maven build in AWS code pipeline, is there any steps that needs to be done before maven packaging  the bwce code in AWS code pipeline.

[WARNING] The POM for com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100 is missing, no dependency information available

My steps -
1. mavenise the tibco bwce project.
2. generate process diagrams.
3. generate POM files .
4. check in the code back to git hub repo.
configure the AWS codepipeline to pull code from git and then build the code using maven in code build where in encounter this issue.


[INFO]
--
8227 | [INFO] ---------------------< com.tibco.bw:tibcoCICD_POC >---------------------
8228 | [INFO] Building tibcoCICD_POC 1.0.0-SNAPSHOT                              [3/4]
8229 | [INFO] ------------------------------[ bwmodule ]------------------------------
8230 | Downloading from central: https://repo.maven.apache.org/maven2/com/tibco/plugins/com.tibco.bw.palette.shared/6.1.100/com.tibco.bw.palette.shared-6.1.100.pom
8231 | [WARNING] The POM for com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100 is missing, no dependency information available
8232 | Downloading from central: https://repo.maven.apache.org/maven2/com/tibco/plugins/com.tibco.bw.palette.shared/6.1.100/com.tibco.bw.palette.shared-6.1.100.jar
8233 | [INFO] ------------------------------------------------------------------------
8234 | [INFO] Reactor Summary for tibcoCICD_POC.application.parent 1.0.0-SNAPSHOT:
8235 | [INFO]
8236 | [INFO] tibcoCICD_POC.application.parent ................... SUCCESS [  0.003 s]
8237 | [INFO] TIBCOResources ..................................... SUCCESS [ 30.605 s]
8238 | [INFO] tibcoCICD_POC ...................................... FAILURE [  0.335 s]
8239 | [INFO] tibcoCICD_POC.application .......................... SKIPPED
8240 | [INFO] ------------------------------------------------------------------------
8241 | [INFO] BUILD FAILURE

**Comment by rsunkavalli** [comment]
@diptimoha Can you please check if the jar file is present in user_home/.m2 repository?
It will be under .m2\repository\com\tibco\plugins\com.tibco.bw.palette.shared\6.1.100 directory. If the file name has .lastUpdated appended, remove it and try again.

**Comment by singhr6** [comment]
I had same issue, I updated the settings.xml enable <localRepository>${user.home}/.m2/repository</localRepository>

and last removed the .lastupdated extension from the jars under m2\repository\com\tibco\plugins\com.tibco.bw.palette.shared\6.1.100

**Comment by diptimoha** [comment]
@rsunkavalli  i just checked  
.m2\repository\com\tibco\plugins\com.tibco.bw.palette.shared\6.1.100  ,
the jar file does not have .lastUpdated appended.  by the way , when maven packaging is done in my local laptop works fine , there is no issue with that. but when i push the bwce code to git and then create a pipeline in AWS code pipeline , it encounters this issue and also there is no way to look into the instances that run pipeline. Not sure if some one has tried this way to build and package the bwce application

My aws code pipeline buildSpec snippet

version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - GIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - POM_LOC=tibcoCICD_POC.application.parent/
      - EAR_LOC=/tibcoCICD_POC.application/target/
      - echo $GIT_HASH
      - cd $POM_LOC && mvn package 
the last line  fails

and there are some other steps post the last line which would eventually build the docker image and deploy it in ECS

**Comment by sarundes-tibco** [comment]
looks like duplicate  issue with https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/517
Hence marking this one as closed
