### ISSUE TITLE
unable to install TIBCO maven plugin 2.3.1 on Red Hat Linux 7.0 server

### ISSUE THREAD

**Issue by transferobject** [TIBCOSoftware/bw6-plugin-maven#397]
Maven Plugin version: 2.3.1

Maven version: 

./mvn -version
Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 13:51:28+0000)
Maven home: /opt/fdx/FDXmaven
Java version: 1.7.0_221, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.221-2.6.18.0.el7_6.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-957.21.3.el7.x86_64", arch: "amd64", family: "unix"

Product : TIBCO BW 6.5.1

i run the install.sh script and got the following errors. It also produced attached log files. Obviously Linux server doesn't have internet access. How to install TIBCO maven plugin on Linux server then?

[user123@c00788686 TIB_BW_Maven_Plugin_2.3.1]$ sudo -u tibco ./install.sh
[sudo] password for user123:
Starting Plugin Code for Apache Maven and TIBCO BusinessWorks™ installation ....
Unable to locate tools.jar. Expected to find it in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/lib/tools.jar
Buildfile: /opt/tibco/software/TIB_BW_Maven_Plugin_2.3.1/build.xml

getTibcoHome:
     [echo]
     [echo]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     [echo]                 Installing Plugin Code for Apache Maven and TIBCO BusinessWorks™
     [echo]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     [echo]
    [input]
    [input]                %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [input]
    [input]                  Input the path for Tibco Home here. Default will be c:\tibco
    [input]
    [input]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [input]
    [input]
/opt/tibco
     [echo] BW Version 6.5

setupMacros:

vbuild.launcher.jar:

devbuild.launcher.jar:

studio-install:
     [echo]  Installing Eclipse M2E Plugin to Tibco Home
     [exec] log4j:WARN No appenders could be found for logger (org.apache.http.impl.conn.SingleClientConnManager).
     [exec] log4j:WARN Please initialize the log4j system properly.
     [exec] Unable to load repositories.
     [exec] Application failed, log file location: /opt/tibco/studio/4.0/eclipse/configuration/1576777287324.log
     [exec] Installation failed.
     [exec]
     [exec] Result: 13
     [exec] Installing bw6.maven.dependencies.feature.feature.group 1.0.0.001.
     [exec] Operation completed in 6426 ms.
     [exec] Installing org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836.
     [exec] Installing org.eclipse.m2e.sdk.feature.feature.group 1.6.2.20151013-0836.
     [exec] Installing org.eclipse.m2e.logback.feature.feature.group 1.6.2.20151013-0836.
     [exec] Cannot complete the install because one or more required items could not be found.
     [exec]  Software being installed: m2e - Maven Integration for Eclipse (includes Incubating components) 1.6.2.20151013-0836 (org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836)
     [exec]  Missing requirement: m2e Marketplace 1.6.2.20151013-0836 (org.eclipse.m2e.discovery 1.6.2.20151013-0836) requires 'bundle org.eclipse.equinox.p2.ui.discovery 0.0.0' but it could not be found
     [exec]  Cannot satisfy dependency:
     [exec]   From: m2e - Maven Integration for Eclipse (includes Incubating components) 1.6.2.20151013-0836 (org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836)
     [exec]   To: org.eclipse.m2e.discovery [1.6.2.20151013-0836]
     [exec] Application failed, log file location: /opt/tibco/studio/4.0/eclipse/configuration/1576778093742.log
     [exec] Installation failed.
     [exec]
     [exec] Result: 13
     [echo]  UnInstalling the existing version of Plugin Code for Apache Maven and TIBCO BusinessWorks™
     [exec] Installation failed.
     [exec] The installable unit bw6.studio.maven.feature.feature.group has not been found.
     [exec] Application failed, log file location: /opt/tibco/studio/4.0/eclipse/configuration/1576778100490.log
     [exec]
     [exec] Result: 13
     [echo]  Installing Studio Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorks™ to the Tibco Home
     [exec] Installing bw6.studio.maven.feature.feature.group 2.3.1.001.
     [exec] Installation failed.
     [exec] Cannot complete the install because one or more required items could not be found.
     [exec]  Software being installed: TIBCO BusinessWorks™ Studio Feature for Maven 2.3.1.001 (bw6.studio.maven.feature.feature.group 2.3.1.001)
     [exec]  Missing requirement: TIBCO BusinessWorks™ Studio Plugin for Maven 2.3.1.001 (bw6.studio.maven.plugin 2.3.1.001) requires 'bundle org.eclipse.m2e.core [1.3.1,2.0.0)' but it could not be found
     [exec]  Cannot satisfy dependency:
     [exec]   From: TIBCO BusinessWorks™ Studio Feature for Maven 2.3.1.001 (bw6.studio.maven.feature.feature.group 2.3.1.001)
     [exec]   To: bw6.studio.maven.plugin [2.3.1.001]
     [exec] Application failed, log file location: /opt/tibco/studio/4.0/eclipse/configuration/1576778103701.log
     [exec]
     [exec] Result: 13

maven-install:
     [echo]  Installing Maven Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorks™ to Local Maven Repository
    [mkdir] Created dir: /opt/tibco/bw/6.5/maven/plugins
    [unzip] Expanding: /opt/tibco/software/TIB_BW_Maven_Plugin_2.3.1/config/bw6-maven-plugin.zip into /opt/tibco/bw/6.5/maven/plugins/bw6-maven-plugin

winInstall:

linuxInstall:
     [exec] Installing Maven Plugin to Maven Repository
     [exec] ./install.sh: line 3: mvn: command not found
     [exec] ./install.sh: line 5: mvn: command not found
     [exec] ./install.sh: line 7: mvn: command not found
     [exec] ./install.sh: line 9: mvn: command not found
     [exec] Result: 127

maven-plugin-install:

setup:

BUILD SUCCESSFUL
Total time: 13 minutes 50 seconds
[1576777287324.log](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3985072/1576777287324.log)
[1576778084345.log](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3985073/1576778084345.log)
[1576778093742.log](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3985074/1576778093742.log)
[1576778100490.log](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3985076/1576778100490.log)
[1576778103701.log](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/3985077/1576778103701.log)

**Comment by transferobject** [comment]
Hi, can someone pls atleast help me to understand why its going to this location looking for tools.jar and how can i change it?


sudo -u tibco ./install.sh
Starting Plugin Code for Apache Maven and TIBCO BusinessWorks™ installation ....
Unable to locate tools.jar. Expected to find it in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/lib/tools.jar

**Comment by SujataDarekar** [comment]
@transferobject Can you try with Java 8. Also let me know if you are installing the maven plugin first time on the machine? because for the first time plugin requires some plugin to download from .m2 central repository if it is not present in .m2 local repository.

**Comment by transferobject** [comment]
how can i try with Java 8? when i run the install.sh, by default it is looking for below java path for tools.jar

Starting Plugin Code for Apache Maven and TIBCO BusinessWorks™ installation ....
Unable to locate tools.jar. Expected to find it in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.el7_7.x86_64/lib/tools.jar

On my Linux machine, i have java installed at below location which has tools.jar file

/opt/tibco/JDK/jdk1.8.0_231/lib

cd /opt/tibco/JDK/jdk1.8.0_231/lib

total 43184
drwxr-xr-x 3 tibco tibco       33 Oct  5 10:10 amd64
-rw-r--r-- 1 tibco tibco  4576343 Sep 11  2019 ant-javafx.jar
-rw-r--r-- 1 tibco tibco 18247700 Oct  5 10:10 ct.sym
-rw-r--r-- 1 tibco tibco   163047 Oct  5 10:10 dt.jar
-rw-r--r-- 1 tibco tibco    18432 Oct  5 10:10 ir.idl
-rw-r--r-- 1 tibco tibco    36044 Sep 11  2019 javafx-mx.jar
-rw-r--r-- 1 tibco tibco   407728 Oct  5 10:10 jconsole.jar
-rwxr-xr-x 1 tibco tibco    13376 Oct  5 10:10 jexec
drwxr-xr-x 7 tibco tibco     4096 Dec  8  2017 missioncontrol
-rw-r--r-- 1 tibco tibco      640 Oct  5 10:10 orb.idl
-rw-r--r-- 1 tibco tibco     4646 Sep 11  2019 packager.jar
-rw-r--r-- 1 tibco tibco  2415573 Oct  5 10:10 sa-jdi.jar
-rw-r--r-- 1 tibco tibco 18307883 Oct  5 10:10 tools.jar
drwxr-xr-x 6 tibco tibco       61 Jan 14  2017 visualvm



In which TIB_BW_Maven_Plugin_2.3.1 file i need to change the java path to this path /opt/tibco/JDK/jdk1.8.0_231/lib

**Comment by transferobject** [comment]
..
