### ISSUE TITLE
Enhancement Request Summary : Externalizing profile, 'other' option given in POM wizard, does not work if property file (profile) is referenced using relative path. We are using Jenkins job to build EAR file using BW6 Application code & Profile property file (DEV/QA/PROD etc) residing in separate folders in Git Repo and  eventually another jenkins job to deploy the built EAR to runtime (TEA).

### ISSUE THREAD

**Issue by bankarswapnil** [TIBCOSoftware/bw6-plugin-maven#399]
My setup[Windows10_64bit+BW650+TEA230+EMS851+TIB_BW_Maven_Plugin_240]

**Steps to reproduce the issue:**
Main Issues : 
1. If Application has Application level properties set, Build fails
---->Workaound : delete the app level property settings and retry.
2. Relative profile path does not work, ex. <externalProfileLoc>../QA.substvar</externalProfileLoc>	
Subsequent couple of issues I have observed,
1. Although am deleting application from TEA before re-deployment,
	a. Getting exception as 'Failed to remove stats of Application [1.0|Greetings.application] in AppSpace [MyAppSpace] of Domain [MyDomain]' 
	   but actually it does delete the application.
    b. am able to see earlier/old deployment endpoint URL instances in TEA on subsequent deployments.
2. Although, we have selected profile as 'other' pointing to QA (which is not a default profile),
   a. Deployed application endpoint still points to default profile property values, say HTTPPort:8071 instead of 8383.
   workaround : just restart the application

**Additional environment details if any:**

**Describe the results you received:**

**Describe the results you expected:**
In POM, Relative path is supported ? or only absolute path is supported ?

**Additional information you deem important (e.g. issue happens only occasionally):**
I will attach a WebEx to convey steps followed to reproduce the issue.

Thanx,
-Swapnil
[CICD_Ext_Profile_Failed_3.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4031216/CICD_Ext_Profile_Failed_3.zip)

**Comment by swapnilbankar** [comment]
Hello Sujata,
If possible can we have a quick call. We have to showcase demo to client before this week ends.
Let me know your suitable time.
Thanx,
-Swapnil

**Comment by SujataDarekar** [comment]
@bankarswapnil  Please find my below comments:
1. If Application has Application level properties set, Build fails
  --> Could you please share the detailed steps to reproduce this issue. It will really help to reproduce issue in our environment
  
2. Relative profile path does not work, ex. ../QA.substvar
  --> We do not support the relative path option
  
3. Although am deleting application from TEA before re-deployment,
a. Getting exception as 'Failed to remove stats of Application [1.0|Greetings.application] in AppSpace [MyAppSpace] of Domain [MyDomain]'
but actually it does delete the application.
 b. am able to see earlier/old deployment endpoint URL instances in TEA on subsequent deployments.
   --> This issue does not seem from maven side but still we will check and let you know.

4. Although, we have selected profile as 'other' pointing to QA (which is not a default profile),
a. Deployed application endpoint still points to default profile property values, say HTTPPort:8071 instead of 8383.
workaround : just restart the application
   --> will look into this.

**Comment by swapnilbankar** [comment]
Thank you Sujata for reply.
Please find my comments inline…


Thanx,
-Swapnil

Planned absence
None

**Comment by swapnilbankar** [comment]
Hello Sujata,
By any chance, you are able to find the way we can use Jenkins job to build EAR file using BW6 Application code & Profile property file residing in separate folders in Git Repo and Deploy the EAR to TEA ?
This is the only part blocking in our BW6 CICD pipeline framework using BW6 Maven plugin.
Help on this front is highly appreciated.
Thanx,
-Swapnil

**Comment by SujataDarekar** [comment]
@bankarswapnil Currently we only absolute path support for external profile where external profile should be present on the same machine. Now For jenkins, we will required  code changes where the external profile will be downloaded from mentioned URL.

**Comment by swapnilbankar** [comment]
Hi Sujata,
Does that mean, you have created a enhancement request to support for external profile where external profile can reside on different folder of git repo and path can have either link or relative path of profile?
If that is the case, can you share the time lines by when we can have this feature implemented ?

Meanwhile, if you know any workarounds (possibly from existing clients who are using the plugin)
please do share.

Thanx,
-Swapnil

**Comment by SujataDarekar** [comment]
@swapnilbankar You can create the new enhancemnt with your requirement So that I will plan it accordingly.

**Comment by swapnilbankar** [comment]
Hi Sujata,
Can you transform this issue into Enhancement (or assign label as Enhancement) ? I could not find option for creating Enhancement though.

Thanx,
-Swapnil

**Comment by swapnilbankar** [comment]
Hi Sujata,

Did you transfer the issue into enhancement ? or let me know how to create it ?
This requirement is very crucial for many customers and we are stuck on this.
Your help will be highly appreciated.

Thanx,
-Swapnil

**Comment by SujataDarekar** [comment]
@bankarswapnil I have marked this issue as enhancement. Please just change the issue title with requirement summary

**Comment by bankarswapnil** [comment]
Hi Sujata,
I tried to abstract an Enhancement Summary as much as possible.
Hope you have my all webex shared on this to reproduce the issue (https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4031216/CICD_Ext_Profile_Failed_3.zip)

Looking forward to have this feature as early as possible.
Thank you for all support.

-Swapnil
