### ISSUE TITLE
SVG files are not generated while running the Maven Build

### ISSUE THREAD

**Issue by ashutoshbhide** [TIBCOSoftware/bw6-plugin-maven#4]
SVG Files not getting generated while running the Maven Build

**Comment by ashutoshbhide** [comment]
SVGs are generated through the Eclipse RCP code. Not able to port that to Maven.
This issue will remain open until the code to port that is available or the SVGs is available.

**Comment by HiteshNembhwani** [comment]
Fixed with BW 6.4.2 / BWCE 2.3.2 and Maven 1.3.0 version.

**Comment by ashutoshbhide** [comment]
This feature is now available with BW 6.4.2 / BWCE 2.3.2
The diagram can be now generated via studio prior to the Build.

**Comment by mshahat** [comment]
/reopen

BWCE 2.4.1, maven plugin 2.0.2 ... the diagrams are not showing on BWCE Monitor. 
The presumption is that maven plugin are used in all sites and for all practical reasons to produce EARs, so support for generating diagrams is needed please. 
that could be a goal or a switch on an existing goal 

Thanks,

**Comment by subiwani** [comment]
Is there any update over this issue; Like if there is any goal now available which will include process diagrams in ear package during build or we still have to follow the procedure of generating it in studio, so as to be included in ear.

**Comment by HiteshNembhwani** [comment]
@subiwani bwdesign utility is another alternative if you want to generate the process diagrams via CLI. (apart from the Studio option)
