### ISSUE TITLE
Maven Test goal

### ISSUE THREAD

**Issue by anteneh72** [TIBCOSoftware/bw6-plugin-maven#40]
Does the plugin support maven test goal. If so can you give the steps?

![image](https://cloud.githubusercontent.com/assets/12057955/19125659/c3097af4-8aec-11e6-9fe5-202f01acc4f6.png)

**Comment by awagle** [comment]
Currently the plugin doesn't support the test goal. This would be an enhancement.

Thanks,
Aditya

**Comment by Tantino** [comment]
hi @awagle ,
I would like to know how to do the test process.
thanks nad regards.

**Comment by ashutoshbhide** [comment]
Added Test Support. Closing the issue
