### ISSUE TITLE
How to generate POM for external shared modules?

### ISSUE THREAD

**Issue by rsunkavalli** [TIBCOSoftware/bw6-plugin-maven#404]
Hi

I have an application that uses an external shared module. When I import the external shared module and try to generate POM for the application, the external shared module is not getting listed as shared module. How can we generate POM for an application which uses external shared modules?

![image](https://user-images.githubusercontent.com/59032803/72905322-ff885400-3cf5-11ea-8d54-836dbc10b191.png)

Thanks,
Raja

**Comment by rsunkavalli** [comment]
Can someone please help on this?

**Comment by SujataDarekar** [comment]
@rsunkavalli  Which version of BW maven Plugin are you using?

**Comment by SujataDarekar** [comment]
@rsunkavalli  Also Does it show in dependencies(required plugin) of module project ?

**Comment by rsunkavalli** [comment]
@SujataDarekar We are using Maven plugin 1.3.1. And yeah the shared module is shown in the application module dependencies.

**Comment by SujataDarekar** [comment]
@rsunkavalli I would suggest use the the latest BW Maven Plugin and then try your use case.

**Comment by rsunkavalli** [comment]
@SujataDarekar, will it be compatible with BW 6.4.2?

**Comment by SujataDarekar** [comment]
@rsunkavalli  looking at your use case yes it is

**Comment by rsunkavalli** [comment]
@SujataDarekar , I have installed the latest BW Maven Plugin. I have imported the external shared modules to the workspace and tried to generate the POM file. Still the shared modules are not listed.

![image](https://user-images.githubusercontent.com/59032803/73295194-de7ba380-41cc-11ea-99d1-802c43bfab40.png)

**Comment by SujataDarekar** [comment]
@rsunkavalli Can you share the project?

**Comment by rsunkavalli** [comment]
@SujataDarekar Attached the application and shared modules. Please let me know if you need more details.
[VendorHub.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4126205/VendorHub.zip)
[SharedModules.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4126211/SharedModules.zip)

**Comment by SujataDarekar** [comment]
@rsunkavalli  I have checked your project. I am facing some namespace related issues in module project. So I have just created one simple project and added the shared module attached with the issue. I can see the list of all shared module while generating the POM. Even in screenshot shared by you I can see the scroll down option. Please check the same

**Comment by rsunkavalli** [comment]
@SujataDarekar, I checked the scroll down and shared modules are not listed. Wanted to check if we are on the same page, did you import the shared module zipped folders by following: Window > Preferences > Plug-in Development > Target Platform > bw-runtime (Active) > Edit > Locations > Add > BW Shared Module? Or you imported using the Import option?
Namespace issues persist if the shared modules are imported using Import option. Please confirm

**Comment by rsunkavalli** [comment]
@SujataDarekar did you get a chance to look into this?

**Comment by awagle** [comment]
Are you still facing the issue? Have you tried re-generating the application POM after adding the shared modules as dependencies to both application and application module projects?

**Comment by sarundes-tibco** [comment]
We didnot hear back from you and Feature is also available.. Hence marking this as closed
