### ISSUE TITLE
Error on installation of BW6maven plugin in Windows machine

### ISSUE THREAD

**Issue by goutham-muragavel** [TIBCOSoftware/bw6-plugin-maven#406]
@sonalshingavi 
Hi Team,

Please find the below details of error:
Tibco BW Version:6.4.2
Azure Server :10.164.70.172
Maven Versions Tried: TIB_BW_Maven_Plugin_1.3.0, TIB_BW_Maven_Plugin_2.0.1, TIB_BW_Maven_Plugin_2.3.0, TIB_BW_Maven_Plugin_2.5.0.
Error Message : MESSAGE An error occurred while automatically activating bundle org.eclipse.ui.workbench (907).
[Maven Errors.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4138422/Maven.Errors.zip)

**Comment by goutham-muragavel** [comment]
@awagle ,
can you please check on this.

**Comment by ukuppa-tibco** [comment]
BW 6.4.2 is compatible with Maven plugin version 1.3.1 and certified with the same.
Please refer https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/BW-Release-Compatibility-Guide
