### ISSUE TITLE
Jenkin build job failing - BW 6.4.2 & Maven 1.3.1

### ISSUE THREAD

**Issue by sonuschinnatech** [TIBCOSoftware/bw6-plugin-maven#408]
Jenkin build job failing with 1st run - BW 6.4.2 & Maven 1.3.1. 

**Jenkin Build Error logs,**
Failed to transfer Could not transfer artifact com.tibco.bw:SampleBW6app.application.parent:pom:1.0.0 from/to central (https://repo.maven.apache.org/maven2): /home/esbuser/.m2/repository/com/tibco/bw/SampleBW6app.application.parent/1.0.0/SampleBW6app.application.parent-1.0.0.pom.part.lock (Permission denied)
ERROR: Failed to parse POMs
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.tibco.bw:SampleBW6app.application:[unknown-version]: Could not transfer artifact com.tibco.bw:SampleBW6app.application.parent:pom:1.0.0 from/to central (https://repo.maven.apache.org/maven2): /home/esbuser/.m2/repository/com/tibco/bw/SampleBW6app.application.parent/1.0.0/SampleBW6app.application.parent-1.0.0.pom.part.lock (Permission denied) and 'parent.relativePath' points at wrong local POM @ line 5, column 11
[ERROR] Child module /apps/jenkins/workspace/TestMaven/src/bw/SampleBW6app.application.parent/../TestMavenJenkins of /apps/jenkins/workspace/TestMaven/src/bw/SampleBW6app.application.parent/pom.xml does not exist @ 

we followed below link but not able to understand where to run mvn install & where to copy target dependency files. Could you please provide absolute paths for below recommendations from issue 83
-   https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/83

**Comment by SujataDarekar** [comment]
@sonuschinnatech Can you share the project  ans goals you are using?

**Comment by sonuschinnatech** [comment]
Internet access blocked with in enterprise servers so maven not able to connect to maven Central.
Issue fixed after working with n/w team.

Closing the ticket.
