### ISSUE TITLE
TIBCO BWCE with Maven Plugin Integration Problem

### ISSUE THREAD

**Issue by sree-sandeep** [TIBCOSoftware/bw6-plugin-maven#409]
I am using TIBCO BWCE 2.5.0, and installed TIBCO BW Maven Plugin 2.5.0 in order to integrate TIBCO BWCE with Maven. After installation of Maven plugin, I am not able get the context menu like "Generate POM for Application, after right clicking on the TIBCO Business Studio Project.

Please suggest me, is there any other way to Generate POM for TIBCO BWCE Application in order to create Docker image and deploy the same to Kubernetes Cluster.

**Comment by dtredinnick13** [comment]
I am having the exact same issue.  I am running Studio on Windows.  I tried creating a new workspace and project just to see if maybe it would not work with a workspace and project that was created prior to installation of the the plug-in.

If I look in my TIBCO Home, I see the plug-in is installed in the BWCE/2.5 directory.

![BWCE Directory Screenshot](https://user-images.githubusercontent.com/11760424/74762247-12ce0700-5243-11ea-812c-c849843e152f.PNG)

**Comment by sree-sandeep** [comment]
Thanks Don. I have created new TIBCO_HOME for TIBCO BWCE 2.5.1 and installed TIB_BW_Maven_Plugin_2.5.0. Now I can able to see Generate POM for Application. Below the installation console of Maven Plugin. There are few errors. But finally build was successful.
####################################################################
D:\BWCE_Soft\TIB_BW_Maven_Plugin_2.5.0>install.bat

D:\BWCE_Soft\TIB_BW_Maven_Plugin_2.5.0>java -Dtibcohomepath= -cp antpackage.jar org.apache.tools.ant.launch.Launcher
Buildfile: D:\BWCE_Soft\TIB_BW_Maven_Plugin_2.5.0\build.xml

getTibcoHome:
     [echo]
     [echo]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     [echo]                 Installing Plugin Code for Apache Maven and TIBCO BusinessWorksÖ
     [echo]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     [echo]
    [input]
    [input]                %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [input]
    [input]                  Input the path for Tibco Home here. Default will be c:\tibco
    [input]
    [input]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [input]
    [input]
C:\tibco\bwce
     [echo] BWCE Version 2.5

setupMacros:

vbuild.launcher.jar:

devbuild.launcher.jar:

studio-install:
     [echo]  Installing Eclipse M2E Plugin to Tibco Home
     [exec] log4j:WARN No appenders could be found for logger (org.apache.http.impl.conn.SingleClientConnManager).
     [exec] log4j:WARN Please initialize the log4j system properly.
     [exec] Installing org.eclipse.equinox.p2.discovery.feature.feature.group 1.0.200.v20140512-1802.
     [exec] Operation completed in 349033 ms.
     [exec] Installing bw6.maven.dependencies.feature.feature.group 1.0.0.001.
     [exec] Operation completed in 6120 ms.
     [exec] Installing org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836.
     [exec] Installing org.eclipse.m2e.sdk.feature.feature.group 1.6.2.20151013-0836.
     [exec] Installing org.eclipse.m2e.logback.feature.feature.group 1.6.2.20151013-0836.
     [exec] Operation completed in 22526 ms.
     [echo]  UnInstalling the existing version of Plugin Code for Apache Maven and TIBCO BusinessWorksÖ
     [exec] org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
     [exec] The installable unit bw6.studio.maven.feature.feature.group has not been found.
     [exec] Installation failed.
     [exec] Application failed, log file location: C:\tibco\bwce\studio\4.0\eclipse\configuration\1582097171374.log
     [exec]
     [exec] Result: 13
     [echo]  Installing Studio Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorksÖ to the Tibco Home
     [exec] org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
     [exec] Installing bw6.studio.maven.feature.feature.group 2.5.0.001.
     [exec] Operation completed in 7061 ms.

maven-install:
     [echo]  Installing Maven Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorksÖ to Local Maven Repository
    [mkdir] Created dir: C:\tibco\bwce\bwce\2.5\maven\plugins
    [unzip] Expanding: D:\BWCE_Soft\TIB_BW_Maven_Plugin_2.5.0\config\bw6-maven-plugin.zip into C:\tibco\bwce\bwce\2.5\maven\plugins\bw6-maven-plugin

winInstall:
     [exec]
     [exec] C:\tibco\bwce\bwce\2.5\maven\plugins\bw6-maven-plugin>echo Installing Maven Plugin to Maven Repository
     [exec] Installing Maven Plugin to Maven Repository
     [exec]
     [exec] C:\tibco\bwce\bwce\2.5\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=com.tibco.bw.palette.shared_6.1.100.003.jar -DgroupId=com.tibco.plugins -DartifactId=com.tibco.bw.palette.shared -Dversion=6.1.100 -Dpackaging=jar
     [exec]
     [exec] C:\tibco\bwce\bwce\2.5\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=com.tibco.xml.cxf.common_1.3.200.001.jar -DgroupId=com.tibco.plugins -DartifactId=com.tibco.xml.cxf.common -Dversion=1.3.200 -Dpackaging=jar
     [exec]
     [exec] C:\tibco\bwce\bwce\2.5\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=bw6-maven-plugin-2.5.0.jar -DpomFile=pom.xml
     [exec]
     [exec] C:\tibco\bwce\bwce\2.5\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=fabric8/fabric8-maven-plugin-2.2.102.jar -DpomFile=fabric8/pom.xml

linuxInstall:

maven-plugin-install:

setup:

BUILD SUCCESSFUL
Total time: 7 minutes 35 seconds
####################################################################
