### ISSUE TITLE
Imported Shared Module error - "Project build error: Non-readable POM"

### ISSUE THREAD

**Issue by IMurzich** [TIBCOSoftware/bw6-plugin-maven#412]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

Maven Plugin version: 2.3.1

Maven version: Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T21:41:47+03:00)
Java version: 1.8.0_222, vendor: AdoptOpenJDK, runtime: D:\java\jdk-8.0.222.10-hotspot\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows server 2016", version: "10.0", arch: "amd64", family: "windows"

Product : Either of TIBCO ActiveMatrix Businessworks 6

Product version:6.5.1 HF 2

Component: Maven Eclipse Plugin

**Steps to reproduce the issue:**
1. Create and install shared module into maven repository
2. Create application and add the shared module as dependency
3.

**Additional environment details if any:**

**Describe the results you received:**
After clearing the project I see errors for all imported modules:
Description	Resource	Path	Location	Type
Project build error: Non-readable POM d:\maven\.repo\by\a1\tibco6\Expiration.lib\1.0.0\Expiration.lib-1.0.0.jar\pom.xml: d:\maven\.repo\by\a1\tibco6\Expiration.lib\1.0.0\Expiration.lib-1.0.0.jar\pom.xml (The system cannot find the path specified)	pom.xml	/Expiration.lib	line 1	Maven pom Loading Problem

Also, when I create ear in studio I see following error:
![image](https://user-images.githubusercontent.com/20977764/75246148-344d6680-57e0-11ea-9ab8-c409e56ecd99.png)

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by marchelh** [comment]
Having the same issue, only here the problem always happens!
![afbeelding](https://user-images.githubusercontent.com/3594060/77511274-0a37a480-6e71-11ea-8432-857d27b6b0cd.png)
The file is actually readable, so why is it complaining?

**Comment by damienRiv** [comment]
Hi,
@marchelh : for your problem i have see a solution on this issues : https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/231
solution : It seems that disabling maven nature and re-enable it in the module that has the issue. make the issue gone. But 
Personnaly if I disable maven nature the problem is solve but I can't renable it. But it's not a probleme for me because it is an depedency retrieved automatically.
Good day,

**Comment by awagle** [comment]
Please re-open if the suggestion provided by @damienRiv isn't working.
