### ISSUE TITLE
Question: Deploy Tibco BW6.6 Application Using Maven Goals

### ISSUE THREAD

**Issue by talankee** [TIBCOSoftware/bw6-plugin-maven#423]
I am using Maven Task in Azure CICD Release Pipeline and would like to use Maven Goals to Deploy a BW6.6 application to different servers based on the .properties defined. Ex: Dev.properties, Prod.properties.

What is the goal for it? I was browsing through some online content and I found -
initialize cf:push -Dpcf.property.file=pcfdev.properties ( this is used to push to cloud foundry)

We are trying to automate our deployment process through CICD.

Thanks
Satya

**Comment by talankee** [comment]
Is there something similar to the above command for deploying to a AppSpace and Domain running on-prem.

**Comment by SujataDarekar** [comment]
@talankee Please refer https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/Building-applications-for-TIBCO-BusinessWorks-Container-Edition-in-PCF. I hope this is helpful for you

**Comment by talankee** [comment]
@SujataDarekar The link you posted is for CloudFoundry, but I am looking for deploying to TEA running on a my test servers/ local?

**Comment by SujataDarekar** [comment]
@talankee  If you want to deploy it on Tea then generate the POM with appspace, appnode and agent details and run the mvn install goal
