### ISSUE TITLE
...

### ISSUE THREAD

**Issue by transferobject** [TIBCOSoftware/bw6-plugin-maven#425]
..

**Comment by transferobject** [comment]
<img width="913" alt="Capture" src="https://user-images.githubusercontent.com/26683529/78314362-c5260900-7527-11ea-822b-0d3a26151c26.PNG">

**Comment by singhr6** [comment]
could you attach your code/or share the bw log.

**Comment by transferobject** [comment]
Thanks for the response. My test application is very simple. It connects to JMS and DB. (attached screenshot) 

Below i found in appnode log

"2020-04-01 16:47:49.920 ERROR [qtp528190809-37] com.tibco.bw.thor.runtime.model.Application - TIBCO-THOR-FRWK-500202: Application [com.tibco.custom.jms.provider{<none>, [osgi-bundle,], , <unbound>}] is missing a Bundle"

i also compare the EAR file generated by the maven and the directly generated by studio. i found that maven generated EAR file missing resource folder and custom ems driver part.

I can't attach the project here because we use custom ems driver/custom jar file to connect to TIBCO EMS server. If you can share your company email address then i can send the project from my company email address
