### ISSUE TITLE
Generate POM for Application - Project build error: Unknown packaging: bwear

### ISSUE THREAD

**Issue by transferobject** [TIBCOSoftware/bw6-plugin-maven#432]
,,

**Comment by SujataDarekar** [comment]
@transferobject Can you check dependency org.apache.maven:maven-plugin-api:jar:3.3.3 is present in your .m2 repo or not. Also just try to run mvn clean compile goal which should download all the dependencies.
Also make sure bw maven plugin is installed properly in your .m2

**Comment by transferobject** [comment]
I can't find this in .m2 directory - org.apache.maven:maven-plugin-api:jar:3.3.3

i reinstall tibco maven plugin again. does it install properly? attached logs. after the reinstall, I can see these files

C:\Users\3786801\.m2\repository\org\apache\maven\maven-plugin-api\3.3.3
maven-plugin-api-3.3.3.jar.lastUpdated
maven-plugin-api-3.3.3.pom.lastUpdated

i run clean compile goal in TIBCO business studio and attached is the log with errors


[reinstallTIBCOMavenPlugin231.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4523709/reinstallTIBCOMavenPlugin231.txt)
[mvn_clean_compile.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4523710/mvn_clean_compile.txt)
<img width="704" alt="mavenCleanCompilestudio" src="https://user-images.githubusercontent.com/26683529/80121793-b9dc6100-855a-11ea-944d-5952ddae2964.PNG">

**Comment by transferobject** [comment]
..
