### ISSUE TITLE
Unable to start application in Quality after creating ear from maven

### ISSUE THREAD

**Issue by singhalr1** [TIBCOSoftware/bw6-plugin-maven#433]
I have created tibco ear from maven and deployed it development environment and it is working fine.

But when i am deploying it in quality then it is getting deployed but application is not getting started. There are many logs which I am not able to understand. I need someone help in debugging it.

maven: 2.5.0
TIBCO BW: 6.5.1
TEA ADMIN: 2.3.0 HF-9

Thanks
Rishabh
email: rishabh.singhal@zimmerbiomet.com
Mo: +1-574-253-1089

**Comment by awagle** [comment]
Please open an SR. Given the application works fine in one environment the EAR is built correctly.
