### ISSUE TITLE
On MAC I am not able to run CE code bwmodule not recognizing ?

### ISSUE THREAD

**Issue by ganisettis** [TIBCOSoftware/bw6-plugin-maven#434]
From tibco ce I am getting below error for the same artifactory. I have added the certificate in the keytool for this url.

RROR] Unknown packaging: bwmodule @ com.tibco.bw:serviceRevSpringsAsync:[unknown-version], /Users/sganise/Code/CE/revspringsasyncservice/serviceRevSpringsAsync/pom.xml, line 11, column 14
@
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]  
[ERROR]   The project com.tibco.bw:serviceRevSpringsAsync:1.0.0 (/Users/sganise/Code/CE/revspringsasyncservice/serviceRevSpringsAsync/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin com.tibco.plugins:bw6-maven-plugin:1.3.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.tibco.plugins:bw6-maven-plugin:jar:1.3.1: Could not transfer artifact com.tibco.plugins:bw6-maven-plugin:pom:1.3.1 from/to repo (https://artifactory.service.edp.t-mobile.com/artifactory/snapshot-internal-repositories): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 2]
[ERROR]     Unknown packaging: bwmodule @ com.tibco.bw:serviceRevSpringsAsync:[unknown-version], /Users/sganise/Code/CE/revspringsasyncservice/serviceRevSpringsAsync/pom.xml, line 11, column 14
[ERROR]

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->
Maven Plugin version:

Maven version:

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version:

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1.
2.
3.

**Additional environment details if any:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by ganisettis** [comment]
The same artifactory url is working fine in springbok application I am not getting any certificate error can someone help

**Comment by SujataDarekar** [comment]
@ganisettis this issue is not specific with bw-maven-plugin. It's something related to certificate error.

**Comment by awagle** [comment]
Please provide a reproducible project and re-open.
