### ISSUE TITLE
TIBCO Studio - Run/Debug Configuration - Maven Build (New configuration)

### ISSUE THREAD

**Issue by transferobject** [TIBCOSoftware/bw6-plugin-maven#435]
=====================
Maven Plugin version: 2.3.1
Maven version: apache-maven-3.5.3
Product : TIBCO ActiveMatrix Businessworks 6.51. HF2
Product version: BW6.5.1
--------------
On windows 10 Enterprise laptop, I followed the following steps till j and it created an ear file in target folder. (problem is this ear file is only 5kb. if i generate ear file directly from studio using "Export Application for Deployment", the size is 39kb. please note that, i am using sample application from this location C:\tibcobw6\bw\6.5\samples\AppSpace\binding\rest\Basic

**Question is: in the attached screenshot, i left the user settings filed empty. Should this be empty? if not, what path i should mention? attached also maven build output.txt
![Usersettings](https://user-images.githubusercontent.com/26683529/79701201-142ea680-8269-11ea-8c66-9fc8ecb4cbdd.png)
** 

Running the Maven Build from Studio.

a. Open the Studio.

b. Right-Click on the Application project.

c. The Context Menu will show the option "Generate POM for Application".

d. Clicking it will launch the POM Generation UI.

e. Enter the Parent POM details here and Click Finish.

f. The Project will be converted to Maven (Eclipse Project) nature. Note the workspace will index after generating POM files for the first time and may take some time. You can continue with the steps below by allowing this indexing to run in the background.

g. Open Run/Debug Configurations. Create a new Maven Build.

h. Under the "Base directory" choose add variable for Workspace location. The variable name is ${workspace_loc}.

i. In the Goal enter the Goal to be executed. The goal can be any standard Maven goal like package, install, deploy etc.

j. Select the goal as "package" for creating the EAR file. This will create the EAR file in the target folder under the Application project - 'Refresh' your project using the right-click menu if this folder is not visible.

Running the Maven Build from Studio.

a. Open the Studio.

b. Right-Click on the Application project.

c. The Context Menu will show the option "Generate POM for Application".

d. Clicking it will launch the POM Generation UI.

e. Enter the Parent POM details here and Click Finish.

f. The Project will be converted to Maven (Eclipse Project) nature. Note the workspace will index after generating POM files for the first time and may take some time. You can continue with the steps below by allowing this indexing to run in the background.

g. Open Run/Debug Configurations. Create a new Maven Build.

h. Under the "Base directory" choose add variable for Workspace location. The variable name is ${workspace_loc}.

i. In the Goal enter the Goal to be executed. The goal can be any standard Maven goal like package, install, deploy etc.

j. Select the goal as "package" for creating the EAR file. This will create the EAR file in the target folder under the Application project - 'Refresh' your project using the right-click menu if this folder is not visible.

k. Select the goal as "install" for creating the EAR file and installing it to local Maven Repository.
[output.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4500429/output.txt)

**Comment by SujataDarekar** [comment]
@transferobject You don't need provide anything in user setting. For the different size of JAR, can you check which folder is missing in the EAR generated through maven

**Comment by transferobject** [comment]
i have attached both ear files for reference. 

tibco.bw.sample.binding.rest.Basic.application_1.0.0(maven).ear  (generated by maven)
tibco.bw.sample.binding.rest.Basic.application_1.0.0.ear (directly generate from studio)

EAR file generated by maven has missing resource folder. why is that and how to fix it?


Also, i have one more question: if you look at the screenshot which i had attached in my original post. In Base directory, i have this path ${workspace_loc:/tibco.bw.sample.binding.rest.Basic.application}. The reason for this is that, if i use only this ${workspace_loc}, it complain that there is no POM.xml file

**Comment by transferobject** [comment]
Hello Sujata, can you look into my issue and provide a solution?

**Comment by SujataDarekar** [comment]
@transferobject  "resource" folder contains the process diagram. So if you want to include the process Diagram while generating the EAR through Maven then please refer https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/Steps-to-add-Process-Diagram-in-EAR.

Also Please run the package goal on "tibco.bw.sample.binding.rest.Basic.application.parent" project for that you need to select parent project in Base directory. Try this and let me know if you still see the difference in EAR size

**Comment by transferobject** [comment]
@SujataDarekar thanks for your response. I don't want to include the process diagram so i didn't follow the link you mentioned.

now i chose the base directory as you suggested. screenshot

i run the maven build from studio and got errors. I have been trying to resolve maven issues for the last six months. In our company, we have big presence of TIBCO products and this doesn't look good. if possible, can we have a zoom meeting to resolve this? i can share my email address if you are okay?



[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] tibco.bw.sample.binding.rest.Basic.application.parent
[INFO] tibco.bw.sample.binding.rest.Basic
[INFO] tibco.bw.sample.binding.rest.Basic.application
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic.application.parent 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ tibco.bw.sample.binding.rest.Basic ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\3786801\NewSampleWs\tibco.bw.sample.binding.rest.Basic\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ tibco.bw.sample.binding.rest.Basic ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\3786801\NewSampleWs\tibco.bw.sample.binding.rest.Basic\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M4:test (default-test) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/maven-surefire-common/3.0.0-M4/maven-surefire-common-3.0.0-M4.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] tibco.bw.sample.binding.rest.Basic.application.parent SUCCESS [  0.003 s]
[INFO] tibco.bw.sample.binding.rest.Basic ................. FAILURE [ 13.575 s]
[INFO] tibco.bw.sample.binding.rest.Basic.application ..... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.971 s
[INFO] Finished at: 2020-05-11T10:18:29-04:00
[INFO] Final Memory: 17M/371M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-test) on project tibco.bw.sample.binding.rest.Basic: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test failed: Plugin org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.maven.plugins:maven-surefire-plugin:jar:3.0.0-M4 -> org.apache.maven.surefire:maven-surefire-common:jar:3.0.0-M4: Failed to read artifact descriptor for org.apache.maven.surefire:maven-surefire-common:jar:3.0.0-M4: Could not transfer artifact org.apache.maven.surefire:maven-surefire-common:pom:3.0.0-M4 from/to central (https://repo.maven.apache.org/maven2): connect timed out -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :tibco.bw.sample.binding.rest.Basic
Picked up _JAVA_OPTIONS: -Xmx512M

![Base_Dir_parent](https://user-images.githubusercontent.com/26683529/81572871-c2fa6a00-9371-11ea-9de7-eeefd44c7501.PNG)
[base_dir_parent_goal_package.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4610145/base_dir_parent_goal_package.txt)

**Comment by SujataDarekar** [comment]
@transferobject The issue which you are mentioning is not specific with Tibco BW maven Plugin. That are specific with maven configuration things. In above logs also, I can see you are facing issue with Internet connectivity. When you run any maven goal for the first time, it downloads all the required dependencies from maven central repository if they are not present in to your local .m2 repository. If you are using proxy then it's obvious that you need to add proxy details in settings.xml. You can refer https://developers.perfectomobile.com/pages/viewpage.action?pageId=31103886 to add proxy details in settings.xml. This is Maven Configuration. Let us know if you face issue after adding proxy details as well.

**Comment by transferobject** [comment]
@SujataDarekar thanks for your response. i can't find settings.xml in .m2 folder. can you upload settings.xml here?

also, once i update the settings.xml with proxy info, in TIBCO business studio, where i need to reference it?

**Comment by SujataDarekar** [comment]
@transferobject You can refer http://maven.apache.org/settings.html to create settings.xml into your .m2 repository. Also you can google it to download sample settings.xml. In eclipse the refernce is already mentioned in Eclipse -> Preferences -> Maven -> User Settings. Also you add it in "User setting" while running the goal

**Comment by transferobject** [comment]
@SujataDarekar I got the settings.xml from apache-maven-3.5.3/conf. I copied it into .m2 directory and modified it with proxy info. attached file (please note, for privacy, i removed the actual proxy info and uploaded that file here).

the proxy server we are using, it doesn't require any username password so i removed those parameters. i am not sure about nonProxyHosts so i kept some valule.

i run this again but didn't work. do you know anyone who is using proxy to connect to internet?

for now, what i did it is that, on personal laptop at home, which doesn't require proxy, i run the maven goal in TIBCO Studio and it was able to download the required files from internet and able to generate EAR successfully. After that,  i copied .m2 folder from my personal laptop to my company laptop and it able to generate EAR file for same sample project. Till this point, i was playing with the sample TIBCO project.

now i try the actual project which use custom JMS driver to connect to TIBCO EMS. in my company we use custom jar file to connect to TIBCO EMS. Thiis project works and generate EAR file directly but i convereted to maven project and run maven build goal option, it shows error (attached file). Please note that, i run the same maven converted project at my company laptop and personal laptop and got the same error










![class AbstractJMSProvider](https://user-images.githubusercontent.com/26683529/81729585-35df1000-945a-11ea-965f-2ce911bdec35.png)
[class AbstractJMSProvider.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4617624/class.AbstractJMSProvider.txt)

[settings.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4617629/settings.zip)

**Comment by SujataDarekar** [comment]
@transferobject Please follow the below steps to include  Custom JMS Provider Jar in EAR:

1.Add the POM in Custom plugin with Manifest import bundles as a dependency with "provided" scope in POM.xml. Please check attached POM for reference.
[pom.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4621126/pom.zip)

2.Before adding the dependency in pom.xml , install those in .m2 repository using following command:

mvn install:install-file -Dfile= -DgroupId= -DartifactId= -Dversion= -Dpackaging=
example:
mvn install:install-file -Dfile=C:\TIBCO_INSTALLER\BW6\BW6.6.0V39\bw\6.6\system\shared\com.tibco.bw.sharedresource.jms.runtime_6.5.200.025.jar -DgroupId=com.tibco.bw.sr.jms.runtime -DartifactId=com.tibco.bw.sharedresource.jms.runtime -Dversion=6.5.200.025 -Dpackaging=jar


3. Install the custom plugin using the "install" goal.
4. Add the dependency of Custom plugin in the application POM and run the "package" goal.

**Comment by transferobject** [comment]
@SujataDarekar thanks for all the details. 

1. I don't know how to perform this step. can you please elaborate on this? should I add the reference pom under com.tibco.custom.jms.provider (see screenshot)? if you see, there is already pom.xml file. attached com.tibco.custom.jms.provider_pom

I have updated reference pom with the jar info version. i don't know org.eclipse.osgi version and can't find it on my system. can you please check if its correct? what text i need to put for "Manifest import bundles as a dependency with "provided" scope."attached reference_pom

2. for my system, I have below version. can i run this command from any directory or i should be in .m2 directory?

mvn install:install-file -Dfile=C:\tibcobw6\bw\6.5\system\shared\com.tibco.bw.sharedresource.jms.runtime_6.5.100.005.jar -DgroupId=com.tibco.bw.sr.jms.runtime -DartifactId=com.tibco.bw.sharedresource.jms.runtime -Dversion=6.5.100.005 -Dpackaging=jar

3. should I run this step using TIBCO BW studio - maven build - configuration window?

4. attached is the application POM. can you please let me know what I should add in this file application_pom



![com tibco custom jms provider_pom](https://user-images.githubusercontent.com/26683529/81850917-ab181700-9526-11ea-8fea-bce0e96f6a5c.PNG)







[com.tibco.custom.jms.provider_pom.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4623935/com.tibco.custom.jms.provider_pom.zip)

[reference_pom.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4623941/reference_pom.zip)


[application_pom.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4623952/application_pom.zip)

**Comment by SujataDarekar** [comment]
@transferobject Attach your manifest file of Custom JMS provider bundle

**Comment by transferobject** [comment]
@SujataDarekar I have attached the test project. I have removed the company related jar file and jms connection/db connection info so you may see broken link.

Please update this project and let me know which file(s) you have updated and reupload the project. i will make the same changes on my side.

[project1.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4628787/project1.zip)

**Comment by SujataDarekar** [comment]
@transferobject PFA WordPad doc and reference POM to include Custom JMS provider plugin into application EAR

[CustomJMSPlugin.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4642524/CustomJMSPlugin.zip)

**Comment by transferobject** [comment]
@SujataDarekar  thank you for all the details. appreciate it.

in my screenshot, i will refer right side for import package and left side for copy jar path [Plug-in Dependencies]

these are import packages:

com.tibco.bw.sharedresource.trinity.ssl.client.runtime;version="6.4.100",
com.tibco.bw.sr.jms.runtime.api.custom;version="6.4.100",
com.tibco.bw.sr.jms.runtime.api;version="6.4.100",
javax.jms;version="[1.1.0,3.0.0)",
org.osgi.framework;version="[1.6.0,2.0.0)"

as per your doc, from left side, i have to copy the path for each of the above import packages and run mvn install command. i have done for this one com.tibco.bw.sharedresource.trinity.ssl.client.runtime

i have done the copy path and run mvn install for below package as well, 
com.tibco.bw.sr.jms.runtime.api.custom
 com.tibco.bw.sr.jms.runtime.api
which is under C:\tibcobw6\bw\6.5\system\shared\com.tibco.bw.sharedresource.jms.runtime_6.5.100.005.jar 


**My questions are for these packages:** 
 javax.jms;version
 org.osgi.framework


 javax.jms;version - this one is under C:\tibcobw6\bw\6.5\system\shared\com.tibco.tpcl.javax.jms_2.0.0.002\jms-2.0.jar

 org.osgi.framework - this one is under C:\tibcobw6\bw\6.5\system\lib\common\org.eclipse.osgi_3.10.1.v20140909-1633.jar

my question is for mvn install command what will be the  below info for above two packages

Group Id: 
Artifact Id: 
Version: 




![Plug-in-Dep_ImportPackage](https://user-images.githubusercontent.com/26683529/82360489-7baa5400-99d7-11ea-85b8-bf8a572dc05c.png)

**Comment by SujataDarekar** [comment]
@transferobject You can provide it at your own. The only thing is that you need to use same group ID,Artifact Id and version while adding the dependency.
For example:
For C:\tibcobw6\bw\6.5\system\shared\com.tibco.tpcl.javax.jms_2.0.0.002\jms-2.0.jar
Group Id: com.tibco.tpcl
Artifact Id: javax.jms
Version:2.0

For "C:\tibcobw6\bw\6.5\system\lib\common\org.eclipse.osgi_3.10.1.v20140909-1633.jar"
Group Id: com.tibco.bw
Artifact Id: org.eclipse.osgi
Version:2.0.0

**Comment by transferobject** [comment]
@SujataDarekar thanks 

so if i understand correctly, for these three parameters (Group Id, Artifact Id, Version), it should not match the jar file version and its package information ?

**can you please fill out below mvn install parameters for those two examples**


mvn install:install-file -Dfile=C:\tibcobw6\bw\6.5\system\shared\com.tibco.tpcl.javax.jms_2.0.0.002\jms-2.0.jar -DgroupId=? -DartifactId=? -Dversion=? -Dpackaging=jar


mvn install:install-file -Dfile=C:\tibcobw6\bw\6.5\system\lib\common\org.eclipse.osgi_3.10.1.v20140909-1633.jar -DgroupId=? -DartifactId=? -Dversion=? -Dpackaging=jar


**Also, can you check if the below one correct?**

For "C:\tibcobw6\bw\6.5\system\hotfix\shared\com.tibco.bw.sharedresource.jms.runtime_6.5.102.003.jar"
Group Id: com.tibco.bw
Artifact Id: com.tibco.bw.sharedresource.jms.runtime
Version:6.5.102.003

mvn install:install-file -Dfile=C:\tibcobw6\bw\6.5\system\hotfix\shared\com.tibco.bw.sharedresource.jms.runtime_6.5.102.003.jar -DgroupId=com.tibco.bw -DartifactId=com.tibco.bw.sharedresource.jms.runtime -Dversion=6.5.102.003 -Dpackaging=jar

**Comment by transferobject** [comment]
@SujataDarekar i didn't get the response from you so i put together the info.

from your doc, i run the below steps. Step 6 has failed

5. Repeate the step1-4, for  all packages present in "Import-Package" section of MANIFEST.MF
(attached mvn_install_add_dependencies.txt)

6. Right click on "Custom JMS provider" plugin and select "Run As -> Maven install" option. This will install plugin  to .m2 repository
(attached failed logs from tibco bw studio. RunAs__MavenInstall.txt)



[mvn_install_add_dependencies.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4664149/mvn_install_add_dependencies.txt)
[RunAs__MavenInstall.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4664150/RunAs__MavenInstall.txt)

**Comment by SujataDarekar** [comment]
@transferobject Can you check com.tibco.bw.sharedresource.jms.runtime_6.5.102.003.jar get installed properly or not in .m2?

**Comment by transferobject** [comment]
@SujataDarekar command runs successfully. screenshot shows it installed in .m2

C:\tibcobw6\bw\6.5\system\shared>mvn install:install-file -Dfile=C:\tibcobw6\bw\6.5\system\hotfix\shared\com.tibco.bw.sharedresource.jms.runtime_6.5.102.003.jar -DgroupId=com.tibco.bw -DartifactId=com.tibco.bw.sharedresource.jms.runtime -Dversion=6.5.102.003 -Dpackaging=jar
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-install-plugin:2.4:install-file (default-cli) @ standalone-pom ---
[INFO] Installing C:\tibcobw6\bw\6.5\system\hotfix\shared\com.tibco.bw.sharedresource.jms.runtime_6.5.102.003.jar to C:\Users\mm\.m2\repository\com\tibco\bw\com.tibco.bw.sharedresource.jms.runtime\6.5.102.003\com.tibco.bw.sharedresource.jms.runtime-6.5.102.003.jar
[INFO] Installing C:\Users\mm\AppData\Local\Temp\mvninstall8881357337511399471.pom to C:\Users\mm\.m2\repository\com\tibco\bw\com.tibco.bw.sharedresource.jms.runtime\6.5.102.003\com.tibco.bw.sharedresource.jms.runtime-6.5.102.003.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.034 s
[INFO] Finished at: 2020-05-19T13:20:18-04:00
[INFO] ------------------------------------------------------------------------
![Untitled](https://user-images.githubusercontent.com/26683529/82690290-ec48af00-9c29-11ea-9dc2-e05bc83cc8bd.png)

**Comment by transferobject** [comment]
@SujataDarekar hello, please let me know how to resolve this..

**Comment by SujataDarekar** [comment]
@transferobject Can you try to run it using cmd? Open the command prompt from the location where the custom jms provider is present. In your case it's  " C:/Users/mm/workspace-new/com.tibco.custom.jms.provider" as per the attached file. run "mvn clean install" goal

**Comment by transferobject** [comment]
@SujataDarekar command is failed. attached is the completed output
[mvn_clean_install.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4682052/mvn_clean_install.txt)

**Comment by SujataDarekar** [comment]
@transferobject Can you share me the pom.xml for Custom JMS provider?

**Comment by transferobject** [comment]
@SujataDarekar I've attached pom.xml from this location

C:\Users\mm\workspace-new\com.tibco.custom.jms.provider

if i open that pom.xml file in tibco bw studio, and click on Effective POM tab at the bottom (attached screenshot), it has more info (i copy paste that info in attached Effective POM file)

[pom.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4682504/pom.zip)


[EffectivePOM.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4682508/EffectivePOM.zip)

**Comment by SujataDarekar** [comment]
@transferobject As I already mentioned in Doc, you need to add all those dependency in POM which you have installed. However I can see you have added only one dependency in POM which is "com.tibco.bw.sharedresource.trinity.ssl.client.runtime". Also in I am not sure why the <parent> section is added in your POM? I already shared the reference POM with you

**Comment by transferobject** [comment]
@SujataDarekar i've followed your doc step by step and added all those dependencies. i am not sure why its not showing in pom.xml. can we have a zoom meeting pls?

**Comment by SujataDarekar** [comment]
@transferobject Can you please raise the Tibco support request for this?  Please mention all the Github issue id and details in Support request. So that Support representative will reach to me and then we will have a zoom call for the same.

**Comment by transferobject** [comment]
@SujataDarekar i raise a request and here is the case number Case_ID:01868641

**Comment by SujataDarekar** [comment]
@transferobject Thanks ! Will  get back to you.
