### ISSUE TITLE
Execute bwdesign utility using maven goal to Validate BW Project and Generate Process Diagram

### ISSUE THREAD

**Issue by SujataDarekar** [TIBCOSoftware/bw6-plugin-maven#437]
Execute bwdesign utility using maven goal which will perform the following steps:

1. validate the BW Module and application project

2. Generate Process diagram

**Comment by SujataDarekar** [comment]
Please refer https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/Running-BW-Design-Utility-Goal for more details

**Comment by MoSehsah** [comment]
can this be using to execute other bwdesign commands as well ?

**Comment by SujataDarekar** [comment]
@MoSehsah As mentioned in doc https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/Running-BW-Design-Utility-Goal , this support only "Validate BW Project" and "Generate Process Diagram" commands.

**Comment by mismanko** [comment]
Does this work also for Linux? I get following error: ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.7.0:bwdesignUtility (default-cli) on project facade.vpnccs.app: Cannot run program "/opt/tibbwce/bwce/2.5//bin//bwdesign.exe" (in directory "/opt/tibbwce/bwce/2.5/bin"): error=2, No such file or directory -> [Help 1]

I do not like the ".exe" so I this is the reason why I am asking.

**Comment by bibhuduttaGitHub** [comment]
> Does this work also for Linux? I get following error: ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.7.0:bwdesignUtility (default-cli) on project facade.vpnccs.app: Cannot run program "/opt/tibbwce/bwce/2.5//bin//bwdesign.exe" (in directory "/opt/tibbwce/bwce/2.5/bin"): error=2, No such file or directory -> [Help 1]
> 
> I do not like the ".exe" so I this is the reason why I am asking.

@SujataDarekar  and @vpawar-tibco  : this is a valid question. Most of the time the build servers are the linux servers. When we execute the bwdesignutility through maven goals on the linux server, it always ask for the .exe, which is not the case for linux server.  Can you address this or let us know if any work around available?

**Comment by vpawar-tibco** [comment]
@bibhuduttaGitHub It is fixed in version 2.7.1 onwards.
