### ISSUE TITLE
can somone upload .m2 directory and maven directory

### ISSUE THREAD

**Issue by transferobject** [TIBCOSoftware/bw6-plugin-maven#441]
Hello,

On my windows 10 laptop, I am using TIBCO BW 6.5.1. I have installed TIBCO Maven plugin 2.3.1.

I have encounter so many issues and have not received any resolution yet from this forum. 

if someone successfully installed the TIBCO maven plugin 2.3.1 and able to convert the TIBCO BW project into maven project and able to generate EAR file, please share c:\Users\<username>\.m2 folder and C:\tibcobw6\bw\6.5\maven folder. I only need those specific folders (.m2 and maven) from those specific location. I would like to copy the same on my laptop and see if I can get through this ordeal.

**Comment by SujataDarekar** [comment]
@transferobject  As already mentioned on wiki pages, please install Apache Maven Plugin on your machine.After that  Install BW Maven Plugin on your BW tibco home which will create the maven folder into your tibco home also at your .m2 repository as well. When you will run any goal on project then it will download all required dependencies into your .m2 local repository
