### ISSUE TITLE
maven build ears for all projects in GitLab branch

### ISSUE THREAD

**Issue by mail1anshul** [TIBCOSoftware/bw6-plugin-maven#442]
in my GitLab branch, I have around 50 TIBCO 6.4.2 projects. Many projects share same sharedModule. When I create POM.xml for these 50 projects from BW studio, then every time POM.xml of sharedModules gets over written with current parent project. So in this case POM.xml in any sharedModule becomes common for all projects (which are having dependency of this sharedModule).

Now I have requirement to build all 50 ears in one build. but I am facing a duplication issue.

[ERROR] [ERROR] Project 'com.tibco.bw:CommonFramework:1.0.0-SNAPSHOT' is duplicated in the reactor @ 
[ERROR] Project 'com.tibco.bw:CommonFramework:1.0.0-SNAPSHOT' is duplicated in the reactor -> [Help 1] 
[ERROR] 

while doing maven build, I am using a master POM.xml which has details of all 50 services in modules. attached is my master POM.xml
[pom.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4540059/pom.zip)

can someone help here?

**Comment by SujataDarekar** [comment]
@mail1anshul You can use following steps to add dependency of your shared module in to the Module project POM:
1. Right Click on Shared Module and select " Generate POM " option to generate separate POM for Shared Module.
2. Install that shared Module using "Install"  goal
3. Add the dependency of Shared Module in Module POM
In this way you can use Single shared module for different projects
