### ISSUE TITLE
External dependencies should be added in osgi.bundles (config.ini)

### ISSUE THREAD

**Issue by cmocanu1** [TIBCOSoftware/bw6-plugin-maven#444]
Maven Plugin version: 2.6.0
Maven version: 3.6.1
Product : TIBCO ActiveMatrix Businessworks 6.6 HF002 or HF003
Component: Maven build plugin

**Context:**
1. Each shared module have own life-cycle (is a separate git project, have own jenkins build job, is deployed in artifactory);
2. At development time, shared module is imported in workspace
3. At build time, each shared module is added in application pom.xml as dependency (as a regular jar) pointing to Artifactory coordonates and remove the corresponding line from <modules>;
4. When build is produces, the shared modules are included in ear as normal 

**Steps to reproduce the issue:**
1. create a share module having a small schema file;
2. create an application which depends on shared module and use the schema from shared module;
3. build shared module independent and publish in local maven (mvn clean package install);
4. modify application pom.xml and add a dependency to jar created at step 3;
5. modify parent pom.xml and remove from <modules> the entry referring to shared module;
6. add an assert in application process
2. run tests (at build time) on application 

**Describe the results you received:**
I receive Unresolved requirement: Require-Capability: com.tibco.bw.module; filter:="(&(name=https-connection-library)(version=1.0.0))"

**Describe the results you expected:**
To resolve the dependency and run the unit tests.

**How to solve the problem:**
in java file: Source\bw6-maven-plugin\src\main\java\com\tibco\bw\maven\plugin\test\setuplocal\ConfigFileGenerator.java, at line 43, add following lines:
`for( MavenProject project : projects ) {
	if (project.getPackaging().equals("bwmodule") || project.getPackaging().equals("bwear")) {
		Set<Artifact> artifacts = project.getDependencyArtifacts();
		for(Artifact artifact:artifacts) {
			if(!"provided".equals(artifact.getScope())) {
				builder.append( "," );
				addReference(builder, artifact.getFile(), artifact.getArtifactId());
			}
		}
	}
}`

**Comment by SujataDarekar** [comment]
@cmocanu1 Can you share the sample use case to reproduce the issue ? I saw your pull request. If you have sample use case already, then attach it as well.

**Comment by cmocanu1** [comment]
Hello,

Please find below the steps to reproduce the issue:

1. install a shared module in maven local repository using command: mvn install:install-file -Dfile=
[logging-library-1.0.0.jar](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4626328/logging-library-1.0.0.zip) -DgroupId=ro.raiffeisen.mw.libs -DartifactId=logging-library -Dversion=1.0.0 -Dpackaging=jar
2. unzip [unit-testing-sample.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4626341/unit-testing-sample.zip) into a empty folder and run: mvn clean initialize package -f unit-test-1.parent\pom.xml
3. with bw6-plugin-maven 2.6.0 you will obtain error: `Unresolved requirement: Require-Capability: com.tibco.bw.module; filter:="(&(name=logging-library)(version=1.0.0))"`
4. with my proposed changes (in this issue or pull request) the bw node is started successfully and the unit tests are run (in attached project, the one of a unit-test is failing but is expected).

Thank you

**Comment by awagle** [comment]
Pull request #455 is merged into master.
