### ISSUE TITLE
does maven deploy using bwinstall changes any of running Appspace or Appnode properties

### ISSUE THREAD

**Issue by sonuschinnatech** [TIBCOSoftware/bw6-plugin-maven#452]
Does maven bw6mavenplugin deploy using bwinstall changes any of running Appspace or Appnode properties. 

Reason for question : I see bwinstall changing timestamp of existing bw6 appnode & appspace config files like ini or tra files.

do we have any other command other than bwinstall for deployment in TIBCO BW6.

Regards,
Sonu

**Comment by sonuschinnatech** [comment]
Please help to reply

**Comment by sonuschinnatech** [comment]
Please someone provide input on this.

**Comment by HiteshNembhwani** [comment]
@sonuschinnatech not sure what's your exact query but yes deploy command under the covers might need to access the ini or config files during the deployment and that's the reason you see the timestamp change. How does that affect your application lifecycle? Could you please explain your use-case properly? Thanks!

**Comment by sonuschinnatech** [comment]
Hi Hitesh,
My question is, when it is changing time stamp, does it also change any existing properties in config.ini or tra files in BW6 end. Let’s say I set memory as 2gb, ft properties or hma properties or some other properties. Does these proprties have any impact or change.


Also, second question,
While using BWinstall maven command, when we give wrong node name, it is creating that. How to avoid creation  of new node using bwinstall command when we give wrong node name.

Regards,
Sonu

**Comment by HiteshNembhwani** [comment]
1. it only reads the files and does not change any user driven properties. No impact to the properties you called out. 
2. could you share the syntax of the bwinstall command you're using? when you say node name, do you mean appnode here?

**Comment by sonuschinnatech** [comment]
Hi Hitesh,
Please help to update below query.

Regards,
Sonu

**Comment by HiteshNembhwani** [comment]
@sonuschinnatech  yes, per the current behavior, this command will create the appnode if it doesn't exist. We can evaluate as an enhancement to have a flag to let the user decide if they want to create the appnode or not.. cc @SujataDarekar

**Comment by sonuschinnatech** [comment]
Not only node..it creates domain also if wrong domain name supplied...I feel it shouldn’t touch node & domain things when we are doing application deployments.

Regards,
Sonu

**Comment by HiteshNembhwani** [comment]
@sonuschinnatech fair expectation but it also expects the user to know the right domain/appspace/appnode names during the deployments. Only users who have access to do these application deployments should carefully trigger these commands via a scripted approach. In your use-case, are the wrong names supplied accidentally?

**Comment by sonuschinnatech** [comment]
Yes. By mistake we triggered once with wrong domain name. Surprised to see new domain created with app space/node creation & application deployed.

Regards,
Sonu

**Comment by HiteshNembhwani** [comment]
thanks @sonuschinnatech - let us discuss internally and get back when we have further updates to share.

**Comment by sonuschinnatech** [comment]
Thanks for the information

**Comment by SujataDarekar** [comment]
Closing this issue since we have created the enhancement #458 - Provide property based way to create domain/appspace/appnode in case it does not exist
