### ISSUE TITLE
how to add removeunused argument to maven command

### ISSUE THREAD

**Issue by veerareddyakkili** [TIBCOSoftware/bw6-plugin-maven#455]
Maven Plugin version:

Maven version:

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version:

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1.
2.
3.

**Additional environment details if any:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by veerareddyakkili** [comment]
when creating ear,am trying not to include unused rerouceres. tried with below commands
 mvn clean package -Dremoveunused=true
 mvn clean package -Dremoveunused
Still its adding unused resources to ear file.

**Comment by SujataDarekar** [comment]
@veerareddyakkili We don't provide any property to not include unused resources. The only way is that manually you need to deselect the unused resources from "Binary Build" section of build.properties whereas build.properties is present in module project

**Comment by awagle** [comment]
This is not supported yet but you can add it by adding any bwdesign command you want to https://github.com/TIBCOSoftware/bw6-plugin-maven/blob/master/Source/bw6-maven-plugin/src/main/java/com/tibco/bw/maven/plugin/process/BWDesignUtilityExecutorMojo.java just like we have validateProject() and generate process diagrams.
