### ISSUE TITLE
Provide property based way to create domain/appspace/appnode in case it does not exist

### ISSUE THREAD

**Issue by SujataDarekar** [TIBCOSoftware/bw6-plugin-maven#458]
To provide a flag to decide to create a new domain/appspace/appnode or to throw an error in case it doesn't exist

**Comment by sonuschinnatech** [comment]
Thanks for listening to my comments & enhancing it.  Thanks for the support.


Regards,
Sonu

**Comment by SujataDarekar** [comment]
@sonuschinnatech The changes will be available in next Maven Release and yes you need to install it.
