### ISSUE TITLE
Question: Plugin dependencies

### ISSUE THREAD

**Issue by AndreAfonso87** [TIBCOSoftware/bw6-plugin-maven#459]
Maven Plugin version: 2.4.0

Maven version: 3.6.3

Product : TIBCO Businessworks Container edition

Product version: 2.5.0

Component: Maven build plugin

**Steps to reproduce the issue:**
1. Application with java code that depends on plugin classes, for example javax.jms or com.tibco.tibjms
2. Java import dependencies added as plugin dependencies
3. Execute mvn package on application module

**Describe the results you received:**
The build fails for missing classes on the Plugin Dependency, for example:
[ERROR] /C:/work/git/projects/fixml-cme-adapter/fixml-cme-adapter.module/src/main/jms/CustomJms.java:[48,65] package com.tibco.tibjms does not exist
[ERROR] /C:/work/git/projects/fixml-cme-adapter/fixml-cme-adapter.module/src/main/jms/CustomJms.java:[73,26] cannot find symbol
[ERROR]   symbol:   class TibjmsAdminException
[ERROR]   location: class main.jms.CustomJms

**Describe the results you expected:**
Expected that the module plugins would be retrieved from the installation directory, used for compilation using maven.

Do i need to shift all dependencies from plugin dependencies to maven dependencies, even though these dependencies are tibco classes and should be present in the base image?

**Comment by SujataDarekar** [comment]
@AndreAfonso87 Yes you need to install plugin dependencies to maven dependencies and need to add it in pom with "provided" scope.
