### ISSUE TITLE
Capability to provide agent username & password for secured BWAgent

### ISSUE THREAD

**Issue by RajibBiswasTibco** [TIBCOSoftware/bw6-plugin-maven#46]
For deployment of BW applications, if the BW Agent is secured, then there is no way to provide the agent username and password in the current maven plugin. Provide capability to give agent username & password for secured BWAgent for deployment.

**Comment by Tantino** [comment]
Hi @RajibBiswasTibco 
How can the bwagent configurate with authetificaion?
I am trying to configutarate the bwagent and I can not use authetification.

Thanks and regards.

**Comment by Tantino** [comment]
please review the class :
RemoteDeployer
BWEARInstallerMojo.java

**Comment by Tantino** [comment]
New Pull request. Please review!!

**Comment by RajibBiswasTibco** [comment]
This enhancement has been implemented and will be available after the next release.
