### ISSUE TITLE
Maven test throwing error with Unit testing assertion 

### ISSUE THREAD

**Issue by senthilalagesan** [TIBCOSoftware/bw6-plugin-maven#461]
Hi Team, 

We are facing issues while running the maven test for the attached project in the client network (inside VDI) . Have attached the debug log with the mail. 

Note : We were able to execute the same sample project successfully outside the client network/VDI. 

Regards,
Senthil

**Comment by senthilalagesan** [comment]
Added the maven debug log. 
[Maven-test-debug-error.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4712617/Maven-test-debug-error.zip)

**Comment by SujataDarekar** [comment]
@senthilalagesan  Looks like there is OSGI bundle  starting issue. Are you able to run/debug the same BW application(without unit testing) in the client network?
Also could you please attach the use case/sample project?

**Comment by senthilalagesan** [comment]
@SujataDarekar Yes, we are able run the application in debug mode without any issues .  
Have attached logs and the sample project used for this.  

[UnitTestingDemo.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4717831/UnitTestingDemo.zip)

[DebugMode-Logs.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4717837/DebugMode-Logs.zip)

**Comment by SujataDarekar** [comment]
@senthilalagesan Can you check if the config.ini file is present or not. It's getting generated at the the system path  System.getProperty( "java.io.tmpdir" )/bwconfig. So you can check the value of system property "java.io.tmpdir" for the specific machine and check for the config.ini file when you will get error while running the test goal.

**Comment by senthilalagesan** [comment]
@SujataDarekar : I can see config.ini file in the _java.io.tmpdir_ location mentioned in the allProperties,properties file . 

Attaching the config.ini for reference. 

[config.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4734127/config.zip)

**Comment by SujataDarekar** [comment]
@senthilalagesan I have checked the config file and I didn't see any loophole in that. Also the project which you have attached is also working fine at my end. So can you help us to replicate the issue so that we can find out the root cause?

**Comment by senthilalagesan** [comment]
@SujataDarekar : I'm seeing this error only in the client VDI  and as you mentioned, it works fine for me too outside the client n/w, hence i attached the debug enabled error log for reference.   
Let's me when you are available for a working session, so that i can do a screen share and show the issue.

**Comment by senthilalagesan** [comment]
@SujataDarekar  : Also if you can let us know on whether the runtime code is trying to connect to any external URL over the internet and if so, the details, will be able to check with the cyber security team on relaxing the firewall setting in the client network.

**Comment by SujataDarekar** [comment]
@senthilalagesan The issue is coming while starting the bw engine and we do not connect to any external URL while starting the engine. One thing may be you can try is  changing engine debug port. Default debug port is 8090

**Comment by senthilalagesan** [comment]
@SujataDarekar  As discussed in yesterday night working session, if the TIBCO_HOME is outside the user home directory, we could execute the Maven Test goal with assertions successful. But i tried creating test cases and assertions for another GMF project with the same TIBCO_HOME setup and we started getting the same OSGI bundle activation error again . Even the first sample project which we were able to successfully execute started throwing the error now.  

I tried executing both the projects by deleting the  java.io.tmpdir , but no luck. 

Could you please check in the java api and try to identify, which argument is NULL ?

**Comment by senthilalagesan** [comment]
@SujataDarekar - Re installing the tibco suite outside the user home directory in the client network, solved the issue .

**Comment by senthilalagesan** [comment]
@SujataDarekar - Re installing the tibco suite outside the user home directory in the client network, solved the issue .
