### ISSUE TITLE
Missing bundle with maven build

### ISSUE THREAD

**Issue by dmassimi** [TIBCOSoftware/bw6-plugin-maven#462]
Hi,when I try to build application with maven but a common_xpath shared module is not added in the ear (with studio yes).

Attached you can find:
- ear generated with maven (testapp.application_1.0.1.ear)
- ear generated with studio (testapp.application_1.0.0.ear)
- zip with all projects (module,application,parent, common_xpath functions)

**Please help me to understand why the behavior between Maven and Studio is different. Maybe something is wrong in pom files?**

[testapp.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4731565/testapp.zip)
[ear.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4731569/ear.zip)

Maven Plugin version: 2.6.0
Maven version: 3.6.1
Product : TIBCO Businessworks Container edition
Product version: 2.5.2
Component: Maven build plugin

Regards

**Comment by dmassimi** [comment]
Hi, any news on this ?
I need to understand the issue (or my wrong configuration) quickly cause we need to use plugin in a customer project.

**Comment by awagle** [comment]
The modules section in the POM file of  parent project do not have the entry of the custom XPAth functions. Adding the entry will solve the issue

` <modules>
    <module>../testapp</module>
    <module>../testapp.application</module>
   <module>../bw.core_common.xpath</module>
  </modules>`

Please try this and let us know.

**Comment by dmassimi** [comment]
Hi,
sorry but I don't understand why I've to modify the parent pom to add a dependency of bw module.
In bw module pom I've this:

	<dependencies>
		<dependency>
			<groupId>com.tibco.plugins</groupId>
			<artifactId>com.tibco.bw.palette.shared</artifactId>
			<version>6.1.100</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.tibcopsg.esb.framework</groupId>
			<artifactId>bw.core_common_kafka.sharedmodule</artifactId>
			<version>2.0.3-SNAPSHOT</version>
			<type>bwmodule</type>
		</dependency>
		<dependency>
			<groupId>com.tibcopsg.esb.framework</groupId>
			<artifactId>bw.core_common.xpath</artifactId>
			<version>2.0.3-SNAPSHOT</version>
			<type>bwmodule</type>
		</dependency>
	</dependencies>	

and in my parent pom i've this:

	<modules>
		<module>../bw.mc-genapp</module>
		<module>../bw.mc-genapp.application</module>
	</modules>

Why at the end the EAR (bw.mc-genapp.application) contains bw.core_common_kafka.sharedmodule but not bw.core_common.xpath ?

![image](https://user-images.githubusercontent.com/31727023/89187071-034a3c80-d59d-11ea-9d83-f90c94257937.png)

**Comment by awagle** [comment]
This is as per design of Maven multi module projects. Parent POM's must
have all the dependencies defined (

Regards,

*Aditya Wagle *|  *O*  +91 20 71303035

*TIBCO Software Inc.* |  Pune, India

[image: www.tibco.com] <http://www.tibco.com>

The information transmitted in this electronic communication is intended
only for the person or entity to whom it is addressed and may contain
confidential and/or privileged material. Any review, re-transmission,
dissemination or other use of or taking of any action in reliance upon this
information by persons or entities other than the intended recipient is
prohibited.

**Comment by dmassimi** [comment]
Hi,
ok but why bw.core_common_kafka.sharedmodule is in final ear and bw.core_common.xpath not.
Both are not in parent pom.

Regards

**Comment by dmassimi** [comment]
Hi I've solved adding dependencies in application pom (not in module).
With this action the ear is built and it works.

Regards

**Comment by shashank-v-kumar** [comment]
Hi @dmassimi, I'm also facing the same issue while mavenizing my BW application. Can you please explain the solution that worked for you?

Thanks

**Comment by dmassimi** [comment]
Hi, I've just added the dependencies in application pom (instead of module pom).

**Comment by dmassimi** [comment]
@shashank-v-kumar exactly.
