### ISSUE TITLE
maven build failing with package com.tibco.security does not exist

### ISSUE THREAD

**Issue by nagoriyn** [TIBCOSoftware/bw6-plugin-maven#463]
Maven Plugin version: TIB_BW_Maven_Plugin_2.3.1

Maven version: apache-maven-3.6.3

Product : Either of TIBCO ActiveMatrix Businessworks 6 

Product version: 6.5.1

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1. build project using maven.

**Additional environment details if any:**

**Describe the results you received:**
Compilation failure:
[ERROR] /C:/Code/BW6/MyWorkspace/zb-file-watch-utility/zb-file-watch-utility/src/Services/Process/FTPMonitoringAlertOperation/pwdDecryptor.java:[2,26] package com.tibco.security does not exist
[ERROR] /C:/Code/BW6/MyWorkspace/zb-file-watch-utility/zb-file-watch-utility/src/Services/Process/FTPMonitoringAlertOperation/pwdDecryptor.java:[28,25] cannot find symbol
[ERROR] symbol: variable ObfuscationEngine
[ERROR] location: class Services.Process.FTPMonitoringAlertOperation.pwdDecryptor

**Describe the results you expected:**
the package should be build successfully

**Additional information you deem important (e.g. issue happens only occasionally):**
The deployemnt is failing with maven only, I deployed the through studion and it deplyed and running successfully in dev.

**Comment by nagoriyn** [comment]
below is my code location. 
https://github.com/zbintegration/tibco-file-watch-utility/tree/nagoriya

**Comment by awagle** [comment]
The repository is a private repo please provide access. com.tibco.security is not a public API and any use of the ObfuscationEngine class is in violation of the License agreement. Please reopen by removing the private API and attaching a reproducible project + source code in private repository.
