### ISSUE TITLE
Shared module in bw/6.6/system/hotfix/shared/ is not loadded

### ISSUE THREAD

**Issue by cmocanu1** [TIBCOSoftware/bw6-plugin-maven#464]
Hello,

First of all, I opened this issue at TIBCO Support (case number: 01862783) and the resolution was: ".qualifier is a mandatory for the bundle version in BW"

I created a shared module (which contains few schema used in all applications) and placed in bw/6.6/system/hotfix/shared/.
We build shared module using maven plugin and placed the resulting jar in bw/6.6/system/hotfix/shared/. Unfortunate, the shared module is not loaded unless in, shared module MANIFEST.MF, the value of Bundle-Version is in format: 1.0.0.qualifier.

We tried with Bundle-Version as 1.0.0 and 1.0.0.202004xxx without success.

Maven Plugin version: 2.6.0
Maven version: 3.6.1
Product : Either of TIBCO ActiveMatrix Businessworks 6
Product version: 6.5.1 HF2
Component: Maven build plugin

**Steps to reproduce the issue:**
1. Import tibco-support-shared-module.zip into a new workspace
2. build logging-library shared module (go to project folder and mvn clean package install)
3. build and run unit tests for unit-test-1 application (go to workspace folder and mvn clean package -f unit-test-1.parent\pom.xml). When unit tests runs I obtain error: Unresolved requirement: Require-Capability: com.tibco.bw.module; filter:="(&(name=logging-library)(version=1.0.0))"
4. copy logging-library\target\logging-library_1.0.0.jar to tibco\bw\6.6\system\hotfix\shared
[tibco-support-shared-module.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4750316/tibco-support-shared-module.zip)

5. build and run unit tests for unit-test-1 application (go to workspace folder and mvn clean package -f unit-test-1.parent\pom.xml). At this moment, it not complains about unresolved requirement but hangs and the application don't start (BW Application [unit-test-1:1.0] is impaired). Kill the lanched process using task manager.
6. I use 7-zip to modify MANIFEST.MF directly in tibco\bw\6.6\system\hotfix\shared\logging-library_1.0.0.jar and change from "Bundle-Version: 1.0.0" to "Bundle-Version: 1.0.0.qualifier"
7. build and run unit tests for unit-test-1 application (go to workspace folder and mvn clean package -f unit-test-1.parent\pom.xml). Now the unit tests are running ok.

**Describe the results you expected:**
step 5 to be a functional test and not to be needed the workaround from step 6.

**Comment by awagle** [comment]
The system folder is for system (product only). Shared modules should be included as a part of the application and bundled in the EAR file. Exporting shared modules as jars and having them load directly is not supported. For running unit tests shared module needs to be in the workspace or referenced from a maven repository.

**Comment by cmocanu1** [comment]
Hello,

The same problem hapens also when I run a unit test with a shared module referenced from maven repository! It is not loaded if the version do not ends with ".qualifier".

Please, reconsider this issue! I
