### ISSUE TITLE
How to import a shared module jar into workspace using Maven?

### ISSUE THREAD

**Issue by mismanko** [TIBCOSoftware/bw6-plugin-maven#468]
Java version: 1.8.0_241, Maven version: 3.6.3, BW6 Maven Plugin: 2.5.0 and we tried also 2.7.0, Tibco Business Studio version: 2.5.0, BWCE version: 2.5.1

We are not able to add a shared module from jar file into workspace. As we have added the shared module jar into dependencies within pom.xml, Maven is able to download it and we can see the jar within Maven Dependencies branch in Tibco Business Studio (local .m2 repository is used) but the project is not added into the workspace. We tested this also in clean workspace. This situation occurred, when version of jar was 1.0.0. Once we changed the version to 1.0.0-SNAPSHOT or 1.0.0.0 everything was fine, and modules were added into the workspace.

On the other hand, the same steps with version 1.0.0 are fine on different machines with the same versions and same source code. We have noticed, there was very similar problem described here (https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/349), but unfortunately without any solution.

Do you have any hint or solution for this situation please?

**Comment by awagle** [comment]
Please follow the steps on https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/SharedModule.
