### ISSUE TITLE
Plugin Installation with Success but not Completed

### ISSUE THREAD

**Issue by miguelrpenedo** [TIBCOSoftware/bw6-plugin-maven#471]
Maven Plugin version: 2.7.0

Maven version: 3.6.3

Product : TIBCO Businessworks Container edition

Product version: 2.5.3

Component: Maven Eclipse Plugin

**Steps to reproduce the issue:**
Run maven's install.bat (give TIBCO_HOME)

**Additional environment details if any:**
JAVA_HOME set to jdk 1.8

mvn -version in cmd shows the following:
Apache Maven 3.6.3
Maven home: C:\apache-maven-3.6.3\bin\..
Java version: 1.8.0_144, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_144\jre

**Describe the results you received:**
During the exec a lot of errors and instillation fails pop up regarding java version. 
![image](https://user-images.githubusercontent.com/67910341/86603972-aa3ab900-bf9c-11ea-95f2-82bb1f7edd85.png)

The result is "BUILD SUCCESSFUL"

Opening Studio, choosing an application > Right-Click: No "Generate POM" option appears.
In Window > Preferences there is no maven configurations.

**Describe the results you expected:**

"Generate POM" option and Maven Configurations available.

**Comment by awagle** [comment]
Can you also go to the Installation Details (under the Help Menu) and confirm that you see the maven plugin installed there

![image](https://user-images.githubusercontent.com/7453624/86700766-03532d00-c02f-11ea-80a9-b4057565ae3d.png)

**Comment by miguelrpenedo** [comment]
Hi awagle!
Thank you for the reply.

In Installation Details I don't have any maven plugin installed.
![image](https://user-images.githubusercontent.com/67910341/86740935-ecacd600-c02e-11ea-9cc4-7261f4687cb7.png)

**Comment by miguelrpenedo** [comment]
**SOLVED**

I uninstall the version I had of TIBCO CE and, with a new installer, created a new TIBCO_HOME.
Ran the maven installer and it worked.
Seems that the source of the problem was a bad bwce installation in the first place.

**Comment by awagle** [comment]
Thanks for confirming @miguelrpenedo
