### ISSUE TITLE
Issue executing test with goldenFile Test

### ISSUE THREAD

**Issue by alexandrev** [TIBCOSoftware/bw6-plugin-maven#472]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

Maven Plugin version: 2.7.0

Maven version: 3.3.3

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version: BWCE 2.5.2

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1. Import the project
2. Execute the mvn clean initialize site package
3. Check the error

**Additional environment details if any:**

**Describe the results you received:**

[INFO] Total time: 53.745 s
[INFO] Finished at: 2020-07-08T22:32:01+02:00
	at java.io.File.<init>(File.java:277)
	at com.tibco.bw.maven.plugin.test.helpers.TestFileParser.collectAssertions(TestFileParser.java:139)
	at com.tibco.bw.maven.plugin.test.rest.AssertionsLoader.loadAssertions(AssertionsLoader.java:61)
	at com.tibco.bw.maven.plugin.test.rest.BWTestRunner.runTestsPerModule(BWTestRunner.java:114)

**Describe the results you expected:**

To execute the tests

**Additional information you deem important (e.g. issue happens only occasionally):**

It seems is it not able to get the file, it seems the expression object is not well retrieved by the TestFileParser I've tried with different paths (absolute, relative, with the doc () without it, with file:/// with a simple file:// all the situations fails with the same issue.

Regards,

**Comment by alexandrev** [comment]
[TestTransformXML.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4893141/TestTransformXML.zip)
Code to reproduce the issue

**Comment by alexandrev** [comment]
[logs.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4893146/logs.txt)

**Comment by vpawar-ai** [comment]
@alexandrev Please change **testFilePath** mapping for mapper activity in **mapperError.bwp" to -

`doc('file:///C:/datos/workspace_bwce_2.5.3/HelloWorldDocker/HelloWorldDocker.module/Schemas/persona.xml')`

Use single quote instead of double quotes. We will add better error message in the next plugin release.

You will also need to fix mock ouput xml files. Please refer - https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/Steps-To-Add-MockOutput
