### ISSUE TITLE
com.tibco.plugins:bw6-maven-plugin:bwdesignUtility task is not working on Linux

### ISSUE THREAD

**Issue by cmocanu1** [TIBCOSoftware/bw6-plugin-maven#474]
Maven Plugin version: 2.7.0

Maven version: 3.6.1

Product : TIBCO ActiveMatrix Businessworks

Product version: 6.6.1

Component: Maven build plugin

**Steps to reproduce the issue:**
1. invoke task com.tibco.plugins:bw6-maven-plugin:bwdesignUtility for any project

**Comment by vpawar-ai** [comment]
Hi @cmocanu1, 

Please share debug logs and Linux operating system details. You can use `-X` flag.  
`mvn com.tibco.plugins:bw6-maven-plugin:bwdesignUtility -X`

**Comment by cmocanu1** [comment]
Hi @vpawar-ai ,

Seams are more problems. For example, the com.tibco.plugins:bw6-maven-plugin:bwdesignUtility doesn't work if is not ran in an existing Studio for Designers workspace. I'll prepare a pull request that will invoke a import task before running 'validate' and/or 'diagram:gen_diagrams' tasks.

PS: In Source/bw6-maven-plugin/src/main/java/com/tibco/bw/maven/plugin/process/BWDesignUtilityExecutorMojo.java, line 131 looks that invoke bwdesign.exe which available only on Windows platform.
