### ISSUE TITLE
Unable to debug Shared Modules processes in Debug Mode

### ISSUE THREAD

**Issue by nunotunes** [TIBCOSoftware/bw6-plugin-maven#483]
**Maven Plugin version:** 2.7.0

**Maven version:** 1.6.2

**Product :** TIBCO Businessworks Container edition

**Product version:** 2.5.3

**Component:** Maven build plugin

**Steps to reproduce the issue:**
Import shared modules with maven.

**Additional environment details if any:**
Windows 7

**Describe the results you received:**
We can't see detailed information about the activities present in Shared Module's processes, which were imported via Maven. The Input and Output activities are locked.
Furthermore, it's impossible to set a breakpoint in activities that belong to a Shared Module imported via Maven.

**Describe the results you expected:**
Despite the processes/resources present in Shared Modules imported via Maven are read-only, it should be possible to inspect all the info about them.
It should be possible to set breakpoints in processes belonged to Shared Modules imported via Maven.

**Additional information you deem important (e.g. issue happens only occasionally):**
Opened a Tibco Support's case with number 01883479. However, they re-directed me to here as the issue is related to plugin.

**Comment by vpawar-ai** [comment]
Hi @nunotunes the breakpoint is not supported for External shared modules as well. It is not specific to maven plugin. The JIRA ticket **AMBW-40868** has been created. Please ask tibco support to link it with your case. Thanks.
