### ISSUE TITLE
Run as Maven Install fails when performed on any Module in BW

### ISSUE THREAD

**Issue by BhosaleSaurabh** [TIBCOSoftware/bw6-plugin-maven#484]
Maven Plugin version:2.7.0

Maven version:

Product : Either of TIBCO ActiveMatrix Businessworks 6

Product version: 6.6.1

Component: Maven build plugin

**Steps to reproduce the issue:**
1. Import any Shared Module in BW Studio.
2.Generate POM for the SM.
3.Right Click and select Run As-- Maven Install
4. We get error message on the Studio Console and SM is not exported in m2 repo. Have verified on 2.5.0 and 2.6.0 version and it works fine with SM exported in m2 repo.

**Describe the results you received:**
Following are the various errors reported:
1) Error injecting: private org.eclipse.aether.spi.log.Logger org.apache.maven.repository.internal.DefaultVersionRangeResolver.logger
  while locating org.apache.maven.repository.internal.DefaultVersionRangeResolver

**Describe the results you expected:**
No error is expected and SM should be exported in m2 repo. working fine in older Maven builds.

**Comment by vpawar-ai** [comment]
@BhosaleSaurabh You need to upgrade your maven version. Please refer - https://stackoverflow.com/questions/47920305/can-not-set-org-eclipse-aether-spi-log-logger-with-custom-maven-plugin
