### ISSUE TITLE
How to assign different input to the test cases using input files

### ISSUE THREAD

**Issue by senthilalagesan** [TIBCOSoftware/bw6-plugin-maven#485]
As per the discussion with TIBCO team ( Karan, Himesh ), we were advised to raise ticket for the tibco team to evaluate the enhancement for future release.  Below is the requirement description . 

Requirement :  Providing input values to the test cases using files ( similar to gold input files used during assertion) .

Note : We had detailed discussion with Karan Gera and team on the same. Please contact him for more details.

**Comment by vpawar-ai** [comment]
@senthilalagesan An alternative is to use multiple test files and test suites with different set of inputs.  Attaching sample project - 
[MultipleInputsUnitTestDemo.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5020542/MultipleInputsUnitTestDemo.zip)

Use commands -
`clean test -DshowFailureDetails=true -DtestSuiteName=TestSuite1.bwts`
and
`clean test -DshowFailureDetails=true -DtestSuiteName=TestSuite2.bwts`

**Comment by vpawar-ai** [comment]
TIBCO BW 6.7.0 & Maven plugin 2.8.0 supports external xml input file for mocking start activity output.
