### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy  with status code 401 -> [Help 1]

### ISSUE THREAD

**Issue by dmassimi** [TIBCOSoftware/bw6-plugin-maven#486]
Hi,
I've the following error when I try to build from Studio any component (shared module or application or simple maven project is the same):

[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] maven.project.parent                                               [pom]
[INFO] testRest                                                      [bwmodule]
[INFO] testRest.application                                             [bwear]
[INFO] 
[INFO] -----------------< com.tibco.bw:maven.project.parent >------------------
[INFO] Building maven.project.parent 1.0.0-SNAPSHOT                       [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ maven.project.parent ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ maven.project.parent ---
[INFO] Installing C:\Users\tibco\workspace\maven.project.parent\pom.xml to C:\Users\tibco\.m2\com\tibco\bw\maven.project.parent\1.0.0-SNAPSHOT\maven.project.parent-1.0.0-SNAPSHOT.pom
[INFO] 
[INFO] --- maven-deploy-plugin:2.7:deploy (default-deploy) @ maven.project.parent ---
[INFO] Downloading from snapshots: http://tibco.devops:8081/repository/tibco-snapshots/com/tibco/bw/maven.project.parent/1.0.0-SNAPSHOT/maven-metadata.xml
[INFO] Uploading to snapshots: http://tibco.devops:8081/repository/tibco-snapshots/com/tibco/bw/maven.project.parent/1.0.0-SNAPSHOT/maven.project.parent-1.0.0-20200806.094715-1.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for maven.project.parent 1.0.0-SNAPSHOT:
[INFO] 
[INFO] maven.project.parent ............................... FAILURE [  1.411 s]
[INFO] testRest ........................................... SKIPPED
[INFO] testRest.application ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.004 s
[INFO] Finished at: 2020-08-06T11:47:15+02:00
[INFO] ------------------------------------------------------------------------
**[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project maven.project.parent: Failed to deploy artifacts: Could not transfer artifact com.tibco.bw:maven.project.parent:pom:1.0.0-20200806.094715-1 from/to snapshots (http://tibco.devops:8081/repository/tibco-snapshots/): Failed to transfer file http://tibco.devops:8081/repository/tibco-snapshots/com/tibco/bw/maven.project.parent/1.0.0-SNAPSHOT/maven.project.parent-1.0.0-20200806.094715-1.pom with status code 401 -> [Help 1]**
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Do you have some suggestion to fix this issue?
I tried to use **org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy** but it's the same .
PS: it works if I run a **deploy-file** goal with the same settings.xml (so the settings should be ok).

Attached you can find:

- [testRest.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5034053/testRest.zip) with BW projects 

- [settings.xml.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5034064/settings.xml.txt)

Maven Plugin version: 2.6.0

Maven version: 3.6.1

Product : TIBCO Businessworks Container edition

Product version: 2.5.2

Component: Maven build plugin

**Steps to reproduce the issue:**
1. Import projects in studio
2. launch a clean deploy with maven 3.6.1 and plugin 2.6.0

**Additional environment details if any:**
Nexus repository 

**Describe the results you received:**
Not possible to deploy on nexus (401)

**Describe the results you expected:**
Deploy on Nexus

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by vpawar-ai** [comment]
Hi @dmassimi The status code 401 is unauthorized access error.  Please have a look at - 
https://stackoverflow.com/questions/24830610/why-am-i-getting-a-401-unauthorized-error-in-maven
for various reasons for this error. 
You should also check "Windows->Preferences->Maven->User Settings & Installations" configuration in the studio.

**Comment by dmassimi** [comment]
Hi,
to solve I've added this into parent pom:

	<distributionManagement>
		<snapshotRepository>
			<id>tibco-snapshots</id>
			<url>${repo.snapshot.url}</url>
		</snapshotRepository>
		<repository>
			<id>tibco-snapshots</id>
			<url>${repo.snapshot.url}</url>
		</repository>
	</distributionManagement>
