### ISSUE TITLE
Once after restarting app spaces for any operational activity, multiple apps under appspace going to degraded state in BW6

### ISSUE THREAD

**Issue by sonuschinnatech** [TIBCOSoftware/bw6-plugin-maven#489]
Once after restarting app spaces for any operational activity, multiple apps under app space going to degraded state in BW6. which is happening for different appspaces & applications in the domain. Initial deployments happening through jenkins jobs that's using maven framework.

Please help to suggest.

Regards,
Sonu

**Comment by sonuschinnatech** [comment]
Updating the version details,
we are using BW 6.4.x & plugin 1.3.1 on linux environment.

Regards,
Suman

**Comment by sonuschinnatech** [comment]
Please provide suggestions on this.

Regards,
Sonu

**Comment by vpawar-ai** [comment]
@sonuschinnatech It doesnt sound like maven plugin issue. Please raise ticket with TIBCO Support. Please reopen the issue if any help required from maven plugin side.

**Comment by HiteshNembhwani** [comment]
@sonuschinnatech try out these couple of options to check the reason the apps are in degraded state: 
(1) set the appnode logs to DEBUG (2) Use OSGi commands like la to know more about the applications state. Details [here](https://docs.tibco.com/pub/activematrix_businessworks/6.6.0/doc/html/GUID-4AC8019F-701F-48BD-BC44-2A293E4C3796.html) in the documentation for OSGi commands.

**Comment by sonuschinnatech** [comment]
Hitesh,
Thanks for the advise.

we tried enable logs & tried osgi commands approach. below are findings.

this issue started after migrating to maven after app spaces restart. let's say if we start application under app space then 1 app running & others going to degraded state under app space because second application & 3rd, 4th apps going to degraded due to resources unresolved.  can you please provide some inputs on this.

Is there anyway to keep sleep after deploy but before start or any other fix available.

Regards,
Sonu

**Comment by sonuschinnatech** [comment]
> @sonuschinnatech It doesnt sound like maven plugin issue. Please raise ticket with TIBCO Support. Please reopen the issue if any help required from maven plugin side.

**Comment by sonuschinnatech** [comment]
when there is a restart on Appnode, 1 application came back to running & other applications going to degraded state. when i enabled debug logs, I see Shared module where we have java references getting unresolved.  Please let us know if any extra jar or settings we need to apply especially when we have java classes in one shared module which is shared by different apps under same Appnode.

Please help to check & suggest.
