### ISSUE TITLE
Unable to execute install goal to push packaged shared module to maven repository

### ISSUE THREAD

**Issue by jchongtibco** [TIBCOSoftware/bw6-plugin-maven#490]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Maven Plugin version: 2.7.0
Maven version: 3.6.1
Product : TIBCO Businessworks Container edition
Product version: 2.5.3
Component: Maven Build Plugin

**Steps to reproduce the issue:**
1. Create a simple shared module project
2. Right-click and Generate POM for Shared Module (and provide any required information)
3. Use Maven configuration to run "package" goal
4. Use Maven configuration to run "install" goal

**Additional environment details if any:**
Regular Windows 10 development environment. Maven repository is a local Artifactory-OSS.

**Describe the results you received:**
Creation of the jar in the target folder succeeded. However, getting errors per the log files attached during the "install" goal.
[20200813-BWCEMavenErrorLog.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5070213/20200813-BWCEMavenErrorLog.txt)

**Describe the results you expected:**
I was expecting the install to push the jar into Artifactory-OSS successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**
This is reproducible everytime.

**Comment by jchongtibco** [comment]
[CommonLog.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5070265/CommonLog.zip)
I am also attaching the project that I was using here in case it is needed.
I also tried the "deploy" goal which gave me the same error.

**Comment by vpawar-ai** [comment]
Hi @jchongtibco Please change maven installtion setting in your eclipse. Navigate to "Window->Preferences" and add maven installation as below. Click Apply and OK, then try mvn install goal again.
![image](https://user-images.githubusercontent.com/29373785/90213711-19b18d00-de14-11ea-8fe4-18f30367ed2a.png)

**Comment by jchongtibco** [comment]
Thanks @vpawar-ai , your suggestion solved the issue. This issue can be closed.
