### ISSUE TITLE
Unable to Reference Binary Shared Module From Maven Repository

### ISSUE THREAD

**Issue by jchongtibco** [TIBCOSoftware/bw6-plugin-maven#491]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Maven Plugin version: 2.7.0
Maven version: 3.6.1
Product : TIBCO Businessworks Container edition
Product version: 2.5.3
Component: Unsure.... Maven Eclipse Plugin or Maven Build Plugin

**Steps to reproduce the issue:**
1. Have a binary shared module deployed in Maven repository (e.g., Artifactory-OSS)
2. Follow the instruction here to reference the shared module in Maven Repository (https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/SharedModule)
3. After following the instruction, the shared module did not appear in the workspace as described in the instruction.

**Additional environment details if any:**
Regular Windows 10 development environment. Maven repository is a local Artifactory-OSS.

**Describe the results you received:**
The referenced shared module did not appear in the workspace as described in the instruction.

**Describe the results you expected:**
I expect the shared module to appear on the workspace as descibed in the instruction.

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue is reproducible.
![20200813-ScreenshotBinarySharedModuleReferencedNotShowing](https://user-images.githubusercontent.com/48462373/90161797-aa7b6080-dd61-11ea-85c6-57cd3fa05c4e.png)

**Comment by jchongtibco** [comment]
I am also attaching the project that I was using here in case it is needed.
[CommonApp.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5070277/CommonApp.zip)

**Comment by vpawar-ai** [comment]
@jchongtibco Once the issue #490 is fixed and the mvn install goal is successful, please check shared module jar under .m2 repository. You may also need to use "1.0.0-SNAPSHOT" version while adding dependency in pom.xml.

**Comment by jchongtibco** [comment]
Hi @vpawar-ai , unfortunately, this issue is still not solved even when #490 is resolved. I am able to include the shared module in the POM and not errors there but the shared module still did not appear in my workspace for use. Please advise.

**Comment by vpawar-ai** [comment]
Hi @jchongtibco, please check the shared module jar under local m2 repository on your machine. The location should be - 
```
<M2-repo-home>\repository\<namespace-folder-path>\<Shared-Module>\1.0.0-SNAPSHOT
```
Example on windows - ```C:\Users\{user}\.m2\repository\com\tibco\bw\CommonLog\1.0.0-SNAPSHOT```

If it is not present at default location, please configure it in eclipse via - "Window->Preferences->Maven->User Settings".

![image](https://user-images.githubusercontent.com/29373785/90359355-5aa8dc00-e076-11ea-9697-6ee14444f262.png)

**Comment by jchongtibco** [comment]
Hi @vpawar-ai, 
   Yes, my local repo has the jar and also my eclipse setting is pointed to the right repo but the shared module is still not showing.

![20200817-MavenRepo](https://user-images.githubusercontent.com/48462373/90406166-c426eb80-e072-11ea-8905-a6178680a8fc.png)
![20200817-SharedModuleNotShowing](https://user-images.githubusercontent.com/48462373/90406169-c4bf8200-e072-11ea-8ff2-6b80c4ed728c.png)
![20200817-EclipseMavenUserSetting](https://user-images.githubusercontent.com/48462373/90406175-c5581880-e072-11ea-9b14-6a5c0b3470a2.png)

**Comment by jchongtibco** [comment]
I wanted to add a note here that this is resolved. Originally, I added the dependency in the pom.xml of the application. This is incorrect. The dependency needs to be added into the pom.xml of the Application Module instead. Doing this, I was able to see the binary shared module now. Thank you for helping solve this, @vpawar-ai .
