### ISSUE TITLE
I am raising new case to track issue

### ISSUE THREAD

**Issue by suman-tibco** [TIBCOSoftware/bw6-plugin-maven#492]
when there is a restart on Appnode, 1 application came back to running & other applications going to degraded state. when i enabled debug logs, I see Shared module where we have java references getting unresolved. Please let us know if any extra jar or settings we need to apply especially when we have java classes in one shared module which is shared by different apps under same Appnode.

Please help to check & suggest.

**Comment by sonuschinnatech** [comment]
when there is a restart on Appnode, 1 application came back to running & other applications going to degraded state. when i enabled debug logs, I see Shared module where we have java references getting unresolved. Please let us know if any extra jar or settings we need to apply especially when we have java classes in one shared module which is shared by different apps under same Appnode.

Please help to check & suggest.

**Comment by sonuschinnatech** [comment]
@HiteshNembhwani @SujataDarekar Please help to check on this issue & suggest. It is impacting many applications under different appnodes. Maven deployments working fine & all 5 apps running under X Appnode When X Appnode restarts, 1 app running & other 4 applications going to degraded state. when analyzed we found that shared module which is having java references getting unresolved.

**Comment by sonuschinnatech** [comment]
Shared modules not getting loaded after appspace restart & we found this issue in osgi logs. Especially where we have java classes in shared module not getting resolved. Maven Deployment happening fine & apps running fine but whenever there is a restart of app node or app for operational activity, some apps under app node going to degraded state. 1 app running but other apps going to degraded state under 1 app node.

We don't have this issue with manual deployments. This issue started after using maven deployments.

Please help to suggest.


Regards,
Sonu

**Comment by vpawar-ai** [comment]
Hi @sonuschinnatech 

Could you please share the project, generated EAR & logs? If Github cannot be used, please create a SR with TIBCO support to share the artifacts and provide the SR number here. Please also share the BW and maven plugin versions.

**Comment by sonuschinnatech** [comment]
@vpawar-ai case number # 01886815 for Tibco support raised on this. Which is having all the accurate details.

Please help to use case# support way for further communication on this if possible.

Regards,
Sonu

**Comment by sonuschinnatech** [comment]
@vpawar-ai  updated all version details on the tibco support case. Thanks.

Regards,
Sonu

**Comment by vpawar-ai** [comment]
@sonuschinnatech I see the Shared module dependencies are added in application project instead of adding those in "application module" for "IH_837_Vendor_Inbound" application. Please follow the steps at -
https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/SharedModule
Please try adding all the dependencies in application module pom.xml and regenerate the EAR.

**Comment by sonuschinnatech** [comment]
@vpawar-ai ok. I will follow your instructions & update by tomorrow. Thanks.

**Comment by sonuschinnatech** [comment]
Could you please edit your response & remove actual app name in the
response. I got what you are saying so just edit with  “XXXX” application
Instead of actual name.

Thanks for understanding.

**Comment by sonuschinnatech** [comment]
@vpawar-ai I followed suggestions as per instructions & kept shared module references in app module pom.xml. I am still facing issue.

More details for better understanding -
1. removed module entries from application pom.xml
2. added shared module entries in app module pom.xml
3. svn check in done
4. deployed 3 applications using jenkin maven deployment belongs to same app space/appnodes.
5. all 3 applications came to running state
6. stopped app nodes/appspace. started app nodes/appspace.
7. 1 application came back to running & 2 applications going to degraded state.
8. enabled more logging & found shared module references getting unresolved. we have shared modules contains java classes.
9. more details can be found in tibco support case #01886815.

Note : Temporary fix - redeploying applications whenever we need to restart apps/app nodes for operational activities. this becomes operational risk for long run.

Please help to suggest permanent fix as it is impacting many apps in the environment after restart.

Thanks a lot for support in advance.

**Comment by vpawar-ai** [comment]
Hi @sonuschinnatech, Please share below details on the support case -

- EAR files for all 3 application generated from BW
- EAR files for all 3 application generated using maven.
- Output of OSGI commands -"la" and "bundles" when all applications are in running state.
- Output of OSGI commands -"la" and "bundles" after restarting the appnode.
- Please mention the application name which goes into running state after appnode restart. Is it the same application which goes into running state each time?

**Comment by sonuschinnatech** [comment]
@vpawar-ai  I will update details in support case & update. For last point, it's not same app which is going to degraded state after restart. It's changing.

**Comment by sonuschinnatech** [comment]
@vpawar-ai actually most of the requested details mentioned in support case already. Regular ear's are under ANT & other osgi logs also attached along with maven based ears. Could you please help to join zoom call if possible. Thanks.

**Comment by sonuschinnatech** [comment]
@vpawar-ai  I updated with tibco support case #01886815 with all requested details.

Zip file name mentioned below for reference,

 GITHUB-CASE#492-Requested-Docs-1.zip

Please help to check & suggest.

**Comment by sonuschinnatech** [comment]
@vpawar-ai Could you please help to check on this & let me know if require we can join for a quick zoom session. Thanks.

**Comment by vpawar-ai** [comment]
Hi @sonuschinnatech Based on the logs, your shared module has dependency on custom xpath function and it fails to resolve after appnode restart. I couldn't find output for "bundles" osgi command (after restart) in the provided zip. It looks like your custom xpath function project is not a maven project. (Please note that BW6 maven plugin does not provide support for building custom xpath functions yet.)
However, Could you uncheck "Activate this plugin-in when one of its classes is loaded" in custom xpath function project plugin.xml->Overview tab and regenerate ears for all 3 applications?

**Comment by sonuschinnatech** [comment]
@vpawar-ai Thanks. I see java references also not loading. Is it also due to custom x-path related.

I can attach missing log in 10 mins.

If possible, can we connect over zoom on this. This issue pending for a week & impacting complete environment. Especially, I am working from US so it's very tough to reach in India time.

**Comment by sonuschinnatech** [comment]
@vpawar-ai what is the rational behind redeploy vs restart. when redeploy application all shared modules resolving fine. when there is restart shared modules not getting loaded.

is there any work around for this.

**Comment by sonuschinnatech** [comment]
@vpawar-ai We will test it & update. Thanks for suggestions on the same.

**Comment by suman-tibco** [comment]
@vpawar-ai I followed above suggestion & tested but Issue not fixed.

custom xpath & cross walk jar which is not mavenized under shared path - BW_HOME/version/system/shared/*.jar.

One observation, whatever placed under shared path not getting loaded when there is restart. It used to work with ANT framework. 

Please help to check & suggest.

**Comment by suman-tibco** [comment]
@vpawar-ai Could you please suggest on this.

**Comment by suman-tibco** [comment]
Issues with build & deploy scripts along with resolver hence closing case.
