### ISSUE TITLE
Unit Test Report Generated Without Project Or Coverage Information

### ISSUE THREAD

**Issue by jchongtibco** [TIBCOSoftware/bw6-plugin-maven#493]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Maven Plugin version: 2.7.0
Maven version: 3.6.1
Product : TIBCO Businessworks Container edition
Product version: 2.5.3
Component: Unsure.... Maven Eclipse Plugin or Maven Build Plugin

**Steps to reproduce the issue:**
1. Create unit tests for the project
2. Run maven goal "clean initialize site"

**Additional environment details if any:**
Regular Windows 10 development environment.

**Describe the results you received:**
Opening the index.html in target/site folder does not contain any information about the test result.

**Describe the results you expected:**
I expected html report with pages on the project and test result.

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue is reproducible. I have attached screenshots, the sample project, the target site produced and the console output.
[OutputOfSiteGoal.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5109721/OutputOfSiteGoal.zip)
![ProjectTestCoverageNotThere](https://user-images.githubusercontent.com/48462373/90908801-d9698600-e3a2-11ea-8394-65d78a5b5bdb.png)
[AppOne.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5109722/AppOne.zip)
![MavenConfiguration-CleanInitializeSiteGoal](https://user-images.githubusercontent.com/48462373/90908834-eb4b2900-e3a2-11ea-87e7-4f1d99b6433c.png)
[ConsoleOutput-CleanInitializeSite-Goal.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5109727/ConsoleOutput-CleanInitializeSite-Goal.txt)

**Comment by vpawar-ai** [comment]
Hi @jchongtibco, Please refresh the projects after executing the maven goal. The test and coverage report should be located under "AppOne->target->site"

![image](https://user-images.githubusercontent.com/29373785/91004300-699d0a80-e5f1-11ea-80d0-5c3187f08cfd.png)

**Comment by jchongtibco** [comment]
Hi @vpawar-ai , Thanks for the pointer. I did refresh and also go their via the file system.... but I don't see any bwcoverage.html or bwtest.html file generated. Please see the attached OutputOfSiteGoal.zip above.
