### ISSUE TITLE
Issue - Plugin execution not covered by lifecycle configuration

### ISSUE THREAD

**Issue by amitvmane** [TIBCOSoftware/bw6-plugin-maven#498]
Hi , 

We have created simple project and post hello world project creation , we generated POM file and we got below error. any suggestion how we can fix it ? All projectName.Application files are giving this errors in pom.xml. 

FB versions of tool : 

TIBCO BW CE - 2.5.4 

Maven Plugin used - TIB_BW_Maven_Plugin_2.7.0

Appache Maven - Apache Maven 3.6.3

PFB Screenshot of error. Error :

Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:properties-maven-plugin:1.0.0:read-project-properties (execution: default, phase: initialize)

`
 Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:properties-maven-plugin:1.0.0:read-project-properties (execution: default, phase: initialize)`

Thanks

**Comment by amitvmane** [comment]
PFA Sample pom file ( check line no 34 where this error is received.)
[pom.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5236935/pom.zip)

**Comment by vpawar-ai** [comment]
Hi @amitvmane This is known behavior in eclipse m2e plugin. Please refer - https://www.eclipse.org/m2e/documentation/m2e-execution-not-covered.html#execute-plugin-goal

You can use eclipse quick fix option to generate lifecycle mapping metadata and then replace <ignore/> action with <execute/>
