### ISSUE TITLE
Project is not validated before during the Maven Build

### ISSUE THREAD

**Issue by ashutoshbhide** [TIBCOSoftware/bw6-plugin-maven#5]

**Comment by mohankotha** [comment]
When will this feature be available? I intentionally created a problem in the BW Process and still able to compile and package the application Sucessfully

**Comment by fanninj3** [comment]
Hi,

Will the validation feature be present in this plugin in the future?
It seems like a very good feature to have included.

**Comment by awagle** [comment]
Please use the bwdesign utility to achieve validation. Since the validation code is deeply tied to eclipse features this cannot be achieved in the Maven plugin.
