### ISSUE TITLE
invalid version "test": non-numeric "test": For input string: "test"

### ISSUE THREAD

**Issue by dmassimi** [TIBCOSoftware/bw6-plugin-maven#500]
Hi,
For one client we would like to use non-numeric version in pom (linked to the branchs gitlab), but today is not possible (below the error using "test" as version):

[ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.6.0:bwmodule (default-bwmodule) on project bw.core_replay: Execution default-bwmodule of goal com.tibco.plugins:bw6-maven-plugin:2.6.0:bwmodule failed: invalid version "test": non-numeric "test": For input string: "test" -> [Help 1]

Do you think it will be possible in the future?

Maven Plugin version: 2.6.0

Maven version: 3.6.1

Product : ETIBCO Businessworks Container edition 

Product version: 2.5.2

Component: Maven build plugin

**Comment by vpawar-ai** [comment]
Hi @dmassimi, Are you looking for version "test" or "1.0.0.test"? if it is just "test" then OSGi will complain. You may want to try using qualifier component for non-numeric part.

**Comment by dmassimi** [comment]
Hi, I'm looking just for "test" because the target in my client is to use the name of branch (development, fix-abc, feature-jira-123, etc...) .
This "non-numeric" behavior is linked to maven or to tibco maven plugin ?

**Comment by vpawar-ai** [comment]
The bw6 maven plugin validates the provided version. The "non-numeric" error was thrown during the validation by the plugin.

https://www.osgi.org/developer/white-papers/semantic-versioning/semantic-versions/
https://maven.apache.org/pom.html#Version_Order_Specification

**Comment by dmassimi** [comment]
Hi @vpawar-ai 
ok I will communicate this to my client.
They have to stay in standard format as defined in links you sent.
