### ISSUE TITLE
Container error when deploying bwce application in Jenkins

### ISSUE THREAD

**Issue by vine-nam** [TIBCOSoftware/bw6-plugin-maven#501]
Maven Plugin version: 2.7.0

Maven version: 3.6.2

Product :  TIBCO Businessworks Container edition

Product version: 2.5.4

Component: Maven build plugin

**Steps to reproduce the issue:**
1. Create a new bwce application.
2. Push the application to github.
3. Create a Maven job in Jenkins and create a Source code management and Build.
    - Repository URL: https://github.com/vine-nam/bwce-hello
    - Root POM: hello.application.parent/pom.xml
    - Goals and options: clean package initialize docker:build docker:start

**Additional environment details if any:**

**Describe the results you received:**
Container errors are as follows:
```
error: cannot open zipfile [ /tmp/tibco.home/bwce/2.5/bin/bwapp.ear ]
Permission denied
unzip: cannot find or open /tmp/tibco.home/bwce/2.5/bin/bwapp.ear, /tmp/tibco.home/bwce/2.5/bin/bwapp.ear.zip or /tmp/tibco.home/bwce/2.5/bin/bwapp.ear.ZIP.
BW_PROFILE is set to 'default.substvar'
./scripts/setup.sh: line 148: /tmp/META-INF/MANIFEST.MF: No such file or directory
cp: cannot stat '/tmp/META-INF/default.substvar': No such file or directory
java.io.FileNotFoundException: /tmp/tmp/pcf.substvar (No such file or directory)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.<init>(FileInputStream.java:138)
at java.io.FileReader.<init>(FileReader.java:72)
at com.tibco.bwce.profile.resolver.ProfileResolverHelper.getKeysForConfig(ProfileResolverHelper.java:35)
at com.tibco.bwce.profile.resolver.DockerProfileTokenResolver.resolveTokens(DockerProfileTokenResolver.java:223)
at com.tibco.bwce.profile.resolver.DockerProfileTokenResolver.resolve(DockerProfileTokenResolver.java:37)
at com.tibco.bwce.profile.resolver.Resolver.main(Resolver.java:24)
```

**Describe the results you expected:**
Hope the container status is Up. Instead of Exited (1)

**Additional information you deem important (e.g. issue happens only occasionally):**
I set up the root user because it was a permission problem, so the container runs without problem.
`docker run -u root tibco/test:hello`

Why am I having permission issues?

**Comment by vpawar-ai** [comment]
Hi @vine-nam, please re-create the BWCE base image and try again. Please follow the steps at - https://docs.tibco.com/pub/bwce/2.5.4/doc/html/GUID-91EA80AA-08EF-4CB3-A6A7-E8551A441AC1.html

**Comment by vine-nam** [comment]
Hi @vpawar-ai.
I made a new BWCE base image.
And I also tried a test run.

First, I made a base image using `centos7` from the URL you gave me.
This does not create a bwce user.
So the bwce application docker container ran fine without any permission error.
```Dockerfile
FROM centos:7
LABEL maintainer="TIBCO Software Inc."
ADD . /
RUN chmod 755 /scripts/*.sh && yum -y update && yum -y install unzip ssh net-tools
ENTRYPOINT ["/scripts/start.sh"]
```

And I created a new BWCE base image as a Dockerfile that uses `debian` that is included when bwce is installed.
As you can see, create a new user and use it.
```Dockerfile
FROM debian:stretch-slim
LABEL maintainer="TIBCO Software Inc."
ADD . /
RUN chmod 755 /scripts/*.sh && apt-get update && apt-get --no-install-recommends -y install unzip ssh net-tools && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN groupadd -g 2001 bwce \
&& useradd -m -d /home/bwce -r -u 2001 -g bwce bwce
USER bwce
ENTRYPOINT ["/scripts/start.sh"]
```

The problem is that containers created with `docker:build docker:start` in **bwce studio** run fine, but containers run with the same command in **Jenkins** get **permission errors**.
Do you know why?

I'll upload my base image to Docker Hub.
vine/bwce:centos7, vine/bwce:debian

**Comment by vpawar-ai** [comment]
Hi @vine-nam, Could you please ensure the new BWCE base image is present on the jenkins server or the jenkins job is using the new image? Please also change `bwdocker.from=<new-bwce-base-image>` in `hello.application\docker-dev.properties` file.

**Comment by vine-nam** [comment]
Hi @vpawar-ai.
I deleted all related images and built a Jenkins job using the following Goals.
`clean package initialize -Dbwdocker.from=vine/bwce:debian -Ddocker.image=tibco/test docker:build docker:start`

But I still get a permission denied error.

**Comment by vpawar-ai** [comment]
Hi @vine-nam , I executed the maven command - `mvn clean package initialize -Dbwdocker.from=vine/bwce:debian -Ddocker.image=tibco/test docker:build docker:start`. It works fine for me. Attaching logs for your reference.
[Issue-501logs.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5290005/Issue-501logs.txt)
