### ISSUE TITLE
Support export application profiles as .properties file with Maven

### ISSUE THREAD

**Issue by rekhachougule** [TIBCOSoftware/bw6-plugin-maven#504]
Please refer case id: https://supportapps.tibco.com/id/01888163 for more info about the requirement.

Customer requirement:
"Since we need to automate as much as possible the application deployment, we would like to know if there is an option inside the Maven plugin that allows to export the application tokenized profiles as .properties file with dot notation."

BWCE supports this case using bwdesign utility (since 2.6.0)by :
when user wants to export the profile using dot separator they need to use -dot parameter.
so now the command pattern will be 
export -pr {profile name} -alsomoduleproperty -dot {application name} {location}

But same is not supported using maven as per 
https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/Running-BW-Design-Utility-Goal
and 
https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/437

Can you please support the same for exporting profile properties command.

**Comment by vpawar-ai** [comment]
Please provide `commandName` and `arguments` parameters to provide arguments for BW design utility goal from 2.8.0 onwards.
