### ISSUE TITLE
 Execution default-bwmodule of goal com.tibco.plugins:bw6-maven-plugin:2.7.0:bwmodule failed.: NullPointerException

### ISSUE THREAD

**Issue by bibhuduttaGitHub** [TIBCOSoftware/bw6-plugin-maven#506]
Maven Plugin version:2.7.0

Maven version:3.4.3

Product :  TIBCO Businessworks Container edition

Product version:2.5.4

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
Outlined in the Case#01898373 , all the logs and details attached

**Additional environment details if any:**
the bw maven plugin does not give much details on the null pointer exception. Most of our customxpathfunction projects are failing.
None of the jars are corrupted and all of the jars were having MANIFEST as 1st/2nd entry in the jar. I have already validated.

**Describe the results you received:**
null pointer exception

**Describe the results you expected:**
successful build

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by bibhuduttaGitHub** [comment]
Can i expect an update here.

**Comment by vpawar-ai** [comment]
Hi @bibhuduttaGitHub As discussed in #502, You have fixed the jars and now MANIFEST is 1st/2nd entry in the jar. Could you share the debug logs with the new exception? Are you using the Custom Xpath function jars "as is" from BW5.x into BW6.x? Thanks.

**Comment by bibhuduttaGitHub** [comment]
I have renamed the jar as per the module name as mentioned in the issue#505.. debug logs are attached to the case now.

**Comment by bibhuduttaGitHub** [comment]
Do we have an update. As we are waiting for similar setup for a bunch of similar apps .

**Comment by bibhuduttaGitHub** [comment]
HI Vishal,
This is a different project. We are seeing the same null pointer exception here as well.
The one i fixed was part of a different project altogether.

**Comment by bibhuduttaGitHub** [comment]
@vpawar-ai  - Did you get a chance to verify the debug logs attached to the case.

**Comment by vpawar-ai** [comment]
Hi @bibhuduttaGitHub I had a look at code attached to case #01898373. There are couple of issues -

- Please review java classes & their required dependencies present in both Application project and custom xpath function project.
- If you are looking to add those dependencies the maven way then those jars should be removed from lib folder and project classpath. Those should not be present in `Bundle-ClassPath` in Manifest file as well. Please add those dependencies in pom.xml file for both application module and custom xpath project.
- Add custom xpath function project as a module in parent project.
- Please ensure that there are no validation errors in the project.

**Comment by bibhuduttaGitHub** [comment]
@vpawar-ai - when the customxpathfunction module is created post migration, it by default create the jars inside lib of the respective modules. Do you mean we need to chenge this approach? FYI: the project works fine in studio mode with the current folder structure.
 And also did you check the renaming aspect of the jar in customxpathfunction module? As we have to upload those jars to JFrog, those jars should have unique names to it.

**Comment by bibhuduttaGitHub** [comment]
@vpawar-ai - It makes more sense to get into a call to discuss this for clarity . let me know if you can setup a call to go over this.

**Comment by vpawar-ai** [comment]
hi @bibhuduttaGitHub, It will work either way. I couldn't reproduce the issue with both ways - keeping in lib folder or adding as pom dependencies. I could see the jars added in classpath but missing in lib folder and same also added in pom dependencies as well. 
About renaming of the "customXPathFunction.jar",  I would suggest to check on how the jars were generated during migration and the approach you want to take to publish on JFrog. Please contact TIBCO support for any help on migration. Thanks.

**Comment by bibhuduttaGitHub** [comment]
HI Vishal,
The code that i have provided is export of the GitHub Repo. As a policy we are not allowed to checkin the jars/binaries to GitHib. We are pulling them from JFrog during mvn build through dependencyin the POM. As you can see POM file has the required dependency available. But with this setup, i am getting the NULL Pointer exception. Let me know what is the way forward then. How can we troubleshot this further.
