### ISSUE TITLE
Not able to import BW external Shared Module into Workspace using maven dependencies

### ISSUE THREAD

**Issue by babppv** [TIBCOSoftware/bw6-plugin-maven#508]
Maven Plugin version: 1.2.2 and 1.3.1

Maven version: 3.6.3

Product :  TIBCO Businessworks Container edition

Product version: 2.3.2 and 2.3.4

Component: Maven Eclipse Plugin

**Steps to reproduce the issue:**
1. Installed shared modules  into the local .m2 repo

2. Added external shared modules as dependencies in pom.xml of Application Module:
  
![image](https://user-images.githubusercontent.com/31319781/95774414-479e3b00-0cb8-11eb-8383-5dc515f50d45.png)

3. None of the dependent shared module appears on the project explorer and norelated  errors on the workspace log are shown.

**Additional environment details if any:**

**Describe the results you received:**
 None of the dependent shared module appears on the project explorer and norelated  errors on the workspace log are shown.
How can I troubleshoot the issue?

**Describe the results you expected:**
Expected that the dependen external shared module appear on workspace project explorer (as happening in latest bwce / plugin versions).

**Additional information you deem important (e.g. issue happens only occasionally):**
Tests were done with bwce 2.3.2 with bw6 Maven plugin 1.2.2 and bwce 2.3.4 with bw6 maven plugin 1.3.1 
Maven version: 3.6.3

**Comment by vpawar-ai** [comment]
Hi @babppv Could you please check -

- The shared module project was installed successfully into local .m2 repo and it is present at .m2 location. For windows - `C:\Users\<user>\.m2\repository\com\tibco\bw\<Shared-Module-Name>\1.0.0-SNAPSHOT\`
- Check Local .m2 repo location in eclipse preferences. Please refer [Troubleshooting Guide](https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/Troubleshooting)
- Please follow the steps at - [External Shared Module with Maven](https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/SharedModule#external-shared-modules-with-maven)

**Comment by babppv** [comment]
Hi @vpawar-ai ,

1 -  I can see the installed modules under my local .m2 location:
- C:\Users\tibco\\.m2\repository\pt\tap\tip\tibco\bw\shared\TAP_TSUTIL_AUDIT\1.0.0-SNAPSHOT
- C:\Users\tibco\\.m2\repository\pt\tap\tip\tibco\bw\shared\TAP_API_SHARED_RESOURCES\1.0.0-SNAPSHOT
- C:\Users\tibco\\.m2\repository\pt\tap\tip\tibco\bw\shared\TAP_API_SHARED_JWT\1.0.0-SNAPSHOT

Below a snippet of the pom.xml of the application module with the declared dependencies:
  <dependencies>
    <dependency>
      <groupId>com.tibco.plugins</groupId>
      <artifactId>com.tibco.bw.palette.shared</artifactId>
      <version>6.1.100</version>
    </dependency>
    <dependency>
      <groupId>pt.tap.tip.tibco.bw.shared</groupId>
      <artifactId>TAP_API_SHARED_RESOURCES</artifactId>
      <version>1.0.0-SNAPSHOT</version>
      <type>bwmodule</type>
    </dependency>
    <dependency>
      <groupId>pt.tap.tip.tibco.bw.shared</groupId>
      <artifactId>TAP_TSUTIL_AUDIT</artifactId>
      <version>1.0.0-SNAPSHOT</version>
      <type>bwmodule</type>
    </dependency>
    <dependency>
      <groupId>pt.tap.tip.tibco.bw.shared</groupId>
      <artifactId>TAP_API_SHARED_JWT</artifactId>
      <version>1.0.0-SNAPSHOT</version>
      <type>bwmodule</type>
    </dependency>
  </dependencies>

2 - the location in eclipse preferences is  C:\Users\tibco\\.m2\repository:
![image](https://user-images.githubusercontent.com/31319781/95871336-73c3c580-0d65-11eb-8bdb-131c52bef8c4.png)

3 - I have followed the steps described in the referenced link but with no success.

How can I troubleshoot?

**Comment by vpawar-ai** [comment]
Hi @babppv, Please remove ` <type>bwmodule</type>` from all shared module dependencies and save the pom.xml. 
Please share a sample project to reproduce the issue, if this does not help.

**Comment by babppv** [comment]
Hi @vpawar-ai, many thanks, it worked with BW6 plugin 1.3.1 on both BWCE 2.3.2 and 2.3.4.
I've noticed that for latest versions of the plugin  (2.7.0 and 2.7.1) with BWCE 2.5.3 that is not an issue (<type>bwmodule</type>.
