### ISSUE TITLE
Error when building Application with shared modules

### ISSUE THREAD

**Issue by John-Zg** [TIBCOSoftware/bw6-plugin-maven#51]
Hi,
we tried to build and deploy an application with different shared modules, but we are getting dependencies  issues. We hope you can help us. Below you can find the jenkins output:

Building in workspace /home/tibco/.jenkins/jobs/IF34/workspace
Fetching changes from the remote Git repository
Checking out Revision 3d130229fb1e18d20d04c97ec9051dd (refs/remotes/origin/feature/JenkinsTest)
Parsing POMs
Found a module with path ..\..\..\SharedModules\SharedModule_CLE\Source_Code\BW_Shared_CLE_v1 but no associated projectFound a module with path ..\..\..\SharedModules\SharedModule_LockProcess\Source_Code\LockProc_SharedModule but no associated projectFound a module with path ..\..\..\SharedModules\BW_SDI_Client\BW_Shared_SDI_v1 but no associated projectFound a module with path ..\BW_Resolve_MasterCrewData_v1.module but no associated projectFound a module with path ..\BW_Resolve_MasterCrewData_v1 but no associated projectModules changed, recalculating dependency graph
[BW_Resolve_MasterCrewData_v1.parent] $ /opt/java/jdk1.7.0_71//bin/java -cp /home/tibco/.jenkins/plugins/maven-plugin/WEB-INF/lib/maven31-agent-1.5.jar:/home/tibco/.jenkins/tools/hudson.tasks.Maven_MavenInstallation/DEV_Maven/boot/plexus-classworlds-2.5.1.jar:/home/tibco/.jenkins/tools/hudson.tasks.Maven_MavenInstallation/DEV_Maven/conf/logging jenkins.maven3.agent.Maven31Main /home/tibco/.jenkins/tools/hudson.tasks.Maven_MavenInstallation/DEV_Maven /home/tibco/.jenkins/war/WEB-INF/lib/remoting-2.47.jar /home/tibco/.jenkins/plugins/maven-plugin/WEB-INF/lib/maven31-interceptor-1.5.jar /home/tibco/.jenkins/plugins/maven-plugin/WEB-INF/lib/maven3-interceptor-commons-1.5.jar 45679
<===[JENKINS REMOTING CAPACITY]===>channel started
Executing Maven:  -B -f /home/tibco/.jenkins/jobs/IF34/xyz/Interface34_MasterCrewData/Source_Code/BW_Resolve_MasterCrewData_v1.parent/pom.xml install
[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install-file (default-cli) @ standalone-pom ---
[INFO] Installing /home/tibco/.jenkins/jobs/IF34/xyz/SharedModule_CLE/Source_Code/BW_Shared_CLE_v1/.temp/.tibcoadapter/native/BW_Shared_CLE_v1.jar to /home/tibco/.m2/repository/tempbw/BW_Shared_CLE_v1/0.0.0/BW_Shared_CLE_v1-0.0.0.jar
[INFO] Installing /tmp/mvninstall2181926363409375551.pom to /home/tibco/.m2/repository/tempbw/BW_Shared_CLE_v1/0.0.0/BW_Shared_CLE_v1-0.0.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.248 s
[INFO] Finished at: 2016-11-21T08:31:31+01:00
[INFO] Final Memory: 14M/481M
[INFO] ------------------------------------------------------------------------
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install-file (default-cli) @ standalone-pom ---
[INFO] Installing /home/tibco/.jenkins/jobs/IF34/xyz/SharedModule_CLE/Source_Code/BW_Shared_CLE_v1/.temp/.tibcoadapter/native/BW_Shared_CLE_v1.jar to /home/tibco/.m2/repository/tempbw/BW_Shared_CLE_v1/0.0.0/BW_Shared_CLE_v1-0.0.0.jar
[INFO] Installing /tmp/mvninstall6475568348028311276.pom to /home/tibco/.m2/repository/tempbw/BW_Shared_CLE_v1/0.0.0/BW_Shared_CLE_v1-0.0.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.632 s
[INFO] Finished at: 2016-11-21T08:31:34+01:00
[INFO] Final Memory: 14M/481M
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] BW_Resolve_MasterCrewData_v1.parent
[INFO] BW_Shared_CLE_v1
[INFO] LockProc_SharedModule
[INFO] BW_Shared_SDI_v1
[INFO] BW_Resolve_MasterCrewData_v1.module
[INFO] BW_Resolve_MasterCrewData_v1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building BW_Resolve_MasterCrewData_v1.parent 1.12.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ BW_Resolve_MasterCrewData_v1.parent ---
[INFO] Installing /home/tibco/.jenkins/jobs/IF34/xyz/Interface34_MasterCrewData/Source_Code/BW_Resolve_MasterCrewData_v1.parent/pom.xml to /home/tibco/.m2/repository/com/tui/com/BW_Resolve_MasterCrewData_v1.parent/1.12.0/BW_Resolve_MasterCrewData_v1.parent-1.12.0.pom
[WARNING] Failed to notify spy hudson.maven.Maven3Builder$JenkinsEventSpy: null
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building BW_Shared_CLE_v1 1.12.0
[INFO] ------------------------------------------------------------------------
[INFO] Downloading: http://repo.maven.apache.org/maven2/tempbw/BW_Shared_CLE_v1/0.0.0/BW_Shared_CLE_v1-0.0.0.pom
[WARNING] The POM for tempbw:BW_Shared_CLE_v1:jar:0.0.0 is missing, no dependency information available
[INFO] Downloading: http://repo.maven.apache.org/maven2/tempbw/BW_Shared_CLE_v1/0.0.0/BW_Shared_CLE_v1-0.0.0.jar
[WARNING] Failed to notify spy hudson.maven.Maven3Builder$JenkinsEventSpy: null
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] BW_Resolve_MasterCrewData_v1.parent ................ SUCCESS [  0.565 s]
**[INFO] BW_Shared_CLE_v1 ................................... FAILURE [  1.916 s]**
[INFO] LockProc_SharedModule .............................. SKIPPED
[INFO] BW_Shared_SDI_v1 ................................... SKIPPED
[INFO] BW_Resolve_MasterCrewData_v1.module ................ SKIPPED
[INFO] BW_Resolve_MasterCrewData_v1 ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.464 s
[INFO] Finished at: 2016-11-21T08:31:37+01:00
[INFO] Final Memory: 20M/481M
[INFO] ------------------------------------------------------------------------
**[ERROR] Failed to execute goal on project BW_Shared_CLE_v1: Could not resolve dependencies for project com.tui.com:BW_Shared_CLE_v1:bwmodule:1.12.0: Could not find artifact tempbw:BW_Shared_CLE_v1:jar:0.0.0 in central (http://repo.maven.apache.org/maven2) -> [Help 1]**
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :BW_Shared_CLE_v1
[JENKINS] Archiving /home/tibco/.jenkins/jobs/IF34/xyz/Interface34_MasterCrewData/Source_Code/BW_Resolve_MasterCrewData_v1.parent/pom.xml to com.tui.com/BW_Resolve_MasterCrewData_v1.parent/1.12.0/BW_Resolve_MasterCrewData_v1.parent-1.12.0.pom
/home/tibco/.jenkins/jobs/IF34/xyz/Interface34_MasterCrewData/Source_Code/BW_Resolve_MasterCrewData_v1.parent/pom.xml is not inside /home/tibco/.jenkins/jobs/IF34/workspace/home/tibco/.jenkins/jobs/IF34/xyz/Interface34_MasterCrewData/Source_Code/BW_Resolve_MasterCrewData_v1.parent/; will archive in a separate pass
[workspace] $ /home/tibco/.jenkins/tools/hudson.tasks.Maven_MavenInstallation/DEV_Maven/bin/mvn
channel stopped
[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.250 s
[INFO] Finished at: 2016-11-21T08:31:40+01:00
[INFO] Final Memory: 12M/481M
[INFO] ------------------------------------------------------------------------
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException
Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE

And here is the pom file for the shared module:

`<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.tui.com</groupId>
    <artifactId>BW_Resolve_MasterCrewData_v1.parent</artifactId>
    <version>1.12.0</version>
    <relativePath>..\..\..\..\Interface34_MasterCrewData\Source_Code\BW_Resolve_MasterCrewData_v1.parent</relativePath>
  </parent>
  <artifactId>BW_Shared_CLE_v1</artifactId>
  <packaging>bwmodule</packaging>
  <build>
    <sourceDirectory>src</sourceDirectory>
    <outputDirectory>target/classes</outputDirectory>
    <plugins>
      <plugin>
        <groupId>com.tibco.plugins</groupId>
        <artifactId>bw6-maven-plugin</artifactId>
        <version>1.1.0</version>
        <extensions>true</extensions>
      </plugin>
    </plugins>
  </build>
</project>
`

**Comment by rahulkamdar** [comment]
Thanks for sharing these details. Was the shared module available in the same workspace as to where the application module is getting built from? Btw is this being run from Studio or CLI?

**Comment by John-Zg** [comment]
Hi Rahul, 
thank you for your feedback. Yes, the shared module is in the same workspace. This is the project structure if it helps:

Root
-Application Folder
--Subfolder
---Application.parent
---Application.module
---Application (main)
-Shared Modules Folder
--Subfolder
---Subfolder2
----SharedModule Folder (the folder where the CLE shared module is)

I hope it is understandable. 

We are running it from CLI. The BW version is 6.3.2 HF2

**Comment by HiteshNembhwani** [comment]
@John-Zg 
[Maven-SharedModuletests.docx](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/607733/Maven-SharedModuletests.docx)

Please refer to the attached doc. 

I used the apps under TIBCO_HOME/bw/6.3/samples/core/modularity/AppsWithSharedModule. 

- created EAR for 2 apps using the same shared module using Maven
- deployed them to an appspace with a single appnode

It is working fine without any issues. 

Could you please try the same steps with these sample applications and see if it works for you?

**Comment by John-Zg** [comment]
@HiteshNembhwani 
Thank you for your answer. Unfortunately, it's not exactly what we need. These are the steps we did and the issues we faced:
**Our development environment is a Windows machine and the deployment environment is a Linux machine.**
1. Importing the 2 projects and shared module you mentioned.
2. Going to first application (Hello World Consumer), right clicking and selecting "Generate pom for applicaiton" . poms for the parent, application, module and shared module are generated. Now, here are the first 2 issues:
- In the pom files there are used backslashes, that is not suitable on linux machines. 
- In the shared module there is a "parent" section where a reference to the parent application is. There should not be a reference to a parent application , because then you need for each application a separate pom file. 
3. Then, we right click to the application "Timer Event Component" and select "Generate pom for applicaiton". poms for the parent, application, module and shared module are generated. Here, the already generated pom for the shared module is overwritten.
4. We upload the code to a remote repository (e.g. Git). 
5. We start Jenkins on a Linux machine and generate 2 build elements for the two applications (Hello World Consumer and Timer Event Component)
6. At least one of the applications (Hello World Consumer) will not work because in the pom of the shared module there is a parent section referencing the wrong application (see point 3). Probably the second one will also not work cause of the backslashes.

Could you please advise how to proceed?

**Comment by awagle** [comment]
This should be fixed with #134. Please re-open if the issue still exists. You might need to re-generate the POM files to have the right path separators.
