### ISSUE TITLE
Does Maven->Update work in studio for resolving external maven dependency ?

### ISSUE THREAD

**Issue by bibhuduttaGitHub** [TIBCOSoftware/bw6-plugin-maven#512]
Maven Plugin version: 2.7.0

Maven version: 3.6.3

Product :  TIBCO Businessworks Container edition

Product version:2.5.4

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1. Put your settings.xml exported from JFROG into .m2/ folder
2. Do a Project clean in studio
3. Mavenise the Project in studio and add dependency to the POM
4. Eclipse will show error for not able to find the dependent atifact.
5. Do a Maven->Update to update the project dependency.

Detailed steps ith screenshot is attached to the case #01901251.

**Additional environment details if any:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by vpawar-ai** [comment]
@bibhuduttaGitHub Please check Eclipse maven user settings configuration. 

https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/Troubleshooting#configure-maven-installation-and-local-m2-repo-location-in-eclipse

The "Maven->Update Project" menu option is provided by "Eclipse M2e Plugin". 
Please try restarting the studio after making any changes in the configuration. Thanks.

**Comment by bibhuduttaGitHub** [comment]
@vpawar-ai : i tried to set the maven installation path in the preference. Still its not able to resolve all the maven artifacts.
Let me know how it goes for you.

**Comment by bibhuduttaGitHub** [comment]
@vpawar-ai : I followed the same set of steps in a new workspace too. But the result is still the same. Maven dependencies are not resolved and studio still shows the error for pom.xml.

**Comment by vpawar-ai** [comment]
Hi @bibhuduttaGitHub , Please refer [link](https://stackoverflow.com/questions/31714869/how-to-use-artifactory-maven-with-eclipse) if it helps. It looks like maven indexing is not enabled in Jfrog by default.
