### ISSUE TITLE
How to install the plugin in standalone mode

### ISSUE THREAD

**Issue by bunztic** [TIBCOSoftware/bw6-plugin-maven#514]
Hi everyone,

I try to install version 2.7.0 of the plugin for my client whose computers are not authorized to access the internet. 
How can I do?

The problem is located in this step of the plugin's build.xml file

<target name="studio-install" >

        <echo> Installing Eclipse M2E Plugin to Tibco Home </echo>
        <p2.install repo="http://download.eclipse.org/releases/luna" ius="org.eclipse.equinox.p2.discovery.feature.feature.group"/>

Someone would have an idea to do a standalone installation?

Thanks,

**Comment by vpawar-ai** [comment]
Hi @bunztic, Standalone installation can be achieved by setting up local eclipse p2 repo mirror. I am sharing a script to help you create zip for `org.eclipse.equinox.p2.discovery.feature`.

Steps :
1. Download [script.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5458101/script.zip), extract the zip file. It contains `download-build.xml` ant script.
2. Open the script file and change `repo.dir` property to point to a temporary location.
3. cd `<TIBCO_HOME>\tools\p2director\eclipse` and execute -
>`eclipse.exe -nosplash -verbose -application org.eclipse.ant.core.antRunner -buildfile <path-to-build-file>\download-build.xml`
4. The command will execute in background and will take some time to download and create the zip at temporary folder.
5. Once zip is created. Copy the zip file to the machine where you want to install the maven plugin.
6. Edit `build.xml` file from Maven plugin installer and change -
From -
```xml
<p2.install repo="http://download.eclipse.org/releases/luna" ius="org.eclipse.equinox.p2.discovery.feature.feature.group"/>
```
To -
```xml
<p2.install repo="jar:file:///<path-to-zip>\org.eclipse.equinox.p2.discovery.feature.zip!/" ius="org.eclipse.equinox.p2.discovery.feature.feature.group"/>
```

**Comment by bunztic** [comment]
Hi @vpawar-ai, 

Thank you for your precious help. 
I managed to install the plugin and run "Generate POM for Application" on Studio. But in the end I have this error:

#NOTE: This is an Aether internal implementation file, its format can be changed without prior notice.
#Thu Nov 05 17:34:07 CET 2020
@default-central-https\://repo.maven.apache.org/maven2/.lastUpdated=1604594047275
https\://repo.maven.apache.org/maven2/.error=Could not transfer artifact com.tibco.plugins\:com.tibco.bw.palette.shared\:jar\:6.1.100 from/to central (https\://repo.maven.apache.org/maven2)\: repo.maven.apache.org

**Comment by vpawar-ai** [comment]
Hi @bunztic, Please refer - https://support.tibco.com/s/article/Error-Missing-artifact-com-tibco-plugins-com-tibco-bw-palette-shared-jar-6-1-100-after-generating-for-application

**Comment by katharineyau** [comment]
Hi, we attempted the same steps for maven plugin v2.8 installation against BWCEv2.6. The Ant script looks completed successfully. 
![image](https://user-images.githubusercontent.com/78394993/108022601-f7275780-7074-11eb-849a-4986917ab82c.png)

However, after importing a project with pom.xml, it hung when building workspace.

![image](https://user-images.githubusercontent.com/78394993/108022566-e4ad1e00-7074-11eb-8964-ba2ccbb0cfc0.png)
