### ISSUE TITLE
[question] Update Application Module with new version an external Shared Module.

### ISSUE THREAD

**Issue by jgimenes** [TIBCOSoftware/bw6-plugin-maven#515]
Maven Plugin version: 2.7.1
Maven version: 3.6.3
Product : TIBCO ActiveMatrix Businessworks 6 
Product version: 6.6.1 - HF2

**Steps to reproduce the issue:**
1. Create a new Shared Module and mavenize. 
2. Fixed Maven installation path.
3. Run build clean.
4. Run Build install.
5. Shared Module jar is available on m2 repositories.
6. I switched to project workspace, create new Application Module and mavenize.
7. I configured the module dependency as described https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/SharedModule#external-shared-modules-with-maven.
8. The Shared Module is available on the Project Explorer.
9. I switched to Shared Module workspace.
10. Run build release:update-versions.
11. Run build clean.
12. Run build install.
13. Shared Module jar version 1.0.1 is available on m2 repositories.
14. I switched again to project workspace and I updated (alt + F5) Shared Module.
15. After updated I received error: 

_Project build error: Non-readable POM %USER_HOME%\.m2\repository\com\tibco\bw\com.tibco.bw.SharedResources\1.0.0-SNAPSHOT\com.tibco.bw.SharedResources-1.0.0-SNAPSHOT.jar\pom.xml: %USER_HOME%\.m2\repository\com\tibco\bw\com.tibco.bw.SharedResources\1.0.0-SNAPSHOT\com.tibco.bw.SharedResources-1.0.0-SNAPSHOT.jar\pom.xml (The system cannot find the path specified)._

Let me know where I am going wrong, please, or this is normal behavior? 
I have that update manually pom.xml file or remove dependency and add again when the dependency is updated? 
It's possible an automatic update of Shared Module?

At the attachment I reproduce all executed steps.
[steps.pdf](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5469330/steps.pdf)

Thanks and best 

- [ ] regards!

**Comment by vpawar-ai** [comment]
Hi @jgimenes, Please remove shared module 1.0.0 version pom dependency and add 1.0.1 dependency again. Please also ensure that the Maven POM version and `Bundle-Version` in MANIFEST.MF is same for the shared module.

**Comment by jgimenes** [comment]
I thank for your attention @vpawar-ai! 
I thought that it automatic update was possible.
