### ISSUE TITLE
bw6-maven-plugin:2.7.0:bwmodule failed.: NullPointerException

### ISSUE THREAD

**Issue by bibhuduttaGitHub** [TIBCOSoftware/bw6-plugin-maven#516]
@vpawar-ai : Most of our projects got resolved after applying required exclusion and scope for the jars.
However i see null pointer exception for a project, i have already validated the jar packaging of the dependent jars and transitive jars. I don't see any issue with respect to jar packaging. But still i get the null pointer exception. I have attached the project(Novatus) and the build debug logs and customxpathfunction jars to the case: 01888935. Take a look at them.

_Originally posted by @bibhuduttaGitHub in https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/505#issuecomment-724116047_

**Comment by vpawar-ai** [comment]
@bibhuduttaGitHub Remove the blank line at line no. 11 in `Novatus\META-INF\MANIFEST.MF` and try again.
