### ISSUE TITLE
No "Generate POM for Application"  option in Tibco BW 6.6.1

### ISSUE THREAD

**Issue by vallamv** [TIBCOSoftware/bw6-plugin-maven#518]
i am trying to generate POM file in BW 6.6.1
i installed maven plugin.  i did mvn -version from command line. 

C:\Users\vvallam\Downloads\TIB_BW_Maven_Plugin_2.7.0>mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Users\vvallam\Downloads\apache-maven-3.6.3-bin\apache-maven-3.6.3\bin\..
Java version: 15.0.1, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-15.0.1
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

after that i tried installing TIB_BW_Maven_Plugin_2.7.1 and i tried with TIB_BW_Maven_Plugin_2.7.0 

It shows build successful. but i am not seeing option "Generate POM for Application"
**output:**

C:\Users\vvallam\Downloads\TIB_BW_Maven_Plugin_2.7.0>install.bat

C:\Users\vvallam\Downloads\TIB_BW_Maven_Plugin_2.7.0>java -Dtibcohomepath= -cp antpackage.jar org.apache.tools.ant.launch.Launcher
Unable to locate tools.jar. Expected to find it in C:\Program Files (x86)\Java\jre1.8.0_172\lib\tools.jar
Buildfile: C:\Users\vvallam\Downloads\TIB_BW_Maven_Plugin_2.7.0\build.xml

getTibcoHome:
     [echo]
     [echo]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     [echo]                 Installing Plugin Code for Apache Maven and TIBCO BusinessWorksÖ
     [echo]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     [echo]
    [input]
    [input]                %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [input]
    [input]                  Input the path for Tibco Home here. Default will be c:\tibco
    [input]
    [input]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [input]
    [input]
C:\tibco_6.6
     [echo] BW Version 6.6

setupMacros:

vbuild.launcher.jar:

devbuild.launcher.jar:

studio-install:
     [echo]  Installing Eclipse M2E Plugin to Tibco Home
     [exec] An error has occurred.  See the log file
     [exec] C:\tibco_6.6\studio\4.0\eclipse\configuration\1605543238372.log
     [exec] Result: 13
     [exec] An error has occurred.  See the log file
     [exec] C:\tibco_6.6\studio\4.0\eclipse\configuration\1605543239240.log
     [exec] Result: 13
     [exec] An error has occurred.  See the log file
     [exec] C:\tibco_6.6\studio\4.0\eclipse\configuration\1605543240216.log
     [exec] Result: 13
     [echo]  UnInstalling the existing version of Plugin Code for Apache Maven and TIBCO BusinessWorksÖ
     [exec] An error has occurred.  See the log file
     [exec] C:\tibco_6.6\studio\4.0\eclipse\configuration\1605543241040.log
     [exec] Result: 13
     [echo]  Installing Studio Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorksÖ to the Tibco Home
     [exec] An error has occurred.  See the log file
     [exec] C:\tibco_6.6\studio\4.0\eclipse\configuration\1605543241838.log
     [exec] Result: 13

maven-install:
     [echo]  Installing Maven Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorksÖ to Local Maven Repository
    [mkdir] Created dir: C:\tibco_6.6\bw\6.6\maven\plugins
    [unzip] Expanding: C:\Users\vvallam\Downloads\TIB_BW_Maven_Plugin_2.7.0\config\bw6-maven-plugin.zip into C:\tibco_6.6\bw\6.6\maven\plugins\bw6-maven-plugin

winInstall:
     [exec]
     [exec] C:\tibco_6.6\bw\6.6\maven\plugins\bw6-maven-plugin>echo Installing Maven Plugin to Maven Repository
     [exec] Installing Maven Plugin to Maven Repository
     [exec]
     [exec] C:\tibco_6.6\bw\6.6\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=com.tibco.bw.palette.shared_6.1.100.003.jar -DgroupId=com.tibco.plugins -DartifactId=com.tibco.bw.palette.shared -Dversion=6.1.100 -Dpackaging=jar
     [exec]
     [exec] C:\tibco_6.6\bw\6.6\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=com.tibco.xml.cxf.common_1.3.200.001.jar -DgroupId=com.tibco.plugins -DartifactId=com.tibco.xml.cxf.common -Dversion=1.3.200 -Dpackaging=jar
     [exec]
     [exec] C:\tibco_6.6\bw\6.6\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=bw6-maven-plugin-2.7.0.jar -DpomFile=pom.xml
     [exec]
     [exec] C:\tibco_6.6\bw\6.6\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=fabric8/fabric8-maven-plugin-2.2.102.jar -DpomFile=fabric8/pom.xml

linuxInstall:

maven-plugin-install:

setup:

BUILD SUCCESSFUL
Total time: 28 seconds

C:\Users\vvallam\Downloads\TIB_BW_Maven_Plugin_2.7.0>install.bat

C:\Users\vvallam\Downloads\TIB_BW_Maven_Plugin_2.7.0>java -Dtibcohomepath= -cp antpackage.jar org.apache.tools.ant.launch.Launcher
Unable to locate tools.jar. Expected to find it in C:\Program Files (x86)\Java\jre1.8.0_172\lib\tools.jar
Buildfile: C:\Users\vvallam\Downloads\TIB_BW_Maven_Plugin_2.7.0\build.xml

getTibcoHome:
     [echo]
     [echo]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     [echo]                 Installing Plugin Code for Apache Maven and TIBCO BusinessWorksÖ
     [echo]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     [echo]
    [input]
    [input]                %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [input]
    [input]                  Input the path for Tibco Home here. Default will be c:\tibco
    [input]
    [input]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [input]
    [input]
C:\tibco_6.6
     [echo] BW Version 6.6

setupMacros:

vbuild.launcher.jar:

devbuild.launcher.jar:

studio-install:
     [echo]  Installing Eclipse M2E Plugin to Tibco Home
     [exec] An error has occurred.  See the log file
     [exec] C:\tibco_6.6\studio\4.0\eclipse\configuration\1605543238372.log
     [exec] Result: 13
     [exec] An error has occurred.  See the log file
     [exec] C:\tibco_6.6\studio\4.0\eclipse\configuration\1605543239240.log
     [exec] Result: 13
     [exec] An error has occurred.  See the log file
     [exec] C:\tibco_6.6\studio\4.0\eclipse\configuration\1605543240216.log
     [exec] Result: 13
     [echo]  UnInstalling the existing version of Plugin Code for Apache Maven and TIBCO BusinessWorksÖ
     [exec] An error has occurred.  See the log file
     [exec] C:\tibco_6.6\studio\4.0\eclipse\configuration\1605543241040.log
     [exec] Result: 13
     [echo]  Installing Studio Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorksÖ to the Tibco Home
     [exec] An error has occurred.  See the log file
     [exec] C:\tibco_6.6\studio\4.0\eclipse\configuration\1605543241838.log
     [exec] Result: 13

maven-install:
     [echo]  Installing Maven Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorksÖ to Local Maven Repository
    [mkdir] Created dir: C:\tibco_6.6\bw\6.6\maven\plugins
    [unzip] Expanding: C:\Users\vvallam\Downloads\TIB_BW_Maven_Plugin_2.7.0\config\bw6-maven-plugin.zip into C:\tibco_6.6\bw\6.6\maven\plugins\bw6-maven-plugin

winInstall:
     [exec]
     [exec] C:\tibco_6.6\bw\6.6\maven\plugins\bw6-maven-plugin>echo Installing Maven Plugin to Maven Repository
     [exec] Installing Maven Plugin to Maven Repository
     [exec]
     [exec] C:\tibco_6.6\bw\6.6\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=com.tibco.bw.palette.shared_6.1.100.003.jar -DgroupId=com.tibco.plugins -DartifactId=com.tibco.bw.palette.shared -Dversion=6.1.100 -Dpackaging=jar
     [exec]
     [exec] C:\tibco_6.6\bw\6.6\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=com.tibco.xml.cxf.common_1.3.200.001.jar -DgroupId=com.tibco.plugins -DartifactId=com.tibco.xml.cxf.common -Dversion=1.3.200 -Dpackaging=jar
     [exec]
     [exec] C:\tibco_6.6\bw\6.6\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=bw6-maven-plugin-2.7.0.jar -DpomFile=pom.xml
     [exec]
     [exec] C:\tibco_6.6\bw\6.6\maven\plugins\bw6-maven-plugin>start cmd.exe /C mvn install:install-file -Dfile=fabric8/fabric8-maven-plugin-2.2.102.jar -DpomFile=fabric8/pom.xml

linuxInstall:

maven-plugin-install:

setup:

BUILD SUCCESSFUL
Total time: 28 seconds

**ERROR**:  i do see error at studio built. 

this is error i see:

!SESSION Mon Nov 16 11:14:01 EST 2020 ------------------------------------------
!ENTRY org.eclipse.equinox.launcher 4 0 2020-11-16 11:14:01.058
!MESSAGE Exception launching the Eclipse Platform:
!STACK
java.lang.RuntimeException: Could not find framework
	at org.eclipse.equinox.launcher.Main.getBootPath(Main.java:1004)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:583)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

I tried re install couple times but it didnt worked.

**Comment by vpawar-ai** [comment]
Hi @vallamv, Eclipse error 13 is usually associated with Java and Eclipse version incompatibility. Please check if the installed JDK\JRE is 64-bit. It is recommended to use Java 1.8 (64-bit) with BW6 maven plugin.
