### ISSUE TITLE
How to provide path of profile instead of -Dprofile ?

### ISSUE THREAD

**Issue by aalapargekartibco** [TIBCOSoftware/bw6-plugin-maven#519]
Instead of saying "clean install -Dprofile=prod.substvar -Dredeploy=true" in the maven goals I want to provide path of the .substvar .

Something like this (it didn't work)
"clean install -DprofilePath=/SimpleRest6xAS/prod.substvar -Dredeploy=true"

I don't want to provide the location in the "Generate POM file" wizard because the location will be different for stage and prod.

Also can I get all possible arguments that can be passed in the goals? It would be helpful to have the complete list.

**Comment by vpawar-ai** [comment]
Hi @aalapargekartibco Please use `-DexternalProfile=true` and `-DexternalProfileLoc=<path-to-substvar>`. You can refer to application pom.xml `<properties>` element for list of all properties.

**Comment by aalapargekartibco** [comment]
Thanks @vpawar-ai
