### ISSUE TITLE
Can there be an external property file for Appspace ?

### ISSUE THREAD

**Issue by aalapargekartibco** [TIBCOSoftware/bw6-plugin-maven#522]
I have generated the pom for appspace using dev box details (bwagent host, port, domain name, appnode port etc..). A lot of these details are different between dev and prod.
One option is to use java properties in maven goals, something like 
clean install -Dprofile=prod.substvar -Dredeploy=true -DappSpace=xxx -DagentPort=xxx -DagentHost=xxx ........

You can see how the goal with become extremely lengthy. Is there a way to mention all these properties in an external property file instead and mention that property file in the maven goals ?

**Comment by vpawar-ai** [comment]
Hi @aalapargekartibco Please use `-DdeploymentConfigfile=<path-to-external-properties-file>` option to specify all properties.

**Comment by aalapargekartibco** [comment]
@vpawar-ai  perfect. Thanks.

**Comment by aalapargekartibco** [comment]
@vpawar-ai perfect. Thanks.

**Comment by aalapargekartibco** [comment]
@vpawar-ai  Can we mention a url in the -DdeploymentConfigfile ?

If I mention t like this then it is not taking it and proceeds with the configurations in the pom file.

clean install -DdeploymentConfigfile=https://gitlab.com/aalapargekar/artifacts/raw/master/SimpleRest6x/prod.properties -Dhttp.agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"

**Comment by vpawar-ai** [comment]
Externl URL for -DdeploymentConfigFile is supported in 2.8.0

**Comment by aalapargekartibco** [comment]
@vpawar-ai 

I am providing

clean install -DdeploymentConfigFile=https://gitlab.com/aalapargekar/artifacts/raw/master/SimpleRest6x/ProdPhilly.properties -DearUploadPath=/SimpleRest6xAS -Dhttp.agent=Mozilla/5.0

it is not taking the file from the url, it is defaulting to the properties in the pom file.

Am I doing anything wrong ?

**Comment by aalapargekartibco** [comment]
@vpawar-ai  verified, thanks
