### ISSUE TITLE
How to upload the EAR to a specific folder in TEA

### ISSUE THREAD

**Issue by aalapargekartibco** [TIBCOSoftware/bw6-plugin-maven#523]
I see that the EAR gets uploaded to the root folder. In TEA I have a folder for every application and would like the EARs to be uploaded to the specific folder. How can I mention the folder in the pom file or the maven goals ?

**Comment by aalapargekartibco** [comment]
@vpawar-ai  this will fix it.

Remotedeployer.java:
#314:
new change: uploadArchive(domainName, appName, file, true);
previous: uploadArchive(domainName, null, file, true);
#316:
new change: deployApplication(domainName, appSpaceName, earName, appName, true, replace, profile,externalProfile);
previous: deployApplication(domainName, appSpaceName, earName, null, true, replace, profile,externalProfile);

**Comment by vpawar-ai** [comment]
Hi @aalapargekartibco, I have marked this request as an enhancement and support for EAR folder path on TEA is getting added in upcoming release. User will be able to provide custom folder path via `earUploadPath` property in the maven goal. If you wish to contribute please feel free to raise the pull request. Thanks.

**Comment by aalapargekartibco** [comment]
@vpawar-ai  to which branch should I make the changes? Creating a new branch is not working for me.

$ git push -u origin aalap
remote: Permission to TIBCOSoftware/bw6-plugin-maven.git denied to aalapargekartibco.
fatal: unable to access 'https://github.com/TIBCOSoftware/bw6-plugin-maven/': The requested URL returned error: 403

**Comment by vpawar-ai** [comment]
Ear Upload path is supported in Maven plugin 2.8.0. Please provide the path using `earUploadPath` property.

**Comment by aalapargekartibco** [comment]
@vpawar-ai  verified. thanks.
