### ISSUE TITLE
More granular control over the bwrestapi commands in production

### ISSUE THREAD

**Issue by aalapargekartibco** [TIBCOSoftware/bw6-plugin-maven#524]
What is happening when I deploy a new version of an existing Tibco 6 application with redeploy=true is that it is undeploying the old one and then deploying and starting the new one.

In production, this is what I ideally want it  to do:
- Deploy new version (don't undeploy old version yet)
- Stop old version on one appnode.
- Start new version on that appnode.
- If new version started successfully on that appnode then move to 2nd appnode and similarly for rest of the appnodes. 
- If new version started successfully on all appnodes then Undeploy old version.

Is it possible to achieve this?

If not then is it possible that the plugin does what it does but just does not undeploy the old application ie.
- Deploy new version (don't undeploy old version)
- Stop old version.
- Start new version

**Comment by rutujadeo-TIBCO** [comment]
This feature is implemented in 6.10.0GA, as a part of [AMBW-47151](https://jira.tibco.com/browse/AMBW-47151) enhancement. Hence closing this github issue
