### ISSUE TITLE
How to mention gitlab url in externalProfileLoc ?

### ISSUE THREAD

**Issue by aalapargekartibco** [TIBCOSoftware/bw6-plugin-maven#525]
I gave
externalProfileLoc=https://gitlab.com/aalapargekar/artifacts/-/blob/master/SimpleRest6x/prod.substvar

It failed with ,
 Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.7.1:bwinstall (default-bwinstall) on project SimpleRest6xAS: Failed to deploy BW Application: Server returned HTTP response code: 403 for URL: https://gitlab.com/aalapargekar/artifacts/-/blob/master/SimpleRest6x/prod.substvar 

This is a public repositroy, you can open this url in browser without signing in to gitlab.

Is there a way to provide the url in externalProfileLoc?

**Comment by vpawar-ai** [comment]
Hi @aalapargekartibco, The plugin is using "user-agent: Java/1.8.0_41" (via apache commons) which is rejected by Gitlab. You can override that by executing maven goal as below -
`mvn clean install -Dhttp.agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"`
and please use raw file location - https://gitlab.com/aalapargekar/artifacts/raw/master/SimpleRest6x/prod.substvar

**Comment by aalapargekartibco** [comment]
Thanks @vpawar-ai . You are the best.

**Comment by aalapargekartibco** [comment]
@vpawar-ai 
When maven deploys with the property file externalized and the profile on gitlab, it names the profile as "external.
![Screenshot_1](https://user-images.githubusercontent.com/20302957/99998158-3c94fb00-2d8c-11eb-9c0e-890269916d54.jpg)


I am using:
externalProfileLoc=https://gitlab.com/aalapargekar/artifacts/raw/master/SimpleRest6x/prod.substvar, so ideally it should
use the name "prod" and not "external".

Anyways the problem is when I do a rebuild, it is failing while taking a backup.

[INFO] domain -> BW6STAGE-DBEMS earName -> SimpleRest6xAS_10.0.0.ear Ear file to be uploaded -> C:\Windows\System32\config\systemprofile\AppData\Local\Jenkins\.jenkins\workspace\SimpleRest6XASStage\tibco6\Code\ApplicationModules\SimpleRest6xAS\SimpleRest6xAS\target\SimpleRest6xAS_10.0.0.ear
[INFO] Generating backup ear file for application -> SimpleRest6xAS
[INFO] Downloaded successfully at: /SimpleRest6xAS\20201123-124840\SimpleRest6xAS_10.0.0.ear
[INFO] Generating backup substvar file for profile -> external.substvar
[ERROR] 
com.tibco.bw.maven.plugin.admin.client.ClientException: null: TIBCO-BW-ADMIN-500425: Profile [external.substvar] is not present in the Archive [SimpleRest6xAS_10.0.0.ear]

**Comment by aalapargekartibco** [comment]
@vpawar-ai  this is the solution.

add this import org.apache.commons.io.FilenameUtils;

#229 remove profilefile = new File(Constants.TEMP_SUBSTVAR); 
and add 			                
URL url = new URL(externalProfileLoc); 			                                                                  
profilefile = new File(FilenameUtils.getName(url.getPath()));

**Comment by vpawar-ai** [comment]
Fixed in 2.8.0

**Comment by aalapargekartibco** [comment]
@vpawar-ai , verified -  thanks
