### ISSUE TITLE
Service starts on only one appnode

### ISSUE THREAD

**Issue by aalapargekartibco** [TIBCOSoftware/bw6-plugin-maven#528]
starts on all applications after removing the **bolded line.**

private void startApplication(final String domainName, final String appSpaceName, final String appName, final String version, final String appNodeName) throws ClientException {
		init();
		try {
			**addQueryParam("appnode", appNodeName);**
			Response response = r.path("/domains").path(domainName).path("appspaces").path(appSpaceName).path("applications").path(appName).path(version).path("start").request(MediaType.APPLICATION_JSON_TYPE).post(null);
.
.
.
.

**Comment by vpawar-ai** [comment]
Fixed in 2.8.0.

**Comment by aalapargekartibco** [comment]
@vpawar-ai  - verified, thanks.
