### ISSUE TITLE
Proxy Configuration for Download Dependencies?

### ISSUE THREAD

**Issue by christiancgil** [TIBCOSoftware/bw6-plugin-maven#529]
Good Day Community

During plugin installation, the log show the following issue

!ENTRY org.eclipse.core.net 4 0 2020-11-18 12:25:07.763
!MESSAGE WinHttp.GetProxyForUrl for pac failed with error 'Error al procesar el script de configuración automática del proxy
' #12166.

!ENTRY org.eclipse.equinox.p2.transport.ecf 4 1002 2020-11-18 12:25:08.089
!MESSAGE HTTP Proxy Authentication Required: http://download.eclipse.org/releases/luna/artifacts.xml
!STACK 1
org.eclipse.ecf.filetransfer.BrowseFileTransferException: Proxy Authentication Required
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:287)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 org.eclipse.ecf.identity 4 0 2020-11-18 12:25:08.089
!MESSAGE Proxy Authentication Required

What is the procedure for Proxy Configuration?

**Comment by vpawar-ai** [comment]
@christiancgil In the studio, goto menu `Window->Preferences->General->Network Connection` and edit the proxy details.
