### ISSUE TITLE
Binary shared module support

### ISSUE THREAD

**Issue by teivah** [TIBCOSoftware/bw6-plugin-maven#53]
BW 6.3.4 just released the principle of binary shared modules.

I'm not yet an expert of this principle but I would see this feature as an opportunity for the Maven plugin to manage shared modules dependencies within an application module.

We could have one Maven goal to export a shared module as a binary asset. At the end, the obvious target would be to:
- Have the capability to reference a specific shared module (and a specific version) at design time.
- Embed it during the packaging of the application module.

Is it something already planned?

Thanks

**Comment by fanninj3** [comment]
Can anyone confirm if it planned for a future BW release to be able to have a shared module as a dependency in the POM file, instead of having to have the module present in the workspace for building?

**Comment by rahulkamdar** [comment]
@fanninj3 yes we are actively looking at that.

**Comment by mycrEEpy** [comment]
Please provide this feature as soon as possible.
It's currently a show stopper for automating our BW6 lifecycle!

**Comment by John-Zg** [comment]
This is indeed a show stopper for us as well. Hopefully this will be fixed asap. 
Rahul, your last comment was end of Nov last year, something happened since then?

**Comment by artificialintellect** [comment]
@rahulkamdar Is this still being actively worked on?

**Comment by rahulkamdar** [comment]
@artificialintellect, @John-Zg, @mycrEEpy - sorry for the delay. Work on this requires some significant internal arch support to make this a seamless experience. We are looking to address this in the short to medium term so hopefully this capability would be added in the near future. I'll update this again soon.

**Comment by artificialintellect** [comment]
@rahulkamdar - I just wanted to check in to see if this is still something that is planned, and if so if there was any sort of timeline for it

**Comment by rahulkamdar** [comment]
@artificialintellect - addressed and should've been closed. Please refer to https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/SharedModule. Closing now - please reopen with feedback/comments.
