### ISSUE TITLE
Strategy for Prod deployments

### ISSUE THREAD

**Issue by aalapargekartibco** [TIBCOSoftware/bw6-plugin-maven#531]
This is our deployment strategy. We have 2 environments - staging and prod.

There is a service RestService. 

Developer makes a change, increments package version to 2.0, checks in to staging branch in github.

Staging Jenkins job polls staging branch, it gets triggered. It builds RestService_2.0 ear, deploys to staging. This ear RestService_2.0 is not stored anywhere.

For prod deployments, we merge staging code into main branch. Prod Jenkins job polls main branch, it gets triggered. It builds RestService_2.0 ear, deploys to prod.

So the ear is getting built twice.

Is there a way to build only once and deploy across environments? Any recommended best practices ?

**Comment by vpawar-ai** [comment]
@aalapargekartibco Please use `mvn com.tibco.plugins:bw6-maven-plugin:bwdeployer` goal to deploy pre-built EAR without generating a new EAR.

**Comment by aalapargekartibco** [comment]
@vpawar-ai  I am giving the command like this in jenkins:

pom.xml com.tibco.plugins:bw6-maven-plugin:bwdeployer /SimpleRest6xAS/ear/SimpleRest6xAS_13.0.0.ear -DdeploymentConfigfile=/SimpleRest6xAS/download/ProdPhilly.properties -Dhttp.agent=Mozilla/5.0

It fails with this error:
_Unknown lifecycle phase "/SimpleRest6xAS/ear/SimpleRest6xAS_13.0.0.ear". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]_

I think I need to mention the ear path with some property, I did not find any property for this in the deployment.properties.

Can you please let me know the property ?

**Comment by aalapargekartibco** [comment]
@vpawar-ai  
figured it out :)

com.tibco.plugins:bw6-maven-plugin:bwdeployer -DearLocation=/SimpleRest6xAS/ear -DdeploymentConfigfile=/SimpleRest6xAS/download/ProdPhilly.properties -Dhttp.agent="Mozilla/5.0"
