### ISSUE TITLE
TibcoBW Maven plugin (2.7.1)Install is failing on Linux Server for Tibco BW6.6.1

### ISSUE THREAD

**Issue by jayasimhagithub** [TIBCOSoftware/bw6-plugin-maven#532]
Our Tibco BW maven plugin(2.7.1)  installation is failing  on Linux server
Our Linux server has no internet connection. So we need to install maven plugin by providing the dependency jars  from the installation directory to achieve it  We configured our build.xml as below .

Please help to share to share the org.eclipse.equinox.p2.discovery.zip 

Build.xml:
------------

_<target name="studio-install" >
        <echo> Installing Eclipse M2E Plugin to Tibco Home </echo>
        <p2.install repo="jar:file:///${project.dir}/config/org.eclipse.equinox.p2.discovery.zip!/" ius="org.eclipse.equinox.p2.discovery.feature.feature.group"/>
        <p2.install repo="jar:file:///${project.dir}/config/bw6.maven.dependencies-1.0.0.zip!/" ius="bw6.maven.dependencies.feature.feature.group"/>
        <p2.install repo="jar:file:///${project.dir}/config/org.eclipse.m2e.site-1.6.2.zip!/" ius="org.eclipse.m2e.feature.feature.group,org.eclipse.m2e.sdk.feature.feature.group,org.eclipse.m2e.logback.feature.feature.group"/>
        <echo> UnInstalling the existing version of Plugin Code for Apache Maven and TIBCO BusinessWorks™</echo>
        <p2.uninstall ius="bw6.studio.maven.feature.feature.group"/>
        <echo> Installing Studio Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorks™ to the Tibco Home </echo>
        <p2.install repo="jar:file:///${project.dir}/config/bw6.studio.maven.feature_2.7.1.zip!/" ius="bw6.studio.maven.feature.feature.group"/>_

Maven - plugin Install log:

studio-install:
     [echo]  Installing Eclipse M2E Plugin to Tibco Home
     [exec] Installation failed.
     [exec] The installable unit org.eclipse.equinox.p2.discovery.feature.feature.group has not been found.
     [exec] Application failed, log file location: /opt/tibco/studio/4.0/eclipse/configuration/1607536811413.log
     [exec]
     [exec] Result: 13
     [exec] Installing bw6.maven.dependencies.feature.feature.group _1.0.0.001._
     [exec] Operation completed in 6727 ms.
     [exec] Installing org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836.
     [exec] Installing org.eclipse.m2e.sdk.feature.feature.group 1.6.2.20151013-0836.
     [exec] Installing org.eclipse.m2e.logback.feature.feature.group 1.6.2.20151013-0836.
     [exec] Installation failed.
     [exec] Cannot complete the install because one or more required items could not be found.
     [exec]  Software being installed: m2e - Maven Integration for Eclipse (includes Incubating components) 1.6.2.20151013-0836 (org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836)
     [exec]  Missing requirement: m2e Marketplace 1.6.2.20151013-0836 (org.eclipse.m2e.discovery 1.6.2.20151013-0836) requires 'bundle org.eclipse.equinox.p2.ui.discovery 0.0.0' but it could not be found
     [exec]  Cannot satisfy dependency:
     [exec]   From: m2e - Maven Integration for Eclipse (includes Incubating components) 1.6.2.20151013-0836 (org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836)
     [exec]   To: org.eclipse.m2e.discovery [1.6.2.20151013-0836]
     [exec] Application failed, log file location: /opt/tibco/studio/4.0/eclipse/configuration/1607536832216.log
     [exec]
     [exec] Result: 13
     [echo]  UnInstalling the existing version of Plugin Code for Apache Maven and TIBCO BusinessWorks™
     [exec] Installation failed.
     [exec] The installable unit bw6.studio.maven.feature.feature.group has not been found.
     [exec] Application failed, log file location: /opt/tibco/studio/4.0/eclipse/configuration/1607536841894.log
     [exec]
     [exec] Result: 13
     [echo]  Installing Studio Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorks™ to the Tibco Home
     [exec] Installing bw6.studio.maven.feature.feature.group 2.7.1.001.
     [exec] Installation failed.
     [exec] Cannot complete the install because one or more required items could not be found.
     [exec]  Software being installed: TIBCO BusinessWorks™ Studio Feature for Maven 2.7.1.001 (bw6.studio.maven.feature.feature.group 2.7.1.001)
     [exec]  Missing requirement: TIBCO BusinessWorks™ Studio Plugin for Maven 2.7.1.001 (bw6.studio.maven.plugin 2.7.1.001) requires 'bundle org.eclipse.m2e.core [1.3.1,2.0.0)' but it could not be found
     [exec]  Cannot satisfy dependency:
     [exec]   From: TIBCO BusinessWorks™ Studio Feature for Maven 2.7.1.001 (bw6.studio.maven.feature.feature.group 2.7.1.001)
     [exec]   To: bw6.studio.maven.plugin [2.7.1.001]
     [exec] Application failed, log file location: /opt/tibco/studio/4.0/eclipse/configuration/1607536848975.log
     [exec]
     [exec] Result: 13

maven-install:
     [echo]  Installing Maven Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorks™ to Local Maven Repository
    [unzip] Expanding: /opt/fedex/tibco/TIB_BW_Maven_Plugin_2.7.1/config/bw6-maven-plugin.zip into /opt/tibco/bw/6.6/maven/plugins/bw6-maven-plugin

winInstall:

linuxInstall:
     [exec] Installing Maven Plugin to Maven Repository
     [exec] [INFO] Scanning for projects...
     [exec] Downloading: https://repo.maven.apache.org/maven2/org/sonatype/plugins/nexus-staging-maven-plugin/1.6.7/nexus-staging-maven-plugin-1.6.7.pom
     [exec]
     [exec] [ERROR] The build could not read 1 project -> [Help 1][ERROR]
     [exec] [ERROR]   The project com.tibco.plugins:bw6-maven-plugin:2.7.1 (/opt/tibco/bw/6.6/maven/plugins/bw6-maven-plugin/pom.xml) has 1 error
     [exec] [ERROR]     Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.7 or one of its dependencies could not be resolved: Failed to collect dependencies for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.7 (): Failed to read artifact descriptor for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.7: Could not transfer artifact org.sonatype.plugins:nexus-staging-maven-plugin:pom:1.6.7 from/to central (https://repo.maven.apache.org/maven2): Connection to https://repo.maven.apache.org refused: Connection timed out (Connection timed out) -> [Help 2]
     [exec] [ERROR]
     [exec] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
     [exec] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
     [exec] [ERROR]
     [exec] [ERROR] For more information about the errors and possible solutions, please read the following articles:
     [exec] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
     [exec] [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
     [exec] [INFO] Scanning for projects...
     [exec] Downloading: https://repo.maven.apache.org/maven2/org/sonatype/plugins/nexus-staging-maven-plugin/1.6.7/nexus-staging-maven-plugin-1.6.7.pom
     [exec]
     [exec] [ERROR] The build could not read 1 project -> [Help 1][ERROR]
     [exec] [ERROR]   The project com.tibco.plugins:bw6-maven-plugin:2.7.1 (/opt/tibco/bw/6.6/maven/plugins/bw6-maven-plugin/pom.xml) has 1 error
     [exec] [ERROR]     Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.7 or one of its dependencies could not be resolved: Failed to collect dependencies for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.7 (): Failed to read artifact descriptor for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.7: Could not transfer artifact org.sonatype.plugins:nexus-staging-maven-plugin:pom:1.6.7 from/to central (https://repo.maven.apache.org/maven2): Connection to https://repo.maven.apache.org refused: Connection timed out (Connection timed out) -> [Help 2]
     [exec] [ERROR]
     [exec] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
     [exec] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
     [exec] [ERROR]
     [exec] [ERROR] For more information about the errors and possible solutions, please read the following articles:
     [exec] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
     [exec] [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
     [exec] [INFO] Scanning for projects...
     [exec] Downloading: https://repo.maven.apache.org/maven2/org/sonatype/plugins/nexus-staging-maven-plugin/1.6.7/nexus-staging-

**Comment by vpawar-ai** [comment]
Please refer #514

**Comment by jayasimhagithub** [comment]
Thank you Pawar for the information . 
Now we got resolved the p2.discovery dependency issue .  But the maven dependency download is failing for us.

[exec] Installing Maven Plugin to Maven Repository
[exec] [INFO] Scanning for projects...
[exec] Downloading: https://repo.maven.apache.org/maven2/org/sonatype/plugins/nexus-staging-maven-plugin/1.6.7/nexus-staging-maven-plugin-1.6.7.pom
[exec]
[exec] [ERROR] The build could not read 1 project -> [Help 1][ERROR]
[exec] [ERROR] The project com.tibco.plugins:bw6-maven-plugin:2.7.1 (/opt/tibco/bw/6.6/maven/plugins/bw6-maven-plugin/pom.xml) has 1 error
[exec] [ERROR] Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.7 or one of its dependencies could not be resolved: Failed to collect dependencies for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.7 (): Failed to read artifact descriptor for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.7: Could not transfer artifact org.sonatype.plugins:nexus-staging-maven-plugin:pom:1.6.7 from/to central (https://repo.maven.apache.org/maven2): Connection to https://repo.maven.apache.org refused: Connection timed out (Connection timed out) -> [Help 2]
[exec] [ERROR]
[exec] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[exec] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[exec] [ERROR]
[exec] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[exec] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[exec] [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by jayasimhagithub** [comment]
Thank you for sharing the solution to place the jars for standalone  install.

**Comment by transferobject** [comment]
@jayasimhagithub can you list down all the steps which you took to install TIBCO Maven Plugin successfully on Linux server where there is no internet connection?
