### ISSUE TITLE
Generate POM for Application generating empty pom.xml files for module and application

### ISSUE THREAD

**Issue by babppv** [TIBCOSoftware/bw6-plugin-maven#534]
Maven Plugin version: 2.7.1

Maven version: 3.6.3

Product : TIBCO ActiveMatrix Businessworks 6

Product version:6.7.0

Component: Maven Eclipse Plugin

**Steps to reproduce the issue:**
1.Imported the project application in studio (bothe application and module)
2.Change the Maven install to use external maven 3.6.3 (Maven Instalaltions)
3.Select the application project and with the right button select generate POM for application

**Additional environment details if any:**

**Describe the results you received:**
The wizard does not start, no pop-up stating an error, nothing. In the filesystem I can see that the pom.xml were created for application and module projects but with 0 bytes.

**Describe the results you expected:**
I expected the "Generate POM for application" wizzard to display on studio and be able to follow the instructions to create the project.

**Additional information you deem important (e.g. issue happens only occasionally):**
In the .log file of stuido workspace I can see the following error:
!ENTRY com.tibco.bw.studio.maven.plugin 4 0 2020-12-12 17:53:16.078
!MESSAGE Failed to generate the POM file 
!STACK 0
java.lang.NullPointerException
	at com.tibco.bw.studio.maven.helpers.ManifestParser.parseManifest(ManifestParser.java:26)
	at com.tibco.bw.studio.maven.modules.BWProjectBuilder.buildModules(BWProjectBuilder.java:266)
	at com.tibco.bw.studio.maven.modules.BWProjectBuilder.build(BWProjectBuilder.java:66)
	at com.tibco.bw.studio.maven.action.MavenPOMProcessor.run(MavenPOMProcessor.java:72)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:253)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)

[.log](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5683562/default.log)
[SIBS_OpenBanking.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5683563/SIBS_OpenBanking.zip)

**Comment by vpawar-ai** [comment]
@babppv Please import `fwk.core` and `fwk.service` shared module projects in the workspace while launching the pom generation wizard.

**Comment by babppv** [comment]
Hi @vpawar-ai I've imported both of the shared modules but the issue is the same, the wizzard never launches and the same error appear in .log file. I've also created a different workspace and reimported the modules.

**Comment by vpawar-ai** [comment]
Please share the shared module code to reproduce the issue. You can share it via TIBCO support case and share the case number here if the artifacts can't be shared on github. Thanks.

**Comment by babppv** [comment]
Hi @vpawar-ai, my bad..., you were right, it was due to the lack of the other modules. The last time I did I missed one of them :)
