### ISSUE TITLE
Maven deployment  is failing 

### ISSUE THREAD

**Issue by amitmohanty15feb1988** [TIBCOSoftware/bw6-plugin-maven#535]
Maven Plugin version:TIB_BW_Maven_Plugin_2.7.1

Maven version:

Product : TIBCO Businessworks Container edition

Product version:Version: 2.5.3 V26 2020-05-15

Component: Maven build plugin

**Steps to reproduce the issue:**
1-Installed Docker for Desktop and enabled kubernetes
2-Using maven plugin deploying a rest service to local kubernetes cluster
3-Getting below error

**[ERROR] Failed to create Deployment from kubernetes.yml. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.docker.internal:6443/apis/extensions/v1beta1/namespaces/default/deployments. Message: the server could not find the requested resource. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=the server could not find the requested resource, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).. Deployment(apiVersion=extensions/v1beta1, kind=Deployment, metadata=ObjectMeta(annotations={fabric8.io/metrics-path=dashboard/file/kubernetes-pods.json/?var-project=RestService.application&var-version=1.0.0-SNAPSHOT}, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, initializers=null, labels={app=RestService.application, provider=fabric8, version=1.0.0-SNAPSHOT, group=com.tibco.bw}, name=bwcerest-app, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=DeploymentSpec(minReadySeconds=null, paused=null, progressDeadlineSeconds=null, replicas=1, revisionHistoryLimit=2, rollbackTo=null, selector=LabelSelector(matchExpressions=[], matchLabels={app=RestService.application, provider=fabric8, group=com.tibco.bw}, additionalProperties={}), strategy=null, template=PodTemplateSpec(metadata=ObjectMeta(annotations={fabric8.io/metrics-path=dashboard/file/kubernetes-pods.json/?var-project=RestService.application&var-version=1.0.0-SNAPSHOT}, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, initializers=null, labels={container=bwcerest-app, project=bwcerest-app, app=RestService.application, provider=fabric8, version=1.0.0-SNAPSHOT, group=com.tibco.bw}, name=bwcerest-app, namespace=default, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=PodSpec(activeDeadlineSeconds=null, affinity=null, automountServiceAccountToken=null, containers=[Container(args=[], command=[], env=[EnvVar(name=APP_CONFIG_PROFILE, value=docker, valueFrom=null, additionalProperties={}), EnvVar(name=BW_PROFILE, value=Dev, valueFrom=null, additionalProperties={}), EnvVar(name=CONSUL_SERVER_URL, value=http://172.17.0.3:8500, valueFrom=null, additionalProperties={})], envFrom=[], image=150219881234/demorestrep:bwcerestapp, imagePullPolicy=Always, lifecycle=null, livenessProbe=null, name=bwcerest-app, ports=[ContainerPort(containerPort=8080, hostIP=null, hostPort=null, name=http, protocol=null, additionalProperties={})], readinessProbe=null, resources=null, securityContext=null, stdin=null, stdinOnce=null, terminationMessagePath=null, terminationMessagePolicy=null, tty=null, volumeMounts=[], workingDir=null, additionalProperties={})], dnsPolicy=null, hostAliases=[], hostIPC=null, hostNetwork=null, hostPID=null, hostname=null, imagePullSecrets=[], initContainers=[], nodeName=null, nodeSelector=null, restartPolicy=null, schedulerName=null, securityContext=null, serviceAccount=null, serviceAccountName=null, subdomain=null, terminationGracePeriodSeconds=null, tolerations=[], volumes=[], additionalProperties={}), additionalProperties={}), additionalProperties={}), status=null, additionalProperties={})
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.docker.internal:6443/apis/extensions/v1beta1/namespaces/default/deployments. Message: the server could not find the requested resource. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=the server could not find the requested resource, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).**

Added the zipped project its working with docker goals successfully

**Describe the results you received:**

Failure executing: POST at: https://kubernetes.docker.internal:6443/apis/extensions/v1beta1/namespaces/default/deployments
during  Apply step

**Describe the results you expected:**

Should be successfully get deployed to local docker for Desktop Kubernetes

Attached here Error and Project i am using
[Mavenk8sDeploymentCode.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5684129/Mavenk8sDeploymentCode.zip)
[Error.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5684132/Error.zip)

**Comment by vpawar-ai** [comment]
Please refer #499

**Comment by amitmohanty15feb1988** [comment]
Hi @vpawar-ai 

Thanks for looking at the issue .I have done changes as per your suggestion. Changed fabric8-maven-plugin plugin version to 4.4.1 in all 3 pom.xml files

RestService.application.parent
RestService.application
RestService

After that i got a new error below .Full error is attached in 1stError.zip

**[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:4.4.1:resource (default-cli) on project RestService.application: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:4.4.1:resource failed. NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :RestService.application**

**Then i tried to change docker-maven-plugin plugin version from 0.24.1 to 0.34.1  .But still got same error.Full error is  attached in ErrorLatest.zip**

**[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:4.4.1:resource (default-cli) on project RestService.application: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:4.4.1:resource failed. NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :RestService.application**

**Attaching latest code .**
[1stError.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5689752/1stError.zip)
[ErrorLatest.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5689753/ErrorLatest.zip)
[LatestCode.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5689756/LatestCode.zip)


Can you please let me know how to get it work successfully.

Regards,
Amit

**Comment by vpawar-ai** [comment]
@amitmohanty15feb1988 Please enable debug logs to know more about the error. Please check port `fabric8.service.port (default 80) ` is available or not. For more help on fabric8 plugin - https://github.com/fabric8io/fabric8-maven-plugin

**Comment by amitmohanty15feb1988** [comment]
Hi @vpawar-ai 

I have taken another approach now i used yaml files for deployment and gave that yaml file location in k8s.dev.properties

like below 

fabric8.resources.location=D\:\\docker\\yaml

i have put pod.yaml and Service.yaml in above directory i got build success attached success log and pod.yaml and Service.yaml

**[INFO] --- fabric8-maven-plugin:3.5.41:apply (default-cli) @ RestService.application ---
[INFO] F8: Using Kubernetes at https://kubernetes.docker.internal:6443/ in namespace default with manifest D:\Mavenlatestworkspace3\RestService.application\target\classes\META-INF\fabric8\kubernetes.yml 
[INFO] Using namespace: default
[INFO] Creating a Service from kubernetes.yml namespace default name restservice-app
[INFO] Created Service: D:\Mavenlatestworkspace3\RestService.application\target\fabric8\applyJson\default\service-restservice-app.json
[INFO] Creating a Pod from kubernetes.yml namespace default name restservice-app
[INFO] Created Pod result: Pod(apiVersion=v1, kind=Pod, metadata=ObjectMeta(annotations=null, clusterName=null, creationTimestamp=2020-12-15T18:54:40Z, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, initializers=null, labels={app=RestService.application, group=com.tibco.bw, provider=fabric8, version=1.0.0-SNAPSHOT}, name=restservice-app, namespace=default, ownerReferences=[], resourceVersion=2216689, selfLink=/api/v1/namespaces/default/pods/restservice-app, uid=88157979-f831-4ef9-b0ab-49f49420e430, additionalProperties={}), spec=PodSpec(activeDeadlineSeconds=null, affinity=null, automountServiceAccountToken=null, containers=[Container(args=[], command=[], env=[EnvVar(name=BW_LOGLEVEL, value=DEBUG, valueFrom=null, additionalProperties={}), EnvVar(name=BW_PROFILE, value=Dev, valueFrom=null, additionalProperties={}), EnvVar(name=APP_CONFIG_PROFILE, value=docker, valueFrom=null, additionalProperties={}), EnvVar(name=CONSUL_SERVER_URL, value=http://172.17.0.3:8500, valueFrom=null, additionalProperties={})], envFrom=[], image=150219881234/demorestrep:v15, imagePullPolicy=Always, lifecycle=null, livenessProbe=null, name=restservice-app, ports=[ContainerPort(containerPort=8080, hostIP=null, hostPort=null, name=http, protocol=TCP, additionalProperties={})], readinessProbe=null, resources=ResourceRequirements(limits=null, requests=null, additionalProperties={}), securityContext=null, stdin=null, stdinOnce=null, terminationMessagePath=/dev/termination-log, terminationMessagePolicy=File, tty=null, volumeMounts=[VolumeMount(mountPath=/var/run/secrets/kubernetes.io/serviceaccount, name=default-token-rlncg, readOnly=true, subPath=null, additionalProperties={})], workingDir=null, additionalProperties={})], dnsPolicy=ClusterFirst, hostAliases=[], hostIPC=null, hostNetwork=null, hostPID=null, hostname=null, imagePullSecrets=[], initContainers=[], nodeName=null, nodeSelector=null, restartPolicy=Always, schedulerName=default-scheduler, securityContext=PodSecurityContext(fsGroup=null, runAsNonRoot=null, runAsUser=null, seLinuxOptions=null, supplementalGroups=[], additionalProperties={}), serviceAccount=default, serviceAccountName=default, subdomain=null, terminationGracePeriodSeconds=30, tolerations=[Toleration(effect=NoExecute, key=node.kubernetes.io/not-ready, operator=Exists, tolerationSeconds=300, value=null, additionalProperties={}), Toleration(effect=NoExecute, key=node.kubernetes.io/unreachable, operator=Exists, tolerationSeconds=300, value=null, additionalProperties={})], volumes=[Volume(awsElasticBlockStore=null, azureDisk=null, azureFile=null, cephfs=null, cinder=null, configMap=null, downwardAPI=null, emptyDir=null, fc=null, flexVolume=null, flocker=null, gcePersistentDisk=null, gitRepo=null, glusterfs=null, hostPath=null, iscsi=null, name=default-token-rlncg, nfs=null, persistentVolumeClaim=null, photonPersistentDisk=null, portworxVolume=null, projected=null, quobyte=null, rbd=null, scaleIO=null, secret=SecretVolumeSource(defaultMode=420, items=[], optional=null, secretName=default-token-rlncg, additionalProperties={}), storageos=null, vsphereVolume=null, additionalProperties={})], additionalProperties={enableServiceLinks=true, priority=0}), status=PodStatus(conditions=[], containerStatuses=[], hostIP=null, initContainerStatuses=[], message=null, phase=Pending, podIP=null, qosClass=BestEffort, reason=null, startTime=null, additionalProperties={}), additionalProperties={})
[INFO] F8: HINT: Use the command `kubectl get pods -w` to watch your pods start up
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] RestService.application.parent ..................... SUCCESS [  5.124 s]
[INFO] RestService ........................................ SUCCESS [  4.103 s]
[INFO] RestService.application ............................ SUCCESS [ 37.101 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 51.037 s
[INFO] Finished at: 2020-12-16T00:24:44+05:30
[INFO] Final Memory: 46M/453M
[INFO] ------------------------------------------------------------------------**

But when i am putting Deployment.yaml build is  failing attaching DEBUG logs (by using D:\bwce253\studio\4.0\eclipse\TIBCOBusinessStudio.exe -console -consoleLog -debug
command )and console logs from studio console also attached the latest code

wanted to know why only when deployment yaml i am giving build is failing

Regards,
Amit

[LatestCode_v1.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5698011/LatestCode_v1.zip)
[pod.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5698015/pod.zip)
[Service.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5698017/Service.zip)
[Deployment.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5698018/Deployment.zip)
[LatestError_V1.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5698019/LatestError_V1.zip)
[Successlog.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5698020/Successlog.zip)
[DEBUG LOGS.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5698022/DEBUG.LOGS.zip)

**Comment by amitmohanty15feb1988** [comment]
Hi @vpawar-ai ,

Thanks a lot for your inputs its working now

[INFO] F8: Using namespace: default
[INFO] F8: Creating a Deployment from kubernetes.yml namespace default name restservice-deployment
[INFO] F8: Created Deployment: ..\RestService.application\target\fabric8\applyJson\default\deployment-restservice-deployment.json
[INFO] F8: HINT: Use the command `kubectl get pods -w` to watch your pods start up
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] RestService.application.parent ..................... SUCCESS [  4.937 s]
[INFO] RestService ........................................ SUCCESS [  4.073 s]
[INFO] RestService.application ............................ SUCCESS [ 31.544 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 45.461 s
[INFO] Finished at: 2020-12-16T09:28:22+05:30
[INFO] Final Memory: 46M/392M
[INFO] ------------------------------------------------------------------------

But i have a question like if i want to automate the deployment via jenkins cicd then by default fabric8-maven-plugin version in studio in poms its coming as 3.5.41 so i had to do manual intervention to make plugin version to 4.4.1 .If i want to automate deployment then how it will work as default plugin version is coming as 3.5.41 .

**Comment by vpawar-ai** [comment]
The pom generation wizard now uses fabric8-maven-plugin version 4.4.1 from Maven plugin 2.8.0 onwards.

**Comment by amitmohanty15feb1988** [comment]
HI @vpawar-ai ,

Thanks a lot .Appreciate your great help.

Regards,
Amit Mohanty
