### ISSUE TITLE
Cannot generate pom for an application developed on Tibco 6.1

### ISSUE THREAD

**Issue by aalapargekartibco** [TIBCOSoftware/bw6-plugin-maven#540]
I am using maven plugin 2.8.0.

I have an old application that was developed on 6.1. The application has been been migrated to 6.7.1 now and is running fine but it was originally developed in 6.1.

I am getting this error when I try to generate the pom for it.
![generate pom error](https://user-images.githubusercontent.com/20302957/102297734-c6fcf480-3f1d-11eb-8b98-7aea69e4dafd.jpg)

Do I need to do anything different for this ? It is happening only for this application. Remaining applications which were originally developed in 6.7.1 are fine.

**Comment by vpawar-ai** [comment]
Please share the application code to reproduce the issue. You can share it via TIBCO support case and share the case number here if the artifacts can't be shared on github.

**Comment by aalapargekartibco** [comment]
@vpawar-ai  tibco support case number 01914089

**Comment by vpawar-ai** [comment]
@aalapargekartibco Please remove `com.tibco.custom.driver.jdbc.as400` from `Restock->Package Unit->Includes` and add it back again. Save Project. Launch the POM generation wizard.

**Comment by aalapargekartibco** [comment]
@vpawar-ai  that worked. thanks.

**Comment by aalapargekartibco** [comment]
@vpawar-ai that worked. thanks.
