### ISSUE TITLE
deployment.properties not created under parent with 2.8.0

### ISSUE THREAD

**Issue by aalapargekartibco** [TIBCOSoftware/bw6-plugin-maven#541]
This is not causing a problem. Juts want to make sure that this is expected and I am not doing anything wrong.

**Comment by vpawar-ai** [comment]
@aalapargekartibco The plugin is trying to generate `deployment.properties` while parent project is getting created for a new BW application. This will be addressed in future release. Please rerun the POM generation wizard to generate `deployment.properties` file.
