### ISSUE TITLE
com.tibco.plugins:bw6-maven-plugin:bwdeployer seems to be deploying the application thrice

### ISSUE THREAD

**Issue by aalapargekartibco** [TIBCOSoftware/bw6-plugin-maven#546]
In Jenkins, I am doing:

SalesForce/SalesForce.application.parent/pom.xml com.tibco.plugins:bw6-maven-plugin:bwdeployer -DearLocation=${WORKSPACE}/EARs/Current -DdeploymentConfigfile=${PROPERTY_FILES}/SalesForce/Dev.properties

It looks like it is deploying thrice - one for the parent pom, one for application pom, one for module pom.

What am I doing wrong?
[logs.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5741088/logs.txt)

**Comment by vpawar-ai** [comment]
@aalapargekartibco The `bwdeployer` goal is designed to deploy application when you only have an EAR file. You will need to create a dummy pom file. Please refer - https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/EAR-Deployment

**Comment by aalapargekartibco** [comment]
@vpawar-ai that worked. thanks.
