### ISSUE TITLE
need help with plugin project

### ISSUE THREAD

**Issue by aalapargekartibco** [TIBCOSoftware/bw6-plugin-maven#547]
I am using plugin version 2.8.0 and I tried following https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/Custom-XPath-Function-with-Maven

[LEAFClient.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5758039/LEAFClient.zip) and 
[IPSharedModule.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5758040/IPSharedModule.zip) are shared module binaries.

[com.tibco.custom.driver.jdbc.as400.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5758041/com.tibco.custom.driver.jdbc.as400.zip) is a plugin project.

[Restock.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5758042/Restock.zip)
is the application.

- I opened Restock, LEAFClient binary, IPSharedModule binary and com.tibco.custom.driver.jdbc.as400 in studio.
- Windows > preference > made sure maven is selected under maven installations.
- Right clicked Restock application > Generate pom.
- Command prompt > mvn install:install-file -Dfile=C:\tibco6\bw\6.6\system\shared\com.tibco.xml.cxf.common_1.3.600.001.jar -DgroupId=com.tibco.plugins -DartifactId=com.tibco.xml.cxf.common -Dversion=1.3.600 -Dpackaging=jar
- I see com.tibco.xml.cxf.common jar created at .m2 location.
- command prompt > mvn install:install-file -Dfile=C:\tibco6\bw\6.6\system\shared\org.osgi.service.jdbc_5.0.0.001\lib\org.osgi.service.jdbc.jar -DgroupId=com.tibco.plugins -DartifactId=org.osgi.service.jdbc -Dversion=5.0.0 -Dpackaging=jar
- I see org.osgi.service.jdbc jar created at .m2 location
- Added this [dependency.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5762546/dependency.txt)
 to the pom of com.tibco.custom.driver.jdbc.as400 in studio.
- Note that tibco.home and bw.home properties are present in restock application pom.xml.
- I right clicked pom of com.tibco.custom.driver.jdbc.as400 and did mvn install, I see com.tibco.custom.driver.jdbc.as400 jar created in .m2 location. This is the [as 400 pom.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5762552/as.400.pom.txt)
- Deleted  com.tibco.custom.driver.jdbc.as400 from the project.
- Right clicked module of Restock > maven > add dependency > groupId = com.tibco.bw, artifactId = com.tibco.custom.driver.jdbc.as400, version = 1.0.0-SNAPSHOT. It did not import the as400 into the project. I tried same with Right clicked module of Restock > maven > add plugin > provided the same details, still did not import the as400 into the project.

Requesting further direction.

**Comment by aalapargekartibco** [comment]
[LEAFClient.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5758039/LEAFClient.zip) and 
[IPSharedModule.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5758040/IPSharedModule.zip) are shared module binaries.

[com.tibco.custom.driver.jdbc.as400.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5758041/com.tibco.custom.driver.jdbc.as400.zip) is a plugin project.

[Restock.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5758042/Restock.zip)
is the application.

- I opened Restock, LEAFClient binary, IPSharedModule binary and com.tibco.custom.driver.jdbc.as400 in studio.
- Windows > preference > made sure maven is selected under maven installations.
- Right clicked Restock application > Generate pom.
- Command prompt > mvn install:install-file -Dfile=C:\tibco6\bw\6.6\system\shared\com.tibco.xml.cxf.common_1.3.600.001.jar -DgroupId=com.tibco.plugins -DartifactId=com.tibco.xml.cxf.common -Dversion=1.3.600 -Dpackaging=jar
- I see com.tibco.xml.cxf.common jar created at .m2 location.
- Added this [dependency.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5758058/dependency.txt) to the pom of com.tibco.custom.driver.jdbc.as400 in studio.
- After this step I am a not clear. I right clicked pom of com.tibco.custom.driver.jdbc.as400 and did mvn install, I got this [error.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5758053/error.txt). Requesting further direction.

**Comment by aalapargekartibco** [comment]
Requesting assistance on this.

**Comment by aalapargekartibco** [comment]
@vpawar-ai , apologies for tagging directly. This is a blocker for us.  requesting assistance from someone.

**Comment by vpawar-ai** [comment]
Hi @aalapargekartibco The steps mentioned at https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/Custom-XPath-Function-with-Maven are for Custom XPath Function project. Custom driver is a different functionality. Please do not add `com.tibco.xml.cxf.common` dependency for custom driver project. 

The Custom XPath function or Custom driver project is not supported to be added as Maven POM dependency.  Only External Shared Modules supports adding itself as POM dependency and then it imports binary project. So you will need to keep as400 driver project present in the workspace.

**Comment by aalapargekartibco** [comment]
@vpawar-ai if this were an xpath function then what would be the next steps if it is not to be added as a maven dependency?

**Comment by vpawar-ai** [comment]
Hi @aalapargekartibco Please follow below steps -

- command prompt > mvn install:install-file -Dfile=C:\tibco6\bw\6.6\system\shared\org.osgi.service.jdbc_5.0.0.001\lib\org.osgi.service.jdbc.jar -DgroupId=com.tibco.plugins -DartifactId=org.osgi.service.jdbc -Dversion=5.0.0 -Dpackaging=jar
- Import application, module projects and custom driver project in the workspace.
- Launch `Generate POM for application` wizard. You should see custom driver project listed in the project list. Provide details and Click Finish. (If you dont see custom driver project in the list, please add it to "Restock->Package Unit->Includes").
- Edit Custom Driver projects POM.xml and add maven dependency 
```xml
<dependency>
  		<groupId>com.tibco.plugins</groupId>
  		<artifactId>org.osgi.service.jdbc</artifactId>
  		<version>5.0.0</version>
  		<scope>provided</scope>
  </dependency>
```
- Execute maven goal `clean package` on `Restock.parent` project.

**Comment by aalapargekartibco** [comment]
Thanks @vpawar-ai
