### ISSUE TITLE
After deployment if application status is "Starting" then getting error "No enum constant"

### ISSUE THREAD

**Issue by aalapargekartibco** [TIBCOSoftware/bw6-plugin-maven#548]
Using plugin version 2.8.0

Application.java line #32 
public enum ApplicationRuntimeStates {
        Running, Stopped, Impaired, FlowControlled, Paused, StartFailed, AppError, DeployFailed, Unreachable, Deploying, Stopping, Degraded, Starting
    }

The last value is "Starting", but it is not part of the enum for some reason. If the application is actually starting then i get this error:
com.tibco.bw.maven.plugin.admin.client.ClientException: null: TIBCO-BW-ADMIN-500000: No enum constant com.tibco.bw.thor.admin.dto.Application.ApplicationRuntimeStates.Starting
    at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.processErrorResponse (RemoteDeployer.java:724)

I tried changed it to the below and rebuilt the jar but that did not solve the issue. 
public enum ApplicationRuntimeStates {
        Running, Stopped, Impaired, FlowControlled, Paused, StartFailed, AppError, DeployFailed, Unreachable, Deploying, Stopping, Degraded, Starting, Dummy
    }

Whatever the fix, it needs to be applied to the application deployment states and the states mentioned in appspace and appnode java files.

**Comment by aalapargekartibco** [comment]
requesting someone to have a look.

**Comment by aalapargekartibco** [comment]
@vpawar-ai requesting soemone to have a look.

**Comment by aalapargekartibco** [comment]
following up

**Comment by SujataDarekar** [comment]
@aalapargekartibco The issue is not reproducible. Attaching screenshot for your reference

**Comment by SujataDarekar** [comment]
[
![image-2021-05-21-14-08-45-363](https://user-images.githubusercontent.com/31987978/119795572-3aa42400-bef6-11eb-882c-cbc7b8d087f2.png)
](url)
