### ISSUE TITLE
Managing multiple parent applications for shared modules used by more than one application

### ISSUE THREAD

**Issue by rahulkamdar** [TIBCOSoftware/bw6-plugin-maven#55]
Description: If you have a shared module that is used by different applications in the workspace, you have always to create the pom file of the shared module before deploying it because the “parent” section is overwritten where the parent application is referenced

Maven Plugin version: 1.1.0

Maven version: 3.3.3+

Product : Both of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version: BW 6.3.4, BWCE 2.2.0

Component: Maven Eclipse Plugin

**Steps to reproduce the issue:**
1. Have a shared module "SM".
2. Have 2 parent modules "PM1" and "PM2" that both use and depend on "SM".
3. Create POM files for "PM1" & "PM2" and as a result for "SM" as well.
4. Build "PM1" with "SM". Now try building "PM2" with "SM" without re-creating POM file.

**Describe the results you received:**
PM2 doesn't get built since SM's POM refers to PM1 and not PM2. SM POM needs to be re-created to refer to PM2 before building.

**Describe the results you expected:**
SM POM could have 2 parent applications - PM1 and PM2 and hence can be created once and used as required.

**Comment by ashutoshbhide** [comment]
This now can be solved with the "Shared Module as Maven Dependency" functionality. 
Now Shared Module need not be defined in the POM file but can be defined as POM dependency and hence this issue will be solved.
