### ISSUE TITLE
Maven installation requirement wiki page should include JDK 8 dependency

### ISSUE THREAD

**Issue by alexandrev** [TIBCOSoftware/bw6-plugin-maven#551]
As to install the Maven Plugin JDK 8 is required as it is failing using Java 11, we should include that step as a requirement in the Wiki, so no other users can be affected with this problem.

Regards,

**Comment by vpawar-tibco** [comment]
Done. Please refer - https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/BW-Release-Compatibility-Guide
