### ISSUE TITLE
Missing dependent Equinox p2 discovery with Maven plugin v2.8 installation

### ISSUE THREAD

**Issue by katharineyau** [TIBCOSoftware/bw6-plugin-maven#560]
Maven Plugin version:
2.8
Maven version:
3.6.3
Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition
TIBCO Businessworks Container edition
Product version:
2.6
Component: Either of Maven Eclipse Plugin or Maven build plugin
Maven Eclipse Plugin

**Steps to reproduce the issue:**
1. Installed BWCEv2.6
2. Run TIBCO Maven Plugin install
3. Install failed with error:

    [exec] Cannot complete the install because one or more required items could not be found.
     [exec]  Software being installed: m2e - Maven Integration for Eclipse (includes Incubating components) 1.6.2.20151013-0836 (org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836)
     [exec] Installation failed.
    [exec]  Missing requirement: m2e Marketplace 1.6.2.20151013-0836 (org.eclipse.m2e.discovery 1.6.2.20151013-0836) requires 'bundle org.eclipse.equinox.p2.ui.discovery 0.0.0' but it could not be found
     [exec]  Cannot satisfy dependency:
     [exec]   From: m2e - Maven Integration for Eclipse (includes Incubating components) 1.6.2.20151013-0836 (org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836)
     [exec]   To: org.eclipse.m2e.discovery [1.6.2.20151013-0836]
     [exec] Application failed, log file location: /d1/opt/tibco/bwce/studio/4.0/eclipse/configuration/1612314595997.log
     [exec] 
     [exec] Result: 13

4. The TIBCO BusinessWorks™ Studio Feature for Maven v2.8.0.001 is NOT installed in BusinessStudio.
 
**Additional environment details if any:**

**Describe the results you received:**
Full installation output:
[yau_k@dhubdv214 TIB_BW_Maven_Plugin_2.8.0]$ ./install.sh
Starting Plugin Code for Apache Maven and TIBCO BusinessWorks™ installation .... 
Unable to locate tools.jar. Expected to find it in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/lib/tools.jar
Buildfile: /d1/Install/TIB_BW_Maven_Plugin_2.8.0/build.xml

getTibcoHome:
     [echo]  
     [echo]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     [echo]                 Installing Plugin Code for Apache Maven and TIBCO BusinessWorks™
     [echo]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     [echo]                  
    [input] 
    [input] 		   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [input] 
    [input]                  Input the path for Tibco Home here. Default will be c:\tibco  
    [input] 
    [input]                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [input] 		
    [input] 		
/d1/opt/tibco/bwce
     [echo] BWCE Version 2.6

setupMacros:

vbuild.launcher.jar:

devbuild.launcher.jar:

studio-install:
     [echo]  Installing Eclipse M2E Plugin to Tibco Home 
     [exec] log4j:WARN No appenders could be found for logger (org.apache.http.impl.conn.SingleClientConnManager).
     [exec] log4j:WARN Please initialize the log4j system properly.
     [exec] Installation failed.
     [exec] The installable unit org.eclipse.equinox.p2.discovery.feature.feature.group has not been found.
     [exec] Application failed, log file location: /d1/opt/tibco/bwce/studio/4.0/eclipse/configuration/1612314586897.log
     [exec] 
     [exec] Result: 13
     [exec] Installing bw6.maven.dependencies.feature.feature.group 1.0.0.001.
     [exec] Operation completed in 2905 ms.
     [exec] Installing org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836.
     [exec] Installing org.eclipse.m2e.sdk.feature.feature.group 1.6.2.20151013-0836.
     [exec] Installing org.eclipse.m2e.logback.feature.feature.group 1.6.2.20151013-0836.
     [exec] Cannot complete the install because one or more required items could not be found.
     [exec]  Software being installed: m2e - Maven Integration for Eclipse (includes Incubating components) 1.6.2.20151013-0836 (org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836)
     [exec] Installation failed.
     [exec]  Missing requirement: m2e Marketplace 1.6.2.20151013-0836 (org.eclipse.m2e.discovery 1.6.2.20151013-0836) requires 'bundle org.eclipse.equinox.p2.ui.discovery 0.0.0' but it could not be found
     [exec]  Cannot satisfy dependency:
     [exec]   From: m2e - Maven Integration for Eclipse (includes Incubating components) 1.6.2.20151013-0836 (org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836)
     [exec]   To: org.eclipse.m2e.discovery [1.6.2.20151013-0836]
     [exec] Application failed, log file location: /d1/opt/tibco/bwce/studio/4.0/eclipse/configuration/1612314595997.log
     [exec] 
     [exec] Result: 13
     [echo]  UnInstalling the existing version of Plugin Code for Apache Maven and TIBCO BusinessWorks™
     [exec] The installable unit bw6.studio.maven.feature.feature.group has not been found.
     [exec] Application failed, log file location: /d1/opt/tibco/bwce/studio/4.0/eclipse/configuration/1612314600139.log
     [exec] Installation failed.
     [exec] 
     [exec] Result: 13
     [echo]  Installing Studio Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorks™ to the Tibco Home 
     [exec] Installing bw6.studio.maven.feature.feature.group 2.8.0.001.
     [exec] Installation failed.
     [exec] Cannot complete the install because one or more required items could not be found.
     [exec]  Software being installed: TIBCO BusinessWorks™ Studio Feature for Maven 2.8.0.001 (bw6.studio.maven.feature.feature.group 2.8.0.001)
	 
     [exec]  Missing requirement: TIBCO BusinessWorks™ Studio Plugin for Maven 2.8.0.001 (bw6.studio.maven.plugin 2.8.0.001) requires 'bundle org.eclipse.m2e.core [1.3.1,2.0.0)' but it could not be found
     [exec]  Cannot satisfy dependency:
     [exec]   From: TIBCO BusinessWorks™ Studio Feature for Maven 2.8.0.001 (bw6.studio.maven.feature.feature.group 2.8.0.001)
     [exec]   To: bw6.studio.maven.plugin [2.8.0.001]
     [exec] Application failed, log file location: /d1/opt/tibco/bwce/studio/4.0/eclipse/configuration/1612314602995.log
     [exec] 
     [exec] Result: 13

maven-install:
     [echo]  Installing Maven Plugin for Plugin Code for Apache Maven and TIBCO BusinessWorks™ to Local Maven Repository
    [unzip] Expanding: /d1/Install/TIB_BW_Maven_Plugin_2.8.0/config/bw6-maven-plugin.zip into /d1/opt/tibco/bwce/bwce/2.6/maven/plugins/bw6-maven-plugin

winInstall:

linuxInstall:
     [exec] Installing Maven Plugin to Maven Repository
     [exec] [INFO] Scanning for projects...
     [exec] [INFO] Inspecting build with total of 1 modules...
     [exec] [INFO] Installing Nexus Staging features:
     [exec] [INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
     [exec] [INFO] 
     [exec] [INFO] -----------------< com.tibco.plugins:bw6-maven-plugin >-----------------
     [exec] [INFO] Building Plugin Code for Apache Maven and TIBCO BusinessWorks™ 2.8.0
     [exec] [INFO] ----------------------------[ maven-plugin ]----------------------------
     [exec] [INFO] 
     [exec] [INFO] --- maven-install-plugin:2.4:install-file (default-cli) @ bw6-maven-plugin ---
     [exec] [INFO] Installing /d1/opt/tibco/bwce/bwce/2.6/maven/plugins/bw6-maven-plugin/com.tibco.bw.palette.shared_6.1.100.003.jar to /d1/usr/ASXPROD/yau_k/.m2/repository/com/tibco/plugins/com.tibco.bw.palette.shared/6.1.100/com.tibco.bw.palette.shared-6.1.100.jar
     [exec] [INFO] ------------------------------------------------------------------------
     [exec] [INFO] BUILD SUCCESS
     [exec] [INFO] ------------------------------------------------------------------------
     [exec] [INFO] Total time:  1.170 s
     [exec] [INFO] Finished at: 2021-02-03T12:10:09+11:00
     [exec] [INFO] ------------------------------------------------------------------------
     [exec] [INFO] Scanning for projects...
     [exec] [INFO] Inspecting build with total of 1 modules...
     [exec] [INFO] Installing Nexus Staging features:
     [exec] [INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
     [exec] [INFO] 
     [exec] [INFO] -----------------< com.tibco.plugins:bw6-maven-plugin >-----------------
     [exec] [INFO] Building Plugin Code for Apache Maven and TIBCO BusinessWorks™ 2.8.0
     [exec] [INFO] ----------------------------[ maven-plugin ]----------------------------
     [exec] [INFO] 
     [exec] [INFO] --- maven-install-plugin:2.4:install-file (default-cli) @ bw6-maven-plugin ---
     [exec] [INFO] Installing /d1/opt/tibco/bwce/bwce/2.6/maven/plugins/bw6-maven-plugin/com.tibco.xml.cxf.common_1.3.200.001.jar to /d1/usr/ASXPROD/yau_k/.m2/repository/com/tibco/plugins/com.tibco.xml.cxf.common/1.3.200/com.tibco.xml.cxf.common-1.3.200.jar
     [exec] [INFO] ------------------------------------------------------------------------
     [exec] [INFO] BUILD SUCCESS
     [exec] [INFO] ------------------------------------------------------------------------
     [exec] [INFO] Total time:  1.017 s
     [exec] [INFO] Finished at: 2021-02-03T12:10:12+11:00
     [exec] [INFO] ------------------------------------------------------------------------
     [exec] [INFO] Scanning for projects...
     [exec] [INFO] Inspecting build with total of 1 modules...
     [exec] [INFO] Installing Nexus Staging features:
     [exec] [INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
     [exec] [INFO] 
     [exec] [INFO] -----------------< com.tibco.plugins:bw6-maven-plugin >-----------------
     [exec] [INFO] Building Plugin Code for Apache Maven and TIBCO BusinessWorks™ 2.8.0
     [exec] [INFO] ----------------------------[ maven-plugin ]----------------------------
     [exec] [INFO] 
     [exec] [INFO] --- maven-install-plugin:2.4:install-file (default-cli) @ bw6-maven-plugin ---
     [exec] [INFO] Installing /d1/opt/tibco/bwce/bwce/2.6/maven/plugins/bw6-maven-plugin/bw6-maven-plugin-2.8.0.jar to /d1/usr/ASXPROD/yau_k/.m2/repository/com/tibco/plugins/bw6-maven-plugin/2.8.0/bw6-maven-plugin-2.8.0.jar
     [exec] [INFO] Installing /d1/opt/tibco/bwce/bwce/2.6/maven/plugins/bw6-maven-plugin/pom.xml to /d1/usr/ASXPROD/yau_k/.m2/repository/com/tibco/plugins/bw6-maven-plugin/2.8.0/bw6-maven-plugin-2.8.0.pom
     [exec] [INFO] ------------------------------------------------------------------------
     [exec] [INFO] BUILD SUCCESS
     [exec] [INFO] ------------------------------------------------------------------------
     [exec] [INFO] Total time:  1.099 s
     [exec] [INFO] Finished at: 2021-02-03T12:10:14+11:00
     [exec] [INFO] ------------------------------------------------------------------------
     [exec] [INFO] Scanning for projects...
     [exec] [INFO] Inspecting build with total of 1 modules...
     [exec] [INFO] Installing Nexus Staging features:
     [exec] [INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
     [exec] [INFO] 
     [exec] [INFO] -----------------< com.tibco.plugins:bw6-maven-plugin >-----------------
     [exec] [INFO] Building Plugin Code for Apache Maven and TIBCO BusinessWorks™ 2.8.0
     [exec] [INFO] ----------------------------[ maven-plugin ]----------------------------
     [exec] [INFO] 
     [exec] [INFO] --- maven-install-plugin:2.4:install-file (default-cli) @ bw6-maven-plugin ---
     [exec] [INFO] Installing /d1/opt/tibco/bwce/bwce/2.6/maven/plugins/bw6-maven-plugin/fabric8/fabric8-maven-plugin-4.4.1.jar to /d1/usr/ASXPROD/yau_k/.m2/repository/io/fabric8/fabric8-maven-plugin/4.4.1/fabric8-maven-plugin-4.4.1.jar
     [exec] [INFO] Installing /d1/opt/tibco/bwce/bwce/2.6/maven/plugins/bw6-maven-plugin/fabric8/pom.xml to /d1/usr/ASXPROD/yau_k/.m2/repository/io/fabric8/fabric8-maven-plugin/4.4.1/fabric8-maven-plugin-4.4.1.pom
     [exec] [INFO] ------------------------------------------------------------------------
     [exec] [INFO] BUILD SUCCESS
     [exec] [INFO] ------------------------------------------------------------------------
     [exec] [INFO] Total time:  1.070 s
     [exec] [INFO] Finished at: 2021-02-03T12:10:16+11:00
     [exec] [INFO] ------------------------------------------------------------------------

maven-plugin-install:

setup:

BUILD SUCCESSFUL
Total time: 41 seconds

**Describe the results you expected:**
The plugin is successfully installed and mave workspace built successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by richardelowe** [comment]
Additional information for this:

- Issue was occurring on RHEL 7.x
- The machine doesn't have direct access to the internet - internet access is via a proxy

**Comment by vpawar-tibco** [comment]
Hi @richardelowe Please refer #514
