### ISSUE TITLE
shared module disappearing from studio after installing maven plugin 2.7.0 in BWCE 2.5.4

### ISSUE THREAD

**Issue by bibhuduttaGitHub** [TIBCOSoftware/bw6-plugin-maven#561]
Maven Plugin version: 2.7.0

Maven version: 3.6.3

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version: BWCE 2.5.4

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1. Install BWCE 2.5.4 , Import the Project and add Shared Module and add as a dependency to the BW module
2.  Close Studio. Install Maven plugin 2.7.0 in BWCE 2.5.4 HOME
3. Re-open the studio workspace created in step-1, the shared module disappears

**Additional environment details if any:**
Without installing the maven plugin, shared module is available in studio.

**Describe the results you received:**
Shared module disappearing from the workspace.

**Describe the results you expected:**
Shared module should be available.

**Additional information you deem important (e.g. issue happens only occasionally):**
Retried with re-installing maven plugin, did not help.

**Comment by bibhuduttaGitHub** [comment]
Team,
We are in stuck in this issue. Can this be prioritized.

**Comment by SujataDarekar** [comment]
@bibhuduttaGitHub The issue does not look specific to Maven Plugin. Still we will reproduce at our end will update you accordingly

**Comment by vpawar-tibco** [comment]
Hi @bibhuduttaGitHub Could you please provide more information on -

1. Whether the BW application project & Shared module project was already mavenized while importing in step 1?
2. If yes, how the shared module was referenced? was it added as POM dependency in application module pom.xml file?
3. Please share the project on support case to reproduce the issue and share the support case number.

Thanks.

**Comment by bibhuduttaGitHub** [comment]
Hi @vpawar-tibco : find my answers inline:

Whether the BW application project & Shared module project was already mavenized while importing in step 1? --- no
If yes, how the shared module was referenced? was it added as POM dependency in application module pom.xml file? -- NA, as it was not yet mavenized
Please share the project on support case to reproduce the issue and share the support case number. -- case# 01924263 has the details. Please go through it once.

**Comment by bibhuduttaGitHub** [comment]
any update please.

**Comment by SujataDarekar** [comment]
@bibhuduttaGitHub Working on the issue

**Comment by SujataDarekar** [comment]
@bibhuduttaGitHub The project which has been attached with case id is mavenized one and we do not provide support for  ESM added using Target platform and Dependencies section of Module project for Mavenized project. It could be possible that you deleted the pom.xml manually but still in .project.xml when we mavenized the project we add nature as "org.eclipse.m2e.core.maven2Nature" which should be there in project. Can you please check if you have "org.eclipse.m2e.core.maven2Nature" entry in .project.xml file present in module and application project. If the entry is present then please delete it and try to add ESM.

**Comment by SujataDarekar** [comment]
@bibhuduttaGitHub any update?

**Comment by SujataDarekar** [comment]
@bibhuduttaGitHub Closing the issue since there is no response from long time. Please reopen in case you have any query
