### ISSUE TITLE
bwTest: support for passing vm arguments, similar to surefire:test argLine

### ISSUE THREAD

**Issue by robertsi** [TIBCOSoftware/bw6-plugin-maven#563]
We are using njams client.If we exeute` mvn test` it fails with error:

` ERROR [main] com.faizsiegeln.njams.bw6.Activator - nJAMS bundle not started because nJAMS configuration file is not configured. [njams.bw6.config]`

This is because njams requires config file to be passed as vm parameter and it seems we cannot pass it. 
A good solution would be something like argLine on http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#argLine so we could set property argLine in pom or via cmdline like 

`mvn test -DargLine="-Dnjams.bw6.config=c:/tibco_6_6_0/bw/6.6/config/njams/njams.properties"`

KR,
Robert

**Comment by SujataDarekar** [comment]
Closing the issue since changes have been done. Please refer https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/List-of-BW-Maven-Plugin-Properties#5-customargengine for more details
