### ISSUE TITLE
Cannot open shared module process mapping

### ISSUE THREAD

**Issue by AndreAfonso87** [TIBCOSoftware/bw6-plugin-maven#564]
Maven Plugin version: 2.7.1

Maven version: 3.6.3

Product : TIBCO Businessworks Container edition

Product version: 2.5.4

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1. Having Maven shared module with sub process
2. Open shared module process activity, for example mapper with some complex xml elements mapped
3. Try to check mapped elements inside closed xml elements. Try to scroll if there are more mappings below.

**Additional environment details if any:**

**Describe the results you received:**
Cannot open/see some mappings. Scroll is locked
Issue present on BWCE 2.5.3/2.5.4/2.6.0

**Describe the results you expected:**
Able to check/open mappings. This was working on BWCE 2.5.0

**Additional information you deem important (e.g. issue happens only occasionally):**
Also during debug, cannot add breakpoints to processes in shared module. This was working in 2.5.0
Issue is related to #483

**Comment by SujataDarekar** [comment]
@AndreAfonso87 This has been fixed with BWCE2.6.2. For details please refer BWCE-3587

**Comment by AndreAfonso87** [comment]
I installed 2.62 + maven plugin 2.8.1 and still it doesn't work.
I can't check any element mapping or scroll in maven shared modules.
