### ISSUE TITLE
Can't create an external Shared Module using Maven Plugin 2.8.0 from within BusinessStudio

### ISSUE THREAD

**Issue by richardelowe** [TIBCOSoftware/bw6-plugin-maven#565]
-------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

Maven Plugin version: 2.8.0

Maven version: 3.3.3 (embedded within Studio)

Product : TIBCO Businessworks Container edition

Product version: 2.6.0

Component: Maven Eclipse Plugin

**Steps to reproduce the issue:**
1. Follow instructions here for creating an External Shared Module (Steps 1 and 2) with Maven:
https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/SharedModule

**Additional environment details if any:**
MacOS

**Describe the results you received:**
When trying to complete Step 2 (creating a Maven debug configuration in BW and installing the shared module as a plugin) the build fails with the attached error message

**Describe the results you expected:**
Expected that the build would install the Shared Module into the local .m2 repository 

**Additional information you deem important (e.g. issue happens only occasionally):**
If you add a new Maven installation and use 3.6.1 then the Shared Module builds correctly

[MavenSharedModuleError.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/6007346/MavenSharedModuleError.txt)

**Comment by richardelowe** [comment]
This also happens with BWCE 2.6.1

**Comment by SujataDarekar** [comment]
@richardelowe As per the logs I can see the error is "Error injecting: private org.eclipse.aether.spi.log.Logger org.apache.maven.repository.internal.DefaultVersionResolver.logger" .This looks Maven Version incompatible issue. You can set Maven Installation version to latest one in the Studio
For details please refer "_Configure Maven Installation and local m2 repo location in Eclipse_" point from page https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/Troubleshooting

**Comment by richardelowe** [comment]
Thanks Sujata. Should it work with version that is bundled with Studio? If not, we should update the documentation to say that a separate Maven installation is required, e.g. in this page: 
https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/Building-applications-for-TIBCO-BusinessWorks-Container-Edition
...instead of just the troubleshooting.

**Comment by SujataDarekar** [comment]
@richardelowe We have updated the documentation. Thanks! Closing the issue. Reopen for any query
