### ISSUE TITLE
Backward compatibility of Maven Plugin 2.8 with BWCE 2.5.4

### ISSUE THREAD

**Issue by bibhuduttaGitHub** [TIBCOSoftware/bw6-plugin-maven#566]
Team,
We have complete CI/CD structure defined in Jenkins using Maven PLugin 2.7.
As i see the Maven Plugin 2.8 version is getting released and compatible with only  BWCE 2.6, we want to know whether we can use Maven plugin 2.8 with BWCE 2.5.4 codebase or not?
 Do we really have to start using BWCE 2.6 to take benefit of Maven Plugin 2.8?
Is there a migration process involved? Or Will it work seamlessly after updating the Plugin to 2.8 ?

Maven Plugin version: 2.7

Maven version:3.4.3

Product : TIBCO Businessworks Container edition

Product version: 2.5.4

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1. Migration Approach from 2.7 to 2.8.

**Additional environment details if any:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by SujataDarekar** [comment]
You can use Maven plugin 2.8.0  with BWCE 2.5.4
