### ISSUE TITLE
Question:- Deploying in multiple appnodes

### ISSUE THREAD

**Issue by ant85** [TIBCOSoftware/bw6-plugin-maven#57]
Hi, 

Does this plugin support deployment of a single application across 2 appnodes ( in 2 different servers) ?

How to give multiple BW Host names and appnode names in the pom.xml. 
(Single appspace spread across 2 machines and each machine contains an appnode) 
Maven Plugin version: 1.1.0

Maven version: 3.3.9

Product : Either of TIBCO ActiveMatrix Businessworks 6 

Product version: 6.3.3

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Additional environment details if any:**
(Single appspace spread across 2 machines and each machine contains an appnode)

**Comment by edlegaspi** [comment]
Hi @ant85, configure your POM to deploy in either of the two hostnames and appnodes.

Host: Host1 OR Host2
Appspace: CommonAppspace
Appnode: Appnode1 OR Appnode2

As long as the appnodes are within the same appspace, the EAR would be deployed in BOTH machines. I already tried this and it worked for me.

**Comment by ant85** [comment]
Thank you **edlegaspi** . I'll do that.

**Comment by ant85** [comment]
Hi @edlegaspi the syntax Appnode1 OR Appnode2 doesnt work for me

**Comment by RajibBiswasTibco** [comment]
Hi @ant85 , is this question still open?

**Comment by ant85** [comment]
Hello.
I used the plugin to build the ear and then I'm using the BWadmin command line deployment option from jenkins to achieve this. In this way, I have control over the list of host/appspace/appnode.

**Comment by ant85** [comment]
Hello.
I used the plugin to build the ear and then I'm using the BWadmin command line deployment option from jenkins to achieve this. In this way, I have control over the list of host/appspace/appnode.
