### ISSUE TITLE
mvn build bwce application Ear does not contain manifest file

### ISSUE THREAD

**Issue by kdudani** [TIBCOSoftware/bw6-plugin-maven#571]
Maven Plugin version: 2.8.0

Maven version:

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version: bwce 2.6.0

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1.  mvn package
2.
3.

**Additional environment details if any:**

**Describe the results you received:**
The EAR contents differ:

1) EAR generated by studio (deployable)

marek@embedell:~/dist/HelloWorld_1.0.0$ jar tvf HelloWorld_1.0.0.ear
   349 Wed Feb 17 13:20:28 WET 2021 META-INF/MANIFEST.MF
 29831 Wed Feb 17 13:20:28 WET 2021 HelloWorld.module_1.0.0.20210217132027.jar
     0 Wed Feb 17 13:20:28 WET 2021 resources/
     0 Wed Feb 17 13:20:28 WET 2021 resources/HelloWorld.module/
     0 Wed Feb 17 13:20:28 WET 2021 resources/HelloWorld.module/diagrams/
  8495 Wed Feb 17 13:20:28 WET 2021 resources/HelloWorld.module/diagrams/helloworld.module.Publisher.bwd
  6532 Wed Feb 17 13:20:28 WET 2021 resources/HelloWorld.module/diagrams/helloworld.module.Subscriber.bwd
   226 Wed Feb 17 13:20:28 WET 2021 manifest.json
  3026 Wed Feb 17 13:20:28 WET 2021 META-INF/default.substvar
  3869 Wed Feb 17 13:20:28 WET 2021 META-INF/TIBCO.xml

2) EAR file denerated by maven plugin (not deployable)
marek@embedell:~/projects/bwce/HelloWorld/HelloWorld/target$ jar tvf HelloWorld_1.0.0.ear
     0 Wed Feb 24 13:17:46 WET 2021 META-INF/
   450 Wed Feb 24 13:17:44 WET 2021 META-INF/MANIFEST.MF
 16337 Wed Feb 24 13:17:46 WET 2021 HelloWorld.module_1.0.0.202102241317.jar
  3026 Tue Feb 16 22:32:30 WET 2021 META-INF/default.substvar
  5498 Wed Feb 24 13:17:46 WET 2021 META-INF/TIBCO.xml
     0 Wed Feb 24 13:17:46 WET 2021 META-INF/maven/
     0 Wed Feb 24 13:17:46 WET 2021 META-INF/maven/com.tibco.bw/
     0 Wed Feb 24 13:17:46 WET 2021 META-INF/maven/com.tibco.bw/HelloWorld/
  1253 Wed Feb 17 12:02:56 WET 2021 META-INF/maven/com.tibco.bw/HelloWorld/pom.xml
   116 Wed Feb 24 13:17:46 WET 2021 META-INF/maven/com.tibco.bw/HelloWorld/pom.properties
marek@embedell:~/projects/bwce/HelloWorld/HelloWorld/target$

Maven build reports build successful.

**Describe the results you expected:**
1. maven build bwce application ear should contain manifest file

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by kdudani** [comment]
[HelloWorld_buildsamples.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/6041714/HelloWorld_buildsamples.zip)

Uploading sample ears built by business studio and built by maven plugin

**Comment by SujataDarekar** [comment]
@kdudani In attached project I have seen the Manifest.MF which has Deployment Target as Tibco Cloud . Since the Deployment Target is Tibco Cloud Studio is generating the manifest.json However currently BW-Maven-Plugin do not provide support for Tibco Cloud Platform and hence it is not generating the manifest.json . Tibco Cloud platform support will be provided in BW-Maven-Plugin 2.8.1
