### ISSUE TITLE
External Shared Module code is not getting downloaded

### ISSUE THREAD

**Issue by tarun6006** [TIBCOSoftware/bw6-plugin-maven#573]
When dependency is as added as per the steps mentioned [Wiki](https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/SharedModule) the JAR is getting downloaded but the shared module code is not getting downloaded to the studio as a shared module . We have raised support ticket with TIBCO(01928083) as per their suggestion we are raising GitHub issue.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

Maven Plugin version: 2.8.0

Maven version: embedded 3.3.3

Product : TIBCO BusinessWorks Container edition

Product version: 2.6.0

Component: Maven build plugin

**Steps to reproduce the issue:**
1. add dependency in the pom.xml and save the project
2. Review your .m2 location to check whether JAR is downloaded

**Additional environment details if any:**
Windows 10 Laptop

**Describe the results you received:**
External shared module code is not getting downloaded

**Describe the results you expected:**
SharedModule code should be downloaded as demonstrated in  the Wiki page

**Additional information you deem important (e.g. issue happens only occasionally):**
 This is working for my other teammates . Please refer to case 01928083 for relevant images

**Comment by SujataDarekar** [comment]
@tarun6006 Can you attach your project and shared module POM  present in .m2 to the  case ID

**Comment by tarun6006** [comment]
@SujataDarekar Hi Sujatha , requested projects are uploaded in the case.

**Comment by SujataDarekar** [comment]
Thanks @tarun6006 .
I found the configuration issue in your project.
When We Add ESM as POM dependency, the Shared Module entry get added in Application Module POM and Module Descriptor dependencies but in your project I can see the entry of shared module in Application Parent POM as well which is wrong
Can you please check the same.
You just need to follow the exact steps given on wiki https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/SharedModule#external-shared-modules-with-maven

After adding the Dependency in Module POM, ESM will get pulled in Workspace and after that you need to add reference of ESM sub-processes in your module project processes.

**Comment by tarun6006** [comment]
Hi @SujataDarekar  the ESM is not getting pulled into the worspace as mentioned in wiki. That is why we have raised the support ticket. This is happening even with brand new projects. Please help us by setting up a working session as needed.

**Comment by SujataDarekar** [comment]
closing the issue since it has been fixed.
