### ISSUE TITLE
 Is Maven Plug-in 2.8.0 compatible with BWCE 2.6.1?

### ISSUE THREAD

**Issue by cspi-support** [TIBCOSoftware/bw6-plugin-maven#576]
Maven Plugin version: 2.8.0

Maven version: 3.6.3

Product : TIBCO Businessworks Container edition

Product version: 2.6.1

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1.  Is Maven Plug-in 2.8.0 compatible with BWCE 2.6.1?

**Additional environment details if any:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by kavitanalawade27** [comment]
Is it supported?

**Comment by burkass** [comment]
Hi when i'm using bw ce 2.6.1 I got below error when installling plugin. Is this error possible due to 2.6.1 version not supported yet?

![image](https://user-images.githubusercontent.com/5495419/114548543-1d8afd00-9c8a-11eb-83e7-02471fec1a71.png)

**Comment by vpawar-tibco** [comment]
Yes, Maven plugin 2.8.0 is compatible with BWCE 2.6.1.
