### ISSUE TITLE
Docker build issue using maven-plugin

### ISSUE THREAD

**Issue by nagamed** [TIBCOSoftware/bw6-plugin-maven#581]
Hi,

I am trying to run below mvn command from windows laptop but getting an error.

`mvn -f SampleProject.parent\pom.xml clean package initialize docker:build`

_[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.26.1:build (default-cli) on project SampleProject: Execution default-cli of goal io.fabric8:docker-maven-plugin:0.26.1:build failed: An API incompatibility was encountered while executing io.fabric8:docker-maven-plugin:0.26.1:build: java.lang.UnsatisfiedLinkError: unknown_

It works fine until only package but when I try docker build it throws the above error.

Maven version : 3.5.4
OS name: "windows 10"
Docker : Docker desktop 2.3.0.5
Product version: BWCE 2.6.1 
bw6-maven-plugin version : 2.0.1

Properties file used in bwce application project has the below : 

`bwdocker.host=unix\:///var/run/docker.sock`

Can you please help if I'm missing something here?

Thanks.

**Comment by cmocanu1** [comment]
Hi,
if you run on Windows, you can switch from 
`unix:///var/run/docker.sock` to 
`tcp://localhost:2375`

PS: Before that, set Docker to expose unsecure API on port 2375

**Comment by nagamed** [comment]
Thank you, it worked.
