### ISSUE TITLE
Question- deploy the app without auto start otion

### ISSUE THREAD

**Issue by singhr6** [TIBCOSoftware/bw6-plugin-maven#585]
Hi, Is there an option to prevent auto start of deployed app in mvn deploy ?

Ranjeet Singh.

**Comment by SujataDarekar** [comment]
@singhr6 Currently we don't provide any property to prevent auto start of deployed app. We will introduced it in future Maven Release

**Comment by SujataDarekar** [comment]
Change has been done and will be available with Maven 2.8.1. For more details please refer https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/List-of-BW-Maven-Plugin-Properties#8-startondeploy.
