### ISSUE TITLE
Unable to install Maven Plugin for Tibco Studio in windows VDI

### ISSUE THREAD

**Issue by anand2993** [TIBCOSoftware/bw6-plugin-maven#588]
Maven Plugin version:2.8.0

Maven version:3.8.1

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version:2.6.1

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1. While installing the Maven BW plugin, it's not able to download dependency for creating M2E home.
2.Unable to access below URL         <echo> Installing Eclipse M2E Plugin to Tibco Home </echo>
        <p2.install repo="http://download.eclipse.org/releases/luna" ius="org.eclipse.equinox.p2.discovery.feature.feature.group"/>
3.

**Additional environment details if any** Development URL

**Describe the results you received:** Attached the error log

**Describe the results you expected:** We need some alternative if we can use instead of URL.
[MavenLogsLatest.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/6424719/MavenLogsLatest.zip)
[MavenLogsLatest.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/6424720/MavenLogsLatest.zip)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by SujataDarekar** [comment]
@anand2993  It looks like internet connection issue. For now We don't provide offline installation support for BW Maven Plugin. Please check your connectivity issue.

**Comment by SujataDarekar** [comment]
@anand2993 You may refer #514 for more details

**Comment by anand2993** [comment]
Thank you Sujata. Looks like we need to do changes the #514 . In that also we have dependency to download from build file. I downloaded the zip file now and installed successful Maven now.
