### ISSUE TITLE
The POM for com.tibco.plugins:bw6-maven-plugin:jar:1.1.0 is missing, no dependency information available

### ISSUE THREAD

**Issue by bankarswapnil** [TIBCOSoftware/bw6-plugin-maven#59]
Hello Team,

I am getting below exception while executing Jenkins job,
**The POM for com.tibco.plugins:bw6-maven-plugin:jar:1.1.0 is missing, no dependency information available**

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
D:\Development\CICD\TIB_BW_Maven_Plugin_1.2.0>mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T22:11:47+05:30)
Maven home: D:\Development\CICD\ApacheMaven_3.3.9
Java version: 1.7.0_60, vendor: Oracle Corporation
Java home: D:\Development\3rdparty\jdk_1.7.0_60\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "windows"

Product : TIBCO ActiveMatrix Businessworks 634_HF01

Product version: BW634_HF01

Component: Maven build plugin : TIB_BW_Maven_Plugin_1.2.0

**Steps to reproduce the issue:**
1.  I have BW634_HF01 installed along with TIB_BW_Maven_Plugin_1.2.0 configured.
2.  I have generated POM using BWStudio and checked-in the code to GOGs(Git).
3.  Created a Jenkins Job with goals, clean package & install.

**Additional environment details if any:**
I have BW634_HF01, TEA220_HF09, Jenkins, Maven, Git, Gogs & TIB_BW_Maven_Plugin_1.2.0 in my setup.

**Describe the results you received:**

Console Output
Started by user swapnil bankar
Building in workspace D:\Development\CICD\Jenkins_2.32.1\workspace\BW6_Deploy_Job
 > git.exe rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git.exe config remote.origin.url http://localhost:3000/sbankar/myFirstProject.git # timeout=10
Fetching upstream changes from http://localhost:3000/sbankar/myFirstProject.git
 > git.exe --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git.exe fetch --tags --progress http://localhost:3000/sbankar/myFirstProject.git +refs/heads/*:refs/remotes/origin/*
 > git.exe rev-parse "refs/remotes/origin/master^{commit}" # timeout=10
 > git.exe rev-parse "refs/remotes/origin/origin/master^{commit}" # timeout=10
Checking out Revision 9c37854d4402b924aa75d0c7c70f8a46c339980b (refs/remotes/origin/master)
 > git.exe config core.sparsecheckout # timeout=10
 > git.exe checkout -f 9c37854d4402b924aa75d0c7c70f8a46c339980b
 > git.exe rev-list 9c37854d4402b924aa75d0c7c70f8a46c339980b # timeout=10
[BW6_Deploy_Job] $ cmd.exe /C "D:\Development\CICD\ApacheMaven_3.3.9\bin\mvn.cmd -f C:\Users\sbankar\git\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application.parent\pom.xml clean package && exit %%ERRORLEVEL%%"
[INFO] Scanning for projects...
[WARNING] The POM for com.tibco.plugins:bw6-maven-plugin:jar:1.1.0 is missing, no dependency information available
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin com.tibco.plugins:bw6-maven-plugin:1.1.0 or one of its dependencies could not be resolved: Failure to find com.tibco.plugins:bw6-maven-plugin:jar:1.1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ 
[ERROR] Unresolveable build extension: Plugin com.tibco.plugins:bw6-maven-plugin:1.1.0 or one of its dependencies could not be resolved: Failure to find com.tibco.plugins:bw6-maven-plugin:jar:1.1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ 
 @ 
[ERROR] The build could not read 2 projects -> [Help 1]
[ERROR]   
[ERROR]   The project com.tibco.bw:tibco.bw.sample.binding.rest.Basic:1.0.0-SNAPSHOT (C:\Users\sbankar\git\MyFirstProject\tibco.bw.sample.binding.rest.Basic\pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin com.tibco.plugins:bw6-maven-plugin:1.1.0 or one of its dependencies could not be resolved: Failure to find com.tibco.plugins:bw6-maven-plugin:jar:1.1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
[ERROR]   
[ERROR]   The project com.tibco.bw:tibco.bw.sample.binding.rest.Basic.application:1.0.0-SNAPSHOT (C:\Users\sbankar\git\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application\pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin com.tibco.plugins:bw6-maven-plugin:1.1.0 or one of its dependencies could not be resolved: Failure to find com.tibco.plugins:bw6-maven-plugin:jar:1.1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException
Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE
**Describe the results you expected:**
Application getting uploaded & deployed with success in TEA

**Additional information you deem important (e.g. issue happens only occasionally):**
Below 2 scripts copied from Jenkins execution job (which is failing) and executed explicitly in command prompt which went thr' with success, I could see application getting deployed in TEA with success.
cmd.exe /C "D:\Development\CICD\ApacheMaven_3.3.9\bin\mvn.cmd -f C:\Users\sbankar\git\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application.parent\pom.xml clean packa
exe /C "D:\Development\CICD\ApacheMaven_3.3.9\bin\mvn.cmd -f C:\Users\sbankar\git\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application.parent\pom.xml clean package
D:\Development\IDE\AMXBW_6.3.4\bw\6.3\maven\plugins\bw6-maven-plugin>cmd.exe /C "D:\Development\CICD\ApacheMaven_3.3.9\bin\mvn.cmd -f C:\Users\sbankar\git\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application.parent\pom.xml install

**Comment by bankarswapnil** [comment]
+
TIB_BW_Maven_Plugin_1.2.0 is installed on top of TIB_BW_Maven_Plugin_1.1.0.

**Comment by allalirema** [comment]
same problem but with version 1.2:

The POM for com.tibco.plugins:bw6-maven-plugin:jar:1.2.0 is missing
C:\apache-maven-3.3.9\bin\mvn.cmd -f C:\TFSBuildAgent\_work\2\s\Sources\Maven.parent\pom.xml package
 Scanning for projects...

The POM for com.tibco.plugins:bw6-maven-plugin:jar:1.2.0 is missing, no dependency information available

[ERROR] Some problems were encountered while processing the POMs:

Unresolveable build extension: Plugin com.tibco.plugins:bw6-maven-plugin:1.2.0 or one of its dependencies could not be resolved: Failure to find com.tibco.plugins:bw6-maven-plugin:jar:1.2.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ 

Unknown packaging: bwmodule @ com.tibco.bw:Maven.module:[unknown-version], C:\TFSBuildAgent\_work\2\s\Sources\Maven.module\pom.xml, line 12, column 14

Unresolveable build extension: Plugin com.tibco.plugins:bw6-maven-plugin:1.2.0 or one of its dependencies could not be resolved: Failure to find com.tibco.plugins:bw6-maven-plugin:jar:1.2.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ 

Unknown packaging: bwear @ com.tibco.bw:Maven:[unknown-version], C:\TFSBuildAgent\_work\2\s\Sources\Maven\pom.xml, line 12, column 14
 @ 

The build could not read 2 projects -> [Help 1]



The project com.tibco.bw:Maven.module:1.0.0-SNAPSHOT (C:\TFSBuildAgent\_work\2\s\Sources\Maven.module\pom.xml) has 2 errors

Unresolveable build extension: Plugin com.tibco.plugins:bw6-maven-plugin:1.2.0 or one of its dependencies could not be resolved: Failure to find com.tibco.plugins:bw6-maven-plugin:jar:1.2.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]

Unknown packaging: bwmodule @ com.tibco.bw:Maven.module:[unknown-version], C:\TFSBuildAgent\_work\2\s\Sources\Maven.module\pom.xml, line 12, column 14



The project com.tibco.bw:Maven:1.0.0-SNAPSHOT (C:\TFSBuildAgent\_work\2\s\Sources\Maven\pom.xml) has 2 errors

Unresolveable build extension: Plugin com.tibco.plugins:bw6-maven-plugin:1.2.0 or one of its dependencies could not be resolved: Failure to find com.tibco.plugins:bw6-maven-plugin:jar:1.2.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]

Unknown packaging: bwear @ com.tibco.bw:Maven:[unknown-version], C:\TFSBuildAgent\_work\2\s\Sources\Maven\pom.xml, line 12, column 14



To see the full stack trace of the errors, re-run Maven with the -e switch.

Re-run Maven using the -X switch to enable full debug logging.



For more information about the errors and possible solutions, please read the following articles:

[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

[Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException

**Comment by bankarswapnil** [comment]
With fresh install of 1.2.0, I got a success,

Console Output

Started by user Swapnil C Bankar
Building in workspace C:\Development\Jenkins_2.32.1\workspace\BW6_Package_Deploy
 > C:\Development\Git_2.11\bin\git.exe rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > C:\Development\Git_2.11\bin\git.exe config remote.origin.url http://localhost:3000/sbankar/myFirstProject.git # timeout=10
Fetching upstream changes from http://localhost:3000/sbankar/myFirstProject.git
 > C:\Development\Git_2.11\bin\git.exe --version # timeout=10
using GIT_ASKPASS to set credentials 
 > C:\Development\Git_2.11\bin\git.exe fetch --tags --progress http://localhost:3000/sbankar/myFirstProject.git +refs/heads/*:refs/remotes/origin/*
 > C:\Development\Git_2.11\bin\git.exe rev-parse "refs/remotes/origin/master^{commit}" # timeout=10
 > C:\Development\Git_2.11\bin\git.exe rev-parse "refs/remotes/origin/origin/master^{commit}" # timeout=10
Checking out Revision 7cadd582f8a3ed059cb5820f1107a8c3c31ba6bb (refs/remotes/origin/master)
 > C:\Development\Git_2.11\bin\git.exe config core.sparsecheckout # timeout=10
 > C:\Development\Git_2.11\bin\git.exe checkout -f 7cadd582f8a3ed059cb5820f1107a8c3c31ba6bb
 > C:\Development\Git_2.11\bin\git.exe rev-list 7cadd582f8a3ed059cb5820f1107a8c3c31ba6bb # timeout=10
[BW6_Package_Deploy] $ cmd.exe /C "C:\Development\apache-maven-3.3.9\bin\mvn.cmd -f C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application.parent\pom.xml -s C:\Development\apache-maven-3.3.9\conf\settings.xml clean package && exit %%ERRORLEVEL%%"
[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] tibco.bw.sample.binding.rest.Basic.application.parent
[INFO] tibco.bw.sample.binding.rest.Basic
[INFO] tibco.bw.sample.binding.rest.Basic.application
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic.application.parent 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ tibco.bw.sample.binding.rest.Basic.application.parent ---
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] Deleting C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\target
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ tibco.bw.sample.binding.rest.Basic ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ tibco.bw.sample.binding.rest.Basic ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:testCompile (default-testCompile) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] No tests to run.
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.0:bwmodule (default-bwmodule) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] Module Packager Mojo started for Module tibco.bw.sample.binding.rest.Basic ...
[INFO] Updated the Manifest version 
[INFO] Removing the externals entries if any. 
[INFO] Created Plugin JAR with name C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\target\tibco.bw.sample.binding.rest.Basic_1.0.0.201702231510.jar
[INFO] Adding Maven Dependencies to the Plugin JAR file
[INFO] Creating the Plugin JAR file
[INFO] Building jar: C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\target\tibco.bw.sample.binding.rest.Basic_1.0.0.201702231510.jar
[INFO] BW Module Packager Mojo finished execution.
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic.application 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] Deleting C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application\target
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ tibco.bw.sample.binding.rest.Basic.application ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ tibco.bw.sample.binding.rest.Basic.application ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:testCompile (default-testCompile) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] No tests to run.
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.0:bwear (default-bwear) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] BWEARPackager Mojo started ...
[INFO] Adding Modules to the EAR file
[INFO] Adding EAR Information to the EAR File
[INFO] Building jar: C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application\target\tibco.bw.sample.binding.rest.Basic.application_1.0.0.ear
[INFO] BWEARPackager Mojo finished execution
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] tibco.bw.sample.binding.rest.Basic.application.parent SUCCESS [  0.162 s]
[INFO] tibco.bw.sample.binding.rest.Basic ................. SUCCESS [  1.593 s]
[INFO] tibco.bw.sample.binding.rest.Basic.application ..... SUCCESS [  1.055 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.330 s
[INFO] Finished at: 2017-02-23T15:10:38+05:30
[INFO] Final Memory: 16M/297M
[INFO] ------------------------------------------------------------------------
[BW6_Package_Deploy] $ cmd.exe /C "C:\Development\apache-maven-3.3.9\bin\mvn.cmd -f C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application.parent\pom.xml -s C:\Development\apache-maven-3.3.9\conf\settings.xml install && exit %%ERRORLEVEL%%"
[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] tibco.bw.sample.binding.rest.Basic.application.parent
[INFO] tibco.bw.sample.binding.rest.Basic
[INFO] tibco.bw.sample.binding.rest.Basic.application
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic.application.parent 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ tibco.bw.sample.binding.rest.Basic.application.parent ---
[INFO] Installing C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application.parent\pom.xml to C:\Users\sbankar\.m2\repository\com\tibco\bw\tibco.bw.sample.binding.rest.Basic.application.parent\1.0.0-SNAPSHOT\tibco.bw.sample.binding.rest.Basic.application.parent-1.0.0-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ tibco.bw.sample.binding.rest.Basic ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ tibco.bw.sample.binding.rest.Basic ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:testCompile (default-testCompile) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] No tests to run.
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.0:bwmodule (default-bwmodule) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] Module Packager Mojo started for Module tibco.bw.sample.binding.rest.Basic ...
[INFO] Updated the Manifest version 
[INFO] Removing the externals entries if any. 
[INFO] Created Plugin JAR with name C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\target\tibco.bw.sample.binding.rest.Basic_1.0.0.201702231510.jar
[INFO] Adding Maven Dependencies to the Plugin JAR file
[INFO] Creating the Plugin JAR file
[INFO] Building jar: C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\target\tibco.bw.sample.binding.rest.Basic_1.0.0.201702231510.jar
[INFO] BW Module Packager Mojo finished execution.
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] Installing C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\target\tibco.bw.sample.binding.rest.Basic_1.0.0.201702231510.jar to C:\Users\sbankar\.m2\repository\com\tibco\bw\tibco.bw.sample.binding.rest.Basic\1.0.0-SNAPSHOT\tibco.bw.sample.binding.rest.Basic-1.0.0-SNAPSHOT.jar
[INFO] Installing C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\pom.xml to C:\Users\sbankar\.m2\repository\com\tibco\bw\tibco.bw.sample.binding.rest.Basic\1.0.0-SNAPSHOT\tibco.bw.sample.binding.rest.Basic-1.0.0-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic.application 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ tibco.bw.sample.binding.rest.Basic.application ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ tibco.bw.sample.binding.rest.Basic.application ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:testCompile (default-testCompile) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] No tests to run.
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.0:bwear (default-bwear) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] BWEARPackager Mojo started ...
[INFO] Adding Modules to the EAR file
[INFO] Adding EAR Information to the EAR File
[INFO] Building jar: C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application\target\tibco.bw.sample.binding.rest.Basic.application_1.0.0.ear
[INFO] BWEARPackager Mojo finished execution
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] Installing C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application\target\tibco.bw.sample.binding.rest.Basic.application_1.0.0.ear to C:\Users\sbankar\.m2\repository\com\tibco\bw\tibco.bw.sample.binding.rest.Basic.application\1.0.0-SNAPSHOT\tibco.bw.sample.binding.rest.Basic.application-1.0.0-SNAPSHOT.ear
[INFO] Installing C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application\pom.xml to C:\Users\sbankar\.m2\repository\com\tibco\bw\tibco.bw.sample.binding.rest.Basic.application\1.0.0-SNAPSHOT\tibco.bw.sample.binding.rest.Basic.application-1.0.0-SNAPSHOT.pom
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.0:bwinstall (default-bwinstall) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] BWEAR Installer Mojo started ...
[INFO] No Deployment Config File set. Reading the deployment Properties from POM File.
[INFO] Connected to BWAgent. Agents found.
[INFO] Agent Name -> kohls-dt6
[INFO] Domain exists with Name -> myDomain
[INFO] AppSpace exists with Name -> myAppSpace in Domain -> myDomain
[INFO] AppNode exists with Name -> myAppNode-8064 in Domain -> myDomain and in AppSpace -> myAppSpace
[INFO] AppNode HTTP Port  -> 8064. AppNode OSGi Port -> -1
[INFO] AppSpace is Running.
[INFO] Uploading the Archive file -> tibco.bw.sample.binding.rest.Basic.application_1.0.0.ear
[INFO] Deploying the Application with name -> tibco.bw.sample.binding.rest.Basic.application with Profile -> WindowsProfile.substvar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] tibco.bw.sample.binding.rest.Basic.application.parent SUCCESS [  0.326 s]
[INFO] tibco.bw.sample.binding.rest.Basic ................. SUCCESS [  1.605 s]
[INFO] tibco.bw.sample.binding.rest.Basic.application ..... SUCCESS [ 19.782 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.666 s
[INFO] Finished at: 2017-02-23T15:11:05+05:30
[INFO] Final Memory: 31M/369M
[INFO] ------------------------------------------------------------------------
Finished: SUCCESS

This query can be closed.

Thanx,
-Swapnil

**Comment by rahulkamdar** [comment]
Thanks @bankarswapnil. @allalirema can you open a new issue and share the environment details?
