### ISSUE TITLE
Getting error, Could not find goal 'bwmodule' in plugin com.tibco.plugins:bw6-maven-plugin:1.2.0 among available goals

### ISSUE THREAD

**Issue by bankarswapnil** [TIBCOSoftware/bw6-plugin-maven#60]
Started by user swapnil bankar
Building in workspace C:\WINDOWS\system32\config\systemprofile\.jenkins\workspace\myFirstProject
 > D:\Development\CICD\Git_2.11.0.3\bin\git.exe rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > D:\Development\CICD\Git_2.11.0.3\bin\git.exe config remote.origin.url http://localhost:3000/sbankar/MyFirstRepo.git # timeout=10
Fetching upstream changes from http://localhost:3000/sbankar/MyFirstRepo.git
 > D:\Development\CICD\Git_2.11.0.3\bin\git.exe --version # timeout=10
using GIT_ASKPASS to set credentials 
 > D:\Development\CICD\Git_2.11.0.3\bin\git.exe fetch --tags --progress http://localhost:3000/sbankar/MyFirstRepo.git +refs/heads/*:refs/remotes/origin/*
 > D:\Development\CICD\Git_2.11.0.3\bin\git.exe rev-parse "refs/remotes/origin/master^{commit}" # timeout=10
 > D:\Development\CICD\Git_2.11.0.3\bin\git.exe rev-parse "refs/remotes/origin/origin/master^{commit}" # timeout=10
Checking out Revision 400d50e4bd1d621a334470824e9c2906c9691576 (refs/remotes/origin/master)
 > D:\Development\CICD\Git_2.11.0.3\bin\git.exe config core.sparsecheckout # timeout=10
 > D:\Development\CICD\Git_2.11.0.3\bin\git.exe checkout -f 400d50e4bd1d621a334470824e9c2906c9691576
First time build. Skipping changelog.
[myFirstProject] $ cmd.exe /C "D:\Development\CICD\ApacheMaven_3.3.9\bin\mvn.cmd -f D:\Temp\CICD\MyFirstProject1\tibco.bw.sample.binding.rest.Basic.application.parent\pom.xml clean package && exit %%ERRORLEVEL%%"
[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] tibco.bw.sample.binding.rest.Basic.application.parent
[INFO] tibco.bw.sample.binding.rest.Basic
[INFO] tibco.bw.sample.binding.rest.Basic.application
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic.application.parent 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ tibco.bw.sample.binding.rest.Basic.application.parent ---
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] tibco.bw.sample.binding.rest.Basic.application.parent SUCCESS [  0.067 s]
[INFO] tibco.bw.sample.binding.rest.Basic ................. FAILURE [  0.066 s]
[INFO] tibco.bw.sample.binding.rest.Basic.application ..... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.239 s
[INFO] Finished at: 2017-02-17T19:50:41+05:30
[INFO] Final Memory: 13M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Could not find goal 'bwmodule' in plugin com.tibco.plugins:bw6-maven-plugin:1.2.0 among available goals help -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoNotFoundException
Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE

**Comment by bankarswapnil** [comment]
Below script gives me,

[INFO] com.tibco.plugins:bw6-maven-plugin:1.2.0

Name: Plugin Code for Apache Maven and TIBCO BusinessWorksÖ
Description: Plugin Code for Apache Maven and TIBCO BusinessWorksÖ. This is
  the Maven Plugin for BW6 Build.
Group Id: com.tibco.plugins
Artifact Id: bw6-maven-plugin
Version: 1.2.0
Goal Prefix: bw6maven

This plugin has 5 goals:

bw6maven:bwcompile
  Description: (no description available)

bw6maven:bwear
  Description: (no description available)

bw6maven:bwinstall
  Description: (no description available)

bw6maven:bwmodule
  Description: (no description available)

bw6maven:help
  Description: Display help information on bw6-maven-plugin.
    Call mvn bw6maven:help -Ddetail=true -Dgoal=<goal-name> to display
    parameter details.

For more information, run 'mvn help:describe [...] -Ddetail'

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.929 s
[INFO] Finished at: 2017-02-17T20:00:59+05:30
[INFO] Final Memory: 13M/125M
[INFO] ------------------------------------------------------------------------

**Comment by rahulkamdar** [comment]
Was 1.2.0 installed on top of 1.1.0 or as a fresh new install? We need to mark on the 1.2.0 install that customers need a fresh install currently.

**Comment by bankarswapnil** [comment]
Yes Rahul, my setup was promoted from 110 to 120.
Let me try with rebasing the platform to directly go to 120.

Thanx,
-Swapnil

**Comment by bankarswapnil** [comment]
Hi Rahul,
It worked for me.
Console Output

Started by user Swapnil C Bankar
Building in workspace C:\Development\Jenkins_2.32.1\workspace\BW6_Package_Deploy
 > C:\Development\Git_2.11\bin\git.exe rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > C:\Development\Git_2.11\bin\git.exe config remote.origin.url http://localhost:3000/sbankar/myFirstProject.git # timeout=10
Fetching upstream changes from http://localhost:3000/sbankar/myFirstProject.git
 > C:\Development\Git_2.11\bin\git.exe --version # timeout=10
using GIT_ASKPASS to set credentials 
 > C:\Development\Git_2.11\bin\git.exe fetch --tags --progress http://localhost:3000/sbankar/myFirstProject.git +refs/heads/*:refs/remotes/origin/*
 > C:\Development\Git_2.11\bin\git.exe rev-parse "refs/remotes/origin/master^{commit}" # timeout=10
 > C:\Development\Git_2.11\bin\git.exe rev-parse "refs/remotes/origin/origin/master^{commit}" # timeout=10
Checking out Revision 7cadd582f8a3ed059cb5820f1107a8c3c31ba6bb (refs/remotes/origin/master)
 > C:\Development\Git_2.11\bin\git.exe config core.sparsecheckout # timeout=10
 > C:\Development\Git_2.11\bin\git.exe checkout -f 7cadd582f8a3ed059cb5820f1107a8c3c31ba6bb
 > C:\Development\Git_2.11\bin\git.exe rev-list 7cadd582f8a3ed059cb5820f1107a8c3c31ba6bb # timeout=10
[BW6_Package_Deploy] $ cmd.exe /C "C:\Development\apache-maven-3.3.9\bin\mvn.cmd -f C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application.parent\pom.xml -s C:\Development\apache-maven-3.3.9\conf\settings.xml clean package && exit %%ERRORLEVEL%%"
[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] tibco.bw.sample.binding.rest.Basic.application.parent
[INFO] tibco.bw.sample.binding.rest.Basic
[INFO] tibco.bw.sample.binding.rest.Basic.application
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic.application.parent 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ tibco.bw.sample.binding.rest.Basic.application.parent ---
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] Deleting C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\target
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ tibco.bw.sample.binding.rest.Basic ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ tibco.bw.sample.binding.rest.Basic ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:testCompile (default-testCompile) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] No tests to run.
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.0:bwmodule (default-bwmodule) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] Module Packager Mojo started for Module tibco.bw.sample.binding.rest.Basic ...
[INFO] Updated the Manifest version 
[INFO] Removing the externals entries if any. 
[INFO] Created Plugin JAR with name C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\target\tibco.bw.sample.binding.rest.Basic_1.0.0.201702231510.jar
[INFO] Adding Maven Dependencies to the Plugin JAR file
[INFO] Creating the Plugin JAR file
[INFO] Building jar: C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\target\tibco.bw.sample.binding.rest.Basic_1.0.0.201702231510.jar
[INFO] BW Module Packager Mojo finished execution.
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic.application 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] Deleting C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application\target
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ tibco.bw.sample.binding.rest.Basic.application ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ tibco.bw.sample.binding.rest.Basic.application ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:testCompile (default-testCompile) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] No tests to run.
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.0:bwear (default-bwear) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] BWEARPackager Mojo started ...
[INFO] Adding Modules to the EAR file
[INFO] Adding EAR Information to the EAR File
[INFO] Building jar: C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application\target\tibco.bw.sample.binding.rest.Basic.application_1.0.0.ear
[INFO] BWEARPackager Mojo finished execution
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] tibco.bw.sample.binding.rest.Basic.application.parent SUCCESS [  0.162 s]
[INFO] tibco.bw.sample.binding.rest.Basic ................. SUCCESS [  1.593 s]
[INFO] tibco.bw.sample.binding.rest.Basic.application ..... SUCCESS [  1.055 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.330 s
[INFO] Finished at: 2017-02-23T15:10:38+05:30
[INFO] Final Memory: 16M/297M
[INFO] ------------------------------------------------------------------------
[BW6_Package_Deploy] $ cmd.exe /C "C:\Development\apache-maven-3.3.9\bin\mvn.cmd -f C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application.parent\pom.xml -s C:\Development\apache-maven-3.3.9\conf\settings.xml install && exit %%ERRORLEVEL%%"
[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] tibco.bw.sample.binding.rest.Basic.application.parent
[INFO] tibco.bw.sample.binding.rest.Basic
[INFO] tibco.bw.sample.binding.rest.Basic.application
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic.application.parent 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ tibco.bw.sample.binding.rest.Basic.application.parent ---
[INFO] Installing C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application.parent\pom.xml to C:\Users\sbankar\.m2\repository\com\tibco\bw\tibco.bw.sample.binding.rest.Basic.application.parent\1.0.0-SNAPSHOT\tibco.bw.sample.binding.rest.Basic.application.parent-1.0.0-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ tibco.bw.sample.binding.rest.Basic ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ tibco.bw.sample.binding.rest.Basic ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:testCompile (default-testCompile) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] No tests to run.
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.0:bwmodule (default-bwmodule) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] Module Packager Mojo started for Module tibco.bw.sample.binding.rest.Basic ...
[INFO] Updated the Manifest version 
[INFO] Removing the externals entries if any. 
[INFO] Created Plugin JAR with name C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\target\tibco.bw.sample.binding.rest.Basic_1.0.0.201702231510.jar
[INFO] Adding Maven Dependencies to the Plugin JAR file
[INFO] Creating the Plugin JAR file
[INFO] Building jar: C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\target\tibco.bw.sample.binding.rest.Basic_1.0.0.201702231510.jar
[INFO] BW Module Packager Mojo finished execution.
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] Installing C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\target\tibco.bw.sample.binding.rest.Basic_1.0.0.201702231510.jar to C:\Users\sbankar\.m2\repository\com\tibco\bw\tibco.bw.sample.binding.rest.Basic\1.0.0-SNAPSHOT\tibco.bw.sample.binding.rest.Basic-1.0.0-SNAPSHOT.jar
[INFO] Installing C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic\pom.xml to C:\Users\sbankar\.m2\repository\com\tibco\bw\tibco.bw.sample.binding.rest.Basic\1.0.0-SNAPSHOT\tibco.bw.sample.binding.rest.Basic-1.0.0-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic.application 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ tibco.bw.sample.binding.rest.Basic.application ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ tibco.bw.sample.binding.rest.Basic.application ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:testCompile (default-testCompile) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] No tests to run.
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.0:bwear (default-bwear) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] BWEARPackager Mojo started ...
[INFO] Adding Modules to the EAR file
[INFO] Adding EAR Information to the EAR File
[INFO] Building jar: C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application\target\tibco.bw.sample.binding.rest.Basic.application_1.0.0.ear
[INFO] BWEARPackager Mojo finished execution
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] Installing C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application\target\tibco.bw.sample.binding.rest.Basic.application_1.0.0.ear to C:\Users\sbankar\.m2\repository\com\tibco\bw\tibco.bw.sample.binding.rest.Basic.application\1.0.0-SNAPSHOT\tibco.bw.sample.binding.rest.Basic.application-1.0.0-SNAPSHOT.ear
[INFO] Installing C:\Development\LocalGogsRepo\MyFirstProject\tibco.bw.sample.binding.rest.Basic.application\pom.xml to C:\Users\sbankar\.m2\repository\com\tibco\bw\tibco.bw.sample.binding.rest.Basic.application\1.0.0-SNAPSHOT\tibco.bw.sample.binding.rest.Basic.application-1.0.0-SNAPSHOT.pom
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.0:bwinstall (default-bwinstall) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] BWEAR Installer Mojo started ...
[INFO] No Deployment Config File set. Reading the deployment Properties from POM File.
[INFO] Connected to BWAgent. Agents found.
[INFO] Agent Name -> kohls-dt6
[INFO] Domain exists with Name -> myDomain
[INFO] AppSpace exists with Name -> myAppSpace in Domain -> myDomain
[INFO] AppNode exists with Name -> myAppNode-8064 in Domain -> myDomain and in AppSpace -> myAppSpace
[INFO] AppNode HTTP Port  -> 8064. AppNode OSGi Port -> -1
[INFO] AppSpace is Running.
[INFO] Uploading the Archive file -> tibco.bw.sample.binding.rest.Basic.application_1.0.0.ear
[INFO] Deploying the Application with name -> tibco.bw.sample.binding.rest.Basic.application with Profile -> WindowsProfile.substvar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] tibco.bw.sample.binding.rest.Basic.application.parent SUCCESS [  0.326 s]
[INFO] tibco.bw.sample.binding.rest.Basic ................. SUCCESS [  1.605 s]
[INFO] tibco.bw.sample.binding.rest.Basic.application ..... SUCCESS [ 19.782 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.666 s
[INFO] Finished at: 2017-02-23T15:11:05+05:30
[INFO] Final Memory: 31M/369M
[INFO] ------------------------------------------------------------------------
Finished: SUCCESS

Concern can be closed now.

Thanx,
-Swapnil

**Comment by rahulkamdar** [comment]
Great, thanks for confirming. Closing the issue.
