### ISSUE TITLE
PVM-XML-106018: Expression Creation Error: with Activity Assertions with "Gold Input From File"

### ISSUE THREAD

**Issue by medecigo3** [TIBCOSoftware/bw6-plugin-maven#605]
Maven Plugin version: 2.8.0

Maven version: 3.5.4

Product : Either of TIBCO ActiveMatrix Businessworks 6 

Product version: 6.7.0

Component:  Maven Eclipse Plugin 

**Steps to reproduce the issue:**
This assumes you have already added the "Test" file for the sub-process in question. Please refer "Adding Unit Tests Assertions" section from https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/UnitTesting to add test file.
This assumes the test project is Mavenized. 
1. Right click on the Activity from the subprocess and Click on "Add Test -> Add Assertion" option. This will add the "Test" tab
2. Open the "Tests" tab. You will see Assertion Mode drop down which will have the "Primitive" and "Activity" mode options. See rectangle in blue below.
![image](https://user-images.githubusercontent.com/36109246/122724844-a28b2780-d274-11eb-8238-456ba19c0951.png)
3. Select "Activity" option from "Assertion Mode" drop down, you will see the "Gold Input From File" option. See rectangle in red below.
![image](https://user-images.githubusercontent.com/36109246/122724937-be8ec900-d274-11eb-9765-8a039d54bea5.png)
4. To provide the gold output through xml file, select the checkbox "Gold Input From File". Map Activity variable from "datasource" section (for instance from a Mapper activity) to "activityTestInput" field. In "testFilePath" field, use the doc function from the URI function and provide the input file path in the format 'file:///inputFilepath'(In image the value of testFilePath is doc('file:///C:/Tests/UnitTestingsComplex.xml')). In the case of Unix systems, please provide the absolute path preceding the extra forward slash. Example: doc('file:////home/Test/Mock_files/Activity_Assetion_IP_File.xml'). See rectangle in red below.
![image](https://user-images.githubusercontent.com/36109246/122725025-debe8800-d274-11eb-9f53-a01d6ca301eb.png)
5. Now provide the relative Gold Input file path in "Gold Input From File" field. User need to keep gold input file in "Tests" folder of the BW project. The relative path will have the value like doc('file:///Tests/UnitTestingsComplex.xml'). It's mandatory to provide the "Tests" folder name also in relative path. In case of Unix please provide the relative path like below: :- ('file:///Tests/Mock_files/Activity_Assetion_IP_File.xml'). In my case I'm using doc('file:///Tests/output.xml')
6. To create gold input file, Run the activity for which you need to add the assertions. Copy the input JOB data from debug console using the "copy values" option and paste in xml file. Linearize the copied xml data.Change the input value with gold input values.
![image](https://user-images.githubusercontent.com/36109246/122725105-f3028500-d274-11eb-9b47-f9262c2aa20e.png)
7. To run the test case please refer "Running the Unit Tests in Business Studio" from https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/UnitTesting

**Additional environment details if any:**
N/A

**Describe the results you received:**
Received ambiguous error message: PVM-XML-106018: Expression Creation Error:
![image](https://user-images.githubusercontent.com/36109246/122725456-4f65a480-d275-11eb-8306-dee69bdc583f.png)

**Describe the results you expected:**
Expected report bwtestreport.xml with passed results. 

**Additional information you deem important (e.g. issue happens only occasionally):**
Error happens systematically when using "Gold Input From File" with activity assertions.

**Comment by SujataDarekar** [comment]
@medecigo3 Can you please attach your sample project to reproduce the issue?

**Comment by medecigo3** [comment]
Hi Sujata,
I wasn't able to reproduce and  I'm not experiencing this issue any more. Closing issue.
