### ISSUE TITLE
Bug in End activity assertion with "Gold Input From File" option.

### ISSUE THREAD

**Issue by medecigo3** [TIBCOSoftware/bw6-plugin-maven#606]
Maven Plugin version: 2.8.0

Maven version: 3.5.4

Product : Either of TIBCO ActiveMatrix Businessworks 6

Product version: 6.7.0

Component: Maven Eclipse Plugin

**Steps to reproduce the issue:**
Steps to reproduce the issue:
This assumes you have already added the "Test" file for the sub-process in question. Please refer "Adding Unit Tests Assertions" section from https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/UnitTesting to add test file.
This assumes the test project is Mavenized.

1.Right click on the End activity from the subprocess and Click on "Add Test -> Add Assertion" option. This will add the "Test" tab
2.Open the "Tests" tab. You will see Assertion Mode drop down which will have the "Primitive" and "Activity" mode options. 
3.Select "Activity" option from "Assertion Mode" drop down, you will see the "Gold Input From File" option. 
4. To provide the gold output through xml file, select the checkbox "Gold Input From File" (See red circle below). The  "activityTestInput" and "testFilePath" fields doesn't show up. 
![image](https://user-images.githubusercontent.com/36109246/122807949-7e5b3500-d2cc-11eb-9f76-583a1f8d2a7a.png)

**Describe the results you received:**
The  "activityTestInput" and "testFilePath" fields doesn't show up when with activity assertion with "Gold Input From File" option.

**Describe the results you expected:**
The  "activityTestInput" and "testFilePath" fields should show up when configuring activity assertion in END activity. Same as with the Mapper activity: 
![image](https://user-images.githubusercontent.com/36109246/122808585-5f10d780-d2cd-11eb-9a72-5931b1928655.png)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by SujataDarekar** [comment]
@medecigo3  This has been fixed in 6.7.0 HF-002 . Hence closing the ticket
