### ISSUE TITLE
Dependencies not fully resolved in BW Studio

### ISSUE THREAD

**Issue by kvansaders** [TIBCOSoftware/bw6-plugin-maven#62]
After adding a dependency to a private Maven repository to the BW project pom.xml, the project is rebuilt and the dependency Jar files are loaded under the "Maven Dependencies" folder in the project.  When attempting to refer to public classes in these dependencies, the XML to Java palette cannot resolve the input schema for the Java class.  These classes work fine when importing the Jar file directly without MVN.

Related communities ticket:
https://community.tibco.com/questions/tibco-bw-63-using-jar-class-maven-xml-java-palette

Maven Plugin version:

Maven version:

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version:

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1.
2.
3.

**Additional environment details if any:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by awagle** [comment]
This is a product limitation due to Eclipse. Any artifacts which are being used at design time need to be present in the workspace. This explains why this works when the jar is part of the project.

The maven plugin however does allow you to pick the jar from maven repository when the EAR file is built.

**Comment by kvansaders** [comment]
Is there a recommended pattern for loading a dependency via MVN, attaching the jar to the project in design, then making it available one again at build time?  That type of workaround/documentation would at least make the usefulness of MVN (external dependencies) available for BW.
