### ISSUE TITLE
The SchemaCacheService operation [LocXsdCacheService.getCache] returned "null" with maven build - TIBCO BW6

### ISSUE THREAD

**Issue by esbmt** [TIBCOSoftware/bw6-plugin-maven#639]
Hi Team,

We have a TIBCO BW6 code where we have referred one schema from a shared module but when we create a EAR via bw6-maven-plugin we are getting below error while starting the service , however we don’t see this error in local studio run nor with manually created EAR directly from studio

Error:
--------------------------------------------------------------------------------------------
2021-12-13 23:26:59.317 ERROR [pool-44-thread-5] com.tibco.bw.thor.runtime.model.Constituent - TIBCO-BW-CORE-500102: Failed to install BW Module [ULDStatusiCargoAdapter.module:2.2.0], DeploymentUnit [ULDStatusiCargoAdapter:2.2].
<CausedBy> com.tibco.bx.core.faults.BxException: BX-600025: Create module failed for module [ULDStatusiCargoAdapter.module] version [2.2.0] application [ULDStatusiCargoAdapter 2.2].
<CausedBy> com.tibco.bx.core.faults.BxException: BX-600028: Adding definition failed for process [lh.lcag.esb.uldstatus.icargoadapter.source-esb.publishULDShipmentDetails.starter].
<CausedBy> com.tibco.bw.core.runtime.schemaresolver.SchemaNotFoundException: TIBCO-BW-SCHEMA-RESOLVER-500101: Schema not found. Schema [namespace=http://www.ibsplc.com/icargo/services/types/OperationsFlthandlingService/PublishULDShipmentDetails/external/2013/10/11, location=/../iCargoSchemas/Schemas/iCargoSchemas/wsdl/types/operations/shipment/external/lh/uldshpdtl/PublishULDShipmentDetails.xsd, baseURI=bundleentry://738.fwk1849602253/Processes/lh/lcag/esb/uldstatus/icargoadapter/source-esb/publishULDShipmentDetails/starter.bwp] not found in cache for the BW Module [ULDStatusiCargoAdapter.module:2.2.0]. The SchemaCacheService operation [LocXsdCacheService.getCache] returned "null".

2021-12-13 23:27:01.728 INFO [pool-44-thread-5] com.tibco.thor.frwk.Application - TIBCO-THOR-FRWK-300008: Stopped BW Application [ULDStatusiCargoAdapter:2.2]

--------------------------------------------------------------------------------------------------

below are the plugin details used in pom.xml while building 

application.pom
    <plugins>
      <plugin>
        <groupId>com.tibco.plugins</groupId>
        <artifactId>bw6-maven-plugin</artifactId>
        <version>2.8.0</version>
      </plugin>
    </plugins>

parent.pom
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-site-plugin</artifactId>
        <version>3.7.1</version>
      </plugin>
    </plugins>
  </build>
</project>

Thanks in Advance.

**Comment by sarundes-tibco** [comment]
Based on conclusion and comments provided in the below tickets,
https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/693
https://jira.tibco.com/browse/AMBW-47641
Hence closing this ticket.
