### ISSUE TITLE
Problem with the new "Manifest Version update with maven version" feature

### ISSUE THREAD

**Issue by uportalis** [TIBCOSoftware/bw6-plugin-maven#64]
Hi

One of our needs is to have the Manifest Version updated with the value of the Maven project version when we build with Maven.

I can see that bw-plugin-maven 1.2 provides that functionality (called "Manifest Version update with maven version").

However, I see that this was implemented with the following 'if' statement in ManifestWriter.java :
`if((attributes.getValue(Name.MANIFEST_VERSION) == null || attributes.getValue(Name.MANIFEST_VERSION).equals("1.0")) && project.getVersion().equals("1.0.0-SNAPSHOT"))`

Correct me if I missed something, but this feature works only if the Maven project version is "1.0.0-SNAPSHOT"... which is not really useful.

**Comment by uportalis** [comment]
Seems corrected with commit 5ce84e0b280cff25ef73f52b264258720a520b53

**Comment by RajibBiswasTibco** [comment]
Fixed in Release Version 1.2.2
