### ISSUE TITLE
Installation error - HTTP Response Code (301)

### ISSUE THREAD

**Issue by maintilla** [TIBCOSoftware/bw6-plugin-maven#652]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

Maven Plugin version: 2.8.1

Maven version: 3.8.4

Product : TIBCO Businessworks Container edition

Product version: 2.6.3

Component: Maven Eclipse Plugin

**Steps to reproduce the issue:**
1. Run the plugin installer

**Describe the results you received:** the installation process fails and from logs we can see the following: 

!MESSAGE HTTP Server Unknown HTTP Response Code (301):http://download.eclipse.org/releases/luna/artifacts.xml
!STACK 1
org.eclipse.ecf.filetransfer.BrowseFileTransferException: General connection error with response code=301
    at org.eclipse.ecf.provider.filetransfer.browse.URLFileSystemBrowser.runRequest(URLFileSystemBrowser.java:131)
    at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 org.eclipse.ecf.identity 4 0 2022-02-18 12:38:20.028
!MESSAGE General connection error with response code=301
!ENTRY org.eclipse.equinox.p2.director.app 4 0 2022-02-18 12:38:22.934
!MESSAGE The installable unit org.eclipse.equinox.p2.discovery.feature.feature.group has not been found.

[1645184296841.log](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/8117124/1645184296841.log)

**Comment by vpawar-tibco** [comment]
The eclipse update site **http://download.eclipse.org/releases/luna/** is no longer available.

After extracting the installer zip, please replace **http://download.eclipse.org/releases/luna/** with **https://download.eclipse.org/eclipse/updates/4.4/** in build.xml.
