### ISSUE TITLE
TIBCO Studio - Run/Debug Configuration - Maven Build

### ISSUE THREAD

**Issue by RohithKumarKM** [TIBCOSoftware/bw6-plugin-maven#662]
### Maven Plugin version: 2.7.1

Maven Build Output Attached. Please review and let know what needs to be changed. 
Also attached an other case with same issue.

[output.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/8755876/output.txt)

[https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/435](url)

**Comment by sarundes-tibco** [comment]
Not able to reproduce the above issue with latest 2.9.8. Hence marking this as closed
