### ISSUE TITLE
How to exclude some processes/packages from EAR using the POM file

### ISSUE THREAD

**Issue by JaganChinthakayala** [TIBCOSoftware/bw6-plugin-maven#67]
Hi

I have written some test processes in an application module and I would like to exclude them from EAR.

Can I use the application module's POM to do that. In Java Maven projects, we would specify the following in POM to exclude certain packages from jar

		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-jar-plugin</artifactId>
			<version>3.0.2</version>
			<configuration>
				<excludes>
					<exclude>com/slb/sims/aes/*</exclude>
					<exclude>com/slb/sims/fpe/*</exclude>
					<exclude>com/slb/sims/rsa/*</exclude>
					<exclude>com/slb/sims/utils/*</exclude>
				</excludes>
			</configuration>
		</plugin>

So for BW6 application module's POM can I specify as shown below to exclude some packages from POM

**Comment by JaganChinthakayala** [comment]
![excludeprocessesfromear](https://cloud.githubusercontent.com/assets/21689038/23768743/9b573ac2-04d2-11e7-842b-94a714fd7c54.PNG)

**Comment by rahulkamdar** [comment]
Hi @JaganChinthakayala a recommended practice for test projects is to separate out these into a separate project and hence a separate artifact at both design-time and runtime. Even in Java based projects it's common to have a .tests project that packages the test resources.

We'd be using the same mechanism going forward and have no plans to change this currently.

**Comment by JaganChinthakayala** [comment]
I have never seen a .tests project in Java. This will require the original project to referenced as a jar in the test project and unnecessary complications.

What I have seen is .tests package within the same project and maven used to exclude those test packages from the jar/ear.

**Comment by JaganChinthakayala** [comment]
I am trying to do Unit testing, basically testing sub processes that do transformation tasks.

If I create a test application then I have to call the transformation processes from the original project so that will mean the original project should be converted and added as an shared module to test application. This is all NOT good, please re-open this case... I don't really think what you suggested will work.

**Comment by rahulkamdar** [comment]
Hi @JaganChinthakayala separating out test artifacts from your actual project is a recommended practice. Testing flows for most of the users has been generally against the services/processes -in a client manner which doesn't need any project dependency.

That said, I understand your need specific to testing sub-processes and will re-open this issue. We will update this when we have more information.

**Comment by awagle** [comment]
Please use the build.properties files for excluding content from the project.
