### ISSUE TITLE
Issue starting multiple appnodes from Jenkins

### ISSUE THREAD

**Issue by RohithKumarKM** [TIBCOSoftware/bw6-plugin-maven#670]
Hi,

Does this plugin support deployment of a single application across 2 appnodes on 2 different servers ?

Have given 2 different hostnames on the config file but one appnode fails to start and Jenkins Console log does not specifies this(Attached).

Maven Plugin version: 2.7.1

Product :TIBCO ActiveMatrix Businessworks 6 

Product version:6.6.0

Component: Maven build plugin

@SujataDareka
[JenkinsBuild.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/9395083/JenkinsBuild.txt)
![JenkinsBuildIssue-TEA](https://user-images.githubusercontent.com/39291234/185942223-ec11ce0d-92a5-49bc-bd9f-70677a129476.JPG)
r

**Comment by sarundes-tibco** [comment]
Please contact to BW customer support for this issue.
