### ISSUE TITLE
Documentation not accurate - cannot install plugin in fresh environment

### ISSUE THREAD

**Issue by LukaszChrzanowski** [TIBCOSoftware/bw6-plugin-maven#687]
Maven Plugin version: Latest GA

Maven version: NA

Product : TIBCO BusinessWorks 6.8

Product version: Latest GA

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1.read how to install plugin
2.go to download page -> see there is no package to download
3.find in TIBCO documentations, that plugin is installed in BW6 installation
4.reinstall BW with MAVEN plugin option checked
5.run install bat and see errors
6.find olny confusion how to find help (bwinstall not supporting bw6-maven-plugin installation

Errors:
Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install-file (default-cli) on project standalone-pom: The specified file '/opt/tibco/bw/6.8/system/shared/%shared_RU%' not exists -> [Help 1]

what should be in parameters (%%) values?

**Comment by sarundes-tibco** [comment]
@LukaszChrzanowski  Can you please check latest documentation.
