### ISSUE TITLE
Exclude particular jar not being downloaded from maven repo ?

### ISSUE THREAD

**Issue by TLNarayanaRao** [TIBCOSoftware/bw6-plugin-maven#694]
Maven Plugin version: 2.9.2

Maven version:

Product :  TIBCO Businessworks Container edition

Product version: 2.7.3

Component: Maven build plugin

Pom.xml dependency : 

`<build>
    <plugins>
      <plugin>
        <groupId>com.tibco.plugins</groupId>
        <artifactId>bw6-maven-plugin</artifactId>
        <version>2.9.2</version>
        <extensions>true</extensions>
        <executions>
      		<execution>
       			 <goals>
          			<goal>enforce</goal>
       			 </goals>
       		 <configuration>
         		 <rules>
            		<bannedDependencies>
             			 <excludes>
               				 <exclude>org.apache.maven.reporting:maven-reporting-impl</exclude>
             			 </excludes>
            		</bannedDependencies>
          		</rules>
       		 </configuration>
     	 </execution>
        </executions>
      </plugin>
    </plugins>
  </build>`

We would like to exclude the above dependency jar when we execute mvn clean package command from linux. 

this dependency got the vulnerability which we need to address. I tried with above exclude dependency but didnt work. 

if this feature is already implemented, please provide the example to exclude the dependency.

**Comment by TLNarayanaRao** [comment]
`<build>
    <plugins>
      <plugin>
        <groupId>com.tibco.plugins</groupId>
        <artifactId>bw6-maven-plugin</artifactId>
        <version>2.9.2</version>
        <extensions>true</extensions>
        <executions>
      		<execution>
       			 <goals>
          			<goal>enforce</goal>
       			 </goals>
       		 <configuration>
         		 <rules>
            		<bannedDependencies>
             			 <excludes>
               				 <exclude>org.apache.maven.reporting:maven-reporting-impl</exclude>
             			 </excludes>
            		</bannedDependencies>
          		</rules>
       		 </configuration>
     	 </execution>
        </executions>
      </plugin>
    </plugins>
  </build>`

**Comment by rutujadeo-TIBCO** [comment]
Dependency exclusions do work while creating EAR using Maven ; when included on parent pom only. using the below tag:

      <exclusions>
        <exclusion>
          <groupId>com.tibco.bw</groupId> 
          <artifactId>ProjectD</artifactId>
        </exclusion>
      </exclusions>

**Comment by rutujadeo-TIBCO** [comment]
Addressed in Enhancement :  [BWCE-5298](https://jira.tibco.com/browse/BWCE-5298) , which is fixed in maven plugin version 2.9.8
