### ISSUE TITLE
Error - The goal you specified requires a project to execute ...

### ISSUE THREAD

**Issue by bahmad1** [TIBCOSoftware/bw6-plugin-maven#698]
Maven Plugin version: plugin for 2.7.2

Maven version: 3.6.3

Product : bwce

Product version: 2.7.2

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1.
2.
3.

**Additional environment details if any:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
![Error](https://user-images.githubusercontent.com/37160941/217885452-e05ed3c1-5877-42ca-b21e-e980c30e4e2c.PNG)

**Comment by sarundes-tibco** [comment]
We didnot hear back from you @bahmad1 .. Hence marking this issue as closed.
