### ISSUE TITLE
How to deploy the same ear to different Env

### ISSUE THREAD

**Issue by akpuvvada** [TIBCOSoftware/bw6-plugin-maven#70]
I am using Jenkins to automate build and deploy to different environments.
I am using package goal and building the ear from the code in BW6x and uploading the ear to GitHub.
I need to create a new job to use the ear and config file uploaded to the same GitHub to deploy (only) to an environment.
Any idea how I may do this?

**Comment by Tantino** [comment]
you can use maven and differents profiles

**Comment by awagle** [comment]
Yes using profiles is the right thing to do. Please re-open if this does not answer your question.
