### ISSUE TITLE
Post maven set up, and successfully installed bw6 maven zip file by providing tibco home location. but not getting option in tibco bw6.7 designer to generate pom application.

### ISSUE THREAD

**Issue by vaishnavishan** [TIBCOSoftware/bw6-plugin-maven#705]
Maven Plugin version:

Maven version:

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version:

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1.
2.
3.

**Additional environment details if any:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by vaishnavishan** [comment]
![image](https://github.com/TIBCOSoftware/bw6-plugin-maven/assets/137862186/1eef6751-3ca8-4858-8fc4-ef5f8ffeb882)
![image](https://github.com/TIBCOSoftware/bw6-plugin-maven/assets/137862186/603afa48-7d6c-4a8b-8c62-388f1ebb122b)
first image is m2
second image is user directory where i downloaded source code

**Comment by vaishnavishan** [comment]
Any Update on this

**Comment by ukuppa-tibco** [comment]
@vaishnavishan Can you confirm BW version and Maven version once again? Is it BW 6.7.0 GA or 6.7.0 HF2?

**Comment by vaishnavishan** [comment]
Business Studio for BusinessWorks(TM)

TIBCO ActiveMatrix BusinessWorks 6.7.0

mvn --version
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T20:36:16+05:30)
Maven home: C:\javakehi3\tools\apache-maven-3.6.2\bin\..
Java version: 1.8.0_141, vendor: Oracle Corporation, runtime: C:\javakehi3\sdk\jdk1.8.0_141-x64\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by vaishnavishan** [comment]
@ukuppa-tibco @mkeskar-tibco any update on this

**Comment by vaishnavishan** [comment]
@ukuppa-tibco update: while installing it asks for tbco home location it throws errors while giving exact location. then after providing new tibco home ...build is successful but there is no option to generate pom application in designer.

**Comment by vaishnavishan** [comment]
@ukuppa-tibco @mkeskar-tibco any update on this

**Comment by vaishnavishan** [comment]
Please provide update at earliest @ukuppa-tibco @mkeskar-tibco  @ashutoshbhide

**Comment by vaishnavishan** [comment]
[INFO] Using 'UTF-8' encoding to read mojo source files.
[INFO] java-javadoc mojo extractor found 0 mojo descriptor.
Downloading from op-approved.m2repo.kehi.okobank.net: https://oppartifactory.eficode.com/op-approved/org/apache/maven/reporting/maven-reporting-impl/3.0.0/maven-reporting-impl-3.0.0-sources.jar
[WARNING] Unable to get sources artifact for org.apache.maven.reporting:maven-reporting-impl:3.0.0. Some javadoc tags (@since, @deprecated and comments) won't be used
Downloading from op-approved.m2repo.kehi.okobank.net: https://oppartifactory.eficode.com/op-approved/org/apache/maven/plugins/maven-compiler-plugin/3.3/maven-compiler-plugin-3.3-sources.jar
[WARNING] Unable to get sources artifact for org.apache.maven.plugins:maven-compiler-plugin:3.3. Some javadoc tags (@since, @deprecated and comments) won't be used
[INFO] java-annotations mojo extractor found 0 mojo descriptor.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:23 min
[INFO] Finished at: 2023-07-18T17:25:03+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.5:descriptor (default-descriptor) on project bw6-maven-plugin: Error extracting plugin descriptor: 'No mojo definitions were found for plugin: com.tibco.plugins:bw6-maven-plugin.' -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException


after giving mvn clean install in C:\Program Files\tibco\bw6\bw\6.7\maven\plugins\bw6-maven-plugin facing build failure 

 @ukuppa-tibco @mkeskar-tibco @ashutoshbhide @prashanthme88 @vpawar-tibco

**Comment by vaishnavishan** [comment]
any update on this @ukuppa-tibco @mkeskar-tibco @ashutoshbhide @prashanthme88 @vpawar-tibco

**Comment by ukuppa-tibco** [comment]
Kindly check _installinfo folder in your TIBCO home. This will help you to figure out if there is a HF installed. Also your About screen in BusinessStudio will show the same. If you have BW 6.7.0 without any HF; kindly uninstall maven plugin 2.8.1 and install 2.8.0 as per this https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/BW-Release-Compatibility-Guide

**Comment by vaishnavishan** [comment]
As you mentioned, checked installinfo folder in tibco home (please check
the new attachment) look like there is no hf. How to uninstall maven plugin
2.8.1.
Thanks for the suggestion.
Awaiting for your reply.

Thanks & Regards
Vaishnavi. S

**Comment by ukuppa-tibco** [comment]
I would recommend you to try this on a new TIBCO home. If possible please move from BW 6.7.0 to 6.8.0 or above; so that you get out of the box support for Maven plugin.
If you decide to still stick with BW 6.7.0; follow steps from https://github.com/TIBCOSoftware/bw6-plugin-maven and install Maven plugin 2.8.0 on top of BW 6.7.0 (a fresh TIBCO home installation).

**Comment by vaishnavishan** [comment]
Hi Usha,

As yu suggest I will try to install again with new tibco home (you mean new
tibco home is something like moving tibco folder to different location
right).
Also we are trying to do in bw 6.7.0 only.

Thanks,
Vaishnavi. S

**Comment by ukuppa-tibco** [comment]
You need to do a fresh BW 6.7.0 installation in a different folder.And then install Maven 2.8.0.

**Comment by vaishnavishan** [comment]
Hi Usha & team,
How to uninstall plugin 2.8.1 which I previous installed where I got build
success message at end.

Thanks & Regards,
Vaishnavi. S

**Comment by vaishnavishan** [comment]
I could hotfix is installed tibco activematrix businessworks version 6.7.0
hotfix 8, build v174, which means I need to install maven plugin v 2.8.1?
Please let me know. Awaiting your reply.
Attachment for your reference.

Thanks
Vaishnavi. S

**Comment by vaishnavishan** [comment]
Please refer this attachment if in this case I can install maven bw6 plugin
v2. 8.0 or v2. 8.1.

**Comment by vaishnavishan** [comment]
Please share your inputs as early as possible.

**Comment by vaishnavishan** [comment]
Hi,
Could yu please provide update if bw 6.7.0 hotfix 8 installed.can i proceed
with maven plugin version 2.8.1..
Also kindly refer the attachment.
Maven version  3.6.2
Java 1.8.
If I need to install maven plugin 2.8.0 how to uninstall maven 2.8.1.

Awaiting your reply
Thanks.,
Vaishnavi. S

**Comment by vaishnavishan** [comment]
Any update on this

**Comment by vaishnavishan** [comment]
Hi Usha & Team,

Please suggest way to uninstall bw6 maven plugin 2.8.1 which I got build
success message at the end of installation.
Awaiting your reply.
I need to do task at earliest. Please do the needful.
Thanks & Regards,

Vaishnavi. S

**Comment by ukuppa-tibco** [comment]
@vaishnavishan I cant see any attachment on this issue. 
We cannot uninstall Maven plugin once installed in a TIBCO home.
I would recommend you to install a fresh BW 670 home. If you are having HF2 or above; you would need Maven plugin 2.8.1; else if it is BW 6.7.0 GA you can go with Maven plugin 2.8.0.
Retry generating pom and let us know.

**Comment by vaishnavishan** [comment]
This is attachment for install_info folder I will proceed with maven 2.8.0
since there is no hf.. But please cross check install_info folder files
below attachment from your end if this is applicable for 2.8.0.

**Comment by ukuppa-tibco** [comment]
@vaishnavishan The image in attachment is blurred.
Cant see; provide a clear image.you can send me a screenshot taken using "Print screen" or a snipping tool.

**Comment by vaishnavishan** [comment]
Hi Usha,
Sorry for the inconvenience, Please refer to the attached image for
reference, Could you please confirm if I can install bw maven plugin 2.8.0.
so that i can uninstall the present one.
awaiting for your reply

Thanks in advance.
[image: image.png]

[image: image.png]
[image: image.png]

**Comment by vaishnavishan** [comment]
+++

**Comment by vaishnavishan** [comment]
Hi Usha,
Please ignore above attachment. Just came to know while trying to install
hf-02 files were present in install_info but in designer it is not working.
Let me do fresh installation as you suggested with bw6 maven plugin 2.8.0
for tibco bw 6.7.
Please kindly check once again. If this version is compactible,
Bw6 maven plugin 2.8.0
Business work 6.7
Maven version- 3.6.2
Java version- 1.8.0_252
Awaiting for your reply,
Thanks,
Vaishnavi. S

**Comment by ukuppa-tibco** [comment]
This stack looks good.Please go ahead @vaishnavishan

**Comment by vaishnavishan** [comment]
Hi Usha,
As mentioned , I have installed maven plugin 2.8.0 with fresh tibco home
installation.But i am getting a build success message at the end. But i
couldn't get an option in bw6.7 studio designer. I have pasted the below
logs .Please check and kindly provide a solution.
 Awaiting for your reply
=======
setupMacros:

vbuild.launcher.jar:

devbuild.launcher.jar:

studio-install:
     [echo]  Installing Eclipse M2E Plugin to Tibco Home
     [exec] log4j:WARN No appenders could be found for logger
(org.apache.http.impl.conn.SingleClientConnManager).
     [exec] log4j:WARN Please initialize the log4j system properly.
     [exec] Unable to load repositories.
     [exec] Installation failed.
     [exec] Application failed, log file location:
C:\ProgramData\output\studio\4.0\eclipse\configuration\1691081729642.log
     [exec]
     [exec] Result: 13
     [exec] Installing bw6.maven.dependencies.feature.feature.group
1.0.0.001.
     [exec] Operation completed in 5861 ms.
     [exec] Installing org.eclipse.m2e.feature.feature.group
1.6.2.20151013-0836.
     [exec] Installing org.eclipse.m2e.sdk.feature.feature.group
1.6.2.20151013-0836.
     [exec] Installing org.eclipse.m2e.logback.feature.feature.group
1.6.2.20151013-0836.
     [exec] Cannot complete the install because one or more required items
could not be found.
     [exec]  Software being installed: m2e - Maven Integration for Eclipse
(includes Incubating components) 1.6.2.20151013-0836
(org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836)
     [exec]  Missing requirement: m2e Marketplace 1.6.2.20151013-0836
(org.eclipse.m2e.discovery 1.6.2.20151013-0836) requires 'bundle
org.eclipse.equinox.p2.ui.discovery 0.0.0' but it could not be found
     [exec]  Cannot satisfy dependency:
     [exec]   From: m2e - Maven Integration for Eclipse (includes
Incubating components) 1.6.2.20151013-0836
(org.eclipse.m2e.feature.feature.group 1.6.2.20151013-0836)
     [exec]   To: org.eclipse.m2e.discovery [1.6.2.20151013-0836]
     [exec] Application failed, log file location:
C:\ProgramData\output\studio\4.0\eclipse\configuration\1691081743697.log
     [exec] Installation failed.
     [exec]
     [exec] Result: 13
     [echo]  UnInstalling the existing version of Plugin Code for Apache
Maven and TIBCO BusinessWorksÖ
     [exec] The installable unit bw6.studio.maven.feature.feature.group has
not been found.Installation failed.
     [exec]
     [exec] Application failed, log file location:
C:\ProgramData\output\studio\4.0\eclipse\configuration\1691081749664.log
     [exec]
     [exec] Result: 13
     [echo]  Installing Studio Plugin for Plugin Code for Apache Maven and
TIBCO BusinessWorksÖ to the Tibco Home
     [exec] Installing bw6.studio.maven.feature.feature.group 2.8.0.001.
     [exec] Installation failed.
     [exec] Cannot complete the install because one or more required items
could not be found.
     [exec]  Software being installed: TIBCO BusinessWorksÖ Studio Feature
for Maven 2.8.0.001 (bw6.studio.maven.feature.feature.group 2.8.0.001)
     [exec]  Missing requirement: TIBCO BusinessWorksÖ Studio Plugin for
Maven 2.8.0.001 (bw6.studio.maven.plugin 2.8.0.001) requires 'bundle
org.eclipse.m2e.core [1.3.1,2.0.0)' but it could not be found
     [exec]  Cannot satisfy dependency:
     [exec]   From: TIBCO BusinessWorksÖ Studio Feature for Maven 2.8.0.001
(bw6.studio.maven.feature.feature.group 2.8.0.001)
     [exec]   To: bw6.studio.maven.plugin [2.8.0.001]
     [exec] Application failed, log file location:
C:\ProgramData\output\studio\4.0\eclipse\configuration\1691081752672.log
     [exec]
     [exec] Result: 13

maven-install:
     [echo]  Installing Maven Plugin for Plugin Code for Apache Maven and
TIBCO BusinessWorksÖ to Local Maven Repository
    [mkdir] Created dir: C:\ProgramData\output\bw\6.7\maven\plugins
    [unzip] Expanding:
C:\Users\B729223\Mavenplugin\TIB_BW_Maven_Plugin_2.8.0\config\bw6-maven-plugin.zip
into C:\ProgramData\output\bw\6.7\maven\plugins\bw6-maven-plugin

winInstall:
     [exec]
     [exec]
C:\ProgramData\output\bw\6.7\maven\plugins\bw6-maven-plugin>echo Installing
Maven Plugin to Maven Repository
     [exec] Installing Maven Plugin to Maven Repository
     [exec]
     [exec]
C:\ProgramData\output\bw\6.7\maven\plugins\bw6-maven-plugin>start cmd.exe
/C mvn install:install-file
-Dfile=com.tibco.bw.palette.shared_6.1.100.003.jar
-DgroupId=com.tibco.plugins -DartifactId=com.tibco.bw.palette.shared
-Dversion=6.1.100 -Dpackaging=jar
     [exec]
     [exec]
C:\ProgramData\output\bw\6.7\maven\plugins\bw6-maven-plugin>start cmd.exe
/C mvn install:install-file -Dfile=com.tibco.xml.cxf.common_1.3.200.001.jar
-DgroupId=com.tibco.plugins -DartifactId=com.tibco.xml.cxf.common
-Dversion=1.3.200 -Dpackaging=jar
     [exec]
     [exec]
C:\ProgramData\output\bw\6.7\maven\plugins\bw6-maven-plugin>start cmd.exe
/C mvn install:install-file -Dfile=bw6-maven-plugin-2.8.0.jar
-DpomFile=pom.xml
     [exec]
     [exec]
C:\ProgramData\output\bw\6.7\maven\plugins\bw6-maven-plugin>start cmd.exe
/C mvn install:install-file -Dfile=fabric8/fabric8-maven-plugin-4.4.1.jar
-DpomFile=fabric8/pom.xml

linuxInstall:

maven-plugin-install:

setup:

BUILD SUCCESSFUL
Total time: 1 minute 0 seconds

Thanks,
Vaishnavi.S

**Comment by ukuppa-tibco** [comment]
@vaishnavishan I can see some installation failures in the output you shared. Can you share me a zip of "C:\ProgramData\output\studio\4.0\eclipse\configuration" folder.

**Comment by ukuppa-tibco** [comment]
Cant see any attachment. 
Are you making sure you give the correct path of TIBCO home to the install.sh script while installing maven plugin?
You need to give path of the parent directory which will have sub-folders like "bw","p2repos" etc.
Do you see a "maven" folder under <TIBCO_HOME>/bw/6.7 ? If yes; do you see a folder structure like <TIB_HOME>/bw/6.7/maven/plugins/bw6-maven-plugin ? Share a screenshot of what contents you see in this folder.
@vaishnavishan

**Comment by vaishnavishan** [comment]
Yes I have created tibco home C:\ProgramData\output (where output is folder
name for tibco) this contain install_info, bw, eclipse-platform, p2presos,
reales notes, studio, thor, tibcojre, tools. Please refer image.

Yes I do see maven folder under
C:\ProgramData\output\bw\6.7\maven\plugins\bw6-maven-plugin under this I
can see install. Sh, bat, jar files.

**Comment by ukuppa-tibco** [comment]
Can you try creating TIBCO home in another location apart from Program Data or Program Files? Something like C:/<tibcoHomeName>. @vaishnavishan

**Comment by vaishnavishan** [comment]
Hi Usha,
 I have tried couple of times for creating fresh tibco home still facing
same issue.

Please let me know if any steps I need to perform.

Thanks,
Vaishnavi

**Comment by vaishnavishan** [comment]
Hi Usha,

Any update on this?

**Comment by ukuppa-tibco** [comment]
@vaishnavishan As I mentioned please create a new TIBCO home on a location other than "ProgramData" folder. It can be something like C:/TIBCO/Newhome

**Comment by vaishnavishan** [comment]
Yes Usha I tried in C:\tibhome. I could see folders are creating properly.
But options are not available in bw6 designer either maven or generate pom.

**Comment by ukuppa-tibco** [comment]
Do you see "maven" folder in your TIBCO home/bw/6.7 ?
If yes; please check <USER_HOME>\.m2\repository\com\tibco\plugins\bw6-maven-plugin\2.8.0 folder. It should have maven plugin jar file,pom file and sha1 file and properties file.
You can try running install.sh script again which sits in tibco home/maven folder; this might help solving your issues.

**Comment by vaishnavishan** [comment]
Hi Usha,
Kindly Refer the attached file for your reference in zip file. Let me know
if this is visible.

**Comment by vaishnavishan** [comment]
Hi,

Any update on this?

Thanks,
Vaishnavi. S

**Comment by ukuppa-tibco** [comment]
@vaishnavishan Did you happen to successfully install Maven plugin on this machine in the past? It looks like an issue with your machine. We are able to successfully install and work with the same stack as mentioned by you.
maven plugin 2.8.0
Business work 6.7
Maven version- 3.6.2
Can you or someone in your team try the same stack on another machine and let us know if you still see issue?
You can also alternatively pick BW 6.8.0 which has out of the box support for Maven plugin.

As a last check - I will ask you to send me a screenshot of the following window in Business Studio.
Windows -> Preferences -> BusinessWorks -> Maven Defaults

**Comment by vaishnavishan** [comment]
Hi Usha,

Could you please share your folder structure under home especially m2
setting.xml.

**Comment by sarundes-tibco** [comment]
We didn't hear back from you @vaishnavishan . Hence marking this issue as closed
