### ISSUE TITLE
Failed to create BW EAR Archive: NullPointerException with SharedModule dependency and bw6-maven-plugin 2.9.6

### ISSUE THREAD

**Issue by ijh880304** [TIBCOSoftware/bw6-plugin-maven#710]
Maven Plugin version: 2.9.6

Maven version: 3.6.3

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version: BW 6.9.1

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1. Failed to create BW EAR Archive: NullPointerException when maven package the BW Application Project with SharedModule Project

**Additional environment details if any:**
If i change bw6-maven-plugin version to 2.9.4 or 2.9.2 or 2.9.0, it builds normally.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
[TEST.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/12583883/TEST.zip)
[mvnlog.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/12583886/mvnlog.txt)

**Comment by sarundes-tibco** [comment]
Tested on 6.10.1 V6 , Not able to see any error while generating EAR file.
