### ISSUE TITLE
post installing bw6 maven plugin in tibco studio designer. we could see option for maven and generated pom.xml. while trying to mavenixing and deploying application facing this below error.

### ISSUE THREAD

**Issue by vaishnavishan** [TIBCOSoftware/bw6-plugin-maven#714]
we followed https://tibtechtutorial.wordpress.com/2020/07/29/installing-maven-and-maven-plug-in-for-tibco-bw6-x/ - your steps for plugin installation but at last step:
Before using BW Studio to generate POM file need to update maven repository by executing below commands which downloads all the dependency. This can be used using attached setting.xml. Below attached sample setting.xml needs to place under maven repository.
while installing mvn dependencies facing errors;
C:\tibmaven\bw\6.7\maven\plugins\bw6-maven-plugin>mvn install dependency:copy-dependencies
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]
[INFO] -----------------< com.tibco.plugins:bw6-maven-plugin >-----------------
[INFO] Building Plugin Code for Apache Maven and TIBCO BusinessWorks? 2.8.0
[INFO] ----------------------------[ maven-plugin ]----------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ bw6-maven-plugin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\tibmaven\bw\6.7\maven\plugins\bw6-maven-plugin\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ bw6-maven-plugin ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-plugin-plugin:3.5:descriptor (default-descriptor) @ bw6-maven-plugin ---
[INFO] Using 'UTF-8' encoding to read mojo source files.
[INFO] java-javadoc mojo extractor found 0 mojo descriptor.
Downloading from site
approved/org/apache/maven/reporting/maven-reporting-impl/3.0.0/maven-reporting-impl-3.0.0-sources.jar
[WARNING] Unable to get sources artifact for org.apache.maven.reporting:maven-reporting-impl:3.0.0. Some javadoc tags (@since, @deprecated and comments) won't be used
Downloading from op-approved.m2repo.kehi.okobank.net: approved/org/apache/maven/plugins/maven-compiler-plugin/3.3/maven-compiler-plugin-3.3-sources.jar
[WARNING] Unable to get sources artifact for org.apache.maven.plugins:maven-compiler-plugin:3.3. Some javadoc tags (@since, @deprecated and comments) won't be used
[INFO] java-annotations mojo extractor found 0 mojo descriptor.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19.469 s
[INFO] Finished at: 2023-10-26T15:15:45+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.5:descriptor (default-descriptor) on project bw6-maven-plugin: Error extracting plugin descriptor: 'No mojo definitions were found for plugin: com.tibco.plugins:bw6-maven-plugin.' -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by vaishnavishan** [comment]
@ashutoshbhide @abhide-tibco @rahulkamdar

**Comment by vaishnavishan** [comment]
Could you please share what are the dependency jar files names to install maven plugin 2.8.0 in tibco designer studio bw 6.7. Could you please comment at the earliest. awaiting for your response. @todell-tibco @atupatil-tibco @pdhar-tibco ..let us know fix for the error. Thanks
=========================
C:\tibmaven\bw\6.7\maven\plugins\bw6-maven-plugin>mvn clean install
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]
[INFO] -----------------< com.tibco.plugins:bw6-maven-plugin >-----------------
[INFO] Building Plugin Code for Apache Maven and TIBCO BusinessWorks? 2.8.0
[INFO] ----------------------------[ maven-plugin ]----------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ bw6-maven-plugin ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ bw6-maven-plugin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\tibmaven\bw\6.7\maven\plugins\bw6-maven-plugin\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ bw6-maven-plugin ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-plugin-plugin:3.5:descriptor (default-descriptor) @ bw6-maven-plugin ---
[INFO] Using 'UTF-8' encoding to read mojo source files.
[INFO] java-javadoc mojo extractor found 0 mojo descriptor.
Downloading from op-approved.m2repo.kehi.okobank.net: https://oppartifactory.eficode.com/op-approved/org/apache/maven/reporting/maven-reporting-impl/3.0.0/maven-reporting-impl-3.0.0-sources.jar
[WARNING] Unable to get sources artifact for org.apache.maven.reporting:maven-reporting-impl:3.0.0. Some javadoc tags (@since, @deprecated and comments) won't be used
Downloading from op-approved.m2repo.kehi.okobank.net: https://oppartifactory.eficode.com/op-approved/org/apache/maven/plugins/maven-compiler-plugin/3.3/maven-compiler-plugin-3.3-sources.jar
[WARNING] Unable to get sources artifact for org.apache.maven.plugins:maven-compiler-plugin:3.3. Some javadoc tags (@since, @deprecated and comments) won't be used
[INFO] java-annotations mojo extractor found 0 mojo descriptor.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  31.917 s
[INFO] Finished at: 2023-10-27T17:41:45+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.5:descriptor (default-descriptor) on project bw6-maven-plugin: Error extracting plugin descriptor: 'No mojo definitions were found for plugin: com.tibco.plugins:bw6-maven-plugin.' -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by vaishnavishan** [comment]
@vpawar-tibco any update on this

**Comment by ukuppa-tibco** [comment]
Please try re-generating your pom file. @vaishnavishan

**Comment by vaishnavishan** [comment]
i have tried regeneration pom file in tibco studio designer still facing the same. post maven plugin install. i cant dwonload all dependencies 
Before using BW Studio to generate POM file need to update maven repository by executing below commands which downloads all the dependency. This can be used using attached setting.xml. Below attached sample setting.xml needs to place under maven repository.
C:\tibmaven\bw\6.7\maven\plugins\bw6-maven-plugin>mvn clean install
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]
[INFO] -----------------< com.tibco.plugins:bw6-maven-plugin >-----------------
[INFO] Building Plugin Code for Apache Maven and TIBCO BusinessWorks? 2.8.0
[INFO] ----------------------------[ maven-plugin ]----------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ bw6-maven-plugin ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ bw6-maven-plugin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\tibmaven\bw\6.7\maven\plugins\bw6-maven-plugin\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ bw6-maven-plugin ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-plugin-plugin:3.5:descriptor (default-descriptor) @ bw6-maven-plugin ---
[INFO] Using 'UTF-8' encoding to read mojo source files.
[INFO] java-javadoc mojo extractor found 0 mojo descriptor.
Downloading from op-approved.m2repo.kehi.okobank.net: https://oppartifactory.eficode.com/op-approved/org/apache/maven/reporting/maven-reporting-impl/3.0.0/maven-reporting-impl-3.0.0-sources.jar
[WARNING] Unable to get sources artifact for org.apache.maven.reporting:maven-reporting-impl:3.0.0. Some javadoc tags (@since, @deprecated and comments) won't be used
Downloading from op-approved.m2repo.kehi.okobank.net: https://oppartifactory.eficode.com/op-approved/org/apache/maven/plugins/maven-compiler-plugin/3.3/maven-compiler-plugin-3.3-sources.jar
[WARNING] Unable to get sources artifact for org.apache.maven.plugins:maven-compiler-plugin:3.3. Some javadoc tags (@since, @deprecated and comments) won't be used
[INFO] java-annotations mojo extractor found 0 mojo descriptor.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  31.917 s
[INFO] Finished at: 2023-10-27T17:41:45+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.5:descriptor (default-descriptor) on project bw6-maven-plugin: Error extracting plugin descriptor: 'No mojo definitions were found for plugin: com.tibco.plugins:bw6-maven-plugin.' -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by vaishnavishan** [comment]
Please refer  com repository
[com.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/13204035/com.zip)
[com.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/13204037/com.zip)

**Comment by vaishnavishan** [comment]
[INFO] java-javadoc mojo extractor found 0 mojo descriptor.
[WARNING] Unable to get sources artifact for org.apache.maven.reporting:maven-reporting-impl:3.0.0. Some javadoc tags (@since, @deprecated and comments) won't be used
[WARNING] Unable to get sources artifact for org.apache.maven.plugins:maven-compiler-plugin:3.3. Some javadoc tags (@since, @deprecated and comments) won't be used
[INFO] java-annotations mojo extractor found 0 mojo descriptor.

please suggest how to resolve this issue, awaiting for your response

**Comment by vaishnavishan** [comment]
Hi All,

Please check and update us and update at earliest.


Thanks,
Vaishnavi.s

**Comment by vaishnavishan** [comment]
Any update on this ..please awaiting for yur response.
@ukuppa-tibco

**Comment by vaishnavishan** [comment]
Hello,
Please procide update for this.  awaiting for your response.

**Comment by ukuppa-tibco** [comment]
What is exactly the issue? Warnings seen can be ignore. Are you able to execute Maven test goal?

**Comment by vaishnavishan** [comment]
i can see options for maven and pom.application in tibco studio designer bw 6.7 . i can generate pom.xml as well. But when i try to run maven clean in bw studio designer it fails. and maven depencies folder seems to be empty.  it looks like target folder is not created under tibco home (C:\tibmaven\bw\6.7\maven\plugins\bw6-maven-plugin).
Please refer com repository as well if files are proper.
if possible please set up a meeting.
==================================
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.5:descriptor (default-descriptor) on project bw6-maven-plugin: Error extracting plugin descriptor: 'No mojo definitions were found for plugin: com.tibco.plugins:bw6-maven-plugin.' -> [Help 1]

**Comment by ukuppa-tibco** [comment]
Which maven dependency folder is empty? Kindly attach the project you are trying to execute maven goal.

**Comment by vaishnavishan** [comment]
[maven.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/13237754/maven.zip)
Please find the attached maven folder.let us know if anything else required.

**Comment by vaishnavishan** [comment]
Any update on this @ukuppa-tibco @vpawar-tibco

**Comment by ukuppa-tibco** [comment]
@vaishnavishan Please share the BusinessWorks project you are using

**Comment by vaishnavishan** [comment]
this issue got resolved, creting new case , please respond at earliest
