### ISSUE TITLE
How to do deploying ear using maven bw6 plugin in test tibco servers. Please share steps and configuration.

### ISSUE THREAD

**Issue by vaishnavishan** [TIBCOSoftware/bw6-plugin-maven#718]
Maven bw6 plugin is successful, I could see maven option and generate pom application is available in my studio , I tried doing in local deployment it works .but actually requirement is deploying ear in test server using maven bw6 plugin , But while giving port and ip details it is not happening as expected. logs looks like it deploying in local host not in test servers.

**Comment by vaishnavishan** [comment]
@abhide-tibco @Ushakuppa

**Comment by vaishnavishan** [comment]
Any update on this @mkent-tibco @pdhar-tibco

**Comment by ukuppa-tibco** [comment]
Please cross-check all the field values in "Deployment details for TIBCO BusinessWorks Application" wizard. Configure correct values of Agent host and Agent port.

**Comment by vaishnavishan** [comment]
do we need to configure firewall and i have provided correct agent host and port..can you please share documentation steps for the same @ukuppa-tibco

**Comment by ukuppa-tibco** [comment]
Please run clean install goal to ensure the values are picked.

**Comment by ukuppa-tibco** [comment]
Before you begin
Ensure that the TIBCO® Enterprise Administrator is up and running with the registered BWAgent.
To deploy EAR on AppSpace via TIBCO Business Studio for BusinessWorks, perform the following steps:
Procedure
Right-click a .parent application and select Generate POM for Application. The Generate POM for Application dialog opens.
To set Deploy Options, select AppSpace from the dropdown list while generating pom.xml. Then click Next.
Update the required configuration details (Agent, AppNode, and so on) in the Deployment Details for TIBCO BusinessWorks™ wizard and select the appropriate Profile..
Click Finish. Right-click the .parent folder and run the Maven > Install command.

The application is now deployed on AppSpace.

**Comment by vaishnavishan** [comment]
What is exact maven command to run..  Please share... is it mvn clean install

**Comment by vaishnavishan** [comment]
<img width="547" alt="image" src="https://github.com/TIBCOSoftware/bw6-plugin-maven/assets/137862186/43c7b619-06ae-4cb1-bba9-e2fd329f4ae8">

i run with package as goal for localhost it works and ear file is generated

**Comment by vaishnavishan** [comment]
Do we have any video links or logs to compare how it will generate ear and please share goal if it should have package or mvn clean install. when i ran with package it shows successful in local where i ran mvn clean install it fails

**Comment by ukuppa-tibco** [comment]
In the goal field in your screenshot enter "clean install". "package" goal will only create EAR.

**Comment by vaishnavishan** [comment]
Clean install is the command to deployment.

**Comment by vaishnavishan** [comment]
[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository

C:\Users\B729223>mvn -s C:\Users\B729223\AppData\Local\Temp\2\settings4449059262810332755.xml install:install-file  -Dfile="C:\Users\B729223\card-transaction-server-v2\main\CtsServiceMain\lib\commons-cli-1.4.jar" -DgroupId=tempbw -DartifactId=commons-cli-1.4 -Dversion=0.0.0 -Dpackaging=jar -DlocalRepositoryPath="C:\Users\B729223\.m2\repository" 
Error occurred during initialization of VM
Unable to allocate 131072KB bitmaps for parallel garbage collection for the requested 4194304KB heap.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[INFO] The C:\Users\B729223\AppData\Local\Temp\2\settings4449059262810332755.xml Temporal file is deleted sucessfully

C:\Users\B729223>mvn -s C:\Users\B729223\AppData\Local\Temp\2\settings7910447508738609831.xml install:install-file  -Dfile="C:\Users\B729223\card-transaction-server-v2\main\CtsServiceMain\lib\commons-codec-1.15.jar" -DgroupId=tempbw -DartifactId=commons-codec-1.15 -Dversion=0.0.0 -Dpackaging=jar -DlocalRepositoryPath="C:\Users\B729223\.m2\repository" 
Error occurred during initialization of VM
Unable to allocate 131072KB bitmaps for parallel garbage collection for the requested 4194304KB heap.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[INFO] The C:\Users\B729223\AppData\Local\Temp\2\settings7910447508738609831.xml Temporal file is deleted sucessfully

C:\Users\B729223>mvn -s C:\Users\B729223\AppData\Local\Temp\2\settings6671175218982428352.xml install:install-file  -Dfile="C:\Users\B729223\card-transaction-server-v2\main\CtsServiceMain\lib\jackson-annotations-2.9.0.jar" -DgroupId=tempbw -DartifactId=jackson-annotations-2.9.0 -Dversion=0.0.0 -Dpackaging=jar -DlocalRepositoryPath="C:\Users\B729223\.m2\repository" 
Error occurred during initialization of VM
Unable to allocate 131072KB bitmaps for parallel garbage collection for the requested 4194304KB heap.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[INFO] The C:\Users\B729223\AppData\Local\Temp\2\settings6671175218982428352.xml Temporal file is deleted sucessfully

C:\Users\B729223>mvn -s C:\Users\B729223\AppData\Local\Temp\2\settings6922801870075888309.xml install:install-file  -Dfile="C:\Users\B729223\card-transaction-server-v2\main\CtsServiceMain\lib\jackson-core-2.9.9.jar" -DgroupId=tempbw -DartifactId=jackson-core-2.9.9 -Dversion=0.0.0 -Dpackaging=jar -DlocalRepositoryPath="C:\Users\B729223\.m2\repository" 
Error occurred during initialization of VM
Unable to allocate 131072KB bitmaps for parallel garbage collection for the requested 4194304KB heap.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[INFO] The C:\Users\B729223\AppData\Local\Temp\2\settings6922801870075888309.xml Temporal file is deleted sucessfully

C:\Users\B729223>mvn -s C:\Users\B729223\AppData\Local\Temp\2\settings3054107288175891907.xml install:install-file  -Dfile="C:\Users\B729223\card-transaction-server-v2\main\CtsServiceMain\lib\jackson-databind-2.9.9.3.jar" -DgroupId=tempbw -DartifactId=jackson-databind-2.9.9.3 -Dversion=0.0.0 -Dpackaging=jar -DlocalRepositoryPath="C:\Users\B729223\.m2\repository" 
Error occurred during initialization of VM
Unable to allocate 131072KB bitmaps for parallel garbage collection for the requested 4194304KB heap.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[INFO] The C:\Users\B729223\AppData\Local\Temp\2\settings3054107288175891907.xml Temporal file is deleted sucessfully

C:\Users\B729223>mvn -s C:\Users\B729223\AppData\Local\Temp\2\settings2482378414182969749.xml install:install-file  -Dfile="C:\Users\B729223\card-transaction-server-v2\main\CtsServiceMain\lib\jdom2-2.0.6.jar" -DgroupId=tempbw -DartifactId=jdom2-2.0.6 -Dversion=0.0.0 -Dpackaging=jar -DlocalRepositoryPath="C:\Users\B729223\.m2\repository" 
Error occurred during initialization of VM
Unable to allocate 131072KB bitmaps for parallel garbage collection for the requested 4194304KB heap.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[INFO] The C:\Users\B729223\AppData\Local\Temp\2\settings2482378414182969749.xml Temporal file is deleted sucessfully

C:\Users\B729223>mvn -s C:\Users\B729223\AppData\Local\Temp\2\settings7416626290804024697.xml install:install-file  -Dfile="C:\Users\B729223\card-transaction-server-v2\main\CtsServiceMain\lib\jpos-2.1.6.jar" -DgroupId=tempbw -DartifactId=jpos-2.1.6 -Dversion=0.0.0 -Dpackaging=jar -DlocalRepositoryPath="C:\Users\B729223\.m2\repository" 
Error occurred during initialization of VM
Unable to allocate 131072KB bitmaps for parallel garbage collection for the requested 4194304KB heap.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[INFO] The C:\Users\B729223\AppData\Local\Temp\2\settings7416626290804024697.xml Temporal file is deleted sucessfully
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] CtsServiceApp.parent                                               [pom]
[INFO] CtsServiceMain                                                [bwmodule]
[INFO] CtsServiceApp                                                    [bwear]
[INFO] 
[INFO] -----------------< com.tibco.bw:CtsServiceApp.parent >------------------
[INFO] Building CtsServiceApp.parent 2.53.5-SNAPSHOT                      [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ CtsServiceApp.parent ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ CtsServiceApp.parent ---
[INFO] Installing C:\Users\B729223\card-transaction-server-v2\main\CtsServiceApp.parent\pom.xml to C:\Users\B729223\.m2\repository\com\tibco\bw\CtsServiceApp.parent\2.53.5-SNAPSHOT\CtsServiceApp.parent-2.53.5-SNAPSHOT.pom
[INFO] 
[INFO] --------------------< com.tibco.bw:CtsServiceMain >---------------------
[INFO] Building CtsServiceMain 2.53.5-SNAPSHOT                            [2/3]
[INFO] ------------------------------[ bwmodule ]------------------------------
[INFO] Downloading from op-approved.m2repo.kehi.okobank.net: https://oppartifactory.eficode.com/op-approved/tempbw/commons-cli-1.4/0.0.0/commons-cli-1.4-0.0.0.pom
[WARNING] The POM for tempbw:commons-cli-1.4:jar:0.0.0 is missing, no dependency information available
[INFO] Downloading from op-approved.m2repo.kehi.okobank.net: https://oppartifactory.eficode.com/op-approved/tempbw/commons-codec-1.15/0.0.0/commons-codec-1.15-0.0.0.pom
[WARNING] The POM for tempbw:commons-codec-1.15:jar:0.0.0 is missing, no dependency information available
[INFO] Downloading from op-approved.m2repo.kehi.okobank.net: https://oppartifactory.eficode.com/op-approved/tempbw/jackson-annotations-2.9.0/0.0.0/jackson-annotations-2.9.0-0.0.0.pom
[WARNING] The POM for tempbw:jackson-annotations-2.9.0:jar:0.0.0 is missing, no dependency information available
[INFO] Downloading from op-approved.m2repo.kehi.okobank.net: https://oppartifactory.eficode.com/op-approved/tempbw/jackson-core-2.9.9/0.0.0/jackson-core-2.9.9-0.0.0.pom
[WARNING] The POM for tempbw:jackson-core-2.9.9:jar:0.0.0 is missing, no dependency information available
[INFO] Downloading from op-approved.m2repo.kehi.okobank.net: https://oppartifactory.eficode.com/op-approved/tempbw/jackson-databind-2.9.9.3/0.0.0/jackson-databind-2.9.9.3-0.0.0.pom
[WARNING] The POM for tempbw:jackson-databind-2.9.9.3:jar:0.0.0 is missing, no dependency information available
[INFO] Downloading from op-approved.m2repo.kehi.okobank.net: https://oppartifactory.eficode.com/op-approved/tempbw/jdom2-2.0.6/0.0.0/jdom2-2.0.6-0.0.0.pom
[WARNING] The POM for tempbw:jdom2-2.0.6:jar:0.0.0 is missing, no dependency information available
[INFO] Downloading from op-approved.m2repo.kehi.okobank.net: https://oppartifactory.eficode.com/op-approved/tempbw/jpos-2.1.6/0.0.0/jpos-2.1.6-0.0.0.pom
[WARNING] The POM for tempbw:jpos-2.1.6:jar:0.0.0 is missing, no dependency information available
[INFO] Downloading from op-approved.m2repo.kehi.okobank.net: https://oppartifactory.eficode.com/op-approved/tempbw/commons-cli-1.4/0.0.0/commons-cli-1.4-0.0.0.jar
[INFO] Downloading from op-approved.m2repo.kehi.okobank.net: https://oppartifactory.eficode.com/op-approved/tempbw/jackson-annotations-2.9.0/0.0.0/jackson-annotations-2.9.0-0.0.0.jar
[INFO] Downloading from op-approved.m2repo.kehi.okobank.net: https://oppartifactory.eficode.com/op-approved/tempbw/commons-codec-1.15/0.0.0/commons-codec-1.15-0.0.0.jar
[INFO] Downloading from op-approved.m2repo.kehi.okobank.net: https://oppartifactory.eficode.com/op-approved/tempbw/jackson-core-2.9.9/0.0.0/jackson-core-2.9.9-0.0.0.jar
[INFO] Downloading from op-approved.m2repo.kehi.okobank.net: https://oppartifactory.eficode.com/op-approved/tempbw/jackson-databind-2.9.9.3/0.0.0/jackson-databind-2.9.9.3-0.0.0.jar
[INFO] Downloading from op-approved.m2repo.kehi.okobank.net: https://oppartifactory.eficode.com/op-approved/tempbw/jdom2-2.0.6/0.0.0/jdom2-2.0.6-0.0.0.jar
[INFO] Downloading from op-approved.m2repo.kehi.okobank.net: https://oppartifactory.eficode.com/op-approved/tempbw/jpos-2.1.6/0.0.0/jpos-2.1.6-0.0.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for CtsServiceApp.parent 2.53.5-SNAPSHOT:
[INFO] 
[INFO] CtsServiceApp.parent ............................... SUCCESS [  0.831 s]
[INFO] CtsServiceMain ..................................... FAILURE [  3.105 s]
[INFO] CtsServiceApp ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.790 s
[INFO] Finished at: 2023-12-28T17:16:24+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project CtsServiceMain: Could not resolve dependencies for project com.tibco.bw:CtsServiceMain:bwmodule:2.53.5-SNAPSHOT: The following artifacts could not be resolved: tempbw:commons-cli-1.4:jar:0.0.0, tempbw:commons-codec-1.15:jar:0.0.0, tempbw:jackson-annotations-2.9.0:jar:0.0.0, tempbw:jackson-core-2.9.9:jar:0.0.0, tempbw:jackson-databind-2.9.9.3:jar:0.0.0, tempbw:jdom2-2.0.6:jar:0.0.0, tempbw:jpos-2.1.6:jar:0.0.0: Could not find artifact tempbw:commons-cli-1.4:jar:0.0.0 in op-approved.m2repo.kehi.okobank.net (https://oppartifactory.eficode.com/op-approved) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :CtsServiceMain

**Comment by ukuppa-tibco** [comment]
Please check if you have added all dependencies on module pom.

**Comment by vaishnavishan** [comment]
Can you share you the sample on module pom..so that I can cross verify
from my side.

**Comment by rutujadeo-TIBCO** [comment]
@vaishnavishan Kindly follow the latest technical documentation,  [Tibco_Maven_Bw6](https://docs.tibco.com/pub/activematrix_businessworks/6.10.0/doc/pdf/TIB_BW_6.10.0_maven_plug-in.pdf?id=7)
 or  [Git_Hub_Wiki_Maven_BW6](https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki)
