### ISSUE TITLE
Deploy options are not visible in BW studio 6.9

### ISSUE THREAD

**Issue by CAbhishek28** [TIBCOSoftware/bw6-plugin-maven#723]
Hi Team,

I have installed Tibco BW 6.9 with maven plugin 2.9.6. When I am trying to generate POM for the application I am not seeing the Deploy options.
like: Engine debug port, deploy options etc.
I have attached the image as well
Once the EAR/POM file is generated we want to deploy the application using Azure devops.
Kindly help us with the issue.

Regards
Abhishek

-----------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->
Maven Plugin version: 2.9.6

Maven version:

Product : Either of TIBCO ActiveMatrix Businessworks 6.9

Product version: 6.9.1

Component:  Maven build plugin

**Steps to reproduce the issue:**
1. Import the project
2. right click on the application and we see option "Generate POM for application"
3.

**Additional environment details if any:**

**Describe the results you received:**
I am unable to see the deploy options

<img width="759" alt="image" src="https://github.com/TIBCOSoftware/bw6-plugin-maven/assets/167678632/c48e1973-625a-4d6a-8efb-f6adc11ce92f">

**Describe the results you expected:**
I am expected to see Engine port number, Appspace details to deploy application
<img width="563" alt="expected_result" src="https://github.com/TIBCOSoftware/bw6-plugin-maven/assets/167678632/f9832a71-5f51-4f08-b669-b1dc58d5f826">

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by ukuppa-tibco** [comment]
Can you please check the drop-down options for "Deploy options". It will show PCF,Docker,Platform,Appspace.
Please select Appspace and click Next; you will see the deploy options then.

**Comment by CAbhishek28** [comment]
HI Usha,
![image](https://github.com/TIBCOSoftware/bw6-plugin-maven/assets/167678632/8a2e72b2-bcb2-4bcb-be93-a75875f31da0)

The above image I shared is the unexpected one, I am not able to see the deploy section to select the Appspace.

**Comment by CAbhishek28** [comment]
Hi Usha,

I have checked and even if I reduce the resolution it still doesn't show the options.

Regards
Abhishek

**Comment by ukuppa-tibco** [comment]
@CAbhishek28 Are you still facing this issue?

**Comment by ukuppa-tibco** [comment]
Closing this issue since we did not hear back from you.
