### ISSUE TITLE
Do we need BW6 to be installed on DevOps agent when building app via MVN?

### ISSUE THREAD

**Issue by vkrejcirik** [TIBCOSoftware/bw6-plugin-maven#725]
I'm building VM which will serve as DevOps agent for building BW6 application and deploying it to BW6 domain. Do we need to install complete BusinessWorks on this box? I would like to avoid it. I would rather provide only necessary jars /  binaries which are need to build and deploy ear file into BW6 domain.

Thanks,
Vlad

**Comment by sarundes-tibco** [comment]
@vkrejcirik  Can you please reach out BW support for this.
