### ISSUE TITLE
 buildear: command not found Build step 'Execute shell' marked build as failure

### ISSUE THREAD

**Issue by rupasrinunna** [TIBCOSoftware/bw6-plugin-maven#735]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Product : TIBCO ActiveMatrix Businessworks 5 
Product version: BW5 jenkins deployment

Building in workspace /var/lib/jenkins/workspace/PN02-NCM-continuous-BB
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
The recommended git tool is: NONE
using credential Bitbucket_NewPassword
Cloning the remote Git repository
Cloning repository
 > git init /var/lib/jenkins/workspace/PN02-NCM-continuous-BB # timeout=10
Fetching upstream changes from 
 > git --version # timeout=10
 > git --version # 'git version 2.40.1'
using GIT_ASKPASS to set credentials Bitbucket_NewPassword for jenkins(Surendra)
 > git fetch --tags --force --progress -- +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
Avoid second fetch
 > git rev-parse refs/remotes/origin/Develop^{commit} # timeout=10
Checking out Revision d4ab41e0130753b7bb34a7e3fc0ff917ee0892ec (refs/remotes/origin/Develop)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f d4ab41e0130753b7bb34a7e3fc0ff917ee0892ec # timeout=10
Commit message: "Removed ProdDay jar"
 > git rev-list --no-walk 4d0a574e756f202321d741adf3c649f2fcad972f # timeout=10
No emails were triggered.
Xvfb starting$ /usr/bin//Xvfb :100 -screen 0 1024x768x16 -fbdir XXXXXXXXXXXs-BB/.xvfb-3631-..fbdir1533429839591625067
[PN02-NCM-continuous-BB] $ /bin/sh -xe /tmp/jenkins3238031037421588481.sh
+ export VersionName=3.169
+ VersionName=3.169
+ export PATH=/cint/local/appl/tibco/cinteaiBW513/tra/5.10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
+ PATH=/cint/local/appl/tibco/cinteaiBW513/tra/5.10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
+ mkdir build
+ NAME=PN02-NCM
+ NAME=PN02-NCM
+ EAR_NAME=/Deployment/PN02-NCM.archive
+ awk '-F\' -v ws=/var/lib/jenkins/workspace/PN02-NCM-continuous-BB '{libName=substr($1,0,index($1,"-")-1);print $1"="ws"/"libName"/"$1}'
+ awk -F= '{if (NF==3) {if($2!="File Alias"){print $2}}}' PN02-NCM/.designtimelibs
+ echo stax2-api-3.1.4.jar=/var/lib/jenkins/workspace/PN02-NCM-continuous-BB/Jars/stax2-api-3.1.4.jar
+ echo scanner-resource.jar=/var/lib/jenkins/workspace/PN02-NCM-continuous-BB/lib/scanner-resource.jar
+ echo scanner-resourceLatest.jar=/var/lib/jenkins/workspace/PN02-NCM-continuous-BB/lib/scanner-resourceLatest.jar
+ echo ncm-resource.jar=/var/lib/jenkins/workspace/PN02-NCM-continuous-BB/lib/ncm-resource.jar
+ echo restfulresource-0.7.jar=/var/lib/jenkins/workspace/PN02-NCM-continuous-BB/restfulresource/restfulresource-0.7.jar
+ echo java-json.jar=/var/lib/jenkins/workspace/PN02-NCM-continuous-BB/lib/java-json.jar
+ buildear -x -v -a /var/lib/jenkins/workspace/PN02-NCM-continuous-BB/build/projlibs.properties -o /var/lib/jenkins/workspace/PN02-NCM-continuous-BB/build/PN02-NCM-3.169.ear -p /var/lib/jenkins/workspace/PN02-NCM-continuous-BB/PN02-NCM -ear /Deployment/PN02-NCM.archive
/tmp/jenkins3238031037421588481.sh: line 25: buildear: command not found
Build step 'Execute shell' marked build as failure

**Comment by ukuppa-tibco** [comment]
This is a BW5 related issue. Please open a support ticket.
