### ISSUE TITLE
Error installing in BW 6.3.5

### ISSUE THREAD

**Issue by Strickmabil** [TIBCOSoftware/bw6-plugin-maven#74]
Maven Plugin version: 1.2.1

Maven version: 3.2.3

Product : TIBCO ActiveMatrix Businessworks 6

Product version: 6.3.5

Component: Maven Eclipse Plugin 

**Steps to reproduce the issue:**
1. run install.bat

**Additional environment details if any:**
Windows 8

**Describe the results you received:**

[eclipse_err.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/881629/eclipse_err.zip)

Error installing the plugin. 
"The installable unit org.eclipse.equinox.p2.discovery.feature.feature.group has not been found.Installation failed."
(attached eclipse log files).

**Comment by britoruben** [comment]
Same error. Tibco BW 6.3.5
"org.eclipse.equinox.p2.discovery.feature.feature.group has not been found"
Any Suggestion?

**Comment by SujataDarekar** [comment]
@Strickmabil ,
  I am able to install maven plugin 1.2.1 on BW 6.3.5. Issue is not reproducible at our end. I think this is an intermittent issue hence marking the issue as fix.
