### ISSUE TITLE
Missing artifact com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100

### ISSUE THREAD

**Issue by bankarswapnil** [TIBCOSoftware/bw6-plugin-maven#76]
Maven Plugin version: **1.2.1**

Maven version:

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition
**BW635**
Product version:
**BW635**
Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1.BW635+TEA22(HF09)+EMS830
2.Extract BW6MavenPlugin121 & run install.bat
3.Provide %BW_HOME%
4.Restart BStudio
5.Open Sample Rest project in Studio &
6.Click on Generate POM file, eventually
7.Below exception appears in Problems tab,
_Description	Resource	Path	Location	Type
Missing artifact com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100	pom.xml	/tibco.bw.sample.binding.rest.Basic	line 14	Maven Dependency Problem
Project build error: Unknown packaging: bwear	pom.xml	/tibco.bw.sample.binding.rest.Basic.application	line 12	Maven pom Loading Problem
Project build error: Unknown packaging: bwmodule	pom.xml	/tibco.bw.sample.binding.rest.Basic	line 12	Maven pom Loading Problem
Project build error: Unresolveable build extension: Plugin com.tibco.plugins:bw6-maven-plugin:1.2.1 or one of its dependencies could not be resolved: Could not find artifact com.tibco.plugins:bw6-maven-plugin:jar:1.2.1 in central (https://repo.maven.apache.org/maven2)	pom.xml	/tibco.bw.sample.binding.rest.Basic	line 1	Maven pom Loading Problem
Project build error: Unresolveable build extension: Plugin com.tibco.plugins:bw6-maven-plugin:1.2.1 or one of its dependencies could not be resolved: Could not find artifact com.tibco.plugins:bw6-maven-plugin:jar:1.2.1 in central (https://repo.maven.apache.org/maven2)	pom.xml	/tibco.bw.sample.binding.rest.Basic.application	line 1	Maven pom Loading Problem_

**Additional environment details if any:**

**Describe the results you received:**
C:\Development\AMXBW635\studio\4.0\eclipse\configuration\1491920597332.log has following
!SESSION 2017-04-11 19:53:17.100 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_IN
Framework arguments:  -application org.eclipse.equinox.p2.director -uninstallIU bw6.studio.maven.feature.feature.group
Command-line arguments:  -application org.eclipse.equinox.p2.director -uninstallIU bw6.studio.maven.feature.feature.group

!ENTRY com.tibco.bw.sharedresource.jdbc.driver.template 4 0 2017-04-11 19:53:22.861
!MESSAGE [SCR] Component definition XMLs not found in bundle com.tibco.bw.sharedresource.jdbc.driver.template. The component header value is OSGI-INF/*.xml

!ENTRY com.tibco.bw.sharedresource.jdbc.driver.template 4 0 2017-04-11 19:53:22.966
!MESSAGE [SCR] Component definition XMLs not found in bundle com.tibco.bw.sharedresource.jdbc.driver.template. The component header value is OSGI-INF/*.xml

!ENTRY org.eclipse.equinox.p2.director.app 4 0 2017-04-11 19:53:24.667
!MESSAGE The installable unit bw6.studio.maven.feature.feature.group has not been found.
**Describe the results you expected:**
Clean POM file generation

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by dtredinnick13** [comment]
I just ran into this same issue. I am using BWCE 2.3, and already had some plug-ins installed.  There seems to be an issue with the installer where it does not properly place the maven plug-in in the directory structure.  

In my case, the plug-in was placed in a subdirectory or bwce named 2.3;palette.  I created a new subdirectory in bwce\2.3 named palette, and then moved the maven directory into this new subdirectory.  Now it appears that everything is working properly.  I did have to delete the .parent folder and the pom files from my project and regenerate the pom files to make the error go away.

I am running on Windows Server 2016.  I am not sure if that played a role as well.

**Comment by SujataDarekar** [comment]
Missing artifact issue is observed when we provide incorrect BW tibco home path. So please make sure that you are providing the correct BW home path while installing the BW6 maven plugin.

**Comment by SujataDarekar** [comment]
@bankarswapnil closing the issue. Please reopen in case you face the issue.

**Comment by dtredinnick13** [comment]
I am having this issue with BWCE 2.4 and Maven Plugin 2.0.0.  BWCE is installed in /opt/tibco/bwce/bwce/2.4.
When I installed the plugin I specified /opt/tibco/bwce as the tibco home.  This resulted with the plugin being installed at /opt/tibco/bwce/bwce/2.4 as shown:

  dtredinnick@ubuntu:/opt/tibco/bwce/bwce/2.4$ ls
      bin  config  doc  docker  ext  maven  p2repos  samples  scripts  system
When I generate the POM, I get the following error:
   Description	Resource	Path	Location	Type
Missing artifact com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100	pom.xml	/GDay.module	line 14	Maven Dependency Problem

If I look in the GDay.module/pom.xml file, I see the following:
 <dependencies>
    <dependency>
      <groupId>com.tibco.plugins</groupId>
      <artifactId>com.tibco.bw.palette.shared</artifactId>
      <version>6.1.100</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>

**Comment by PavanKuchulakanti** [comment]
We have recently upgraded TIBCO BW 6.3.4 to BW 6.4.2. We have implemented CI/CD using maven 3.3.9 and BW maven plugin 1.1.0.

After upgrading BW maven plugin to 1.3.1 to correct home directory we noticed few errors in the project. we tried deleting the POM files and regenerating the POM files but did not help. Tried deleting the .parent directory and regenerated the POM files but we still have one error complaining about Missing artifact com.tibco.plugins:com.bw.palette.shared:jar6:.1.100.

We have looked at the jar file in bw6 maven plugin directory and also under user plugin directory which exists.

Any suggestions would help.

Thank you

**Comment by HiteshNembhwani** [comment]
![maven1](https://user-images.githubusercontent.com/17696107/48327994-b8350c80-e5f6-11e8-81be-8334e3847def.jpg)
attaching snapshot from @PavanKuchulakanti

**Comment by SujataDarekar** [comment]
@PavanKuchulakanti  Could you please check the com.bw.palette.shared.jar name whether it is updated with .lastUpdated extension ?

**Comment by HiteshNembhwani** [comment]
@SujataDarekar where exactly does this need to be checked? under the bw_home/system/shared or a different location? thanks!

**Comment by SujataDarekar** [comment]
@HiteshNembhwani 
Please check under the folder bw_home \maven\plugins\bw6-maven-plugin

**Comment by HiteshNembhwani** [comment]
thanks @SujataDarekar.. @PavanKuchulakanti - please check under the mentioned location and confirm, thanks.

**Comment by PavanKuchulakanti** [comment]
We have recently upgraded TIBCO BW 6.3.4 to BW 6.4.2. We have implemented CI/CD using maven 3.3.9 and BW maven plugin 1.1.0.

After upgrading BW maven plugin to 1.3.1 to correct home directory we noticed few errors in the project. we tried deleting the POM files and regenerating the POM files but did not help. Tried deleting the .parent directory and regenerated the POM files but we still have one error complaining about Missing artifact com.tibco.plugins:com.bw.palette.shared:jar6:.1.100.

We have looked at the jar file in bw6 maven plugin directory and also under user plugin directory which exists.

Any suggestions would help.

Thank you


> 
> 
> thanks @SujataDarekar.. @PavanKuchulakanti - please check under the mentioned location and confirm, thanks.

@SujataDarekar @HiteshNembhwani - When we received the error first thing we checked was the jar file and we do have the com.tibco.bw.palette.shared_6.1.100.003 jar file. under bw_home\maven\plugins\bw6-maven-plugin. Thank you.

**Comment by PavanKuchulakanti** [comment]
@SujataDarekar @HiteshNembhwani - When we received the error first thing we checked was the jar file and we do have the com.tibco.bw.palette.shared_6.1.100.003 jar file. under bw_home\maven\plugins\bw6-maven-plugin. Is there any additional step of specifying the jar file location? Thank you!

**Comment by HiteshNembhwani** [comment]
@SujataDarekar any further updates on this one? thanks!

**Comment by rubirada** [comment]
I tried installing bw-maven-plugin 1.3.1 and 2.0.2 with BWCE 2.3.4. I did not find any issue while generating POM file for the imported REST sample.

**Comment by rubirada** [comment]
[Uploading zoom_Recording.zip…]
Uploaded the zoom recording for the same.  @PavanKuchulakanti Will, you try with the fresh environment and let me know?

**Comment by SujataDarekar** [comment]
@mshahat 
With Plugin 2.1.0 the first two points get fixed. So now 2.1.0 is available on the central repository and POM generated with the proper version 2.1.0. For the third point, we have an issue https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/228. So closing this issue

**Comment by SudhenduP** [comment]
I had the same issue. What worked for me was starting Business Studio as an admin.

**Comment by MitenCNL** [comment]
Please check if Maven itself is installed/configured in Linux/Windows environment.
For Linux, can use sudo yum install maven.
For Windows:- follow procedure at https://www.mkyong.com/maven/how-to-install-maven-in-windows/

Once done, install maven plugin for BW again and verify.

Above solution worked for me.

**Comment by shaji-bct** [comment]
> @PavanKuchulakanti Could you please check the com.bw.palette.shared.jar name whether it is updated with .lastUpdated extension ?

Hi @SujataDarekar I've the same issue in my local and as well on Azure DevOps agent, I'm currently using maven plugin 2.6.0 & BWCE 2.5.1 

What is the resolution for this?

**Comment by SujataDarekar** [comment]
@shaji-bct remove the .lastUpdated and then try.

**Comment by shaji-bct** [comment]
I tried the method but still it didn't worked, got invalid zip archive error in Studio. We had to remove the dependency from pom.xml to make it work.
