### ISSUE TITLE
 TIBCO-BW-ADMIN-500226: The registration of BW Agent to the domain [EntDomain] failed. 

### ISSUE THREAD

**Issue by bankarswapnil** [TIBCOSoftware/bw6-plugin-maven#77]
Maven Plugin version:
1.2.0

Maven version:
3.3.9

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition
**BW634**
Product version:
**BW634**
Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1. I have one blocking issue opened on BW6.3.5 +TEA2.2_HF09+EMS8.3.0 +BW6Maven 1.2.1,
2. So did a fresh setup using BW6.3.4+1.2.0,
3. Runtime objects (Domain/AppSpace/AppNode) are not created in TEA with intention,
4. After running a Jenkins job getting below esception,
_[ERROR] 
com.tibco.bw.maven.plugin.admin.client.ClientException: TIBCO-BW-ADMIN-500226: The registration of BW Agent to the domain [EntDomain] failed. Cannot create AppNodes in the AppSpace [EntAppSpace] on the remote BW Agent [null] (500)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.createAppNode(RemoteDeployer.java:307)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.getOrCreateAppNode(RemoteDeployer.java:214)
	at com.tibco.bw.maven.plugin.application.BWEARInstallerMojo.execute(BWEARInstallerMojo.java:163)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.tibco.bw.maven.plugin.admin.client.ClientException: TIBCO-BW-ADMIN-500226: The registration of BW Agent to the domain [EntDomain] failed. Cannot create AppNodes in the AppSpace [EntAppSpace] on the remote BW Agent [null] (400)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.processErrorResponse(RemoteDeployer.java:519)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.createAppNode(RemoteDeployer.java:301)
	... 24 more_

**Additional environment details if any:**

**Describe the results you received:**
_**Jenkins console log,**
Console Output

Started by an SCM change
Building in workspace C:\Users\sbankar\.jenkins\workspace\BW6_Demo1
 > D:\Development\CICD\Git_2.11.0.3\bin\git.exe rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > D:\Development\CICD\Git_2.11.0.3\bin\git.exe config remote.origin.url http://localhost:3000/sbankar/Demo1.git # timeout=10
Fetching upstream changes from http://localhost:3000/sbankar/Demo1.git
 > D:\Development\CICD\Git_2.11.0.3\bin\git.exe --version # timeout=10
using GIT_ASKPASS to set credentials 
 > D:\Development\CICD\Git_2.11.0.3\bin\git.exe fetch --tags --progress http://localhost:3000/sbankar/Demo1.git +refs/heads/*:refs/remotes/origin/*
 > D:\Development\CICD\Git_2.11.0.3\bin\git.exe rev-parse "refs/remotes/origin/master^{commit}" # timeout=10
 > D:\Development\CICD\Git_2.11.0.3\bin\git.exe rev-parse "refs/remotes/origin/origin/master^{commit}" # timeout=10
Checking out Revision 6c18a59afc63698339c8458227c17d7f521bfcee (refs/remotes/origin/master)
 > D:\Development\CICD\Git_2.11.0.3\bin\git.exe config core.sparsecheckout # timeout=10
 > D:\Development\CICD\Git_2.11.0.3\bin\git.exe checkout -f 6c18a59afc63698339c8458227c17d7f521bfcee
First time build. Skipping changelog.
Empty changeset (manual trigger?), running build.
[BW6_Demo1] $ cmd.exe /C "D:\Development\CICD\ApacheMaven_3.3.9\bin\mvn.cmd -f D:\Temp\CICD\MyProject_31Mar\tibco.bw.sample.binding.rest.Basic.application.parent\pom.xml -s D:\Development\CICD\ApacheMaven_3.3.9\conf\settings.xml clean package && exit %%ERRORLEVEL%%"

[INFO] Scanning for projects...

[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] tibco.bw.sample.binding.rest.Basic.application.parent
[INFO] tibco.bw.sample.binding.rest.Basic
[INFO] tibco.bw.sample.binding.rest.Basic.application
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic.application.parent 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ tibco.bw.sample.binding.rest.Basic.application.parent ---
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------

[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ tibco.bw.sample.binding.rest.Basic ---

[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\Temp\CICD\MyProject_31Mar\tibco.bw.sample.binding.rest.Basic\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ tibco.bw.sample.binding.rest.Basic ---

[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ tibco.bw.sample.binding.rest.Basic ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\Temp\CICD\MyProject_31Mar\tibco.bw.sample.binding.rest.Basic\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ tibco.bw.sample.binding.rest.Basic ---

[INFO] No tests to run.
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.0:bwmodule (default-bwmodule) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] Module Packager Mojo started for Module tibco.bw.sample.binding.rest.Basic ...
[INFO] Updated the Manifest version 
[INFO] Removing the externals entries if any. 
[INFO] Created Plugin JAR with name D:\Temp\CICD\MyProject_31Mar\tibco.bw.sample.binding.rest.Basic\target\tibco.bw.sample.binding.rest.Basic_1.0.0.201704121540.jar
[INFO] Adding Maven Dependencies to the Plugin JAR file
[INFO] Creating the Plugin JAR file
[INFO] Building jar: D:\Temp\CICD\MyProject_31Mar\tibco.bw.sample.binding.rest.Basic\target\tibco.bw.sample.binding.rest.Basic_1.0.0.201704121540.jar
[INFO] BW Module Packager Mojo finished execution.
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic.application 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ tibco.bw.sample.binding.rest.Basic.application ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\Temp\CICD\MyProject_31Mar\tibco.bw.sample.binding.rest.Basic.application\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ tibco.bw.sample.binding.rest.Basic.application ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\Temp\CICD\MyProject_31Mar\tibco.bw.sample.binding.rest.Basic.application\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] No tests to run.
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.0:bwear (default-bwear) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] BWEARPackager Mojo started ...
[INFO] Adding Modules to the EAR file

[INFO] Adding EAR Information to the EAR File

[INFO] Building jar: D:\Temp\CICD\MyProject_31Mar\tibco.bw.sample.binding.rest.Basic.application\target\tibco.bw.sample.binding.rest.Basic.application_1.0.0.ear
[INFO] BWEARPackager Mojo finished execution
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] tibco.bw.sample.binding.rest.Basic.application.parent SUCCESS [  0.199 s]
[INFO] tibco.bw.sample.binding.rest.Basic ................. SUCCESS [  5.550 s]
[INFO] tibco.bw.sample.binding.rest.Basic.application ..... SUCCESS [  2.657 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23.019 s
[INFO] Finished at: 2017-04-12T15:40:53+05:30
[INFO] Final Memory: 13M/87M
[INFO] ------------------------------------------------------------------------
[BW6_Demo1] $ cmd.exe /C "D:\Development\CICD\ApacheMaven_3.3.9\bin\mvn.cmd -f D:\Temp\CICD\MyProject_31Mar\tibco.bw.sample.binding.rest.Basic.application.parent\pom.xml -s D:\Development\CICD\ApacheMaven_3.3.9\conf\settings.xml install && exit %%ERRORLEVEL%%"

[INFO] Scanning for projects...

[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] tibco.bw.sample.binding.rest.Basic.application.parent
[INFO] tibco.bw.sample.binding.rest.Basic
[INFO] tibco.bw.sample.binding.rest.Basic.application
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic.application.parent 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ tibco.bw.sample.binding.rest.Basic.application.parent ---

[INFO] Installing D:\Temp\CICD\MyProject_31Mar\tibco.bw.sample.binding.rest.Basic.application.parent\pom.xml to C:\Users\sbankar\.m2\repository\com\tibco\bw\tibco.bw.sample.binding.rest.Basic.application.parent\1.0.0-SNAPSHOT\tibco.bw.sample.binding.rest.Basic.application.parent-1.0.0-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ tibco.bw.sample.binding.rest.Basic ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\Temp\CICD\MyProject_31Mar\tibco.bw.sample.binding.rest.Basic\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ tibco.bw.sample.binding.rest.Basic ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\Temp\CICD\MyProject_31Mar\tibco.bw.sample.binding.rest.Basic\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ tibco.bw.sample.binding.rest.Basic ---

[INFO] No tests to run.
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.0:bwmodule (default-bwmodule) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] Module Packager Mojo started for Module tibco.bw.sample.binding.rest.Basic ...
[INFO] Updated the Manifest version 
[INFO] Removing the externals entries if any. 
[INFO] Created Plugin JAR with name D:\Temp\CICD\MyProject_31Mar\tibco.bw.sample.binding.rest.Basic\target\tibco.bw.sample.binding.rest.Basic_1.0.0.201704121540.jar
[INFO] Adding Maven Dependencies to the Plugin JAR file
[INFO] Creating the Plugin JAR file
[INFO] Building jar: D:\Temp\CICD\MyProject_31Mar\tibco.bw.sample.binding.rest.Basic\target\tibco.bw.sample.binding.rest.Basic_1.0.0.201704121540.jar
[INFO] BW Module Packager Mojo finished execution.
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] Installing D:\Temp\CICD\MyProject_31Mar\tibco.bw.sample.binding.rest.Basic\target\tibco.bw.sample.binding.rest.Basic_1.0.0.201704121540.jar to C:\Users\sbankar\.m2\repository\com\tibco\bw\tibco.bw.sample.binding.rest.Basic\1.0.0-SNAPSHOT\tibco.bw.sample.binding.rest.Basic-1.0.0-SNAPSHOT.jar
[INFO] Installing D:\Temp\CICD\MyProject_31Mar\tibco.bw.sample.binding.rest.Basic\pom.xml to C:\Users\sbankar\.m2\repository\com\tibco\bw\tibco.bw.sample.binding.rest.Basic\1.0.0-SNAPSHOT\tibco.bw.sample.binding.rest.Basic-1.0.0-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic.application 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ tibco.bw.sample.binding.rest.Basic.application ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\Temp\CICD\MyProject_31Mar\tibco.bw.sample.binding.rest.Basic.application\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ tibco.bw.sample.binding.rest.Basic.application ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\Temp\CICD\MyProject_31Mar\tibco.bw.sample.binding.rest.Basic.application\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] No tests to run.
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.0:bwear (default-bwear) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] BWEARPackager Mojo started ...
[INFO] Adding Modules to the EAR file
[INFO] Adding EAR Information to the EAR File

[INFO] Building jar: D:\Temp\CICD\MyProject_31Mar\tibco.bw.sample.binding.rest.Basic.application\target\tibco.bw.sample.binding.rest.Basic.application_1.0.0.ear
[INFO] BWEARPackager Mojo finished execution
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] Installing D:\Temp\CICD\MyProject_31Mar\tibco.bw.sample.binding.rest.Basic.application\target\tibco.bw.sample.binding.rest.Basic.application_1.0.0.ear to C:\Users\sbankar\.m2\repository\com\tibco\bw\tibco.bw.sample.binding.rest.Basic.application\1.0.0-SNAPSHOT\tibco.bw.sample.binding.rest.Basic.application-1.0.0-SNAPSHOT.ear
[INFO] Installing D:\Temp\CICD\MyProject_31Mar\tibco.bw.sample.binding.rest.Basic.application\pom.xml to C:\Users\sbankar\.m2\repository\com\tibco\bw\tibco.bw.sample.binding.rest.Basic.application\1.0.0-SNAPSHOT\tibco.bw.sample.binding.rest.Basic.application-1.0.0-SNAPSHOT.pom
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.0:bwinstall (default-bwinstall) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] BWEAR Installer Mojo started ...
[INFO] No Deployment Config File set. Reading the deployment Properties from POM File.

[INFO] Connected to BWAgent. Agents found.
[INFO] Agent Name -> sbankar-t420
[INFO] Creating Domain with name -> EntDomain
[INFO] Creating AppSpace with Name -> EntAppSpace in Domain -> EntDomain

[INFO] Creating AppNode with Name -> EntAppNode_8064 in Domain -> EntDomain and in AppSpace -> EntAppSpace
[ERROR] 
com.tibco.bw.maven.plugin.admin.client.ClientException: TIBCO-BW-ADMIN-500226: The registration of BW Agent to the domain [EntDomain] failed. Cannot create AppNodes in the AppSpace [EntAppSpace] on the remote BW Agent [null] (500)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.createAppNode(RemoteDeployer.java:307)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.getOrCreateAppNode(RemoteDeployer.java:214)
	at com.tibco.bw.maven.plugin.application.BWEARInstallerMojo.execute(BWEARInstallerMojo.java:163)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.tibco.bw.maven.plugin.admin.client.ClientException: TIBCO-BW-ADMIN-500226: The registration of BW Agent to the domain [EntDomain] failed. Cannot create AppNodes in the AppSpace [EntAppSpace] on the remote BW Agent [null] (400)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.processErrorResponse(RemoteDeployer.java:519)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.createAppNode(RemoteDeployer.java:301)
	... 24 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] tibco.bw.sample.binding.rest.Basic.application.parent SUCCESS [  0.747 s]
[INFO] tibco.bw.sample.binding.rest.Basic ................. SUCCESS [  1.645 s]
[INFO] tibco.bw.sample.binding.rest.Basic.application ..... SUCCESS [  4.201 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.950 s
[INFO] Finished at: 2017-04-12T15:41:04+05:30
[INFO] Final Memory: 22M/169M
[INFO] ------------------------------------------------------------------------
[BW6_Demo1] $ cmd /c call D:\Development\CICD\ApacheTomcat_9.0\temp\hudson6391108159189091832.bat

CLINK C:\Users\sbankar\.jenkins\workspace\BW6_Demo1>D:\Development\CICD\ApacheJmeter_3.1\bin\jmeter.bat -Jjmeter.save.saveservice.ouput_format=xml -n -t "D:\Temp\CICD\REST_Test Plan_31March.jmx" -l "D:\Temp\CICD\REST_Test Plan_31March.jtl" 
Writing log file to: C:\Users\sbankar\.jenkins\workspace\BW6_Demo1\jmeter.log

Could not open D:\Temp\CICD\REST_Test Plan_31March.jmx
Uploading Maven asset with groupId: com.tibco.bw artifactId: tibco.bw.sample.binding.rest.Basic.application version: 1.0 To repository: MyFirstBW634

Successfully Uploaded Maven Assets

Performance: Recording JMeter reports 'D:\Temp\CICD\REST_Test Plan_31March.jtl'
Performance: no JMeter files matching 'D:\Temp\CICD\REST_Test Plan_31March.jtl' have been found. Has the report generated?. Setting Build to FAILURE
Build step 'Publish Performance test result report' changed build result to FAILURE
Finished: FAILURE_

**Describe the results you expected:**
_As mentioned in POM generation Wizard, if Runtime objects (Domain/AppSpace/AppNode) are already available in TEA, those will be created which is not happening._

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by RajibBiswasTibco** [comment]
Can you try with latest release V 1.2.2 ?

**Comment by SujataDarekar** [comment]
Hi @bankarswapnil,
       Try the build with latest version of Maven 1.3.0. Please let me know if you face the issue again.
