### ISSUE TITLE
Missing resources folder into Tibco BW6 EAR generated with Maven 

### ISSUE THREAD

**Issue by Joindra** [TIBCOSoftware/bw6-plugin-maven#78]
Maven version: apache-maven-3.3.9

Product : TIBCO ActiveMatrix Businessworks 6

Product version: 6.3.5 hotfix 1

Component: TIB_BW_Maven_Plugin_1.2.0

Hi, generating an BW6 EAR file from maven, we noticed that into EAR is absent the resources folder, see attached images.

Someone has already encountered in the same problem and knows how to solve?

![imageear](https://cloud.githubusercontent.com/assets/27487593/25040439/a75095f0-2109-11e7-9020-c8cd7cdba144.png)

Regards

**Comment by HiteshNembhwani** [comment]
@Joindra - yes, this is an enhancement, refer https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/25

**Comment by HiteshNembhwani** [comment]
Fixed with BW 6.4.2 / BWCE 2.3.2 and Maven 1.3.0 version.

**Comment by mcrodrig** [comment]
Just tested with BW 6.4.2 and Maven 1.3.0 version and still is not generated.

**Comment by HiteshNembhwani** [comment]
@mcrodrig could you list the steps you followed? The diagrams need to be generated separately from Studio before you build an archive via the new Maven version. Did you follow these steps?

**Comment by awagle** [comment]
To generate diagrams in BW 6.4.2 or BWCE 2.3.2 select the option in preferences and you will see an action item on the right click menu in Project Explorer to Generate Process Diagrams
<img width="737" alt="processdiagrams" src="https://user-images.githubusercontent.com/7453624/33196696-e6e7b6b4-d106-11e7-9f5d-f9ec219c53b0.png">

Please re-open if you still see the issue.

**Comment by tirukommi** [comment]
Hi team,
I have referred all the above posts, still, I am facing the Resource folder missing issue. Please help/suggest on this.
Versions are :- BW6.5, Maven 3.6.0 & bw6-plugin-maven-2.1.1

![image](https://user-images.githubusercontent.com/47517154/57120777-2df18800-6d91-11e9-9a37-259d5c0e6c76.png)

Thanks ahead
