### ISSUE TITLE
Install Maven plugin without Internet access

### ISSUE THREAD

**Issue by rajeshdevan** [TIBCOSoftware/bw6-plugin-maven#83]
Maven Plugin version: NA

Maven version: Apache Maven 3.5.0

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version:TIBCO ActiveMatrix BusinessWorks . Version: 6.3.4

Component: Either of Maven Eclipse Plugin or Maven build plugin

I need install Maven plugin in TIBCO BW 6.3.4 without internet access on the server. What are the packages that I need to have and the procedure to install the same. 

Thanks

**Comment by Tantino** [comment]
You need to do the next steps.

* LOCAL MACHINE
1. Download bw6-plugin-maven and unzip.
2. Go to Folder: `bw6-plugin-maven/Source/bw6-maven-plugin/`
3. Run the next command:
`mvn dependency:copy-dependencies -Dmdep.useRepositoryLayout=true`
4. Build ZIP File with content target(ZIP file dependecy).

* SERVER MACHINE
1. Upload bw6-plugin-maven and ZIP file dependecy.
2. unzip (ZIP file dependecy) inside local repository
3. unzip bw6-plugin-maven
4. Run this command `mvn install` in the folder "bw6-plugin-maven"

Good luck and enjoy.

**Comment by RajibBiswasTibco** [comment]
@rajeshdevan , is your questions answered? If so, can you please close this issue?

**Comment by RajibBiswasTibco** [comment]
I am closing this issue since there were no comments from @rajeshdevan .

**Comment by gagankinra** [comment]
@Tantino I was following the instructions you provided, however I got struck at "unzip (ZIP file dependecy) inside local repository" where is this folder? FYI I am using TIB_BW_Maven_Plugin_2.7.0 . TIBCO BW 6.5.0

**Comment by aldair5** [comment]
I also have this problem, I downloaded the dependencies and transferred the zip file to the server without internet access in the .m2 \ repository repository, when I run "mvn install" from the directory "bwce \ 2.6 \ maven \ plugins \ bw6-maven-plugin ", always try to download it from the maven site and not from the local repository
