### ISSUE TITLE
Exception propagation

### ISSUE THREAD

**Issue by phenelle** [TIBCOSoftware/bw6-plugin-maven#84]
Hi Guys,

We are using bw6 maven plugin and are having problem with the "deploy and start" step. 

If, for example, an app is deployed correctly but cannot start correctly, the module reports it, but the build process says "operation complete successfully"... (its not that successfull if the app did not start correctly, no?)

I suggest you propagate exception in BWEARInstallerMojo.java:174, on the "public void execute() throws MojoExecutionException"
with something like "throw new MojoExecutionException("Failed to deploy BW EAR application", e); 
instead of _try catch it_ locally

Another alternative could be to create 2 goal:
 - one for deploy
 - one for start / restart

Thanks for you work, bw6-plugin-maven is still an awesome pluging +1:

**Comment by rahulkamdar** [comment]
Thanks @phenelle. Would you be interested in submitting a PR for your suggestion?

**Comment by RajibBiswasTibco** [comment]
Fixed in Release Version 1.2.2
