### ISSUE TITLE
BW6 -MAVEN-An API incompatibility error when trying to excecute build for tibco project with generated pom.xml

### ISSUE THREAD

**Issue by vinisha91** [TIBCOSoftware/bw6-plugin-maven#87]
installation details : Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-2.b11.el7_3.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-514.16.1.el7.x86_64", arch: "amd64", family: "unix"

ERROr log when trying to build ear from the pom.xml generated from tibco application - mvn clean package : 

[vagrant@tibco helloWorld]$ mvn package
[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building helloWorld 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ helloWorld ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/vagrant/Desktop/helloWorld/helloWorld/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ helloWorld ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ helloWorld ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/vagrant/Desktop/helloWorld/helloWorld/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ helloWorld ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ helloWorld ---
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.0:bwmodule (default-bwmodule) @ helloWorld ---
[INFO] Module Packager Mojo started for Module helloWorld ...
[INFO] Updated the Manifest version 
[INFO] Removing the externals entries if any. 
[INFO] Created Plugin JAR with name /home/vagrant/Desktop/helloWorld/helloWorld/target/helloWorld_1.0.0.201706021654.jar
[INFO] Adding Maven Dependencies to the Plugin JAR file
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.549s
[INFO] Finished at: Fri Jun 02 16:54:49 IST 2017
[INFO] Final Memory: 13M/58M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:1.2.0:bwmodule (default-bwmodule) on project helloWorld: Execution default-bwmodule of goal com.tibco.plugins:bw6-maven-plugin:1.2.0:bwmodule failed: An API incompatibility was encountered while executing com.tibco.plugins:bw6-maven-plugin:1.2.0:bwmodule: java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/eclipse/aether/RepositorySystemSession;
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.tibco.plugins:bw6-maven-plugin:1.2.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/vagrant/.m2/repository/com/tibco/plugins/bw6-maven-plugin/1.2.0/bw6-maven-plugin-1.2.0.jar
[ERROR] urls[1] = file:/home/vagrant/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.plexus/0.3.0/org.eclipse.sisu.plexus-0.3.0.jar
[ERROR] urls[2] = file:/home/vagrant/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[3] = file:/home/vagrant/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[4] = file:/home/vagrant/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.0/org.eclipse.sisu.inject-0.3.0.jar
[ERROR] urls[5] = file:/home/vagrant/.m2/repository/org/apache/maven/maven-builder-support/3.3.3/maven-builder-support-3.3.3.jar
[ERROR] urls[6] = file:/home/vagrant/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar
[ERROR] urls[7] = file:/home/vagrant/.m2/repository/org/eclipse/aether/aether-spi/1.0.2.v20150114/aether-spi-1.0.2.v20150114.jar
[ERROR] urls[8] = file:/home/vagrant/.m2/repository/org/eclipse/aether/aether-impl/1.0.2.v20150114/aether-impl-1.0.2.v20150114.jar
[ERROR] urls[9] = file:/home/vagrant/.m2/repository/org/eclipse/aether/aether-api/1.0.2.v20150114/aether-api-1.0.2.v20150114.jar
[ERROR] urls[10] = file:/home/vagrant/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.jar
[ERROR] urls[11] = file:/home/vagrant/.m2/repository/org/sonatype/sisu/sisu-guice/3.2.5/sisu-guice-3.2.5-no_aop.jar
[ERROR] urls[12] = file:/home/vagrant/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar
[ERROR] urls[13] = file:/home/vagrant/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[14] = file:/home/vagrant/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar
[ERROR] urls[15] = file:/home/vagrant/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
[ERROR] urls[16] = file:/home/vagrant/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[17] = file:/home/vagrant/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[18] = file:/home/vagrant/.m2/repository/org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.jar
[ERROR] urls[19] = file:/home/vagrant/.m2/repository/org/codehaus/plexus/plexus-archiver/2.1/plexus-archiver-2.1.jar
[ERROR] urls[20] = file:/home/vagrant/.m2/repository/org/codehaus/plexus/plexus-io/2.0.2/plexus-io-2.0.2.jar
[ERROR] urls[21] = file:/home/vagrant/.m2/repository/org/apache/maven/maven-embedder/3.1.0/maven-embedder-3.1.0.jar
[ERROR] urls[22] = file:/home/vagrant/.m2/repository/org/sonatype/plexus/plexus-cipher/1.7/plexus-cipher-1.7.jar
[ERROR] urls[23] = file:/home/vagrant/.m2/repository/org/slf4j/slf4j-api/1.7.4/slf4j-api-1.7.4.jar
[ERROR] urls[24] = file:/home/vagrant/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar
[ERROR] urls[25] = file:/home/vagrant/.m2/repository/commons-io/commons-io/1.3.2/commons-io-1.3.2.jar
[ERROR] urls[26] = file:/home/vagrant/.m2/repository/org/apache/maven/plugins/maven-compiler-plugin/3.3/maven-compiler-plugin-3.3.jar
[ERROR] urls[27] = file:/home/vagrant/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.7/maven-shared-utils-0.7.jar
[ERROR] urls[28] = file:/home/vagrant/.m2/repository/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar
[ERROR] urls[29] = file:/home/vagrant/.m2/repository/org/apache/maven/shared/maven-shared-incremental/1.1/maven-shared-incremental-1.1.jar
[ERROR] urls[30] = file:/home/vagrant/.m2/repository/org/codehaus/plexus/plexus-compiler-api/2.5/plexus-compiler-api-2.5.jar
[ERROR] urls[31] = file:/home/vagrant/.m2/repository/org/codehaus/plexus/plexus-compiler-manager/2.5/plexus-compiler-manager-2.5.jar
[ERROR] urls[32] = file:/home/vagrant/.m2/repository/org/codehaus/plexus/plexus-compiler-javac/2.5/plexus-compiler-javac-2.5.jar
[ERROR] urls[33] = file:/home/vagrant/.m2/repository/org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.jar
[ERROR] urls[34] = file:/home/vagrant/.m2/repository/log4j/log4j/1.2.12/log4j-1.2.12.jar
[ERROR] urls[35] = file:/home/vagrant/.m2/repository/commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar
[ERROR] urls[36] = file:/home/vagrant/.m2/repository/com/google/collections/google-collections/1.0/google-collections-1.0.jar
[ERROR] urls[37] = file:/home/vagrant/.m2/repository/junit/junit/3.8.2/junit-3.8.2.jar
[ERROR] urls[38] = file:/home/vagrant/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.1/maven-dependency-tree-2.1.jar
[ERROR] urls[39] = file:/home/vagrant/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
[ERROR] urls[40] = file:/home/vagrant/.m2/repository/javax/xml/bind/jaxb-api/2.2.7/jaxb-api-2.2.7.jar
[ERROR] urls[41] = file:/home/vagrant/.m2/repository/org/glassfish/jersey/core/jersey-client/2.21.1/jersey-client-2.21.1.jar
[ERROR] urls[42] = file:/home/vagrant/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.0.1/javax.ws.rs-api-2.0.1.jar
[ERROR] urls[43] = file:/home/vagrant/.m2/repository/org/glassfish/jersey/core/jersey-common/2.21.1/jersey-common-2.21.1.jar
[ERROR] urls[44] = file:/home/vagrant/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar
[ERROR] urls[45] = file:/home/vagrant/.m2/repository/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.21.1/jersey-guava-2.21.1.jar
[ERROR] urls[46] = file:/home/vagrant/.m2/repository/org/glassfish/hk2/osgi-resource-locator/1.0.1/osgi-resource-locator-1.0.1.jar
[ERROR] urls[47] = file:/home/vagrant/.m2/repository/org/glassfish/hk2/hk2-api/2.4.0-b31/hk2-api-2.4.0-b31.jar
[ERROR] urls[48] = file:/home/vagrant/.m2/repository/org/glassfish/hk2/hk2-utils/2.4.0-b31/hk2-utils-2.4.0-b31.jar
[ERROR] urls[49] = file:/home/vagrant/.m2/repository/org/glassfish/hk2/external/aopalliance-repackaged/2.4.0-b31/aopalliance-repackaged-2.4.0-b31.jar
[ERROR] urls[50] = file:/home/vagrant/.m2/repository/org/glassfish/hk2/external/javax.inject/2.4.0-b31/javax.inject-2.4.0-b31.jar
[ERROR] urls[51] = file:/home/vagrant/.m2/repository/org/glassfish/hk2/hk2-locator/2.4.0-b31/hk2-locator-2.4.0-b31.jar
[ERROR] urls[52] = file:/home/vagrant/.m2/repository/org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA.jar
[ERROR] urls[53] = file:/home/vagrant/.m2/repository/org/glassfish/jersey/media/jersey-media-multipart/2.21.1/jersey-media-multipart-2.21.1.jar
[ERROR] urls[54] = file:/home/vagrant/.m2/repository/org/jvnet/mimepull/mimepull/1.9.6/mimepull-1.9.6.jar
[ERROR] urls[55] = file:/home/vagrant/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.6.1/jackson-core-2.6.1.jar
[ERROR] urls[56] = file:/home/vagrant/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.6.1/jackson-jaxrs-base-2.6.1.jar
[ERROR] urls[57] = file:/home/vagrant/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.6.1/jackson-databind-2.6.1.jar
[ERROR] urls[58] = file:/home/vagrant/.m2/repository/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.6.1/jackson-module-jaxb-annotations-2.6.1.jar
[ERROR] urls[59] = file:/home/vagrant/.m2/repository/org/glassfish/jersey/media/jersey-media-json-jackson/2.21.1/jersey-media-json-jackson-2.21.1.jar
[ERROR] urls[60] = file:/home/vagrant/.m2/repository/org/glassfish/jersey/ext/jersey-entity-filtering/2.21.1/jersey-entity-filtering-2.21.1.jar
[ERROR] urls[61] = file:/home/vagrant/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.6.1/jackson-jaxrs-json-provider-2.6.1.jar
[ERROR] urls[62] = file:/home/vagrant/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.6.1/jackson-annotations-2.6.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>com.tibco.bw:helloWorld:1.0.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

pls help!

attaching 2 pom.xml files 1.generated in the project code base folder(helloWorld) 2.generated in the helloWorld.application folder for reference .
pls help.
very new to maven!
TIA

[pomFiles.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/1047568/pomFiles.zip)

**Comment by RajibBiswasTibco** [comment]
Hi @vinisha91 , Can you try upgrading maven to 3.3 and try again?

**Comment by asatsi** [comment]
Had faced same issue with the pre-installed maven (Apache Maven 3.0.5) on CentOS 7. Confirming that this worked with latest version of maven(Apache Maven 3.5.2). Please note that the build is successful when triggered through studio. However fails when ran through command line using old version of mvn.

**Comment by amsingh21** [comment]
I am getting same error. 
I am trying to build image using Maven plugin on docker.
Below API is generating issue.

 <groupId>io.fabric8</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>0.26.0</version>
Here is complete error trace just to ensure we are talking about same issue.

[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.14.2:build (defa
ult-cli) on project EmployeeApplication.application: Execution default-cli of go
al io.fabric8:docker-maven-plugin:0.14.2:build failed: An API incompatibility wa
s encountered while executing io.fabric8:docker-maven-plugin:0.14.2:build: java.
lang.UnsatisfiedLinkError: unknown
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>io.fabric8:docker-maven-plugin:0.14.2--1106001851
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/amita/.m2/repository/io/fabric8/docker-maven-pl
ugin/0.14.2/docker-maven-plugin-0.14.2.jar
[ERROR] urls[1] = file:/C:/Users/amita/.m2/repository/org/apache/httpcomponents/
httpclient/4.3.6/httpclient-4.3.6.jar
[ERROR] urls[2] = file:/C:/Users/amita/.m2/repository/org/apache/httpcomponents/
httpcore/4.3.3/httpcore-4.3.3.jar
[ERROR] urls[3] = file:/C:/Users/amita/.m2/repository/commons-logging/commons-lo
gging/1.1.3/commons-logging-1.1.3.jar
[ERROR] urls[4] = file:/C:/Users/amita/.m2/repository/commons-codec/commons-code
c/1.6/commons-codec-1.6.jar
[ERROR] urls[5] = file:/C:/Users/amita/.m2/repository/com/github/jnr/jnr-unixsoc
ket/0.8/jnr-unixsocket-0.8.jar
[ERROR] urls[6] = file:/C:/Users/amita/.m2/repository/com/github/jnr/jnr-ffi/2.0
.3/jnr-ffi-2.0.3.jar
[ERROR] urls[7] = file:/C:/Users/amita/.m2/repository/com/github/jnr/jffi/1.2.9/
jffi-1.2.9.jar
[ERROR] urls[8] = file:/C:/Users/amita/.m2/repository/com/github/jnr/jffi/1.2.9/
jffi-1.2.9-native.jar
[ERROR] urls[9] = file:/C:/Users/amita/.m2/repository/org/ow2/asm/asm/5.0.3/asm-
5.0.3.jar
[ERROR] urls[10] = file:/C:/Users/amita/.m2/repository/org/ow2/asm/asm-commons/5
.0.3/asm-commons-5.0.3.jar
[ERROR] urls[11] = file:/C:/Users/amita/.m2/repository/org/ow2/asm/asm-analysis/
5.0.3/asm-analysis-5.0.3.jar
[ERROR] urls[12] = file:/C:/Users/amita/.m2/repository/org/ow2/asm/asm-tree/5.0.
3/asm-tree-5.0.3.jar
[ERROR] urls[13] = file:/C:/Users/amita/.m2/repository/org/ow2/asm/asm-util/5.0.
3/asm-util-5.0.3.jar
[ERROR] urls[14] = file:/C:/Users/amita/.m2/repository/com/github/jnr/jnr-x86asm
/1.0.2/jnr-x86asm-1.0.2.jar
[ERROR] urls[15] = file:/C:/Users/amita/.m2/repository/com/github/jnr/jnr-consta
nts/0.8.7/jnr-constants-0.8.7.jar
[ERROR] urls[16] = file:/C:/Users/amita/.m2/repository/com/github/jnr/jnr-enxio/
0.9/jnr-enxio-0.9.jar
[ERROR] urls[17] = file:/C:/Users/amita/.m2/repository/com/github/jnr/jnr-posix/
3.0.12/jnr-posix-3.0.12.jar
[ERROR] urls[18] = file:/C:/Users/amita/.m2/repository/org/apache/commons/common
s-lang3/3.3.2/commons-lang3-3.3.2.jar
[ERROR] urls[19] = file:/C:/Users/amita/.m2/repository/org/json/json/20140107/js
on-20140107.jar
[ERROR] urls[20] = file:/C:/Users/amita/.m2/repository/org/bouncycastle/bcpkix-j
dk15on/1.51/bcpkix-jdk15on-1.51.jar
[ERROR] urls[21] = file:/C:/Users/amita/.m2/repository/org/bouncycastle/bcprov-j
dk15on/1.51/bcprov-jdk15on-1.51.jar
[ERROR] urls[22] = file:/C:/Users/amita/.m2/repository/org/apache/maven/plugins/
maven-assembly-plugin/2.6/maven-assembly-plugin-2.6.jar
[ERROR] urls[23] = file:/C:/Users/amita/.m2/repository/org/slf4j/slf4j-jdk14/1.5
.6/slf4j-jdk14-1.5.6.jar
[ERROR] urls[24] = file:/C:/Users/amita/.m2/repository/org/slf4j/jcl-over-slf4j/
1.5.6/jcl-over-slf4j-1.5.6.jar
[ERROR] urls[25] = file:/C:/Users/amita/.m2/repository/org/apache/maven/reportin
g/maven-reporting-api/2.2.1/maven-reporting-api-2.2.1.jar
[ERROR] urls[26] = file:/C:/Users/amita/.m2/repository/org/apache/maven/doxia/do
xia-sink-api/1.1/doxia-sink-api-1.1.jar
[ERROR] urls[27] = file:/C:/Users/amita/.m2/repository/org/apache/maven/doxia/do
xia-logging-api/1.1/doxia-logging-api-1.1.jar
[ERROR] urls[28] = file:/C:/Users/amita/.m2/repository/junit/junit/3.8.1/junit-3
.8.1.jar
[ERROR] urls[29] = file:/C:/Users/amita/.m2/repository/commons-cli/commons-cli/1
.2/commons-cli-1.2.jar
[ERROR] urls[30] = file:/C:/Users/amita/.m2/repository/org/codehaus/plexus/plexu
s-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.jar
[ERROR] urls[31] = file:/C:/Users/amita/.m2/repository/backport-util-concurrent/
backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
[ERROR] urls[32] = file:/C:/Users/amita/.m2/repository/org/sonatype/plexus/plexu
s-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[33] = file:/C:/Users/amita/.m2/repository/org/sonatype/plexus/plexu
s-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[34] = file:/C:/Users/amita/.m2/repository/org/apache/maven/shared/m
aven-common-artifact-filters/1.4/maven-common-artifact-filters-1.4.jar
[ERROR] urls[35] = file:/C:/Users/amita/.m2/repository/org/codehaus/plexus/plexu
s-archiver/3.0.1/plexus-archiver-3.0.1.jar
[ERROR] urls[36] = file:/C:/Users/amita/.m2/repository/org/iq80/snappy/snappy/0.
3/snappy-0.3.jar
[ERROR] urls[37] = file:/C:/Users/amita/.m2/repository/org/apache/maven/shared/f
ile-management/1.1/file-management-1.1.jar
[ERROR] urls[38] = file:/C:/Users/amita/.m2/repository/org/apache/maven/shared/m
aven-shared-io/1.1/maven-shared-io-1.1.jar
[ERROR] urls[39] = file:/C:/Users/amita/.m2/repository/commons-io/commons-io/2.2
/commons-io-2.2.jar
[ERROR] urls[40] = file:/C:/Users/amita/.m2/repository/org/apache/maven/shared/m
aven-filtering/1.3/maven-filtering-1.3.jar
[ERROR] urls[41] = file:/C:/Users/amita/.m2/repository/org/apache/maven/shared/m
aven-shared-utils/0.6/maven-shared-utils-0.6.jar
[ERROR] urls[42] = file:/C:/Users/amita/.m2/repository/com/google/code/findbugs/
jsr305/2.0.1/jsr305-2.0.1.jar
[ERROR] urls[43] = file:/C:/Users/amita/.m2/repository/org/sonatype/plexus/plexu
s-build-api/0.0.4/plexus-build-api-0.0.4.jar
[ERROR] urls[44] = file:/C:/Users/amita/.m2/repository/org/codehaus/plexus/plexu
s-io/2.6/plexus-io-2.6.jar
[ERROR] urls[45] = file:/C:/Users/amita/.m2/repository/org/apache/maven/maven-ar
chiver/2.5/maven-archiver-2.5.jar
[ERROR] urls[46] = file:/C:/Users/amita/.m2/repository/org/codehaus/plexus/plexu
s-utils/3.0.21/plexus-utils-3.0.21.jar
[ERROR] urls[47] = file:/C:/Users/amita/.m2/repository/org/apache/maven/shared/m
aven-repository-builder/1.0/maven-repository-builder-1.0.jar
[ERROR] urls[48] = file:/C:/Users/amita/.m2/repository/joda-time/joda-time/2.8.2
/joda-time-2.8.2.jar
[ERROR] urls[49] = file:/C:/Users/amita/.m2/repository/org/yaml/snakeyaml/1.16/s
nakeyaml-1.16.jar
[ERROR] urls[50] = file:/C:/Users/amita/.m2/repository/com/google/guava/guava/18
.0/guava-18.0.jar
[ERROR] urls[51] = file:/C:/Users/amita/.m2/repository/org/codehaus/plexus/plexu
s-interpolation/1.22/plexus-interpolation-1.22.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>com.tibco.bw:Employe
eApplication:1.0.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContaine
rException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :EmployeeApplication.application

C:\Users\amita\bwceworkspace\EmployeeApplication.application.parent>

**Comment by SujataDarekar** [comment]
@asatsi 
     I am able to triggered build successfully with Maven version 3.5.0 and above both from Studio and Command line. Please try with  latest version of bw6-maven-plugin.-1.3.1.
