### ISSUE TITLE
Build failed when deploying using maven plugin

### ISSUE THREAD

**Issue by raj-work** [TIBCOSoftware/bw6-plugin-maven#88]
Maven Plugin version: 1.2.2

Maven version: 3.3.9

Product : TIBCO Businessworks Container edition 

Product version: 2.3.0

Component: Maven build plugin

**Steps to reproduce the issue:**
1. Create a BW CE application with multiple shared modules
2. Generate pom for the above application
3. Execute mvn package command

**Additional environment details if any:**
We had this issue happen in both automated deployment setup and when manually trying to generate mvn package outside eclipse. When using eclipse maven, we did not face any issues.

**Describe the results you received:**
Got an error with NullPointerException when trying to build the EAR.
[ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:1.2.2:bwear (default-bwear) on project serviceNodeSmsProcessor.application: Failed to create BW EAR Archive: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.tibco.plugins:bw6-maven-plugin:1.2.2:bwear (default-bwear) on project serviceNodeSmsProcessor.application: Failed to create BW EAR Archive 

**Describe the results you expected:**
Successful build and deployment.

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue happened only with this application. All other applications which were built and deployed using the same setup worked. And for some reason, after several updates in my code, suddenly it worked again yesterday evening. But since there were no changes related specifically to deployment, I am not sure why this issue occurred for several days (through multiple code changes) and suddenly stopped (after some code changes).

**Comment by raj-work** [comment]
[MavenOutput.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/1064402/MavenOutput.txt)

**Comment by RajibBiswasTibco** [comment]
@raj-work , Can you share the project?

**Comment by SujataDarekar** [comment]
@raj-work Please try with latest version(1.3.1) of BW_Maven_Plugin

**Comment by SujataDarekar** [comment]
Closing the issue. Please reopen if you face the issue.
