### ISSUE TITLE
Exclude Maven dependencies with "provided" scope from EAR

### ISSUE THREAD

**Issue by wbjustman** [TIBCOSoftware/bw6-plugin-maven#96]
Suggesting an enhancement

I am using Plugin version 1.2.2 with BW 6.3.4

When building a BW project that has a java aspect, Plug-in dependencies that refer to jars in the BW runtime are being included in the module jar by BWModulePackageMojo.  These jars are need to compile, but should not be included in the lib folder of the resulting jar.  These jars increase the size of the EAR and cause class loader errors on startup of the application.

On line 173 of BWModulePackageMojo.java the names of jars used by the plugin are excluded from the jar.  The names of these jars are hard-coded.  Instead, I propose we use the dependency scope to determine if the jar should be included in the module jar.  A scope of "provided" would indicate adding the jar to the classpath, but not adding it to the jar.  This scope then could be used with com.tibco.bw.palette.shared and com.tibco.xml.cxf.common as well as plug-in dependencies through imported packages.

**Comment by SujataDarekar** [comment]
Code changes has been committed hence marking the issue as closed
